Object.assign(translations.uk,{academy:'Навчальний маршрут',academyIntro:'HTML → CSS → JavaScript → Git → TypeScript. Пояснення, практика, короткий тест і мініпроєкт у кожному модулі.',lessonGoal:'Мета уроку',theoryRead:'Теорію прочитано',quizTitle:'Короткий тест',checkQuiz:'Перевірити відповідь',quizCorrect:'Правильно',quizWrong:'Спробуй ще раз',practicePassed:'Практика пройдена',projectReview:'Я перевірив мініпроєкт: межові випадки, читабельність та очікуваний результат.',lessonComplete:'Урок завершено',lessonIncomplete:'Для завершення прочитай теорію, пройди практику й тест; у мініпроєкті додай самоперевірку.',addReview:'Додати урок до повторення',lessonNotes:'Нотатки уроку',makeLessonNote:'Створити конспект',previewWidth:'Ширина прев’ю',runCode:'Запустити',checkPractice:'Перевірити практику',practiceOutput:'Вивід та перевірки',practiceTimeout:'Час виконання вичерпано. Перевір цикли й очікування.',practiceSafe:'JS виконується ізольовано, без доступу до даних сайту та мережі. DOM і TypeScript перевіряються за конструкціями в тексті; це не компілятор. Git — симуляція.',sourceOnly:'Цей урок перевіряє конструкції в коді; JS цього уроку не виконується.',downloadExercise:'Завантажити вправу JSON',courseProgress:'Теорія / практика / завершено',practiceFailed:'Перевірки ще не пройдено',practiceError:'Помилка виконання',viewSolution:'Приклад розв’язку',projectLabel:'Мініпроєкт',testExplain:'Чому так',lessonDraft:'Чернетка зберігається автоматично',moduleSummary:'Підсумок модуля',restoreExercise:'Відновити стартовий код'});
Object.assign(translations.en,{academy:'Learning path',academyIntro:'HTML → CSS → JavaScript → Git → TypeScript. Explanations, practice, a short quiz and a mini project in every module.',lessonGoal:'Lesson goal',theoryRead:'Theory read',quizTitle:'Short quiz',checkQuiz:'Check answer',quizCorrect:'Correct',quizWrong:'Try again',practicePassed:'Practice passed',projectReview:'I reviewed the mini project: boundaries, readability and expected behavior.',lessonComplete:'Lesson completed',lessonIncomplete:'Read the theory, pass practice and the quiz; for a mini project, add your self-review.',addReview:'Add lesson to review',lessonNotes:'Lesson notes',makeLessonNote:'Create study note',previewWidth:'Preview width',runCode:'Run',checkPractice:'Check practice',practiceOutput:'Output and checks',practiceTimeout:'Execution timed out. Check loops and waiting.',practiceSafe:'JS runs in isolation without site data or network access. DOM and TypeScript exercises check source constructs, not compilation. Git is a simulation.',sourceOnly:'This lesson checks source constructs; its JS is not executed.',downloadExercise:'Download exercise JSON',courseProgress:'Theory / practice / completed',practiceFailed:'Checks have not passed yet',practiceError:'Execution error',viewSolution:'Reference solution',projectLabel:'Mini project',testExplain:'Why',lessonDraft:'Draft autosaves',moduleSummary:'Module summary',restoreExercise:'Restore starter code'});
const academyLessonList=()=>academyCourses.flatMap(c=>c.lessons);
function validAcademy(a){try{return a&&a.version===1&&(a.previewWidth===undefined||[320,600,900].includes(a.previewWidth))&&['HTML',...academyCourses.map(c=>c.id)].includes(a.course)&&academyLessonList().some(l=>l.id===a.selected)&&a.states&&typeof a.states==='object'&&!Array.isArray(a.states)&&Object.entries(a.states).every(([id,s])=>academyLessonList().some(l=>l.id===id)&&s&&['html','css','js'].every(k=>typeof s.files?.[k]==='string'&&s.files[k].length<=30000)&&['theoryRead','practicePassed','quizPassed','selfReview','completed'].every(k=>typeof s[k]==='boolean')&&Number.isInteger(s.attempts)&&s.attempts>=0&&Number.isInteger(s.hints)&&s.hints>=0&&s.hints<=3&&(s.quiz===null||Number.isInteger(s.quiz)&&s.quiz>=0&&s.quiz<=2));}catch{return false;}}
let academy=readData('devspace-academy',{version:1,course:'HTML',selected:'css-cascade',states:{}},validAcademy),academyResult=null,academyRunning=false,academyGeneration=0;
function academyState(l){return academy.states[l.id] ||= {files:{html:'',css:'',js:'',...l.starter},theoryRead:false,practicePassed:false,quizPassed:false,selfReview:false,completed:false,attempts:0,hints:0,quiz:null};}
function saveAcademy(){const okay=writeData('devspace-academy',academy);syncAcademyProgress();return okay;}
function completeAcademy(l,s){const was=s.completed;s.completed=s.theoryRead&&s.practicePassed&&s.quizPassed&&(!(l.project||l.manualReview)||s.selfReview);if(!was&&s.completed)recordActivity('lessonCompleted',l.title[document.documentElement.lang],l.id);saveAcademy();}
function lessonCatalog(){return [...htmlLessons.map(l=>({id:'html-'+l.id,title:l.title,course:'HTML'})),...academyLessonList()];}
function openLesson(id){if(id.startsWith('html-')&&htmlLessons.some(l=>l.id===id.slice(5))){academy.course='HTML';htmlCourse.selected=id.slice(5);saveHtmlCourse();}else{const l=academyLessonList().find(l=>l.id===id);if(!l)return;academy.course=l.course;academy.selected=id;}saveAcademy();location.hash='learning';showView();renderAcademy();requestAnimationFrame(()=>Q(academy.course==='HTML'?'html-course':'academy-panel').scrollIntoView({block:'start'}));}
function syncAcademyProgress(){for(const course of academyCourses){const group=document.querySelector('[data-tech="'+course.id+'"]')?.closest('.topic-list');if(!group)continue;group.replaceChildren();for(const l of course.lessons){const input=E('input');input.type='checkbox';input.hidden=true;input.dataset.topic='academy-'+l.id;input.dataset.tech=course.id;input.checked=academy.states[l.id]?.completed===true;group.append(input);savedProgress[input.dataset.topic]=input.checked;}const link=E('button','text-link',course.id+' →');link.type='button';link.addEventListener('click',()=>openLesson(course.lessons[0].id));group.append(link);}writeData('devspace-progress',savedProgress);updateProgress();renderLearningOverview();}
// All preview HTML is sanitized. Only trusted measurement code executes in the frame.
function safePracticeDocument(files,measurement=''){
 const doc=new DOMParser().parseFromString(files.html||'<main class="demo"></main>','text/html');doc.querySelectorAll('script,iframe,object,embed,base,meta,link').forEach(n=>n.remove());
 doc.querySelectorAll('*').forEach(el=>{for(const attr of [...el.attributes])if(/^on/i.test(attr.name)||['srcdoc','formaction','action','target','href','src','srcset'].includes(attr.name))el.removeAttribute(attr.name);});
 const base=doc.createElement('style');base.textContent='html{color-scheme:light}body{color:#151519;background:#fff;font-family:system-ui,sans-serif;margin:16px}';doc.head.append(base);const css=doc.createElement('style');css.textContent=files.css;doc.head.append(css);
 const csp="default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' blob:; worker-src blob:; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; form-action 'none'; base-uri 'none'";
 const meta=doc.createElement('meta');meta.httpEquiv='Content-Security-Policy';meta.content=csp;doc.head.prepend(meta);
 if(measurement){const script=doc.createElement('script');script.textContent=measurement;doc.body.append(script);}return '<!doctype html>'+doc.documentElement.outerHTML;
}
function simulateGit(code){const state={initialized:false,statusSeen:false,staged:false,commits:0,lastMessage:'',branch:'main',hasFeature:false,merged:false,pushed:false,upstream:false,remote:''},branches=new Set(['main']),output=[];for(const raw of code.split('\n')){const line=raw.trim();if(!line||line.startsWith('#'))continue;const args=line.match(/"[^"]*"|'[^']*'|\S+/g)?.map(v=>v.replace(/^['"]|['"]$/g,''))||[];if(args[0]!=='git')throw Error('Only simulated git commands are supported: '+line);const cmd=args[1];if(cmd==='init'){state.initialized=true;output.push('Initialized virtual repository');continue;}if(!state.initialized)throw Error('Run git init first');switch(cmd){case'status':state.statusSeen=true;output.push(state.staged?'Staged: index.html':state.commits?'Working tree clean':'Untracked: index.html');break;case'add':if(!['.','index.html'].includes(args[2]))throw Error('Use git add . or git add index.html');state.staged=true;output.push('Staged index.html');break;case'commit':if(!state.staged||args[2]!=='-m'||!args[3])throw Error('Stage changes, then use git commit -m "message"');state.commits++;state.lastMessage=args[3];state.staged=false;output.push('Commit: '+args[3]);break;case'switch':if(args[2]==='-c'){if(!args[3]||branches.has(args[3]))throw Error('Choose a new branch name');branches.add(args[3]);state.branch=args[3];}else{if(!branches.has(args[2]))throw Error('Unknown branch');state.branch=args[2];}state.hasFeature=branches.has('feature');output.push('Branch: '+state.branch);break;case'merge':if(!branches.has(args[2])||args[2]===state.branch)throw Error('Choose another existing branch');state.merged=true;output.push('Simulated merge: '+args[2]+' → '+state.branch);break;case'remote':if(args[2]!=='add'||args[3]!=='origin'||!/^https?:\/\//.test(args[4]||''))throw Error('Use git remote add origin https://...');state.remote=args[4];output.push('Configured origin (no network)');break;case'fetch':if(!state.remote)throw Error('Configure origin first');output.push('Simulated fetch');break;case'push':if(!state.remote||!state.commits)throw Error('Configure origin and commit first');{const target=args.filter(a=>a!=='-u').slice(2);if(target[0]!=='origin'||target[1]!==state.branch)throw Error('Push origin and the current branch');}state.pushed=true;state.upstream=args.includes('-u');output.push('Simulated push: '+state.branch);break;default:throw Error('Unsupported simulated command: '+cmd);}}return{state,output};}
function sourceResults(l,files){return l.checks.filter(c=>c.kind==='text').map(c=>({label:c.label[document.documentElement.lang],passed:new RegExp(c.pattern,'m').test(files[c.file])}));}
function runAcademyPractice(l,files,check=true){
 const textResults=check?sourceResults(l,files):[];if(l.kind==='git'){try{const result=simulateGit(files.js);return Promise.resolve({output:result.output,results:check?l.checks.filter(c=>c.kind==='git').map(c=>({label:c.label[document.documentElement.lang],passed:result.state[c.property]===c.value})):[]});}catch(error){return Promise.resolve({output:[error.message],results:[],error:error.message});}}
 if(['typescript','source'].includes(l.kind))return Promise.resolve({output:[t().sourceOnly],results:textResults});
 const frame=E('iframe','practice-runner');frame.setAttribute('sandbox','allow-scripts');frame.title=t().practiceOutput;frame.hidden=true;const nonce=crypto.randomUUID();
 return new Promise(resolve=>{let settled=false;const finish=result=>{if(settled)return;settled=true;clearTimeout(timeout);window.removeEventListener('message',receive);frame.remove();resolve({...result,results:[...textResults,...(result.results||[])]});};const receive=e=>{if(e.source===frame.contentWindow&&e.data?.nonce===nonce)finish(e.data.result);};window.addEventListener('message',receive);const timeout=setTimeout(()=>finish({error:t().practiceTimeout,output:[],results:[]}),3000);
 if(l.kind==='css'){
 const checks=check?l.checks.filter(c=>c.kind==='computed'):[];const code='setTimeout(()=>{const checks='+JSON.stringify(checks).replace(/</g,'\\u003c')+';parent.postMessage({nonce:'+JSON.stringify(nonce)+',result:{output:[],results:checks.map(c=>{const el=document.querySelector(c.selector);return {label:c.selector+" · "+c.property+" = "+c.value,passed:!!el&&getComputedStyle(el).getPropertyValue(c.property)===c.value};})}},"*");},30);';frame.srcdoc=safePracticeDocument(files,code);
 }else{
 // The worker is created INSIDE an opaque-origin sandbox; it cannot access site storage.
 const tests=check?l.checks.filter(c=>c.kind==='js'):[];const expressions=tests.map(c=>'try { results.push({label:'+JSON.stringify(c.label[document.documentElement.lang])+',passed:!!('+c.expression+')}); } catch(e) { results.push({label:'+JSON.stringify(c.label[document.documentElement.lang])+',passed:false}); }').join('\n');
 const workerSource=`const output=[];const show=v=>{try{return typeof v==='string'?v:JSON.stringify(v);}catch{return '[value]';}};const console={log:(...v)=>{if(output.length<100)output.push(v.map(show).join(' ').slice(0,2000));}};const fetch=async()=>({ok:true,status:200,json:async()=>[{title:'HTML'},{title:'CSS'}]});(async()=>{try{const results=[];${files.js}\n${expressions}\npostMessage({output,results});}catch(e){postMessage({error:String(e.message).slice(0,1000),output,results:[]});}})();`;
 const trusted='const worker=new Worker(URL.createObjectURL(new Blob(['+JSON.stringify(workerSource).replace(/</g,'\\u003c')+'],{type:"text/javascript"})));const timer=setTimeout(()=>{worker.terminate();parent.postMessage({nonce:'+JSON.stringify(nonce)+',result:{error:'+JSON.stringify(t().practiceTimeout)+',output:[],results:[]}},"*");},1500);worker.onmessage=e=>{clearTimeout(timer);worker.terminate();parent.postMessage({nonce:'+JSON.stringify(nonce)+',result:e.data},"*");};worker.onerror=e=>{clearTimeout(timer);worker.terminate();parent.postMessage({nonce:'+JSON.stringify(nonce)+',result:{error:String(e.message),output:[],results:[]}},"*");};';frame.srcdoc=safePracticeDocument({html:'',css:''},trusted);
 }document.body.append(frame);
 });
}
const academyPanel=E('section','academy-panel');academyPanel.id='academy-panel';Q('html-course').before(academyPanel);
function renderAcademy(){
 const language=document.documentElement.lang,l=academyLessonList().find(l=>l.id===academy.selected),s=academyState(l);academyPanel.replaceChildren();academyPanel.append(E('h2','',t().academy),E('p','panel-note',t().academyIntro));const tabs=E('div','task-filters');tabs.setAttribute('role','group');tabs.setAttribute('aria-label',t().academy);for(const course of ['HTML',...academyCourses.map(c=>c.id)]){const b=button(course,()=>{academyGeneration++;academyRunning=false;academy.course=course;if(course!=='HTML')academy.selected=academyCourses.find(c=>c.id===course).lessons[0].id;academyResult=null;saveAcademy();renderAcademy();});b.setAttribute('aria-pressed',String(academy.course===course));tabs.append(b);}academyPanel.append(tabs);Q('html-course').hidden=academy.course!=='HTML';courseStartButton.hidden=academy.course!=='HTML';if(academy.course==='HTML')return;
 const course=academyCourses.find(c=>c.id===academy.course),summary=E('p','panel-note',t().courseProgress+': '+course.lessons.filter(l=>academy.states[l.id]?.theoryRead).length+' / '+course.lessons.filter(l=>academy.states[l.id]?.practicePassed).length+' / '+course.lessons.filter(l=>academy.states[l.id]?.completed).length+' ('+course.lessons.length+')');academyPanel.append(summary);
 const layout=E('div','course-layout'),nav=E('nav','lesson-navigation'),body=E('section','dashboard-panel');nav.setAttribute('aria-label',course.id+' lessons');layout.append(nav,body);academyPanel.append(layout);
 for(const [i,item] of course.lessons.entries()){const b=button((i+1)+'. '+item.title[language]+(academy.states[item.id]?.completed?' ✓':''),()=>{academyGeneration++;academyRunning=false;academy.selected=item.id;academyResult=null;saveAcademy();renderAcademy();});b.className='lesson-button';if(item.id===l.id)b.setAttribute('aria-current','step');nav.append(b);}
 body.append(E('span','badge',l.course+(l.project?' · '+t().projectLabel:'')),E('h2','',l.title[language]),E('h3','',t().lessonGoal),E('p','lesson-theory',l.task[language]),E('h3','',t().courseTheory));for(const paragraph of l.theory[language])body.append(E('p','lesson-theory',paragraph));const read=labelField(body,'theoryRead',E('input'));read.type='checkbox';read.checked=s.theoryRead;read.addEventListener('change',()=>{s.theoryRead=read.checked;completeAcademy(l,s);renderAcademy();});body.append(E('h3','',t().courseTask),E('p','lesson-theory',l.task[language]));
 const editorTabs=E('div','task-filters'),editors=E('div','exercise-editors');let active=l.kind==='css'?'css':'js';for(const file of (l.kind==='design'?['js']:['html','css','js'])){const field=E('div','form-field');field.dataset.file=file;const textarea=labelField(field,l.kind==='design'?'JSON':file.toUpperCase(),E('textarea','course-code'));textarea.id='academy-code-'+file;textarea.previousElementSibling.htmlFor=textarea.id;textarea.value=s.files[file];textarea.rows=12;textarea.maxLength=30000;textarea.spellcheck=false;textarea.addEventListener('input',()=>{academyGeneration++;academyRunning=false;for(const b of actions.children)b.disabled=false;s.files[file]=textarea.value;s.practicePassed=false;s.completed=false;academyResult=null;saveAcademy();Q('academy-results').replaceChildren();});field.hidden=file!==active;editors.append(field);const b=button(l.kind==='design'?'JSON':file.toUpperCase(),()=>{active=file;for(const f of editors.children)f.hidden=f.dataset.file!==file;for(const x of editorTabs.children)x.setAttribute('aria-pressed',String(x.dataset.file===file));Q('academy-code-'+file).focus();});b.dataset.file=file;b.setAttribute('aria-pressed',String(file===active));editorTabs.append(b);}body.append(editorTabs,editors,E('p','panel-note',t().lessonDraft),E('p','panel-note',t().practiceSafe));
 const actions=E('div','editor-actions');const execute=async(check)=>{if(academyRunning)return;academyRunning=true;const generation=++academyGeneration;if(check)s.attempts++;saveAcademy();for(const b of actions.children)b.disabled=true;const files=structuredClone(s.files);const result=await runAcademyPractice(l,files,check);if(generation!==academyGeneration)return;academyRunning=false;academyResult=result;if(check)s.practicePassed=!result.error&&result.results.length>0&&result.results.every(r=>r.passed);completeAcademy(l,s);renderAcademy();};actions.append(button('runCode',()=>execute(false)),button('checkPractice',()=>execute(true),'primary-button'),button('courseHint',()=>{s.hints=Math.min(l.hints.length,s.hints+1);saveAcademy();renderAcademy();}),button('restoreExercise',()=>{if(!confirm(t().courseResetConfirm))return;s.files={html:'',css:'',js:'',...l.starter};s.practicePassed=false;s.completed=false;academyResult=null;saveAcademy();renderAcademy();}),button('downloadExercise',()=>downloadText(l.id+'.json',JSON.stringify(s.files,null,2),'application/json')));body.append(actions);const hints=E('ol','course-hints');for(const hint of l.hints.slice(0,s.hints))hints.append(E('li','',hint[language]));body.append(hints);
 const solution=E('details','course-example');solution.append(E('summary','',t().viewSolution));if(s.attempts){for(const file of ['html','css','js'])if(l.solution[file])solution.append(E('h4','',file.toUpperCase()),E('pre','snippet-code',l.solution[file]));}else{solution.append(E('p','panel-note',t().courseStart));}body.append(solution);
 const resultBox=E('div','course-results');resultBox.id='academy-results';resultBox.setAttribute('role','status');resultBox.setAttribute('aria-live','polite');if(academyResult){if(academyResult.error)resultBox.append(E('p','check-fail',t().practiceError+': '+academyResult.error));for(const line of academyResult.output||[])resultBox.append(E('pre','snippet-code',line));for(const check of academyResult.results||[])resultBox.append(E('p',check.passed?'check-pass':'check-fail',(check.passed?'✓ ':'○ ')+check.label));}body.append(E('h3','',t().practiceOutput),resultBox);
 if(['css','source'].includes(l.kind)){const width=labelField(body,'previewWidth',E('select'));selectOptions(width,[['320','320px'],['600','600px'],['900','900px']],String(academy.previewWidth||600));const wrapper=E('div','practice-preview-scroll'),frame=E('iframe','academy-preview');frame.title=t().coursePreview;frame.setAttribute('sandbox','');frame.referrerPolicy='no-referrer';frame.style.width=(academy.previewWidth||600)+'px';frame.srcdoc=safePracticeDocument(s.files);wrapper.append(frame);width.addEventListener('change',()=>{academy.previewWidth=Number(width.value);frame.style.width=width.value+'px';});body.append(wrapper);}
 body.append(E('h3','',t().quizTitle),E('p','',l.quiz.question[language]));const quiz=E('form','quiz-form');quiz.id='academy-quiz';for(const [i,answer] of l.quiz.options.entries()){const label=E('label','topic-row'),radio=E('input');radio.type='radio';radio.name='answer';radio.value=i;radio.required=true;radio.checked=s.quiz===i;label.append(radio,E('span','',answer[language]));quiz.append(label);}const submit=E('button','secondary-button',t().checkQuiz);submit.type='submit';quiz.append(submit);quiz.addEventListener('submit',e=>{e.preventDefault();s.quiz=Number(new FormData(quiz).get('answer'));s.quizPassed=s.quiz===l.quiz.answer;completeAcademy(l,s);renderAcademy();});body.append(quiz);if(s.quiz!==null)body.append(E('p',s.quizPassed?'check-pass':'check-fail',t()[s.quizPassed?'quizCorrect':'quizWrong']+' · '+l.quiz.explanation[language]));
 if(l.project||l.manualReview){const review=labelField(body,l.kind==='design'?'designReview':'projectReview',E('input'));review.type='checkbox';review.checked=s.selfReview;review.addEventListener('change',()=>{s.selfReview=review.checked;completeAcademy(l,s);renderAcademy();});}body.append(E('p',s.completed?'check-pass':'panel-note',t()[s.completed?'lessonComplete':'lessonIncomplete']),button('addReview',()=>addLessonReview(l.id)),button('makeLessonNote',()=>makeLinkedNote({lessonId:l.id})));const linked=E('div');for(const n of notes.filter(n=>!n.deleted&&n.lessonId===l.id))linked.append(button(n.title||t().untitledNote,()=>openEntity('notes',n.id)));body.append(E('h3','',t().lessonNotes),linked);
 const pagination=E('div','course-pagination');for(const [offset,key] of [[-1,'coursePrevious'],[1,'courseNext']]){const next=course.lessons[course.lessons.indexOf(l)+offset];if(next)pagination.append(button(key,()=>openLesson(next.id)));}body.append(pagination);
}
const baseOpenEntity=openEntity;openEntity=function(kind,id){if(kind==='learning'&&lessonCatalog().some(l=>l.id===id)){openLesson(id);return;}baseOpenEntity(kind,id);};
const baseSearchItems=searchItems;searchItems=function(){return [...baseSearchItems(),...academyLessonList().map(l=>({name:l.title[document.documentElement.lang],body:l.course,kind:'learning',id:l.id}))];};
window.addEventListener('languagechange',()=>{academyResult=null;syncAcademyProgress();renderAcademy();});renderAcademy();syncAcademyProgress();
