// Original bilingual curriculum. Exercises declare observable checks.
const academyCourses=['CSS','JavaScript','Git','TypeScript'].map(id=>({id,lessons:[]}));
const bi=(uk,en)=>({uk,en});
function lesson(course,id,uk,en,theoryUk,theoryEn,taskUk,taskEn,solution,checks,quiz,hints,options={}){
 academyCourses.find(c=>c.id===course).lessons.push({id:course.toLowerCase()+'-'+id,course,title:bi(uk,en),theory:bi(theoryUk,theoryEn),task:bi(taskUk,taskEn),solution,checks,quiz:{question:bi(...quiz[0]),options:quiz[1].map(x=>bi(...x)),answer:quiz[2],explanation:bi(...quiz[3])},hints:hints.map(x=>bi(...x)),starter:options.starter||{html:'<main class="demo"><h1>Kachan</h1><p>Keep building.</p></main>',css:'/* Your CSS */',js:''},kind:options.kind||(course==='CSS'?'css':course==='JavaScript'?'js':course==='Git'?'git':'typescript'),project:!!options.project});
}
const computed=(selector,property,value)=>({kind:'computed',selector,property,value});
const expression=(code,uk,en)=>({kind:'js',expression:code,label:bi(uk,en)});
const source=(file,pattern,uk,en)=>({kind:'text',file,pattern,label:bi(uk,en)});
const gitState=(property,value,uk,en)=>({kind:'git',property,value,label:bi(uk,en)});
const blankJS={html:'',css:'',js:'// Write your solution'};
lesson('Git','init','Репозиторій і статус','Repository and status',
 ['Git зберігає історію локально. Репозиторій містить файли та .git. git init створює його, git status показує робоче дерево. GitHub — сервіс розміщення, не сам Git.','Ця практика — симуляція: команди не змінюють справжній Git. Віртуальний проєкт має index.html. Кожна перевірка починає симуляцію заново.'],
 ['Git stores history locally. A repository contains files and .git. git init creates it; git status reports the working tree. GitHub hosts repositories; it is not Git itself.','This practice is a simulation: commands never change real Git. The virtual project has index.html. Every check starts the simulation afresh.'],
 'Ініціалізуй репозиторій і перевір статус.','Initialize a repository and inspect status.',{js:'git init\ngit status'},[gitState('initialized',true,'Репозиторій створено','Repository initialized'),gitState('statusSeen',true,'Статус перевірено','Status inspected')],
 [['Що створює репозиторій?','What creates a repository?'],[['git init','git init'],['git push','git push'],['git status','git status']],0,['init створює локальну історію.','init creates local history.']], [['Спочатку git init.','First git init.'],['Далі git status.','Then git status.']],{starter:blankJS});
lesson('Git','commit','Індекс і коміт','Staging and commits',
 ['Робоче дерево — поточні файли. Індекс — зміни для наступного коміту. git add index.html додає файл в індекс; git commit -m "message" записує знімок.','Коміт має пояснювати логічну зміну. Перед git add . перевір статус: секрети, тимчасові файли й залежності не повинні потрапляти в історію.'],
 ['The working tree holds current files. The index holds changes for the next commit. git add index.html stages a file; git commit -m "message" records a snapshot.','A commit should explain a logical change. Check status before git add .: secrets, temporary files and dependencies should not enter history.'],
 'Виконай init, add index.html і commit з повідомленням Create page.','Run init, add index.html and commit with message Create page.',{js:'git init\ngit add index.html\ngit commit -m "Create page"'},[gitState('commits',1,'Є один коміт','One commit exists'),gitState('lastMessage','Create page','Повідомлення Create page','Message is Create page')],
 [['Що робить git add?','What does git add do?'],[['Надсилає на сервер','Uploads to server'],['Обирає зміни для коміту','Stages changes'],['Видаляє історію','Deletes history']],1,['add змінює індекс, не remote.','add updates the index, not the remote.']], [['Додай файл перед commit.','Stage before committing.'],['Повідомлення візьми в лапки.','Quote the message.']],{starter:blankJS});
lesson('Git','branches','Гілки','Branches',
 ['Гілка — рухомий покажчик на коміт. git switch -c feature створює гілку й переходить до неї. Окремі гілки допомагають не змішувати незавершені зміни.','git switch main повертає основну гілку. Перед перемиканням перевір робоче дерево. Коміт записується в історію поточної гілки.'],
 ['A branch is a movable pointer to a commit. git switch -c feature creates and switches a branch. Separate branches keep unfinished changes apart.','git switch main returns to main. Inspect the working tree before switching. A commit belongs to the current branch history.'],
 'Створи стартовий коміт, гілку feature і повернись у main.','Create an initial commit, create feature and return to main.',{js:'git init\ngit add .\ngit commit -m "Start"\ngit switch -c feature\ngit switch main'},[gitState('hasFeature',true,'Гілка feature існує','feature exists'),gitState('branch','main','Поточна гілка main','Current branch is main')],
 [['Що робить switch -c?','What does switch -c do?'],[['Створює й перемикає гілку','Creates and switches a branch'],['Видаляє коміт','Deletes a commit'],['Клонує GitHub','Clones GitHub']],0,['-c створює нову гілку.','-c creates a new branch.']], [['Спочатку стартовий коміт.','Create an initial commit first.'],['switch -c feature, потім switch main.','switch -c feature, then switch main.']],{starter:blankJS});
lesson('Git','merge','Об’єднання й конфлікти','Merging and conflicts',
 ['git merge feature інтегрує історію feature в поточну гілку. Спочатку перейди в гілку, яка отримує зміни. За відсутності розходження можливий fast-forward.','Якщо гілки змінювали ті самі рядки, узгодь обидва варіанти, прибери маркери, перевір і закоміть результат. Симулятор покриває просте об’єднання, а не реальні текстові конфлікти.'],
 ['git merge feature integrates feature history into the current branch. First switch to the receiving branch. Without divergence, a fast-forward is possible.','When branches changed the same lines, reconcile both versions, remove markers, verify and commit. The simulator covers simple merging, not real text conflicts.'],
 'Створи feature, повернись у main і виконай merge feature.','Create feature, return to main and merge feature.',{js:'git init\ngit add .\ngit commit -m "Start"\ngit switch -c feature\ngit switch main\ngit merge feature'},[gitState('merged',true,'Feature об’єднано','Feature merged'),gitState('branch','main','Зміни отримує main','main receives changes')],
 [['Що робити з конфліктом?','How do you handle a conflict?'],[['Видалити .git','Delete .git'],['Узгодити, перевірити, закомітити','Resolve, verify, commit'],['Ігнорувати маркери','Ignore markers']],1,['Конфлікт потребує свідомого вибору результату.','A conflict requires choosing the intended result.']], [['Повернись у main перед merge.','Return to main before merge.'],['merge приймає назву іншої гілки.','merge takes the other branch name.']],{starter:blankJS});
lesson('Git','remote','Remote, fetch і push','Remotes, fetch and push',
 ['Remote — іменована адреса репозиторію. origin — звична назва. remote add origin URL додає адресу; push -u origin main публікує гілку й налаштовує upstream.','fetch отримує історію без автоматичного merge. pull поєднує отримання з інтеграцією. У симуляції URL перевіряється, але мережевих запитів немає.'],
 ['A remote is a named repository URL. origin is a convention. remote add origin URL adds it; push -u origin main publishes and sets upstream.','fetch downloads history without automatic merging. pull combines fetching and integration. The simulator checks the URL but makes no network requests.'],
 'Створи коміт, origin https://github.com/example/demo.git і push -u origin main.','Create a commit, origin https://github.com/example/demo.git and push -u origin main.',{js:'git init\ngit add .\ngit commit -m "Start"\ngit remote add origin https://github.com/example/demo.git\ngit push -u origin main'},[gitState('pushed',true,'Push завершено у симуляції','Push completed in simulation'),gitState('upstream',true,'Upstream налаштовано','Upstream configured')],
 [['Що робить fetch?','What does fetch do?'],[['Отримує історію без merge','Fetches history without merge'],['Видаляє файли','Deletes files'],['Створює CSS','Creates CSS']],0,['fetch дає змогу оглянути віддалені зміни.','fetch lets you inspect remote changes.']], [['remote add стоїть перед push.','remote add comes before push.'],['Використай -u для upstream.','Use -u for upstream.']],{starter:blankJS});
lesson('Git','project','Мініпроєкт: робочий цикл','Mini project: workflow',
 ['Поєднай status, commit, окрему гілку, merge і push. У справжньому проєкті перед публікацією також переглянь зміни й перевірки.','Якщо секрет потрапив у коміт, його треба замінити: видалення з останньої версії не прибирає його зі старих комітів. .gitignore допомагає запобігати витокам.'],
 ['Combine status, commit, a separate branch, merge and push. In real projects, review the changes and checks before publishing.','If a secret enters a commit, rotate it: deleting it from the latest version does not remove it from older commits. .gitignore helps prevent exposure.'],
 'Пройди цикл із status, комітом Build dashboard, feature, merge та push із upstream.','Complete a workflow with status, a Build dashboard commit, feature, merge and upstream push.',{js:'git init\ngit status\ngit add .\ngit commit -m "Build dashboard"\ngit switch -c feature\ngit switch main\ngit merge feature\ngit remote add origin https://github.com/example/demo.git\ngit push -u origin main'},[gitState('statusSeen',true,'Статус перевірено','Status checked'),gitState('lastMessage','Build dashboard','Є логічний коміт','Logical commit exists'),gitState('merged',true,'Гілку об’єднано','Branch merged'),gitState('pushed',true,'Push завершено','Push completed')],
 [['Що робити із закоміченим секретом?','What should you do with a committed secret?'],[['Сховати файл','Hide the file'],['Замінити секрет і прибрати витік','Rotate it and remove the exposure'],['Нічого','Nothing']],1,['Історія може зберігати старе значення.','History may retain the old value.']], [['Об’єднай попередні команди.','Combine previous commands.'],['Push виконай із main після merge.','Push main after merging.']],{starter:blankJS,project:true});
lesson('TypeScript','types','Типи та інференція','Types and inference',
 ['TypeScript додає статичні типи до JavaScript. const name: string описує очікуваний тип. Часто він виводиться автоматично. Типи не є автоматичною перевіркою даних у runtime.','Ця практика використовує TypeScript-компілятор у strict-режимі та показує рядки помилок. Не приховуй проблему через any.'],
 ['TypeScript adds static types to JavaScript. const name: string declares an expected type. Types are often inferred. They do not automatically validate runtime data.','This practice uses the TypeScript compiler in strict mode and reports error locations. Do not hide problems using any.'],
 'Оголоси userName: string = "Rubin" і completed: boolean = false.','Declare userName: string = "Rubin" and completed: boolean = false.',{js:'const userName: string = "Rubin";\nlet completed: boolean = false;'},[source('js','userName\\s*:\\s*string','Ім’я string','Name is string'),source('js','completed\\s*:\\s*boolean','Стан boolean','State is boolean')],
 [['Чи TS автоматично перевіряє JSON під час виконання?','Does TS automatically validate JSON at runtime?'],[['Так','Yes'],['Ні','No'],['Лише CSS','Only CSS']],1,['Зовнішні дані потребують runtime-перевірки.','External data needs runtime validation.']], [['Тип стоїть після двокрапки.','A type follows a colon.'],['boolean приймає true або false.','boolean accepts true or false.']],{starter:blankJS});
lesson('TypeScript','unions','Union і статуси','Unions and status',
 ['A | B дозволяє одне з кількох значень. Літеральний тип "active" приймає саме цей рядок, а не довільний string. Це зручно для статусів.','type Status = "planning" | "inProgress" | "finished" обмежує допустимі стани. Optional поле deadline?: string може бути відсутнім: врахуй undefined.'],
 ['A | B allows one of several values. A literal type "active" accepts that exact string, not any string. This is useful for status.','type Status = "planning" | "inProgress" | "finished" restricts valid states. Optional deadline?: string may be absent: handle undefined.'],
 'Створи type Status із planning, inProgress і finished через union.','Create type Status with planning, inProgress and finished as a union.',{js:'type Status = "planning" | "inProgress" | "finished";\nconst status: Status = "planning";'},[source('js','type\\s+Status\\s*=','Status оголошено','Status declared'),source('js','planning["\x27]\\s*\\|\\s*["\x27]inProgress["\x27]\\s*\\|\\s*["\x27]finished','Три статуси через union','Three union states')],
 [['Що означає A | B?','What does A | B mean?'],[['A або B','A or B'],['Лише обидва одночасно','Only both together'],['Коментар','Comment']],0,['Union допускає будь-який варіант.','A union allows either alternative.']], [['Почни з type Status =.','Start with type Status =.'],['Розділи рядки символом |.','Separate literals with |.']],{starter:blankJS});
lesson('TypeScript','interfaces','Інтерфейси','Interfaces',
 ['interface описує форму об’єкта: поля та їх типи. Параметр Task очікує об’єкт з потрібними полями. interface не створює об’єкт.','readonly забороняє присвоєння через цей тип, але не заморожує дані у runtime. ? позначає optional. Вхідні JSON-дані все одно перевіряють окремо.'],
 ['An interface describes an object shape: fields and types. A Task parameter expects the required fields. An interface does not create an object.','readonly prevents assignment through this type but does not freeze runtime data. ? marks optional fields. Incoming JSON still needs separate validation.'],
 'Створи Task: readonly id: string, title: string, completed: boolean, deadline?: string.','Create Task: readonly id: string, title: string, completed: boolean, deadline?: string.',{js:'interface Task {\n readonly id: string;\n title: string;\n completed: boolean;\n deadline?: string;\n}'},[source('js','interface\\s+Task','Є interface Task','Task interface exists'),source('js','readonly\\s+id\\s*:\\s*string','ID readonly','ID is readonly'),source('js','deadline\\?\\s*:\\s*string','Дедлайн optional','Deadline optional'),source('js','completed\\s*:\\s*boolean','Стан boolean','State boolean')],
 [['Що означає ? після поля?','What does ? after a field mean?'],[['Обов’язкове','Required'],['Може бути відсутнє','May be absent'],['Видалене','Deleted']],1,['Optional поле може бути undefined.','An optional field may be undefined.']], [['Поля знаходяться у фігурних дужках.','Put fields inside braces.'],['deadline?: string позначає optional.','deadline?: string marks optional.']],{starter:blankJS});
lesson('TypeScript','generics','Generics','Generics',
 ['Generic зберігає зв’язок між типом входу та виходу. first<T>(items: T[]): T | undefined повертає елемент того самого типу або undefined.','T — параметр типу з довільною назвою. any втрачає цей зв’язок. T extends ... додавай лише коли потрібні певні властивості.'],
 ['A generic preserves a relation between input and output. first<T>(items: T[]): T | undefined returns an element of that type or undefined.','T is an arbitrarily named type parameter. any loses this relation. Add T extends ... only when particular properties are required.'],
 'Напиши first<T>(items: T[]): T | undefined, яка повертає items[0].','Write first<T>(items: T[]): T | undefined returning items[0].',{js:'function first<T>(items: T[]): T | undefined { return items[0]; }'},[source('js','first\\s*<T>','Параметр T','Type parameter T'),source('js','items\\s*:\\s*T\\[\\]','Масив T','Array of T'),source('js','T\\s*\\|\\s*undefined','Порожній список враховано','Empty list handled'),source('js','return\\s+items\\[0\\]','Перший елемент','First item')],
 [['Чому результат може бути undefined?','Why can the result be undefined?'],[['Масив може бути порожнім','The array can be empty'],['Кожний рядок undefined','Every string is undefined'],['Generics не працюють','Generics do not work']],0,['Індекс 0 відсутній у порожньому масиві.','Index 0 is absent in an empty array.']], [['Додай <T> після назви функції.','Add <T> after the function name.'],['Повернення T | undefined.','Return type is T | undefined.']],{starter:blankJS});
lesson('TypeScript','narrowing','Narrowing і unknown','Narrowing and unknown',
 ['unknown приймає невідоме значення, але вимагає перевірки перед операціями. typeof value === "string" звужує тип до string. Це безпечніше за any.','Type guard описує реальну перевірку. Компілятор довіряє value is string, тому реалізація має справді перевіряти значення, а не завжди повертати true.'],
 ['unknown accepts unknown values but requires checks before operations. typeof value === "string" narrows to string. This is safer than any.','A type guard describes an actual check. The compiler trusts value is string, so the implementation must really inspect the value, not always return true.'],
 'Напиши isText(value: unknown): value is string через typeof.','Write isText(value: unknown): value is string using typeof.',{js:'function isText(value: unknown): value is string { return typeof value === "string"; }'},[source('js','value\\s*:\\s*unknown','Вхід unknown','Input unknown'),source('js','value\\s+is\\s+string','Type predicate','Type predicate'),source('js','typeof\\s+value\\s*===\\s*["\x27]string','Runtime перевірка','Runtime check')],
 [['Що вимагає unknown?','What does unknown require?'],[['Перевірки перед використанням','Checks before use'],['Вимкнення перевірок','Disabling checks'],['Числа','A number']],0,['unknown не дозволяє довільних операцій без звуження.','unknown prevents arbitrary operations without narrowing.']], [['Тип входу unknown.','Input type is unknown.'],['Перевір typeof value === "string".','Check typeof value === "string".']],{starter:blankJS});
lesson('TypeScript','project','Мініпроєкт: типізовані задачі','Mini project: typed tasks',
 ['З’єднай Task і чисту функцію перемикання. Типізуй вхід та вихід, зберігаючи поведінку попереднього JavaScript-модуля.','Перевір код у TypeScript Playground зі strict і спробуй completed: "yes". Тут перевіряються конструкції, не повний аналіз типів чи будь-яка можлива реалізація.'],
 ['Combine Task with a pure toggle function. Type inputs and output while preserving the earlier JavaScript behavior.','Check in TypeScript Playground with strict and try completed: "yes". These checks assess constructs, not full type analysis or every possible implementation.'],
 'Створи Task з id, title, completed і toggleTask(items: Task[], id: string): Task[] через map.','Create Task with id, title, completed and toggleTask(items: Task[], id: string): Task[] using map.',{js:'interface Task { id: string; title: string; completed: boolean; }\nfunction toggleTask(items: Task[], id: string): Task[] {\n return items.map(task => task.id === id ? {...task, completed: !task.completed} : task);\n}'},[source('js','interface\\s+Task','Модель Task','Task model'),source('js','completed\\s*:\\s*boolean','Стан boolean','State boolean'),source('js','items\\s*:\\s*Task\\[\\]','Вхід Task[]','Input Task[]'),source('js','id\\s*:\\s*string','ID string','ID string'),source('js','items\\.map','Оновлення через map','Update using map')],
 [['Що робить повний аналіз типів?','What performs full type analysis?'],[['tsc або TypeScript Playground','tsc or TypeScript Playground'],['Лише regex','Only regex'],['Скріншот','Screenshot']],0,['Компілятор перевіряє зв’язки, яких текстові умови не бачать.','A compiler checks relations that text patterns cannot verify.']], [['Візьми модель з уроку interface.','Reuse the interface model.'],['Додай типи до функції JS toggleTask.','Add types to the JS toggleTask function.']],{starter:blankJS,project:true});
lesson('JavaScript','values','Змінні та функції','Variables and functions',
 ['const не дозволяє повторне присвоєння, let дозволяє. Рядки, числа, boolean, null та undefined — різні типи. === порівнює без неявного перетворення.','Функція приймає параметри й повертає результат через return. Параметри — назви в оголошенні, аргументи — конкретні значення виклику. console.log лише виводить результат.'],
 ['const prevents reassignment; let allows it. Strings, numbers, booleans, null and undefined are different types. === compares without implicit conversion.','A function accepts parameters and returns a result through return. Parameters are names in a definition; arguments are values passed to a call. console.log only prints a result.'],
 'Оголоси userName = "Rubin" і напиши isPassed(score): true для score >= 60.','Declare userName = "Rubin" and write isPassed(score): true for score >= 60.',{js:'const userName = "Rubin";\nfunction isPassed(score) { return score >= 60; }\nconsole.log(userName, isPassed(60));'},[expression('userName === "Rubin"','Ім’я Rubin','Name is Rubin'),expression('isPassed(60) === true && isPassed(59) === false','Межа 60 працює','Boundary 60 works')],
 [['Що повертає результат функції?','What returns a function result?'],[['console.log','console.log'],['return','return'],['let','let']],1,['return передає значення виклику, log показує його.','return gives a value to the caller; log displays it.']], [['Рядок потребує лапок.','Quote the string.'],['Порівняння score >= 60 вже повертає boolean.','score >= 60 already produces a boolean.']],{starter:blankJS});
lesson('JavaScript','arrays','Масиви: map і filter','Arrays: map and filter',
 ['Масив — впорядкований список. map створює новий масив результатів, filter залишає елементи, callback яких повернув true. Обидва не змінюють оригінальний масив.','Для задач filter відбирає активні, потім map бере назви. Перевір порожній масив і завершені задачі. Не плутай assignment = із comparison ===.'],
 ['An array is an ordered list. map creates a new array of results; filter keeps items whose callback returns true. Neither mutates the original array.','For tasks, filter active items, then map their titles. Test empty arrays and completed items. Do not confuse assignment = with comparison ===.'],
 'Напиши activeTitles(items), яка повертає назви невиконаних задач.','Write activeTitles(items), returning titles of unfinished tasks.',{js:'function activeTitles(items) { return items.filter(item => !item.completed).map(item => item.title); }'},[expression('JSON.stringify(activeTitles([{title:"A",completed:false},{title:"B",completed:true}])) === JSON.stringify(["A"])','Повертається тільки A','Only A is returned'),expression('activeTitles([]).length === 0','Порожній масив працює','Empty array works')],
 [['Що робить filter?','What does filter do?'],[['Обирає за умовою','Selects by condition'],['Змінює кожний елемент','Transforms every item'],['Сортує автоматично','Automatically sorts']],0,['filter зберігає елементи з істинною умовою.','filter keeps items with a true predicate.']], [['Відбери !item.completed.','Keep !item.completed.'],['Додай map(item => item.title).','Add map(item => item.title).']],{starter:blankJS});
lesson('JavaScript','objects','Об’єкти й копіювання','Objects and copies',
 ['Об’єкт зберігає пари ключ–значення. task.title читає поле. {...task} створює поверхневу копію: вкладені об’єкти залишаються спільними.','{...task, completed: true} перевизначає поле після копіювання. Новий об’єкт спрощує порівняння станів і тестування. Перевір, що оригінал не змінився.'],
 ['Objects hold key-value pairs. task.title reads a field. {...task} makes a shallow copy: nested objects remain shared.','{...task, completed: true} overrides a field after copying. New objects simplify comparing state and testing. Verify that the original stays unchanged.'],
 'Напиши completeTask(task): новий об’єкт з completed: true без зміни оригіналу.','Write completeTask(task): a new object with completed: true without changing the original.',{js:'function completeTask(task) { return {...task, completed: true}; }'},[expression('completeTask({title:"A",completed:false}).completed === true','Стан завершено','State is completed'),expression('(()=>{const t={title:"A",completed:false};return completeTask(t)!==t && t.completed===false;})()','Оригінал не змінено','Original unchanged'),expression('completeTask({title:"A"}).title === "A"','Назву збережено','Title preserved')],
 [['Яку копію робить spread?','What kind of copy does spread make?'],[['Поверхневу','Shallow'],['Рекурсивну','Deep recursive'],['Жодної','None']],0,['Вкладені об’єкти не копіюються рекурсивно.','Nested objects are not copied recursively.']], [['Поверни {...task, completed: true}.','Return {...task, completed: true}.'],['Не присвоюй task.completed напряму.','Do not assign task.completed directly.']],{starter:blankJS});
lesson('JavaScript','async','Async і API','Async and APIs',
 ['async-функція повертає Promise. await чекає його результат усередині async. try/catch обробляє помилки, щоб показати зрозуміле повідомлення.','fetch не кидає помилку лише через HTTP 404: перевір response.ok перед response.json(). Тут fetch має локальну тестову відповідь; практика не надсилає запитів.'],
 ['An async function returns a Promise. await waits for its result inside async. try/catch handles failures so the UI can show a meaningful message.','fetch does not throw just because of HTTP 404: check response.ok before response.json(). Here fetch uses a local test response; practice sends no requests.'],
 'Напиши async loadTitles(): fetch /tasks, перевір response.ok, поверни масив title.','Write async loadTitles(): fetch /tasks, check response.ok and return an array of titles.',{js:'async function loadTitles() {\n const response = await fetch("/tasks");\n if (!response.ok) throw new Error("Request failed");\n const items = await response.json();\n return items.map(item => item.title);\n}'},[expression('JSON.stringify(await loadTitles()) === JSON.stringify(["HTML","CSS"])','Повернуто HTML і CSS із тестового API','HTML and CSS returned from test API'),source('js','response\\.ok','Є перевірка HTTP стану','HTTP status is checked')],
 [['Чи fetch автоматично кидає помилку на 404?','Does fetch automatically throw for 404?'],[['Так','Yes'],['Ні, перевір response.ok','No, check response.ok'],['Лише у CSS','Only in CSS']],1,['HTTP помилка може дати успішно отриману Response.','An HTTP error can still produce a fulfilled Response.']], [['await fetch повертає response.','await fetch returns a response.'],['await response.json() повертає список.','await response.json() returns a list.']],{starter:blankJS});
lesson('JavaScript','dom','DOM і події','DOM and events',
 ['DOM — об’єктне дерево документа. querySelector знаходить перший відповідний елемент. textContent записує текст без інтерпретації HTML; innerHTML потребує контрольованого безпечного вмісту.','addEventListener("click", handler) реєструє дію. Передай функцію, а не її виклик. Запусти код у живому прев’ю. Перевірка натискає кнопку двічі й очікує зміну лічильника від 0 до 2.'],
 ['DOM is the document object tree. querySelector finds the first matching element. textContent inserts plain text; innerHTML needs controlled safe content.','addEventListener("click", handler) registers an action. Pass a function, not its call. Run code in the live preview. The checker clicks twice and expects the counter to change from 0 to 2.'],
 'Знайди #count і #increment; додай click-обробник, який збільшує Number(count.textContent) на 1.','Select #count and #increment; attach a click handler that increments Number(count.textContent) by 1.',{html:'<p id="count">0</p><button id="increment" type="button">+1</button>',js:'const count = document.querySelector("#count");\nconst increment = document.querySelector("#increment");\nincrement.addEventListener("click", () => { count.textContent = String(Number(count.textContent) + 1); });'},[source('js','querySelector\\(["\x27]#count','Обрано лічильник','Counter selected'),source('js','querySelector\\(["\x27]#increment','Обрано кнопку','Button selected'),source('js','addEventListener\\(["\x27]click','Є click-обробник','Click handler exists'),source('js','textContent\\s*=','Текст оновлюється','Text is updated')],
 [['Що безпечно записує звичайний текст?','What safely inserts plain text?'],[['Будь-який innerHTML','Any innerHTML'],['textContent','textContent'],['eval','eval']],1,['textContent не інтерпретує HTML або скрипти.','textContent does not interpret HTML or scripts.']], [['Використай querySelector двічі.','Use querySelector twice.'],['Оновлення textContent має бути у callback.','Update textContent inside the callback.']],{kind:'source',starter:{html:'<p id="count">0</p><button id="increment" type="button">+1</button>',css:'',js:'// Select elements and attach a handler'}});
lesson('JavaScript','project','Мініпроєкт: модель задач','Mini project: task model',
 ['Відділи дані від DOM. Додавання й перемикання задач можна перевірити незалежно від сторінки. Такі функції спрощують імпорт і подальший розвиток.','Не змінюй вхідний масив або чужий об’єкт. Перевір невідомий ID і повторне перемикання. Нові масиви та копії дають передбачуваний результат.'],
 ['Separate data from DOM. Adding and toggling tasks can be tested independently of a page. These functions simplify importing and later development.','Do not mutate input arrays or existing objects. Test unknown IDs and toggling twice. New arrays and copies produce predictable results.'],
 'Напиши addTask(items, task) і toggleTask(items, id), які повертають нові масиви без зміни вхідних даних.','Write addTask(items, task) and toggleTask(items, id), returning new arrays without mutating input.',{js:'function addTask(items, task) { return [...items, {...task}]; }\nfunction toggleTask(items, id) { return items.map(task => task.id === id ? {...task, completed: !task.completed} : task); }'},[expression('addTask([], {id:"1",completed:false}).length === 1','Додавання працює','Adding works'),expression('toggleTask([{id:"1",completed:false}],"1")[0].completed === true','Перемикання працює','Toggling works'),expression('(()=>{const a=[{id:"1",completed:false}];toggleTask(a,"1");return !a[0].completed;})()','Оригінал збережено','Input preserved'),expression('!toggleTask([{id:"1",completed:false}],"missing")[0].completed','Невідомий ID безпечний','Unknown ID safe')],
 [['Навіщо відділяти модель від DOM?','Why separate the model from DOM?'],[['Для незалежних перевірок','For independent testing'],['Щоб сховати код','To hide code'],['Щоб вимкнути JS','To disable JS']],0,['Чисті функції можна перевіряти без інтерфейсу.','Pure functions can be tested without a UI.']], [['addTask використовує spread.','addTask uses spread.'],['toggleTask використовує map і копію потрібної задачі.','toggleTask uses map and copies the matching task.']],{starter:blankJS,project:true});
lesson('CSS','cascade','Селектори й каскад','Selectors and cascade',
 ['CSS складається із селектора та декларацій: .card { color: red; }. Клас можна повторювати, id має бути унікальним. Селектор тега обирає всі відповідні елементи.','За однакової важливості браузер порівнює специфічність, потім порядок правил. Клас точніший за тег. color успадковується, margin — ні. Не починай з !important: зрозумілі селектори легше підтримувати.'],
 ['CSS combines a selector and declarations: .card { color: red; }. Classes can repeat; IDs should be unique. A type selector matches elements of that type.','At equal importance, the browser compares specificity, then source order. A class is more specific than a type. color is inherited; margin is not. Avoid starting with !important: clear selectors are easier to maintain.'],
 'Задай .demo колір #ff3838 і h1 розмір 32px.','Give .demo color #ff3838 and h1 a 32px font size.',{css:'.demo { color: #ff3838; }\nh1 { font-size: 32px; }'},[computed('.demo','color','rgb(255, 56, 56)'),computed('h1','font-size','32px')],
 [['Що точніше: p чи .intro?','Which is more specific: p or .intro?'],[['p','p'],['.intro','.intro'],['Однаково','Equal']],1,['Клас має більшу специфічність за тег.','A class has greater specificity than a type selector.']], [['Почни з правила .demo.','Start with .demo.'],['Для h1 використай font-size.','Use font-size for h1.']]);
lesson('CSS','box','Блокова модель','Box model',
 ['Елемент має content, padding, border і margin. Padding знаходиться всередині рамки, margin — зовні. З content-box padding та border додаються до width.','border-box включає padding та border в задану ширину. Це зручний default для інтерфейсів. Розмір перевіряй у DevTools, а не лише на око.'],
 ['An element has content, padding, border and margin. Padding is inside the border; margin is outside. With content-box, padding and border increase the declared width.','border-box includes padding and border in the declared width. It is a useful interface default. Inspect dimensions in DevTools rather than relying only on appearance.'],
 'Задай .demo width 240px, padding 24px і border-box.','Set .demo width to 240px, padding to 24px and border-box.',{css:'.demo { box-sizing: border-box; width: 240px; padding: 24px; }'},[computed('.demo','box-sizing','border-box'),computed('.demo','width','240px'),computed('.demo','padding-top','24px')],
 [['Що створює внутрішній відступ?','What creates inner spacing?'],[['margin','margin'],['padding','padding'],['outline','outline']],1,['Padding розташований усередині рамки.','Padding is inside the border.']], [['Три властивості належать .demo.','All three properties belong to .demo.'],['Для розмірів потрібні px.','Use px for dimensions.']]);
lesson('CSS','flex','Flexbox','Flexbox',
 ['Flexbox розкладає безпосередніх дітей уздовж головної осі. За flex-direction: row головна вісь горизонтальна. justify-content керує головною, align-items — поперечною віссю.','gap створює проміжки. flex-wrap: wrap дозволяє переносити дітей. Для вертикального центрування важлива висота контейнера.'],
 ['Flexbox arranges direct children along a main axis. With row, the main axis is horizontal. justify-content controls the main axis; align-items controls the cross axis.','gap spaces items apart. flex-wrap: wrap lets children wrap. Vertical centering also depends on the container height.'],
 'Зроби .demo flex-контейнером із центруванням на обох осях та gap 16px.','Make .demo flex, center both axes and set a 16px gap.',{css:'.demo { display: flex; justify-content: center; align-items: center; gap: 16px; min-height: 200px; }'},[computed('.demo','display','flex'),computed('.demo','justify-content','center'),computed('.demo','align-items','center'),computed('.demo','gap','16px')],
 [['Що керує головною віссю?','What controls the main axis?'],[['align-items','align-items'],['justify-content','justify-content'],['z-index','z-index']],1,['justify-content працює вздовж головної осі.','justify-content operates along the main axis.']], [['Увімкни display: flex.','Set display: flex.'],['justify-content і align-items мають значення center.','Use center for justify-content and align-items.']]);
lesson('CSS','grid','Grid і колонки','Grid and columns',
 ['Grid працює з рядками й колонками. grid-template-columns задає колонки; 1fr — частка доступного простору. repeat(2, 1fr) створює дві рівні колонки.','minmax(0, 1fr) дозволяє колонкам стискатися. Для автоматичної сітки карток можна застосувати repeat(auto-fit, minmax(220px, 1fr)). Перевір довгі назви.'],
 ['Grid controls rows and columns. grid-template-columns defines tracks; 1fr is a share of available space. repeat(2, 1fr) creates two equal columns.','minmax(0, 1fr) lets tracks shrink. Responsive cards can use repeat(auto-fit, minmax(220px, 1fr)). Test long names.'],
 'Задай .demo Grid, дві колонки через repeat(2, …) та gap 20px.','Set .demo to Grid, two columns using repeat(2, …) and a 20px gap.',{css:'.demo { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 20px; }'},[computed('.demo','display','grid'),computed('.demo','gap','20px'),source('css','grid-template-columns\\s*:\\s*repeat\\(2,','Дві колонки через repeat','Two columns use repeat')],
 [['Що означає 1fr?','What does 1fr mean?'],[['Частка простору','Share of space'],['Один піксель','One pixel'],['Висота шрифту','Font height']],0,['fr розподіляє доступний простір.','fr distributes available space.']], [['Використай display: grid.','Use display: grid.'],['Колонки: repeat(2, minmax(0, 1fr)).','Tracks: repeat(2, minmax(0, 1fr)).']]);
lesson('CSS','responsive','Адаптивність і фокус','Responsive layouts and focus',
 ['Почни з однієї колонки й додавай колонки, коли контенту вистачає місця. @media (min-width: 600px) застосовує правило від 600px. Breakpoint обирають за вмістом, не за моделлю телефона.','Не прибирай outline без заміни. :focus-visible робить фокус клавіатури видимим. Перевір Tab, довгі тексти, проміжні ширини та prefers-reduced-motion.'],
 ['Start with one column and add more when content has room. @media (min-width: 600px) applies from 600px upward. Choose breakpoints by content, not phone models.','Never remove outline without replacing it. :focus-visible shows keyboard focus. Test Tab, long text, intermediate widths and prefers-reduced-motion.'],
 'Зроби одну колонку .demo, дві від 600px і додай button:focus-visible з outline 2px solid #ff3838.','Make .demo one column, two from 600px, and add button:focus-visible with outline 2px solid #ff3838.',{html:'<main class="demo"><button type="button">Kachan</button><p>Keep building.</p></main>',css:'.demo { display: grid; grid-template-columns: 1fr; }\n@media (min-width: 600px) { .demo { grid-template-columns: repeat(2, 1fr); } }\nbutton:focus-visible { outline: 2px solid #ff3838; }'},[computed('.demo','display','grid'),source('css','@media\\s*\\(min-width\\s*:\\s*600px\\)','Breakpoint 600px','600px breakpoint'),source('css',':focus-visible','Фокус клавіатури','Keyboard focus'),source('css','outline\\s*:\\s*2px\\s+solid','Видима рамка','Visible outline')],
 [['Коли спрацьовує min-width: 600px?','When does min-width: 600px apply?'],[['Від 600px','600px and above'],['До 600px','Below 600px'],['Лише на телефонах','Only on phones']],0,['min-width задає нижню межу.','min-width is the lower boundary.']], [['Базова сітка має одну колонку.','The base grid has one column.'],['Перевизнач колонки всередині media query.','Override tracks inside the media query.']]);
lesson('CSS','project','Мініпроєкт: картки','Mini project: cards',
 ['Поєднай семантичний HTML, блокову модель, Grid і адаптивність. Повторюваним карткам дай однаковий клас. Почни зі структури, потім додай відступи та стани.','Самоперевірка: немає горизонтального скролу, назви переносяться, кнопки мають фокус. Автоматичні умови не оцінюють усю якість дизайну.'],
 ['Combine semantic HTML, the box model, Grid and responsiveness. Give repeated cards one class. Start with structure, then add spacing and states.','Self-check: no horizontal overflow, names wrap and buttons have focus. Automated checks do not judge the entire design.'],
 'Створи два article.card у .demo, Grid із gap 16px, padding карток 24px, border-box і media query.','Create two article.card items in .demo, Grid with 16px gap, 24px card padding, border-box and a media query.',{html:'<main class="demo"><article class="card"><h2>Kachan</h2><button type="button">Open</button></article><article class="card"><h2>Portfolio</h2><button type="button">Open</button></article></main>',css:'* { box-sizing: border-box; }\n.demo { display: grid; gap: 16px; }\n.card { padding: 24px; border: 1px solid #ddd; border-radius: 12px; }\nbutton:focus-visible { outline: 2px solid #ff3838; }\n@media (min-width: 600px) { .demo { grid-template-columns: repeat(2, minmax(0, 1fr)); } }'},[computed('.demo','display','grid'),computed('.demo','gap','16px'),computed('.card','padding-top','24px'),computed('.card','box-sizing','border-box'),source('html','article class="card"','Є картки article','Article cards exist'),source('css','@media','Є адаптивність','Responsive rule exists')],
 [['Що ще перевірити вручну?','What else should be checked manually?'],[['Лише назву файла','Only the filename'],['Ширини, фокус і читабельність','Widths, focus and readability'],['Тільки колір','Only color']],1,['Якість адаптивності оцінюй на кількох ширинах.','Check responsiveness at multiple widths.']], [['Спочатку створи дві картки в HTML.','Create two cards in HTML first.'],['Відступи належать .card, розкладка — .demo.','Spacing belongs to .card; layout to .demo.']],{project:true});
