// Original teaching examples: explanation comes before terminology and assessment.
const beginnerLessons={};
function beginner(id,code,uk,en){beginnerLessons[id]={code,uk,en};}
beginner('javascript-comparisons','console.log(18 >= 18);\nconsole.log(18 === "18");',
['Програма повинна відповідати на питання: чи вистачає віку, чи задача виконана? Для цього є логічні результати true і false.','>= означає «більше або дорівнює». === порівнює значення без перетворення типів: число 18 відрізняється від тексту "18". Результат можна повернути з функції або використати в умові.','Перед запуском передбач два результати. Потім заміни 18 у першому рядку на 17.','Спочатку true і false; після зміни перший результат false. Для присвоєння використовують =, для порівняння ===.'],
['Programs answer questions such as whether an age is enough or a task is done. The answers are true and false.','>= means greater than or equal. === compares without conversion: numeric 18 differs from text "18". Return the result or use it in a condition.','Predict both outputs, then change the first age to 17.','Initially true and false; the changed first result is false. = assigns and === compares.']);
beginner('javascript-conditions','const age = 16;\nif (age >= 18) { console.log("adult"); }\nelse { console.log("minor"); }',
['Одна дія потрібна для дорослого, інша — для неповнолітнього. Умова обирає, який блок виконати.','Після if у дужках стоїть перевірка. Якщо вона істинна, працює перший блок. Якщо хибна, працює else. У цьому прикладі запуститься лише один console.log.','Зміни age на 18. Потім порівняй 17 і 19, пояснюючи вибір гілки.','Для 18 і 19 виводиться adult, для 17 — minor. Точна межа важлива: > 18 помилково виключить 18.'],
['Different actions may be needed for adults and minors. A condition chooses a block.','Parentheses after if contain the test. A truthy result selects its block; otherwise else runs. Only one log runs here.','Try ages 18, 17 and 19 and explain the branch.','18 and 19 print adult; 17 prints minor. > 18 would incorrectly exclude 18.']);
beginner('javascript-loops','for (let i = 1; i <= 3; i++) {\n  console.log(i);\n}',
['Замість трьох однакових команд можна описати повторення й межу. Це цикл.','let i=1 задає початок. i<=3 перевіряється перед кожним повтором. Після виконання тіла i++ додає 1. Коли i стане 4, умова false і цикл завершиться.','На папері запиши i для кожного повтору. Потім заміни <= на <.','Перший варіант друкує 1,2,3; другий 1,2. Якщо лічильник не змінюється, цикл може не завершитись.'],
['A loop describes repetition instead of duplicating commands.','let i=1 initializes, i<=3 checks before each iteration, and i++ increments afterward. At 4 the condition is false.','List counter values on paper, then replace <= with <.','Outputs change from 1,2,3 to 1,2. A counter that never advances can create an infinite loop.']);
beginner('javascript-strings','const original = " Alex ";\nconst clean = original.trim().toLowerCase();\nconsole.log(original, clean);',
['Текст користувача часто має зайві пробіли чи різний регістр. Рядкові методи допомагають нормалізувати його.','Метод — функція, яку викликають через крапку на значенні. trim() прибирає пробіли лише з країв; toLowerCase() повертає нижній регістр. Дужки запускають метод. Кожний крок повертає новий рядок.','Заміни вхід на " A B ". Передбач, чи зникне пробіл між літерами.','Результат "a b": внутрішній пробіл збережено, original не змінюється. Забуті дужки означають посилання на метод замість його результату.'],
['Input often has extra spaces or inconsistent case. String methods normalize it.','A method is a function called on a value through a dot. trim() removes edge spaces and toLowerCase() returns lowercase text. Parentheses call the method. Each produces a new string.','Try " A B " and predict the middle space.','The result is "a b", preserving the internal space and original input. Without parentheses you refer to a method rather than calling it.']);
beginner('css-units','.card { width: 100%; max-width: 400px; box-sizing: border-box; }',
['Блок має вміщатися в телефон і не ставати надто широким на комп’ютері. Поєднуй гнучку ширину з обмеженням.','width:100% займає доступну ширину контейнера, max-width:400px ставить верхню межу. px — одиниця довжини; rem прив’язаний до кореневого шрифту. border-box включає padding і рамку у ширину.','Порівняй контейнер шириною 300px і 600px. Потім додай padding:20px.','За цих умов картка має ширину 300px або 400px; padding входить усередину. Саме max-width не означає, що ширина завжди 400px.'],
['A box should fit a phone without becoming too wide on desktop. Combine flexibility with a limit.','width:100% follows the container and max-width:400px caps it. px is a length unit and rem relates to root font size. border-box includes padding and borders.','Compare 300px and 600px containers, then add 20px padding.','The box is 300px or 400px wide under these conditions, including padding. max-width does not force a constant 400px.']);
beginner('css-typography','p { font-size: 16px; line-height: 1.6; max-width: 65ch; }',
['Коли рядки злипаються чи розтягуються на весь монітор, навіть правильний текст важко читати.','font-size задає розмір, line-height:1.6 множить його на 1.6, max-width обмежує довжину рядка. ch орієнтується на ширину символу 0 у шрифті; 65ch не гарантує рівно 65 літер.','Встав довгий абзац. Порівняй line-height:1 і 1.6, потім прибери max-width.','Другий варіант дає більше простору між рядками, обмеження ширини полегшує читання. HTML-рівні заголовків обирають за змістом, а не за потрібним розміром.'],
['Cramped or extremely wide lines make text difficult to read.','font-size sets size, unitless line-height multiplies it and max-width limits line length. ch relates to the font’s 0 width, not an exact character count.','Compare a long paragraph with line-height:1 and 1.6, then remove max-width.','Larger line height creates breathing space and limited width helps reading. Choose HTML heading levels by meaning, not size.']);
// Each entry: real purpose, explanation, experiment, expected outcome.
beginner('html-document','<!doctype html>\n<html lang="uk">\n<head><meta charset="UTF-8"><title>My page</title></head>\n<body><h1>Hello!</h1></body>\n</html>',
['Ти пишеш текст, а браузер має зрозуміти, де назва вкладки, а де зміст сторінки. HTML — спосіб передати йому цю структуру. Файл .html можна відкрити браузером; сам текст коду пишуть у редакторі.', 'Кутові дужки позначають теги. <h1> відкриває заголовок, </h1> закриває його; разом із Hello! це елемент. body містить видимий зміст. head містить налаштування: title називає вкладку, charset задає кодування. Відступи допомагають людині побачити вкладеність, а не визначають її.', 'Заміни Hello! своїм ім’ям, а My page — назвою свого сайту. Перед запуском скажи, які дві ділянки браузера зміняться.', 'Ім’я з’явиться на сторінці, назва — на вкладці. Зміна title не створює заголовок у body. Якщо бачиш код як текст, перевір розширення файлу: воно має бути .html, не .txt.'],
['You write text, and the browser needs to know which part names the tab and which part belongs on the page. HTML communicates that structure. A browser opens an .html file; an editor is where you write it.', 'Angle brackets mark tags. <h1> opens a heading and </h1> closes it; together with Hello! they form an element. body holds visible content. head holds metadata: title names the tab, and charset selects character encoding. Indentation helps people see nesting; tags define it.', 'Replace Hello! with your name and My page with your site name. Predict which two browser areas change.', 'Your name appears on the page and your site name on the tab. title does not create a body heading. If the browser shows plain code, check that the file ends in .html rather than .txt.']);
beginner('html-text','<h1>My portfolio</h1>\n<h2>About me</h2>\n<p>I am learning <strong>HTML</strong>.</p>',
['Уяви зміст книги: назва, розділи й абзаци. Сторінці потрібна така сама зрозуміла структура.', 'h1 називає головну тему, h2 — її підрозділ. p створює абзац. strong виділяє важливий зміст, а не лише робить шрифт жирним. Розмір змінюють CSS, тому менший на вигляд заголовок не обов’язково має бути h3.', 'Додай h2 «Мої інтереси» і абзац під ним. Залиш тільки один головний заголовок у цій вправі.', 'Вийде одна тема й два підрозділи. Якщо використати багато br замість p, переноси з’являться, але структура абзаців не буде описана.'],
['Think of a book: title, sections and paragraphs. A page needs that same clear structure.', 'h1 names the main topic, h2 a section, and p a paragraph. strong marks important content. CSS controls visual size, so choosing h3 just to make text smaller changes the meaning.', 'Add an “Interests” h2 and a paragraph below it. Keep one main heading in this exercise.', 'You now have one topic and two sections. Many br elements make line breaks but do not describe paragraphs.']);
beginner('html-links','<a href="#contact">Contact</a>\n<section id="contact"><h2>Contact me</h2></section>',
['Меню має вести читача до потрібного місця. Посилання складається з адреси та зрозумілого напису.', 'a створює посилання. href — атрибут, тобто налаштування елемента; його значення тут #contact. Символ # означає місце на цій сторінці, а id дає цьому місцю унікальне ім’я. Текст між тегами — те, на що натискає читач.', 'Зміни id на contacts. Спочатку натисни старе посилання, потім виправ href.', 'Старе посилання більше не знайде ціль. Значення після # повинно точно збігатися з id. Для переходу на інший сайт потрібна повна адреса https://…'],
['A menu helps readers reach a place. A link contains a destination and a meaningful label.', 'a creates the link. href is an attribute: an element setting. #contact refers to this page, and id gives the destination a unique name. Text between the tags becomes the clickable label.', 'Rename id to contacts. Test the old link, then fix href.', 'The old link no longer finds its target. The value after # must match id exactly. Another website needs an address beginning with https://.']);
beginner('html-lists','<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n</ul>',
['Навички чи покупки — це окремі пункти, а не один довгий абзац. Список передає цю думку браузеру.', 'ul об’єднує рівнозначні пункти. Кожний пункт записують у li всередині списку. Для інструкції, де порядок важливий, використовують ol: номери тоді мають зміст.', 'Додай JavaScript третім пунктом. Потім заміни тільки ul на ol в обох тегах.', 'Пункти отримають номери. Не залишай закривальний </ul> після відкривального <ol>: парні теги мають збігатися.'],
['Skills or shopping items are separate entries rather than one paragraph. A list tells the browser that.', 'ul groups equivalent items, each written as an li child. ol represents a meaningful sequence such as instructions.', 'Add JavaScript as the third item. Then change both ul tags to ol.', 'The entries become numbered. An opening ol and closing ul do not match; keep the pair consistent.']);
beginner('html-images','<img src="photo.jpg" alt="My desk with a laptop" width="400">',
['Зображення — окремий файл. HTML вказує браузеру, де його знайти й що він означає.', 'src — шлях до файлу; photo.jpg тут шукається поряд із HTML. alt передає важливий зміст, коли зображення недоступне або його читає допоміжна програма. img не потребує закривального тега. width тут задає ширину в пікселях.', 'У своєму проєкті підстав реальну назву картинки. Потім навмисно зроби помилку в src.', 'Картинка не завантажиться, але alt залишиться її текстовою альтернативою. Виправ шлях і перевір регістр літер. Для суто декоративної картинки використовують alt="".'],
['An image is a separate file. HTML tells the browser where to find it and what it means.', 'src is a file path; photo.jpg is beside the HTML here. alt conveys important content when the image is unavailable or read by assistive software. img has no closing tag. width sets a pixel width.', 'Use an actual image filename in your project, then deliberately misspell src.', 'The image fails to load but alt remains its text alternative. Fix the path and capitalization. Pure decoration uses alt="".']);
beginner('html-semantics','<header><h1>My site</h1></header>\n<main><section><h2>Projects</h2></section></main>\n<footer>Contact</footer>',
['Коли сторінка росте, важливо бачити її частини: вступ, головний зміст і завершення.', 'header описує вступну область, main — головний зміст, footer — завершальну. section об’єднує тему із заголовком. Це ролі, а не готове оформлення: браузер не зробить із header красиве меню автоматично.', 'Додай розділ About усередині main з власним h2. Прочитай сторінку без CSS.', 'Порядок читання лишається зрозумілим. Для обгортки без окремої теми підійде div; не треба механічно замінювати кожний div на section.'],
['As a page grows, identify its introduction, main content and ending.', 'header describes introductory content, main the main content and footer an ending. section groups a topic with a heading. These are meanings, not automatic styling.', 'Add an About section with its own h2 inside main and read it without CSS.', 'The reading order stays meaningful. A wrapper without a distinct topic can use div; do not replace every div with section.']);
beginner('html-forms','<form>\n<label for="email">Email</label>\n<input id="email" name="email" type="email" required>\n<button type="submit">Send</button>\n</form>',
['Форма збирає дані: наприклад адресу для відповіді. Спершу людині треба зрозуміти, що вводити.', 'label називає поле. for зв’язується з id, тому натискання на підпис переводить фокус у input. type=email задає базову перевірку формату; required вимагає значення. name стане ключем даних при надсиланні. Тут немає сервера, тому лист не надсилається.', 'Натисни Send з порожнім полем, потім із text, потім із a@example.com.', 'Перші два значення браузер відхилить, третє пройде перевірку формату. Це не доводить існування адреси. Placeholder не замінює label.'],
['A form collects data, such as a reply address. People first need to know what to enter.', 'label names the field. for matches id, so clicking the label focuses input. type=email enables basic syntax validation, required requires a value, and name identifies submitted data. No server is connected here, so no email is sent.', 'Submit an empty value, text, then a@example.com.', 'The first two fail browser validation; the third has acceptable syntax. That does not prove the address exists. A placeholder does not replace label.']);
beginner('html-tables','<table><caption>Study hours</caption>\n<tr><th scope="col">Topic</th><th scope="col">Hours</th></tr>\n<tr><td>HTML</td><td>2</td></tr></table>',
['Таблиця потрібна, коли дані читають через перетин рядка й стовпця: тема та кількість годин.', 'tr — рядок, th — заголовок, td — значення. caption називає таблицю. scope=col пояснює, що заголовок стосується стовпця. Кожний рядок цього простого прикладу має дві комірки.', 'Додай рядок CSS із трьома годинами. Перевір, під яким заголовком стоїть число.', 'Тема має бути в першій комірці, число — у другій. Таблиці призначені для даних; картки й меню розташовують CSS.'],
['Tables suit data read by intersecting a row and a column: a topic and its hours.', 'tr is a row, th a header and td a value. caption names the table. scope=col associates a header with its column. Each simple row here has two cells.', 'Add a CSS row with three hours and inspect the number’s header.', 'The topic belongs in the first cell and hours in the second. Tables describe data; CSS arranges menus and cards.']);
beginner('html-accessibility','<button type="button">Open menu</button>\n<label for="name">Your name</label><input id="name">',
['Не всі користуються мишею або бачать екран однаково. Зручний сайт дозволяє виконати дію різними способами.', 'Нативна button уже підтримує фокус і клавіатуру. Tab переходить між інтерактивними елементами; Enter або Space активує кнопку. Підпис input пояснює поле. Видима рамка фокуса показує, де ти зараз.', 'Не торкаючись миші, дійди до кнопки й поля клавішею Tab. Повернись через Shift+Tab.', 'Обидва елементи доступні, і фокус видно. Клікабельний div без додаткової реалізації не дає такої поведінки. Не прибирай outline без іншого індикатора.'],
['People do not all use a mouse or perceive a screen the same way. A usable site supports different ways to act.', 'Native button already supports focus and keyboard activation. Tab moves between controls; Enter or Space activates buttons. A label names the input, and a visible focus outline shows your position.', 'Reach both controls using Tab, then go back with Shift+Tab.', 'Both are reachable with visible focus. A clickable div does not provide this behavior automatically. Do not remove outline without a replacement.']);
beginner('html-portfolio','<main><h1>My portfolio</h1>\n<section><h2>Projects</h2><article><h3>First page</h3><p>What I built.</p></article></section></main>',
['Портфоліо відповідає на три питання: хто ти, що зробив і як із тобою зв’язатися.', 'Не починай із кольорів. Запиши зміст, потім познач головну назву h1, розділи h2, окремий проєкт h3. article доречний для самостійної картки проєкту. Опис має пояснювати роботу, а посилання — вести до неї.', 'Додай другу картку з іншим описом і розділ контактів. Перевір кожне посилання.', 'З’явиться читабельна сторінка навіть без CSS. Не вигадуй досвід: навчальний проєкт можна так і назвати.'],
['A portfolio answers who you are, what you built and how to contact you.', 'Start with content, then use h1 for the page, h2 for sections and h3 for a project. article can represent a self-contained project card. Explain the work and link to it.', 'Add a second project with a different description and a contact section. Test every link.', 'The page remains readable without CSS. A practice project can honestly be described as practice.']);
beginner('css-cascade','.intro { color: #176c9d; }\np { color: gray; }',
['HTML описує текст, а CSS визначає його вигляд. Одне правило може оформити багато схожих елементів.', 'Селектор перед { шукає елементи. p означає всі абзаци; .intro — елементи з class="intro". Усередині стоїть властивість color і значення після двокрапки. Якщо обидва правила підходять одному абзацу, клас у цих звичайних правилах одного шару має більшу специфічність.', 'Напиши <p class="intro">Hello</p> і другий p без класу. Спрогнозуй кольори.', 'Перший буде блакитним, другий сірим. Якщо стиль не з’явився, перевір крапку перед назвою класу, збіг class і підключення CSS.'],
['HTML describes text; CSS controls appearance. One rule can style many related elements.', 'The selector before { finds elements. p matches paragraphs, .intro matches class="intro". Inside, color is a property followed by its value. In these ordinary same-layer rules, a class is more specific than a type selector.', 'Create an intro paragraph and a second paragraph without the class. Predict their colors.', 'The first is blue and the second gray. Check the class dot, spelling and stylesheet connection if nothing changes.']);
beginner('css-box','.card { width: 200px; padding: 20px; border: 2px solid; box-sizing: border-box; }',
['Картка — це коробка: текст усередині, простір довкола нього, рамка й відстань до сусідів.', 'padding створює внутрішній простір, border — рамку, margin — зовнішній. За border-box задані 200px включають padding і border, тому змісту лишається 156px. Без нього при content-box зовнішня ширина стане 244px.', 'Перемкни border-box на content-box та порівняй ширину. Збільш padding до 30px.', 'У border-box загальна ширина лишиться 200px, а зміст звузиться. У content-box зовнішня ширина виросте. Не плутай padding із gap між картками.'],
['A card is a box: content, inner space, border and distance from neighbors.', 'padding is inner space, border the edge and margin outer space. border-box includes padding and borders in 200px, leaving 156px for content. content-box instead produces a 244px outer width.', 'Switch to content-box, compare widths, then increase padding to 30px.', 'border-box keeps the total at 200px while content shrinks. content-box grows the outer box. padding is different from gap between cards.']);
beginner('css-flex','.row { display: flex; gap: 12px; justify-content: center; align-items: center; }',
['Потрібно поставити кнопки поруч і вирівняти їх. Flexbox керує дітьми одного контейнера вздовж однієї осі.', 'display:flex ставлять на батька кнопок, не на кожну кнопку. За замовчуванням головна вісь горизонтальна. justify-content вирівнює вздовж неї, align-items — поперек, gap додає проміжки. Для вертикального центрування має бути вільний простір по висоті.', 'Додай три кнопки у row, задавай контейнеру min-height:160px. Потім додай flex-direction:column.', 'Кнопки стануть стовпчиком. Головна вісь тепер вертикальна, тому значення властивостей ті самі, а напрям дії змінився.'],
['You want buttons next to each other and aligned. Flexbox controls a container’s children along an axis.', 'Put display:flex on their parent. The default main axis is horizontal; justify-content follows it, align-items crosses it and gap spaces children. Vertical centering needs available height.', 'Add three buttons to row with min-height:160px, then set flex-direction:column.', 'They form a column. The main axis is now vertical, changing the direction of alignment.']);
beginner('css-grid','.cards { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px; }',
['Для каталогу з кількома рядками й колонками зручніше задати сітку, а не вручну рухати кожну картку.', 'display:grid вмикає сітку батька. repeat(2,…) створює дві колонки. 1fr дає кожній половину доступного простору після gap. minmax(0,1fr) дозволяє колонці стискатись; довгий нерозривний текст усе ще треба переносити окремо.', 'Поклади чотири div у cards. Заміни 2 на 3 та перед запуском передбач розташування.', 'У першому рядку стане три картки, четверта перейде в другий. Порядок іде з HTML. Не задавай карткам ширину, більшу за їхню колонку.'],
['For a catalog with rows and columns, define a grid instead of positioning each card manually.', 'display:grid enables it on the parent. repeat creates two tracks, and 1fr shares available space after gaps. minmax(0,1fr) permits shrinking; long unbroken text still needs wrapping.', 'Add four child divs. Change 2 to 3 and predict placement.', 'Three cards occupy the first row and the fourth the second. HTML determines order. Avoid widths larger than a card’s track.']);
beginner('css-responsive','.cards { display: grid; grid-template-columns: 1fr; }\n@media (min-width: 700px) { .cards { grid-template-columns: 1fr 1fr; } }',
['На телефоні дві широкі картки можуть не вміститись. Адаптивність — зміна компонування відповідно до доступного простору.', 'Спочатку правило дає одну колонку. @media застосовує додаткове правило, коли ширина вікна не менша за 700px. Це умова, а не визначення моделі телефону. Однаковий сайт повинен працювати й на проміжних ширинах.', 'Порівняй 699px і 700px, потім додай довгий текст. Перевір також кнопку клавішею Tab.', 'На 700px з’являються дві колонки; зміст не обрізається, фокус видно. Якщо є горизонтальний скрол, шукай фіксовану ширину або нерозривний текст.'],
['Two wide cards may not fit a phone. Responsive design changes layout with available space.', 'The base rule has one column. @media adds a rule when the viewport is at least 700px wide. This is a condition, not a phone model; intermediate sizes must work too.', 'Compare 699px and 700px, add long text and reach a button with Tab.', 'At 700px there are two columns. Content should fit and focus remain visible. Overflow often comes from fixed widths or unbroken text.']);
beginner('css-project','.cards { display: grid; gap: 16px; }\n.card { padding: 24px; border: 1px solid #777; }',
['Мініпроєкт збирає правила в систему. Твоя мета — однакові картки, а не набір випадкових відступів.', 'Спочатку напиши зміст трьох карток. Для контейнера обери Grid, для картки — padding і border. Потім додай адаптивні колонки. Однаковий клас card дозволяє виправити всі картки одним правилом.', 'Зроби одну назву втричі довшою. Перевір вузьке вікно й повернись до звичайної назви.', 'Картки повинні зберігати зміст без обрізання. Гарний вигляд одного короткого прикладу ще не доводить, що компонування працює.'],
['A mini project combines rules into a system. Aim for consistent cards rather than unrelated spacing.', 'Write three cards first. Use Grid for their container and padding and border for each card, then add responsive columns. A shared class lets one rule fix every card.', 'Make one title three times longer and test a narrow viewport.', 'Content must remain visible. A layout working with short text alone is not enough.']);
beginner('javascript-values','const name = "Alex";\nfunction greet(person) { return "Hello, " + person; }\nconsole.log(greet(name));',
['JavaScript дозволяє отримувати результат із даних: наприклад привітати різних людей, не переписуючи повідомлення.', 'const дає значенню ім’я. Лапки позначають текст, + тут з’єднує рядки. function описує дію; person — параметр, місце для вхідного значення. return повертає результат, а greet(name) викликає функцію. console.log показує його в консолі, не на сторінці.', 'Зміни name, потім виклич greet двічі з різними текстами.', 'З’являться два різні привітання. Якщо забути return, виклик поверне undefined. Оголошення функції саме по собі її не запускає.'],
['JavaScript can produce results from data, such as greeting people without rewriting a message.', 'const names a value; quotes mark text. + joins strings here. function describes an action, person is its input parameter, return provides the result and greet(name) calls it. console.log displays it in the console, not the page.', 'Change name and call greet twice with different strings.', 'You see different greetings. Without return the call gives undefined. Defining a function does not run it.']);
beginner('javascript-arrays','const scores = [1, 2, 3];\nconsole.log(scores.map(score => score * 2));\nconsole.log(scores.filter(score => score > 1));',
['Масив зберігає список: результати, задачі чи товари. Часто треба змінити кожний пункт або залишити лише потрібні.', 'Квадратні дужки створюють масив. map бере кожне значення й записує результат callback у новий масив. filter залишає значення, для яких умова істинна. score => … — короткий запис функції з одним параметром.', 'Перед запуском запиши обидва результати. Заміни > 1 на > 10.', 'Перший результат [2,4,6], другий [2,3], а після зміни умови — []. Початковий scores у цьому прикладі не змінюється. map не призначений для відбору.'],
['An array holds a list: scores, tasks or products. You may need to transform every item or select some.', 'Square brackets create an array. map puts callback results into a new array. filter keeps values whose condition is true. score => … is a short one-parameter function.', 'Predict both outputs, then change > 1 to > 10.', 'Outputs are [2,4,6], [2,3], then []. scores remains unchanged here. map does not select items.']);
beginner('javascript-objects','const task = { title: "Learn", done: false };\nconst updated = { ...task, done: true };\nconsole.log(task.done, updated.done);',
['Одна задача має кілька пов’язаних властивостей. Об’єкт об’єднує їх в одному записі.', 'Фігурні дужки містять пари ключ:значення. task.title читає назву. false і true — логічні значення, не тексти. ...task копіює верхній рівень властивостей у новий об’єкт; done:true після нього замінює скопійоване значення.', 'Заміни title лише в updated. Виведи обидві назви.', 'Назва task не зміниться. Але вкладені об’єкти при такому копіюванні можуть залишатися спільними: це поверхнева копія.'],
['A task has related properties. An object groups them into one record.', 'Braces contain key:value pairs. task.title reads a property. false and true are booleans rather than text. ...task copies top-level properties; the later done:true overrides one.', 'Change title only in updated and print both titles.', 'task stays unchanged. Nested objects can remain shared because this is a shallow copy.']);
beginner('javascript-async','async function load() {\n  const response = await fetch("/data.json");\n  if (!response.ok) throw new Error("Request failed");\n  return await response.json();\n}',
['Дані з сервера приходять не миттєво. Поки запит іде мережею, сайт має чекати результат або показувати стан завантаження.', 'fetch повертає Promise — майбутній результат. await усередині async чекає його. response.ok перевіряє HTTP-успіх; json() читає тіло й перетворює JSON на дані. JSON — текстовий формат, об’єкт JavaScript — значення у програмі.', 'У власному проєкті створи data.json із {"name":"Alex"}. Виклич load().then(console.log).catch(console.error) через локальний сервер.', 'Побачиш об’єкт або помилку. 404 сам по собі не відхиляє fetch, тому потрібен response.ok. У практиці Kachan використовуй її навчальний API, а не цей зовнішній запит.'],
['Server data is not instant. While a request travels, the app waits for a result or displays loading.', 'fetch returns a Promise: a future result. await inside async waits for it. response.ok checks HTTP success; json() parses the body into data. JSON is text, while a JavaScript object is a program value.', 'In your own project create data.json containing {"name":"Alex"}. Call load().then(console.log).catch(console.error) using a local server.', 'You get an object or an error. fetch does not reject just because of a 404; check ok. Kachan exercises use their training API instead of this request.']);
beginner('javascript-dom','const button = document.querySelector("button");\nbutton.addEventListener("click", () => {\n  button.textContent = "Done";\n});',
['HTML створює кнопку, але дія після натискання потребує JavaScript. DOM — дерево елементів сторінки, з яким працює код.', 'document представляє документ. querySelector шукає перший елемент за CSS-селектором. addEventListener підписує функцію на подію click. Код усередині запуститься після натискання. textContent записує звичайний текст без інтерпретації HTML.', 'Створи <button type="button">Start</button>, виконай код і натисни кнопку.', 'Напис зміниться на Done. Якщо querySelector повернув null, елемент не знайдено: перевір селектор і чи код запускається після створення HTML.'],
['HTML creates a button; JavaScript supplies its action. The DOM is the page’s element tree available to code.', 'document represents the page. querySelector finds the first CSS-selector match. addEventListener registers a callback for click, which runs after a click. textContent writes plain text without parsing HTML.', 'Create a Start button, run the code and click it.', 'Its label becomes Done. null means the selector found nothing: check spelling and whether the element existed when the code ran.']);
beginner('javascript-project','const tasks = [{ id: 1, title: "HTML", done: false }];\nconst completed = tasks.map(task => task.id === 1 ? { ...task, done: true } : task);',
['Список задач починається з моделі даних. Екран можна змінювати, але зміст задач має бути описаний незалежно від кнопок.', 'id відрізняє записи, title зберігає назву, done — стан. map переглядає весь список. Умова task.id===1 вибирає запис; ? … : … означає результат для істинної та хибної умови. Новий об’єкт створюється лише для вибраної задачі.', 'Додай задачу з id:2. Перевір, що виконаною стала тільки перша.', 'Другий запис не змінюється. Не використовуй індекс масиву як постійний id, якщо записи можна видаляти чи переставляти.'],
['A task app begins with a data model independent of its buttons.', 'id distinguishes records, title holds text and done holds state. map visits the list. task.id===1 selects a record; ? … : … chooses a value for true or false. Only the selected task gets a new object.', 'Add a task with id:2 and complete only the first.', 'The second is unchanged. An array position is a poor permanent id when records can be deleted or reordered.']);
beginner('git-init','git init\ngit status',
['Ти змінив файл і хочеш пам’ятати попередні робочі версії. Git зберігає історію проєкту на твоєму комп’ютері.', 'Термінал — місце для текстових команд. Спочатку відкрий його в папці проєкту. git init створює сховище історії .git, а git status показує стан файлів. Це ще не публікація в інтернеті. GitHub — окремий сервіс для розміщення репозиторіїв.', 'У симуляторі виконай обидві команди й прочитай статус.', 'Репозиторій створено, але коміту ще немає. Не запускай init у випадковій батьківській папці: спочатку перевір, де ти знаходишся.'],
['You changed a file and want to keep previous working versions. Git records project history locally.', 'A terminal accepts text commands. Open it in the project folder first. git init creates the .git history store; status reports file state. This does not publish anything online. GitHub is a separate repository-hosting service.', 'Run both commands in the simulator and read the status.', 'A repository exists but there is no commit. Check your directory before initializing a real project.']);
beginner('git-commit','git add index.html\ngit commit -m "Add heading"\ngit status',
['Потрібно зберегти одну завершену зміну в історію. Коміт — зафіксований стан із поясненням.', 'Спершу файли змінюються у робочій папці. add обирає поточні зміни для наступного коміту — це індекс. commit записує вибране. -m задає повідомлення в лапках. Якщо після add знову редагувати файл, нові зміни ще раз треба додати.', 'Після init додай index.html, зроби коміт і перевір статус.', 'У симуляторі з’явиться коміт. add не надсилає файли на GitHub. Повідомлення повинно пояснювати зміну, а не просто «update».'],
['Save one completed change in history. A commit is a recorded state with an explanation.', 'Edits happen in the working folder. add selects current changes for the next commit, called staging. commit records them and -m supplies a quoted message. Edits made after staging need staging again.', 'After init, stage index.html, commit and inspect status.', 'The simulator records a commit. add does not upload to GitHub. Describe the change in your message.']);
beginner('git-branches','git switch -c experiment\ngit switch main',
['Хочеш спробувати нову ідею, зберігаючи окремий напрям роботи. Для цього є гілки.', 'Гілка вказує на коміт. switch -c створює нову гілку й переходить у неї, звичайний switch переходить до наявної. Файли не дублюються в окрему папку: Git змінює робочу копію відповідно до вибраної історії.', 'У симуляторі спочатку створи стартовий коміт, потім experiment і повернися до main.', 'Обидві гілки існують. Незбережені зміни можуть перешкодити перемиканню; у реальному проєкті перевіряй status перед switch.'],
['Try an idea on a separate line of work by using a branch.', 'A branch points to a commit. switch -c creates and selects it; switch selects an existing branch. Git changes the working copy rather than creating a separate folder.', 'Create an initial commit in the simulator, create experiment, then return to main.', 'Both branches exist. Uncommitted changes can prevent switching; inspect status in a real project first.']);
beginner('git-merge','git switch main\ngit merge feature',
['Коли окрема робота готова, її потрібно об’єднати з основним напрямом.', 'merge приєднує історію названої гілки до поточної. Тому спочатку переходять у main. Якщо обидві сторони змінили те саме місце несумісно, Git просить людину вибрати результат: це конфлікт, а не втрата всього проєкту.', 'У навчальній вправі створи потрібні гілки й перед merge перевір поточну.', 'Зміни потраплять у ту гілку, де ти стоїш. У реальному конфлікті прочитай обидва варіанти, прибери маркери й перевір готовий файл перед комітом.'],
['Once separate work is ready, combine it with the main line.', 'merge brings a named branch’s history into the current branch, so select main first. Incompatible edits to the same area may need a human decision: a conflict.', 'Create the branches required by the exercise and inspect the current branch before merging.', 'Changes enter the branch you are on. For real conflicts, read both versions, remove markers and verify the final file before committing.']);
beginner('git-remote','git remote add origin https://github.com/example/demo.git\ngit fetch origin\ngit push -u origin main',
['Щоб перенести історію на інший комп’ютер, потрібен віддалений репозиторій. Це адреса сховища, а не сама гілка.', 'origin — звичайне ім’я цієї адреси. fetch отримує віддалену історію без автоматичного об’єднання з твоєю гілкою. push надсилає коміти. -u встановлює зв’язок із відповідною віддаленою гілкою. Адреса в прикладі умовна.', 'У симуляції виконай команди з адресою, яку вимагає завдання. Перед push зроби коміт.', 'Надсилаються коміти, а не просто незбережені зміни файлу. У справжньому GitHub потрібні доступ і автентифікація; симулятор їх не налаштовує.'],
['A remote repository lets history travel between computers. It is a storage address, not a branch.', 'origin is a conventional remote name. fetch downloads history without merging your branch; push uploads commits. -u establishes an upstream branch. The example URL is a placeholder.', 'Use the exercise’s URL in the simulator and commit before pushing.', 'push sends commits, not uncommitted file edits. Real GitHub needs authentication; the simulator does not configure it.']);
beginner('git-project','git status\ngit add index.html\ngit commit -m "Build page"\ngit push',
['Повторюваний робочий цикл допомагає не загубити зміни й пояснити свою роботу.', 'Редагуй одну логічну частину, перевір її, подивись status, обери файли, зроби коміт і лише потім push. Секрети й паролі не повинні потрапляти в історію. Для першої публікації remote і upstream налаштовують окремо.', 'Перед кожною командою поясни, які дані вона змінить: файли, індекс, історію чи сервер.', 'add змінює індекс, commit — локальну історію, push — remote. status лише показує стан. Це різні кроки, не взаємозамінні кнопки.'],
['A repeatable workflow keeps changes safe and understandable.', 'Edit one logical part, check it, inspect status, stage files, commit and then push. Keep secrets out of history. Set up a remote and upstream before the first publication.', 'Explain whether each command affects files, staging, history or a server.', 'add updates staging, commit local history and push the remote. status only reports state. These steps are not interchangeable.']);
beginner('typescript-types','const price: number = 20;\nconst label: string = "Book";\nconst available: boolean = true;',
['Після JavaScript ти вже знаєш значення. TypeScript додає перевірку того, які значення дозволені, ще до запуску.', 'number — число, string — текст, boolean — true або false. Після : стоїть опис типу, не саме значення. TypeScript також часто визначає тип сам. Перед запуском у браузері типові позначення прибираються компілятором.', 'Спробуй присвоїти price текст "20" у TypeScript-практиці.', 'Перевірка типів відхилить текст замість числа. Тип не перетворює "20" на 20 і не перевіряє, що ціна додатна.'],
['After learning JavaScript values, TypeScript checks which values are allowed before execution.', 'number means numeric, string text and boolean true or false. After : comes a type description rather than a value. Types can also be inferred and are removed during compilation.', 'Try assigning "20" to price in TypeScript practice.', 'The checker rejects text where a number is required. A type does not convert text or ensure a positive price.']);
beginner('typescript-unions','type Status = "todo" | "done";\nconst status: Status = "todo";',
['Статус задачі повинен мати лише кілька допустимих значень. Довільний текст легко створює помилки.', 'type дає ім’я опису типу. Символ | означає «або»: тут дозволені лише точні тексти todo і done. Це літеральні типи. Вони допомагають компілятору помітити помилку в написанні.', 'Заміни todo на doing, а потім на done.', 'doing не входить у тип, done входить. Якщо вводиш статус із сервера, перевір його під час виконання: опис типу не перевіряє зовнішні дані сам.'],
['Task status should have a few allowed values, not arbitrary text.', 'type names a type description. | means either: only the exact strings todo and done are allowed. Literal types help catch spelling mistakes.', 'Replace todo with doing, then done.', 'doing is rejected and done accepted. Server input still needs runtime validation; a type alone does not check it.']);
beginner('typescript-interfaces','interface User { name: string; age?: number; }\nconst user: User = { name: "Alex" };',
['Коли функції передають записи, їм потрібна домовленість про форму даних.', 'interface описує властивості об’єкта. name обов’язкова й текстова. ? біля age робить поле необов’язковим. Опис інтерфейсу не створює користувача; об’єкт створює запис після =.', 'Додай age:20, потім спробуй об’єкт без name.', 'Вік допустимий, відсутнє ім’я — помилка. Читання необов’язкового поля вимагає враховувати undefined.'],
['Functions exchanging records need an agreement about their shape.', 'interface describes properties. name is required text; ? makes age optional. The interface creates no user; the expression after = creates the object.', 'Add age:20, then try an object without name.', 'Age is accepted; missing name is rejected. Reading an optional field must account for undefined.']);
beginner('typescript-generics','function first<T>(items: T[]): T | undefined {\n  return items[0];\n}',
['Одна функція може працювати зі списком чисел і зі списком текстів, зберігаючи правильний тип результату.', 'T — ім’я параметра типу. T[] означає масив цих значень. Для чисел T стане number, для текстів string. |undefined враховує порожній список. Це не довільне any: зв’язок між входом і виходом зберігається.', 'Порівняй first([10]), first(["a"]) і first([]).', 'Результати 10, "a" й undefined. Не обіцяй завжди T, якщо масив може бути порожнім.'],
['One function can handle numbers and strings while preserving the result type.', 'T is a type parameter and T[] an array of that type. Numbers infer number, strings infer string. |undefined accounts for an empty array. This preserves an input-output relationship rather than using any.', 'Compare first([10]), first(["a"]) and first([]).', 'Results are 10, "a" and undefined. Do not promise T for a possibly empty list.']);
beginner('typescript-narrowing','function lengthOf(value: unknown) {\n  if (typeof value === "string") return value.length;\n  return 0;\n}',
['Зовнішні дані можуть бути чим завгодно. Без перевірки небезпечно поводитися з ними як із текстом.', 'unknown означає «тип ще не відомий». typeof перевіряє значення під час виконання. Усередині if компілятор уже знає, що це string: звуження типу, або narrowing. Лише там можна читати довжину як довжину тексту.', 'Передай "hello", 10 і null.', 'Повернуться 5, 0 і 0. typeof null дорівнює object; для перевірки об’єктів потрібна окрема перевірка на null і, за потреби, масив.'],
['External data can be anything. Treating it as text without checking is unsafe.', 'unknown means the type is not known yet. typeof checks at runtime; inside if the compiler knows value is a string. This narrowing allows string operations.', 'Pass "hello", 10 and null.', 'Results are 5, 0 and 0. typeof null is object, so object validation needs a separate null check and sometimes an array check.']);
beginner('typescript-project','interface Task { id: number; title: string; done: boolean; }\nfunction active(tasks: Task[]): Task[] {\n  return tasks.filter(task => !task.done);\n}',
['Типізований список задач об’єднує форму запису та поведінку функцій.', 'Task описує один запис, Task[] — список. active приймає та повертає списки Task. !task.done означає «не виконано». Типи перевіряють форму даних, filter реалізує відбір. Обидві частини потрібні.', 'Передай одну виконану й одну активну задачу. Потім заміни умову на task.done.', 'Спочатку повернеться активна задача, потім виконана. Обидва варіанти можуть компілюватися: неправильну логіку помічає поведінкова перевірка.'],
['A typed task list combines record shape with function behavior.', 'Task describes one record and Task[] a list. active accepts and returns such lists. !task.done means unfinished. Types check shapes; filter implements selection.', 'Pass one completed and one active task, then reverse the predicate.', 'The result changes from active to completed. Both may compile, so behavior tests are still necessary.']);
beginner('figma-frames','Mobile (390 × 844)\n  Header\n  Content\n  Footer',
['Перед кодом можна спланувати екран. Figma — редактор макетів; він не створює готовий сайт автоматично.', 'Фрейм — область із розмірами, подібна до екрана. Layers показує дерево вкладених об’єктів. У прикладі Header, Content і Footer — діти Mobile. Перейменування шарів допомагає читати структуру.', 'Створи Mobile, додай три вкладені фрейми й перемісти батька.', 'Усі три секції рухаються разом. Якщо одна лишилась, перевір її батька в Layers. Звіт JSON у Kachan записує твою перевірку, але не читає файл Figma.'],
['Plan a screen before coding. Figma is a design editor, not an automatic website builder.', 'A frame is a sized area like a screen. Layers shows nesting. Header, Content and Footer are children of Mobile here. Named layers make the structure readable.', 'Create the frames and move their parent.', 'All sections should move together. Check nesting if one stays behind. Kachan’s JSON report records your review; it cannot inspect the Figma file.']);
beginner('figma-auto-layout','Card\n  Title\n  Description\n  Button\nGap: 16 · Padding: 24 · Height: Hug',
['Якщо опис стане довшим, кнопка не повинна накривати текст. Auto Layout дозволяє змісту керувати розташуванням.', 'Вертикальний напрям розкладає дітей зверху вниз. Gap — відстань між ними, padding — від краю картки. Hug підлаштовує розмір під зміст, Fill займає доступне місце у відповідному батьківському компонуванні.', 'Зроби опис із трьох рядків, потім із шести. Перевір висоту картки.', 'Висота має збільшитись, а проміжки — зберегтись. Фіксована мала висота може обрізати зміст; це перевіряють у макеті, не лише у звіті.'],
['Longer text should push a button down rather than cover it. Auto Layout lets content drive placement.', 'Vertical layout stacks children; gap separates them and padding separates content from edges. Hug sizes to content, while Fill occupies available parent layout space.', 'Change the description from three lines to six.', 'The card should grow while spacing stays consistent. A small fixed height can clip content; inspect the actual design.']);
beginner('figma-components','Button component\n  Default\n  Hover\n  Disabled\nInstance → local label',
['На сайті багато однакових кнопок. Компонент дозволяє підтримувати їх як одну систему.', 'Головний компонент задає основу, екземпляр використовує її. Зміна основи поширюється на екземпляри, якщо властивість не перевизначена локально. Варіант — стан або різновид компонента, не нова випадкова копія.', 'Створи два екземпляри, зміни їхні написи, потім колір головного компонента.', 'Обидва успадкують колір, а написи залишаться власними. Не від’єднуй екземпляри лише заради зміни тексту.'],
['Repeated buttons should belong to one system. Components keep them consistent.', 'The main component defines a base; instances use it. Base changes propagate unless locally overridden. Variants represent states or kinds rather than unrelated copies.', 'Make two instances, change labels, then change the main color.', 'Both inherit the color while keeping local labels. Detaching is unnecessary just to change text.']);
beginner('figma-typography','Page title: 32\nSection heading: 24\nBody: 16\nLine height: 24',
['Читач має одразу бачити головну тему й пояснення. Типографічна ієрархія створює цей порядок.', 'Обери кілька повторюваних розмірів, а не окремий стиль для кожного напису. Міжрядкова відстань дає тексту простір. Стиль тексту дозволяє змінити всі пов’язані написи разом. Числа прикладу — навчальна шкала, не універсальна вимога.', 'Зроби заголовок і два абзаци. Звузь фрейм і перевір довгий заголовок при 100%.', 'Текст переноситься без обрізання, заголовок відрізняється від абзацу. Не оцінюй читабельність лише на сильно зменшеному масштабі.'],
['Readers need to distinguish the main topic from its explanation. Typography creates that hierarchy.', 'Choose a small repeatable size scale and enough line spacing. Text styles update related labels together. These numbers are a practice scale, not universal requirements.', 'Create a heading and paragraphs, narrow the frame and inspect a long heading at 100%.', 'Text should wrap without clipping, with a clear hierarchy. A zoomed-out view is not enough to judge readability.']);
beginner('figma-prototype','Home → click Project → Project\nProject → click Back → Home',
['Макет показує вигляд, прототип — як людина переходить між екранами.', 'Зв’язок має початковий елемент, подію та ціль. Натискання картки веде до Project, Back повертає на Home. Present дозволяє пройти сценарій. Це імітація взаємодії, не справжня база даних чи JavaScript.', 'Пройди обидва переходи в Present. Спробуй натиснути поза карткою.', 'Спрацьовувати має потрібна область; повернення не веде в тупик. Підпис Back без налаштованого зв’язку сам нічого не робить.'],
['A design shows appearance; a prototype shows navigation between screens.', 'A connection has a source, trigger and destination. The card leads to Project and Back to Home. Present lets you walk the scenario. This simulates interaction rather than a database or JavaScript.', 'Test both transitions in Present and click outside the card.', 'Only the intended area should act and the return should work. A Back label alone creates no interaction.']);
beginner('figma-project','Desktop / Mobile\nNavigation → Content → Action\nDefault / Empty / Long content',
['Готовий макет має пояснювати наступну дію і працювати з різним змістом, а не лише з красивими короткими написами.', 'Спочатку склади сценарій: куди людина заходить, що читає, що натискає. Повторно використовуй компоненти. Потім перевір широкий і вузький екран, порожні дані й довгі назви. Усі стани належать одному продукту.', 'Створи порожній список і список із довгою назвою. Перевір їх на Mobile.', 'Порожній стан пояснює, що робити, довга назва не накриває кнопку. Звіт у Kachan підтверджує лише записані значення; макет перевіряй вручну.'],
['A finished design explains the next action and handles varied content rather than only short attractive labels.', 'Plan the user flow, reuse components, then test wide and narrow screens, empty data and long titles. All states should belong to one product.', 'Create an empty list and a long-title list on Mobile.', 'The empty state guides an action and the title does not overlap controls. Kachan checks report values; review the design manually.']);
for(const id of ['javascript-comparisons','javascript-conditions','javascript-loops','javascript-strings','css-units','css-typography']){const row=beginnerLessons[id];depthExamples[id]=[row.code,row.uk[1],row.en[1]];}
