// Load before saved academy state: new lesson IDs must exist during validation.
lesson('JavaScript','comparisons','Порівняння та логічні значення','Comparisons and booleans',
 ['Порівняння ставить питання й повертає true або false. 5 > 3 — true, 5 === 3 — false. === перевіряє рівність без автоматичного перетворення типів. Один = присвоює значення, тому це інша дія.','&& означає, що обидві умови мають виконатися; || — достатньо однієї. ! змінює логічне значення на протилежне.'],
 ['A comparison asks a question and returns true or false. 5 > 3 is true; 5 === 3 is false. === compares without converting types. A single = assigns rather than compares.','&& requires both conditions; || requires either; ! negates a boolean.'],
 'Напиши isAdult(age), яка повертає true для віку від 18 включно й false для меншого.','Write isAdult(age), returning true for ages at least 18 and false otherwise.',{js:'function isAdult(age) { return age >= 18; }'},[expression('isAdult(18) === true','18 — повнолітній','18 is adult'),expression('isAdult(17) === false','17 — неповнолітній','17 is not adult'),expression('isAdult(30) === true','30 — повнолітній','30 is adult')],
 [['Який оператор перевіряє рівність без перетворення типів?','Which checks equality without conversion?'],[['=','='],['===','==='],['+','+']],1,['=== порівнює, = присвоює.','=== compares; = assigns.']],[['Порівняй age з 18.','Compare age with 18.'],['Потрібен >=, бо 18 входить у результат true.','Use >= to include 18.']],{starter:{html:'',css:'',js:'function isAdult(age) {\n  // Return a boolean\n}'}});
lesson('JavaScript','conditions','Умови if і else','if and else conditions',
 ['if виконує блок лише за істинної умови. else містить іншу гілку. Блок — інструкції між фігурними дужками. Функція може повертати різні значення залежно від входу.','return завершує виклик функції. Якщо умова false і жоден return не виконався, функція може повернути undefined. Перевір обидві гілки й точну межу.'],
 ['if runs a block when its condition is truthy; else runs the alternative. Braces delimit a block. A function can return different results for different inputs.','return ends the call. If no return runs, a function may return undefined. Test both branches and the exact boundary.'],
 'Напиши labelAge(age): від 18 поверни "adult", інакше "minor".','Write labelAge(age): return "adult" for ages at least 18, otherwise "minor".',{js:'function labelAge(age) {\n  if (age >= 18) return "adult";\n  return "minor";\n}'},[expression('labelAge(18) === "adult"','Межа 18','Boundary 18'),expression('labelAge(12) === "minor"','Менший вік','Younger age'),expression('labelAge(40) === "adult"','Більший вік','Older age')],
 [['Що робить else?','What does else do?'],[['Повторює блок','Repeats a block'],['Виконує іншу гілку','Runs an alternative branch'],['Створює масив','Creates an array']],1,['else обирається, коли умова if хибна.','else runs when the if condition is falsy.']],[['Спочатку перевір age >= 18.','Check age >= 18 first.'],['Обидва результати мають бути текстами в лапках.','Both results are quoted strings.']],{starter:{html:'',css:'',js:'function labelAge(age) {\n  // Choose and return a label\n}'}});
lesson('JavaScript','loops','Цикли та накопичення','Loops and accumulation',
 ['Цикл повторює інструкції. У for спочатку створюють лічильник, потім перевіряють умову перед кожним повтором, після повтору змінюють лічильник. i++ збільшує i на 1.','Накопичувач total починається з 0; total += i додає поточне число. let потрібен для значень, які переприсвоюються. Якщо умова ніколи не стане хибною, цикл не завершиться.'],
 ['A loop repeats instructions. for initializes a counter, checks a condition before each iteration and updates the counter afterward. i++ increases i by one.','An accumulator starts at 0; total += i adds the current number. let supports reassignment. A condition that never becomes false creates an infinite loop.'],
 'Напиши sumTo(n), яка додає цілі числа від 1 до n включно. Для 0 поверни 0.','Write sumTo(n), adding integers from 1 through n inclusive. Return 0 for n=0.',{js:'function sumTo(n) {\n  let total = 0;\n  for (let i = 1; i <= n; i++) total += i;\n  return total;\n}'},[expression('sumTo(3) === 6','1+2+3 = 6','1+2+3 = 6'),expression('sumTo(0) === 0','Нуль без повторень','Zero without iterations'),expression('sumTo(5) === 15','П’ять чисел','Five numbers')],
 [['Навіщо i++ у цьому циклі?','Why is i++ needed?'],[['Рухатись до завершення','Advance toward termination'],['Вивести текст','Print text'],['Змінити HTML','Change HTML']],0,['Лічильник росте до межі й умова стає хибною.','The counter reaches the limit so the condition becomes false.']],[['Створи total=0 перед циклом.','Initialize total=0 before the loop.'],['Поверни total після завершення, не всередині першого повтору.','Return total after the loop, not during its first iteration.']],{starter:{html:'',css:'',js:'function sumTo(n) {\n  // Add integers 1 through n\n}'}});
lesson('JavaScript','strings','Рядки та обробка тексту','Strings and text processing',
 ['Рядок — текст у лапках. Методи рядка повертають перетворений результат: trim прибирає пробіли з країв, toLowerCase змінює регістр. Початковий рядок ці методи не змінюють.','Послідовність викликів читають зліва направо: спочатку trim, потім toLowerCase. length рахує одиниці UTF-16, а не завжди видимі символи; для цієї вправи достатньо звичайного латинського тексту.'],
 ['A string is quoted text. trim removes whitespace at the edges and toLowerCase changes case, returning results without modifying the original string.','Chained calls read left to right: trim, then toLowerCase. length counts UTF-16 units, not necessarily visible characters; this exercise uses ordinary Latin text.'],
 'Напиши normalizeName(value), яка прибирає крайові пробіли та повертає текст малими літерами.','Write normalizeName(value), trimming edge whitespace and lowercasing.',{js:'function normalizeName(value) { return value.trim().toLowerCase(); }'},[expression('normalizeName(" Alex ") === "alex"','Пробіли й регістр','Spaces and case'),expression('normalizeName("") === ""','Порожній текст','Empty string'),expression('normalizeName("A B") === "a b"','Внутрішній пробіл збережено','Inner space preserved')],
 [['Що прибирає trim?','What does trim remove?'],[['Усі літери','All letters'],['Пробіли з країв','Edge whitespace'],['Усі внутрішні пробіли','All internal spaces']],1,['Внутрішні пробіли залишаються.','Internal spaces remain.']],[['Виклич trim на value.','Call trim on value.'],['Поверни результат toLowerCase.','Return the lowercased result.']],{starter:{html:'',css:'',js:'function normalizeName(value) {\n  // Return cleaned lowercase text\n}'}});
lesson('CSS','units','Розміри та одиниці','Sizes and units',
 ['CSS-число часто потребує одиниці: 16px — довжина. rem залежить від розміру кореневого шрифту. Відсотки залежать від властивості та її контексту; width:100% зазвичай орієнтується на ширину контейнера.','max-width обмежує розмір, не змушуючи блок завжди бути широким. width:100% разом із border-box корисні для блока, який має вміститись у батька.'],
 ['CSS numbers often need units: 16px is a length, rem depends on the root font size and percentage meaning depends on property context. width:100% commonly follows the container width.','max-width limits size without requiring a large width. width:100% with border-box helps a box fit its parent.'],
 'Задай .demo width:100%, max-width:400px і box-sizing:border-box.','Set .demo width:100%, max-width:400px and box-sizing:border-box.',{css:'.demo { width:100%; max-width:400px; box-sizing:border-box; }'},[computed('.demo','max-width','400px'),computed('.demo','box-sizing','border-box')],
 [['Від чого залежить rem?','What does rem depend on?'],[['Кореневого шрифту','Root font size'],['Кількості карток','Card count'],['Кольору','Color']],0,['rem прив’язаний до шрифту кореневого елемента.','rem uses the root element font size.']],[['У width потрібне значення 100%.','Use 100% for width.'],['max-width задається окремо.','Set max-width separately.']]);
lesson('CSS','typography','Текст і читабельність','Text and readability',
 ['font-size задає розмір тексту, line-height — висоту рядка. Безрозмірне 1.6 означає множник розміру шрифту: для 16px це 25.6px. Відступ між абзацами задають margin, не довільними br.','Читабельність залежить від розміру, довжини рядка й контрасту. Невеликий набір узгоджених стилів допомагає бачити заголовки й пояснення.'],
 ['font-size sets text size and line-height sets line height. A unitless 1.6 multiplies font size: 16px becomes 25.6px. Use margin rather than arbitrary br elements between paragraphs.','Readability depends on size, line length and contrast. A consistent small style set makes hierarchy clear.'],
 'Для .demo p задай font-size:16px і line-height:1.6.','Set .demo p to font-size:16px and line-height:1.6.',{css:'.demo p { font-size:16px; line-height:1.6; }'},[computed('.demo p','font-size','16px'),computed('.demo p','line-height','25.6px')],
 [['Що означає line-height:1.6?','What does line-height:1.6 mean?'],[['1.6 пікселя','1.6 pixels'],['Множник шрифту','Font-size multiplier'],['Ширину блока','Box width']],1,['Без одиниці значення множить розмір шрифту.','A unitless value multiplies font size.']],[['Обери абзац через .demo p.','Select the paragraph with .demo p.'],['Для line-height не додавай px.','Keep line-height unitless.']]);
for(const course of academyCourses){const order=course.id==='JavaScript'?['values','comparisons','conditions','loops','strings','arrays','objects','dom','async','project']:course.id==='CSS'?['cascade','box','units','typography','flex','grid','responsive','project']:null;if(order)course.lessons.sort((a,b)=>order.indexOf(a.id.slice(a.id.indexOf('-')+1))-order.indexOf(b.id.slice(b.id.indexOf('-')+1)));}
for(const id of ['javascript-comparisons','javascript-conditions','javascript-loops','javascript-strings','css-units','css-typography']){const l=academyCourses.flatMap(c=>c.lessons).find(l=>l.id===id);deepTopics[id]=[l.theory.uk.join(' '),l.theory.en.join(' '),'Перевір точний запис властивості чи оператора та один граничний випадок.','Inspect the exact property or operator and one boundary case.','Зміни одне значення у прикладі й перед запуском передбач результат.','Change one value and predict the result before running.'];}
