// Supabase uses a public browser key. Private service keys are never accepted.
Object.assign(translations.uk,{cloudTitle:'Supabase · Хмарні дані',cloudIntro:'Вхід, перенесення між пристроями та 10 останніх хмарних копій. Зміни надсилаються кнопкою; офлайн працює локальне збереження.',cloudSetup:'Налаштувати підключення',cloudUrl:'Project URL',cloudKey:'Publishable key (публічний)',cloudSetupInfo:'Спочатку виконай supabase/schema.sql у SQL Editor свого проєкту. Інструкція — SUPABASE.md у репозиторії.',email:'Email',password:'Пароль',signIn:'Увійти',signUp:'Створити акаунт',signOut:'Вийти',uploadCloud:'Зберегти в хмару',loadCloud:'Отримати з хмари',cloudHistory:'Історія хмарних копій',cloudConfirmEmail:'Підтвердь email за листом Supabase, потім увійди.',cloudSaved:'Хмарну копію збережено',cloudEmpty:'Хмарних даних ще немає.',cloudConflict:'На іншому пристрої є новіша версія. Отримай її з хмари та об’єднай дані перед наступним збереженням.',cloudError:'Не вдалося виконати запит. Перевір підключення, email, пароль і налаштування Supabase.',cloudBusy:'Виконується…',cloudPublicOnly:'Використовуй HTTPS Project URL і тільки publishable key. Secret / service_role key сюди не вводь.',cloudUploadConfirm:'Надіслати всі поточні дані Kachan у твій акаунт Supabase?',cloudLoaded:'Копія готова. Нижче обери об’єднання або заміну даних.',cloudLoginFirst:'Спочатку увійди.',cloudRevision:'Версія',cloudPending:'Завантажені дані очікують твого рішення: об’єднай або заміни їх перед збереженням у хмару.'});
Object.assign(translations.en,{cloudTitle:'Supabase · Cloud data',cloudIntro:'Sign in, transfer between devices and keep the last 10 cloud backups. Upload using the button; offline changes stay local.',cloudSetup:'Configure connection',cloudUrl:'Project URL',cloudKey:'Publishable key (public)',cloudSetupInfo:'Run supabase/schema.sql in your project SQL Editor first. See SUPABASE.md in the repository.',email:'Email',password:'Password',signIn:'Sign in',signUp:'Create account',signOut:'Sign out',uploadCloud:'Save to cloud',loadCloud:'Fetch from cloud',cloudHistory:'Cloud backup history',cloudConfirmEmail:'Confirm your email using the Supabase email, then sign in.',cloudSaved:'Cloud backup saved',cloudEmpty:'No cloud data yet.',cloudConflict:'Another device has a newer version. Fetch it and merge before saving again.',cloudError:'Request failed. Check your connection, email, password and Supabase setup.',cloudBusy:'Working…',cloudPublicOnly:'Use an HTTPS Project URL and a publishable key only. Never enter a secret / service_role key.',cloudUploadConfirm:'Upload all current Kachan data to your Supabase account?',cloudLoaded:'Backup ready. Choose merge or replace below.',cloudLoginFirst:'Sign in first.',cloudRevision:'Revision',cloudPending:'Fetched data needs your decision: merge or replace before saving to cloud.'});
let cloudConfig=readData('kachan-cloud-config',defaultCloudConfig,c=>c&&typeof c.url==='string'&&typeof c.key==='string'&&(!c.url||/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(c.url))&&(!c.key||/^sb_publishable_[A-Za-z0-9_-]+$/.test(c.key)));
let cloudSession=null,cloudBusy=false,cloudMessage='',cloudFailure=null,cloudHistory=[],cloudRevision=0,cloudFetched=false;
const cloudHints={uk:{over_email_send_rate_limit:'Supabase тимчасово обмежив надсилання листів. Зачекай перед повторною реєстрацією; перевір також пошту та спам.',email_address_invalid:'Supabase не прийняв цю email-адресу. Перевір її написання або використай іншу свою адресу.',signup_disabled:'Реєстрацію вимкнено. У Supabase відкрий Authentication → Providers → Email і дозволь реєстрацію.',weak_password:'Пароль не відповідає вимогам Supabase. Використай довший і складніший пароль.',user_already_exists:'Акаунт уже існує. Спробуй увійти та перевір лист підтвердження.',email_not_confirmed:'Спочатку підтвердь email за листом Supabase. Перевір також спам.',invalid_credentials:'Email або пароль неправильні. Перевір дані входу.',network:'Не вдалося зв’язатися із Supabase. Перевір інтернет і повтори спробу.',unknown:'Supabase відхилив запит. Нижче наведено його відповідь.'},en:{over_email_send_rate_limit:'Supabase temporarily limited confirmation emails. Wait before trying again; also check your inbox and spam.',email_address_invalid:'Supabase rejected this email address. Check the spelling or use another address you own.',signup_disabled:'Signups are disabled. In Supabase open Authentication → Providers → Email and enable signups.',weak_password:'The password does not meet Supabase requirements. Use a longer, stronger password.',user_already_exists:'This account already exists. Try signing in and check your confirmation email.',email_not_confirmed:'Confirm your email using the Supabase email first. Also check spam.',invalid_credentials:'Incorrect email or password. Check your sign-in details.',network:'Could not reach Supabase. Check your connection and try again.',unknown:'Supabase rejected the request. Its response is shown below.'}};
function cloudFailureText(error){const hints=cloudHints[document.documentElement.lang]||cloudHints.en;const code=error.code||'';const network=error.name==='TypeError'||error.name==='TimeoutError'||error.name==='AbortError';const hint=hints[code]||(error.status===429?hints.over_email_send_rate_limit:network?hints.network:hints.unknown);const detail=network?'':[error.status?'HTTP '+error.status:'',code,String(error.message||'').replace(/sb_[A-Za-z0-9_-]+|eyJ[A-Za-z0-9_.-]+/g,'[redacted]').slice(0,350)].filter(Boolean).join(' · ');return hint+(detail?' '+detail:'');}
try{const stored=JSON.parse(sessionStorage.getItem('kachan-cloud-session'));if(stored&&stored.user?.id&&typeof stored.access_token==='string'&&typeof stored.refresh_token==='string'&&Number.isFinite(stored.expires_at)&&stored.url===cloudConfig.url)cloudSession=stored;}catch{}
function storeCloudState(pending=false){if(!cloudSession)return;sessionStorage.setItem('kachan-cloud-state',JSON.stringify({url:cloudConfig.url,user:cloudSession.user.id,revision:cloudRevision,pending}));}
try{const state=JSON.parse(sessionStorage.getItem('kachan-cloud-state'));if(cloudSession&&state?.url===cloudConfig.url&&state.user===cloudSession.user.id&&!state.pending){cloudRevision=state.revision;cloudFetched=true;}}catch{}
window.addEventListener('kachan-data-imported',()=>storeCloudState(false));
const cloudPanel=E('section','dashboard-panel productivity-panel');document.querySelector('.backup-panel').before(cloudPanel);
function snapshotNow(){tickTimerSafe();storeTimer();return {app:'Kachan',version:7,exportedAt:new Date().toISOString(),data:{settings,snippets,favorites,progress:savedProgress,tasks,projects,language:document.documentElement.lang,htmlCourse,notes,dashboard:dashboardData,workspace,extras:{...extras,timer:null},academy,personalization}};}
function rememberCloudSession(value){cloudSession=value?{...value,url:cloudConfig.url,expires_at:value.expires_at||Math.floor(Date.now()/1000)+value.expires_in}:null;try{if(cloudSession)sessionStorage.setItem('kachan-cloud-session',JSON.stringify(cloudSession));else sessionStorage.removeItem('kachan-cloud-session');}catch{}}
async function cloudRequest(path,{method='GET',body,authenticated=false,retry=true}={}){
 if(!cloudConfig.url||!cloudConfig.key)throw Error('CONFIG');
 if(authenticated&&!cloudSession)throw Error('LOGIN');
 if(authenticated&&cloudSession.expires_at<=Date.now()/1000+30){const refreshed=await cloudRequest('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:cloudSession.refresh_token}});rememberCloudSession(refreshed);}
 const headers={apikey:cloudConfig.key,'Content-Type':'application/json'};if(authenticated)headers.Authorization='Bearer '+cloudSession.access_token;
 const response=await fetch(cloudConfig.url+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const raw=await response.text();let result;try{result=raw?JSON.parse(raw):null;}catch{throw Error('RESPONSE');}
 if(!response.ok){if(authenticated&&response.status===401)rememberCloudSession(null);const error=Error(String(result?.message||result?.msg||result?.error_description||'REQUEST'));error.status=response.status;error.code=String(result?.code||result?.error_code||'');throw error;}return result;
}
async function cloudAction(action){if(cloudBusy)return;cloudBusy=true;cloudFailure=null;cloudMessage='cloudBusy';renderCloud();try{await action();}catch(error){cloudMessage=error.message==='SIZE'?'cloudTooLarge':error.message.includes('KACHAN_CONFLICT')?'cloudConflict':error.message==='LOGIN'?'cloudLoginFirst':'cloudError';if(cloudMessage==='cloudError')cloudFailure=error;}finally{cloudBusy=false;renderCloud();}}
function stageCloudBackup(row){if(!validateBackup(row.payload))throw Error('BACKUP');pendingBackup=JSON.parse(JSON.stringify(row.payload.data));if(pendingBackup.extras)pendingBackup.extras.timer=null;storeCloudState(true);Q('confirm-import').hidden=false;backupPreview();cloudMessage='cloudLoaded';document.querySelector('.backup-panel').scrollIntoView({block:'center'});}
function renderCloud(){const draft=Q('cloud-auth-form')?{email:Q('cloud-auth-form').elements.email.value,password:Q('cloud-auth-form').elements.password.value}:null;cloudPanel.replaceChildren();cloudPanel.append(E('h2','',t().cloudTitle),E('p','panel-note',t().cloudIntro));const details=E('details','material-editor');details.open=!cloudConfig.url;const summary=E('summary','',t().cloudSetup),setup=E('form','project-form-grid');setup.id='cloud-setup-form';details.append(summary,E('p','panel-note',t().cloudSetupInfo),setup);for(const [name,label] of [['url','cloudUrl'],['key','cloudKey']]){const input=labelField(setup,label,E('input'));input.name=name;input.value=cloudConfig[name];input.required=true;input.maxLength=name==='url'?200:300;}const save=E('button','primary-button',t().save);save.type='submit';save.disabled=cloudBusy;setup.append(save);setup.addEventListener('submit',e=>{e.preventDefault();const url=setup.elements.url.value.trim().replace(/\/$/,''),key=setup.elements.key.value.trim();if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(url)||!/^sb_publishable_[A-Za-z0-9_-]+$/.test(key)){notice(t().cloudPublicOnly);return;}cloudConfig={url,key};writeData('kachan-cloud-config',cloudConfig);rememberCloudSession(null);cloudHistory=[];cloudRevision=0;cloudFetched=false;renderCloud();});cloudPanel.append(details);
 if(!cloudSession){const auth=E('form','project-form-grid');auth.id='cloud-auth-form';const email=labelField(auth,'email',E('input'));email.name='email';email.type='email';email.required=true;email.autocomplete='username';email.value=draft?.email||'';const password=labelField(auth,'password',E('input'));password.name='password';password.type='password';password.required=true;password.minLength=8;password.autocomplete='current-password';password.value=draft?.password||'';const login=E('button','primary-button',t().signIn);login.type='submit';login.disabled=cloudBusy;auth.append(login);auth.addEventListener('submit',e=>{e.preventDefault();const credentials={email:email.value.trim(),password:password.value};cloudAction(async()=>{const value=await cloudRequest('/auth/v1/token?grant_type=password',{method:'POST',body:credentials});rememberCloudSession(value);cloudFetched=false;cloudMessage='';});});const signup=button('signUp',()=>{if(!auth.reportValidity())return;const credentials={email:email.value.trim(),password:password.value};cloudAction(async()=>{const value=await cloudRequest('/auth/v1/signup',{method:'POST',body:credentials});if(value.access_token){rememberCloudSession(value);cloudMessage='';}else cloudMessage='cloudConfirmEmail';});});signup.disabled=cloudBusy;auth.append(signup);cloudPanel.append(auth);
 }else{cloudPanel.append(E('p','panel-note',cloudSession.user.email||''));const actions=E('div','editor-actions');actions.append(button('uploadCloud',()=>{if(pendingBackup){cloudMessage='cloudPending';renderCloud();return;}if(!confirm(t().cloudUploadConfirm))return;cloudAction(async()=>{if(!cloudFetched){const rows=await cloudRequest('/rest/v1/kachan_snapshots?select=revision,updated_at',{authenticated:true});if(rows.length){cloudMessage='cloudConflict';return;}cloudRevision=0;}const payload=snapshotNow();if(new Blob([JSON.stringify(payload)]).size>4*1024*1024)throw Error('SIZE');if(!validateBackup(payload))throw Error('BACKUP');cloudRevision=await cloudRequest('/rest/v1/rpc/kachan_save',{method:'POST',body:{p_expected:cloudRevision,p_payload:payload},authenticated:true});cloudFetched=true;cloudMessage='cloudSaved';storeCloudState(false);});}),button('loadCloud',()=>cloudAction(async()=>{const rows=await cloudRequest('/rest/v1/kachan_snapshots?select=revision,payload,updated_at',{authenticated:true});if(!rows.length){cloudRevision=0;cloudFetched=true;cloudMessage='cloudEmpty';return;}stageCloudBackup(rows[0]);cloudRevision=rows[0].revision;cloudFetched=true;storeCloudState(true);})),button('cloudHistory',()=>cloudAction(async()=>{cloudHistory=await cloudRequest('/rest/v1/kachan_history?select=revision,payload,updated_at&order=revision.desc&limit=10',{authenticated:true});cloudMessage=cloudHistory.length?'':'cloudEmpty';})),button('signOut',()=>cloudAction(async()=>{try{await cloudRequest('/auth/v1/logout',{method:'POST',authenticated:true});}finally{rememberCloudSession(null);cloudHistory=[];cloudFetched=false;sessionStorage.removeItem('kachan-cloud-state');cloudMessage='';}})));for(const b of actions.children)b.disabled=cloudBusy;cloudPanel.append(actions);for(const row of cloudHistory){cloudPanel.append(button(t().cloudRevision+' '+row.revision+' · '+new Date(row.updated_at).toLocaleString(document.documentElement.lang),()=>{try{stageCloudBackup(row);renderCloud();}catch{cloudMessage='badBackup';renderCloud();}}));}}
 const status=E('p','panel-note',cloudMessage==='cloudError'&&cloudFailure?cloudFailureText(cloudFailure):cloudMessage?t()[cloudMessage]:'');status.id='cloud-status';status.setAttribute('role','status');cloudPanel.append(status);
}
Q('reset-data').addEventListener('click',()=>{ /* Cloud account is not deleted by a local reset. */ });
Object.assign(translations.uk,{cloudTooLarge:'Копія завелика для хмари (до 4 МБ). Завантаж локальний JSON або зменш великі записи.'});Object.assign(translations.en,{cloudTooLarge:'Cloud copy exceeds 4 MB. Download a local JSON backup or reduce large records.'});
window.addEventListener('languagechange',renderCloud);renderCloud();arrangeSettings();
