Object.assign(translations.uk,{workOverview:'Робочий день',workFocus:'Фокус',workHistory:'Історія',workCalendar:'Календар',settingsLook:'Вигляд',settingsBoard:'Dashboard',settingsData:'Дані',settingsAlerts:'Сповіщення',learnTheory:'Теорія',learnPractice:'Практика',learnTest:'Тест',taskActions:'Дії задачі',showEverything:'Показати всі'});
Object.assign(translations.en,{workOverview:'Workday',workFocus:'Focus',workHistory:'History',workCalendar:'Calendar',settingsLook:'Appearance',settingsBoard:'Dashboard',settingsData:'Data',settingsAlerts:'Notifications',learnTheory:'Theory',learnPractice:'Practice',learnTest:'Test',taskActions:'Task actions',showEverything:'Show all'});
function compositionTabs(id,items,current,onSelect){const group=E('div','composition-tabs');group.id=id;group.setAttribute('role','group');for(const [value,key] of items){const b=button(key,()=>onSelect(value));b.dataset.tab=value;b.setAttribute('aria-pressed',String(value===current));group.append(b);}return group;}
let workTab='home',settingsTab='look',learningStep='theory',learningIdentity='';
const workGroups={home:[],overview:['stats','today','projects','tasks','continue','goals','learning'],focus:['focus'],history:['notes','activity','chart'],calendar:['calendar']};
function arrangeWorkday(){const heading=dashboard.querySelector('.page-heading');Q('workday-tabs')?.remove();const tabs=compositionTabs('workday-tabs',[['home','homeTab'],['overview','workOverview'],['focus','workFocus'],['history','workHistory'],['calendar','workCalendar']],workTab,value=>{workTab=value;arrangeWorkday();});heading.after(tabs);const ordered=personalization.blocks.every((b,i)=>b.id===blockDefinitions[i][0])?workGroups[workTab]:personalization.blocks.map(b=>b.id).filter(id=>workGroups[workTab].includes(id));for(const id of ordered){const element=dashboardBlocks.get(id);if(element)dashboard.append(element);}for(const [id,element] of dashboardBlocks){element.hidden=!workGroups[workTab].includes(id)||!personalization.blocks.find(b=>b.id===id)?.visible;}const visible=workTab==='home'||workGroups[workTab].some(id=>!dashboardBlocks.get(id)?.hidden);Q('workday-empty')?.remove();if(!visible){const box=E('div','empty-state');box.id='workday-empty';box.append(E('p','',document.documentElement.lang==='uk'?'Блоки цієї вкладки вимкнені. Увімкни потрібні в налаштуваннях Dashboard.':'These blocks are disabled. Enable them in Dashboard settings.'),button('settingsBoard',()=>{settingsTab='board';location.hash='settings';showView();arrangeSettings();}));dashboard.append(box);}if(typeof renderHome==='function')renderHome();scheduleSectionNavigation();}
const layoutBeforeComposition=applyDashboardLayout;applyDashboardLayout=function(){layoutBeforeComposition();arrangeWorkday();};
const alertsPanel=E('section','dashboard-panel');alertsPanel.id='notification-settings';Q('settings-view').append(alertsPanel);
function splitAlertSettings(){alertsPanel.replaceChildren(E('h2','',t().settingsAlerts));const children=[...comfortPanel.children],start=children.findIndex(el=>el.tagName==='H3'&&el.textContent===t().notifications);if(start>=0){children[start].remove();for(const el of children.slice(start+1))alertsPanel.append(el);}}
const comfortBeforeComposition=renderComfort;renderComfort=function(){comfortBeforeComposition();splitAlertSettings();arrangeSettings();};
function arrangeSettings(){if(settingsTab==='board')settingsTab='look';Q('settings-tabs')?.remove();Q('settings-view').querySelector('.page-heading').after(compositionTabs('settings-tabs',[['look','settingsLook'],['data','settingsData'],['alerts','settingsAlerts']],settingsTab,value=>{settingsTab=value;arrangeSettings();}));for(const panel of Q('settings-view').children){if(panel.classList.contains('page-heading')||panel.id==='settings-tabs')continue;const group=panel.id==='settings-form'||panel===comfortPanel?'look':panel.id==='dashboard-settings'?'board':panel===alertsPanel?'alerts':'data';panel.hidden=group!==settingsTab;}scheduleSectionNavigation();}
function arrangeLesson(){const html=academy.course==='HTML',identity=html?'html-'+htmlCourse.selected:academy.selected;if(identity!==learningIdentity){learningIdentity=identity;learningStep='theory';}const body=html?Q('html-lesson'):academyPanel.querySelector('.course-layout>section');if(!body)return;body.querySelector('.lesson-step-tabs')?.remove();const title=body.querySelector('h2');const tabs=compositionTabs('',[['theory','learnTheory'],['practice','learnPractice'],['test','learnTest']],learningStep,value=>{learningStep=value;arrangeLesson();});tabs.classList.add('lesson-step-tabs');title.after(tabs);let group='theory';for(const child of body.children){if(child===tabs||child===title||child.classList.contains('badge'))continue;if(child.tagName==='H3'){if(child.textContent===t().courseTask)group='practice';else if(child.textContent===t().quizTitle)group='test';else if(child.textContent===t().lessonNotes)group='shared';}if(html&&child.id==='course-results'){child.hidden=learningStep!=='test';continue;}if(child.classList.contains('course-pagination')){child.hidden=false;continue;}child.hidden=group!=='shared'&&group!==learningStep;}if(html){let check=body.querySelector('.html-test-action');if(!check){check=E('div','html-test-action');check.append(E('p','panel-note',document.documentElement.lang==='uk'?'Тест перевіряє структуру HTML із вкладки «Практика».':'This test checks the HTML structure from Practice.'),button('courseCheck',()=>{const actions=body.querySelector('.editor-actions');const original=[...actions.querySelectorAll('button')].find(b=>b.textContent===t().courseCheck);original?.click();}));body.append(check);}check.hidden=learningStep!=='test';}scheduleSectionNavigation();}
const academyBeforeComposition=renderAcademy;renderAcademy=function(){academyBeforeComposition();arrangeLesson();};const htmlBeforeComposition=renderHtmlCourse;renderHtmlCourse=function(){htmlBeforeComposition();if(academy.course==='HTML')arrangeLesson();};
function compactTaskActions(){const list=Q('all-tasks');for(const row of list.children){if(row.querySelector('.task-action-menu'))continue;const menu=E('details','task-action-menu'),summary=E('summary','','');summary.textContent='⋯';summary.setAttribute('aria-label',t().taskActions);const content=E('div','task-action-popover');menu.append(summary,content);for(const child of [...row.children])if(child.matches('button,.subtask-editor,.task-linked-notes'))content.append(child);row.append(menu);}Q('bulk-count').closest('.workspace-controls').hidden=taskSelection.size===0;}
const taskRowsBeforeComposition=renderWorkspaceTasks;renderWorkspaceTasks=function(shown){taskRowsBeforeComposition(shown);compactTaskActions();};document.addEventListener('change',event=>{if(event.target.closest('#all-tasks'))queueMicrotask(()=>{Q('bulk-count').closest('.workspace-controls').hidden=taskSelection.size===0;});});
document.addEventListener('click',event=>{for(const menu of document.querySelectorAll('.task-action-menu[open]'))if(!menu.contains(event.target))menu.open=false;});document.addEventListener('keydown',event=>{if(event.key==='Escape')for(const menu of document.querySelectorAll('.task-action-menu[open]')){menu.open=false;menu.querySelector('summary').focus();}});
document.addEventListener('click',event=>{const edit=event.target.closest('.task-edit'),menu=edit?.closest('.task-action-menu');if(menu){editorWindows.get('task').previous=menu.querySelector('summary');menu.open=false;}});
function improveEmptyStates(){for(const state of document.querySelectorAll('.content .empty-state')){if(state.querySelector('button')||state.id==='workday-empty')continue;const view=state.closest('[id$="-view"]');if(!view)continue;let key,action;switch(view.id){case'dashboard-view':key=state.closest('[data-dashboard-block=notes]')?'newNote':'newTask';action=()=>Q(key==='newNote'?'quick-note':'quick-task').click();break;case'tasks-view':key='newTask';action=()=>Q('open-task-window').click();break;case'projects-view':key='newProject';action=()=>Q('open-project-window').click();break;case'notes-view':key='newNote';action=()=>Q('note-new').click();break;case'snippets-view':key='newSnippet';action=()=>{Q('open-snippet-window').click();};break;case'resources-view':key='showEverything';action=()=>{resourceFilter='all';Q('resource-query').value='';Q('resource-collection').value='all';renderResources();};break;}if(action){const b=button(key,action);b.dataset.i18n=key;state.append(b);}}}
let emptyQueued=false;new MutationObserver(()=>{if(emptyQueued)return;emptyQueued=true;queueMicrotask(()=>{emptyQueued=false;improveEmptyStates();});}).observe(document.querySelector('.content'),{childList:true,subtree:true});
window.addEventListener('languagechange',()=>{arrangeWorkday();arrangeSettings();arrangeLesson();compactTaskActions();});splitAlertSettings();arrangeWorkday();arrangeSettings();arrangeLesson();compactTaskActions();improveEmptyStates();
