const contentCopy={uk:{use:'Коли використовувати',walk:'Розбір прикладу',compare:'До → після',before:'До: проблема',after:'Після: виправлення',mistakes:'Типові помилки',library:'Довідник і приклади',reference:'Довідник',examples:'Приклади коду',intro:'CSS, масиви, події, Git і гарячі клавіші. Відкривай тільки потрібну тему.',search:'Знайти матеріал…',all:'Усі теми',empty:'Нічого не знайдено.',access:'Доступ',works:'Вибрані роботи',worksHint:'Назва роботи, твоя роль, результат і посилання. Лише реальні роботи; поле можна залишити порожнім.'},en:{use:'When to use it',walk:'Example walkthrough',compare:'Before → after',before:'Before: the problem',after:'After: the fix',mistakes:'Common mistakes',library:'Reference and examples',reference:'Reference',examples:'Code examples',intro:'CSS, arrays, events, Git and keyboard shortcuts. Open only the topic you need.',search:'Find material…',all:'All topics',empty:'No matches.',access:'Access',works:'Selected work',worksHint:'Work title, your role, outcome and URL. Use real work only; you can leave this empty.'}};
const cx=()=>contentCopy[document.documentElement.lang];
const chapterBeforeContent=renderChapter;
renderChapter=function(){chapterBeforeContent();const l=extraChapters.find(x=>x.id===activeChapter);if(!l?.detail)return;const lang=document.documentElement.lang,d=l.detail,block=E('div','chapter-enrichment');
 block.append(E('h3','',cx().use),E('p','',d.use[lang]));
 const walk=E('details','chapter-fold');walk.append(E('summary','',cx().walk));const ol=E('ol');for(const line of d.lines[lang])ol.append(E('li','',line));walk.append(ol);
 const compare=E('details','chapter-fold');compare.append(E('summary','',cx().compare));for(const [key,code] of [['before',d.before],['after',d.after]]){compare.append(E('h4','',cx()[key]),E('pre','snippet-code',code));}
 const mistakes=E('details','chapter-fold');mistakes.append(E('summary','',cx().mistakes));const ul=E('ul');for(const item of d.mistakes[lang])ul.append(E('li','',item));mistakes.append(ul);block.append(walk,compare,mistakes);chapterBody.querySelector('.chapter-fold').after(block);
};

const contentBody=E('div','content-reference-body'),contentWindow=utilityWindow('content-reference-window','learning',contentBody);contentWindow.dialog.classList.add('chapter-window');
let contentMode='reference',contentQuery='',contentGroup='all';
function openContent(mode='reference',id=''){contentMode=mode;contentQuery='';contentGroup='all';renderContentReference();contentWindow.open();contentWindow.dialog.scrollTop=0;if(id){const row=[...contentBody.querySelectorAll('[data-content-id]')].find(e=>e.dataset.contentId===id);if(row){row.open=true;row.scrollIntoView({block:'start'});}}}
function renderContentReference(){contentBody.replaceChildren();contentBody.append(E('h2','',cx().library));const tabs=E('div','composition-tabs');for(const mode of ['reference','examples']){const b=button(cx()[mode],()=>{contentMode=mode;contentQuery='';contentGroup='all';renderContentReference();});b.setAttribute('aria-pressed',String(contentMode===mode));tabs.append(b);}contentBody.append(tabs);
 const controls=E('div','content-controls'),query=E('input'),group=E('select');query.type='search';query.value=contentQuery;query.placeholder=cx().search;query.setAttribute('aria-label',cx().search);group.setAttribute('aria-label',cx().all);const items=contentMode==='reference'?referenceItems:exampleItems;selectOptions(group,[['all',cx().all],...[...new Set(items.map(x=>x.group))].map(k=>[k,k])],contentGroup);controls.append(query,group);const result=E('div','content-results');result.setAttribute('aria-live','polite');contentBody.append(controls,result);
 const fill=()=>{result.replaceChildren();const lang=document.documentElement.lang,rows=items.filter(x=>(contentGroup==='all'||x.group===contentGroup)&&(x.title[lang]+' '+x.description[lang]+' '+x.code).toLocaleLowerCase().includes(contentQuery.trim().toLocaleLowerCase()));if(!rows.length)result.append(E('p','empty-state',cx().empty));for(const x of rows){const fold=E('details','chapter-fold');fold.dataset.contentId=x.id;fold.append(E('summary','',x.group+' · '+x.title[lang]),E('p','',x.description[lang]),E('pre','snippet-code',x.code),button(t().copy,()=>copyToolText(x.code)));result.append(fold);}};
 query.addEventListener('input',()=>{contentQuery=query.value;fill();});group.addEventListener('change',()=>{contentGroup=group.value;fill();});fill();
}
function renderContentEntry(){const opened=Q('content-library-entry')?.open||false;Q('content-library-entry')?.remove();const fold=E('details','extra-chapter-list');fold.id='content-library-entry';fold.open=opened;fold.append(E('summary','',cx().library),E('p','panel-note',cx().intro));const actions=E('div','chapter-actions');for(const mode of ['reference','examples'])actions.append(button(cx()[mode],()=>openContent(mode)));fold.append(actions);learningLibrary.append(fold);}
const libraryBeforeContent=renderLearningLibrary;renderLearningLibrary=function(){libraryBeforeContent();renderContentEntry();};
const resourcesBeforeContent=renderResources;renderResources=function(){resourcesBeforeContent();for(const card of Q('resource-list').querySelectorAll('article')){const title=card.querySelector('h4,h3,h2')?.textContent;const row=resources.find(x=>x[1]===title),info=row&&contentResourceInfo[row[0]];if(info)card.append(E('p','panel-note resource-access',cx().access+': '+info[document.documentElement.lang]));}};
const searchBeforeContent=searchItems;searchItems=function(){return [...searchBeforeContent(),...referenceItems.map(x=>({id:x.id,kind:'learning',name:x.title[document.documentElement.lang],body:x.group+' '+x.description[document.documentElement.lang],action:()=>{location.hash='learning';showView();openContent('reference',x.id);}})),...exampleItems.map(x=>({id:'example-'+x.id,kind:'learning',name:x.title[document.documentElement.lang],body:cx().examples+' '+x.description[document.documentElement.lang],action:()=>{location.hash='learning';showView();openContent('examples',x.id);}}))];};
window.addEventListener('languagechange',()=>{renderContentEntry();if(contentWindow.dialog.open)renderContentReference();if(chapterWindow.dialog.open)renderChapter();renderResources();});renderContentEntry();renderResources();
