Object.assign(translations.uk,{quickCreate:'Створити',cardsView:'Картки',listView:'Список',myHome:'Під рукою',todayFocus:'Головна задача сьогодні',chooseFocus:'Обрати задачу',noFocus:'Обери одну задачу, на якій зосередишся сьогодні.',pinnedItems:'Закріплене',recentOpened:'Нещодавно відкриті',nothingPinned:'Закріпи проєкт або нотатку, щоб вони були тут.',nothingRecent:'Тут з’являться відкриті розділи.',undoAction:'Скасувати',itemDeleted:'Запис видалено',searchStart:'Швидкі дії та розділи',openItem:'Відкрити',unpin:'Відкріпити'});
Object.assign(translations.en,{quickCreate:'Create',cardsView:'Cards',listView:'List',myHome:'Within reach',todayFocus:'Today’s main task',chooseFocus:'Choose a task',noFocus:'Choose one task to focus on today.',pinnedItems:'Pinned',recentOpened:'Recently opened',nothingPinned:'Pin a project or note to keep it here.',nothingRecent:'Opened sections will appear here.',undoAction:'Undo',itemDeleted:'Item deleted',searchStart:'Quick actions and sections',openItem:'Open',unpin:'Unpin'});
function uiPrefs(){const p=extras.preferences;if(!p.workspaceUI||typeof p.workspaceUI!=='object')p.workspaceUI={};const u=p.workspaceUI;if(!Array.isArray(u.projectPins))u.projectPins=[];u.projectPins=u.projectPins.filter(x=>typeof x==='string').slice(0,1000);if(!u.views||typeof u.views!=='object'||Array.isArray(u.views))u.views={};if(typeof u.focusTask!=='string')u.focusTask='';return u;}
function launchCreate(kind){location.hash=kind;showView();if(kind==='tasks')Q('quick-task').click();else if(kind==='projects')Q('quick-project').click();else Q({notes:'note-new',snippets:'open-snippet-window',resources:'open-resource-window'}[kind]).click();}
const createContent=E('div','utility-content create-grid');const createWindow=utilityWindow('create-window','quickCreate',createContent);const globalCreate=button('quickCreate',()=>createWindow.open(),'primary-button');globalCreate.id='global-create';globalCreate.dataset.i18n='quickCreate';document.querySelector('.topbar-actions').prepend(globalCreate);
function fillCreate(){createContent.replaceChildren();for(const kind of ['tasks','projects','notes','snippets','resources']){const b=button(kind,()=>{createWindow.shut();launchCreate(kind);},'create-option');b.prepend(homeIcon(kind));createContent.append(b);}}fillCreate();
const previousSearchItems=searchItems;searchItems=function(){return [...['tasks','projects','notes','snippets','resources'].map(kind=>({name:t().quickCreate+' · '+t()[kind],kind,action:()=>launchCreate(kind)})),...previousSearchItems()];};
searchDialog.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key)||e.target===Q('global-query')&&e.key!=='ArrowDown')return;const items=[...searchDialog.querySelectorAll('.command-result')];if(!items.length)return;e.preventDefault();e.stopImmediatePropagation();let index=items.indexOf(document.activeElement);index=e.key==='Home'?0:e.key==='End'?items.length-1:(index+(e.key==='ArrowUp'?-1:1)+items.length)%items.length;items[index].focus();},true);
function decorateSearch(){if(!searchDialog.open)return;searchDialog.querySelector('#search-start-label')?.remove();if(!Q('global-query').value){const hint=E('p','panel-note',t().searchStart);hint.id='search-start-label';Q('global-query').after(hint);}for(const result of searchDialog.querySelectorAll('.command-result')){const small=result.querySelector('small');if(small&&!small.textContent)small.textContent=t().openItem;}}
searchDialog.addEventListener('input',decorateSearch);new MutationObserver(decorateSearch).observe(searchDialog,{attributes:true,attributeFilter:['open']});
const collectionSelectors={projects:'#all-projects',snippets:'#snippet-list',resources:'#resource-list'};
function setupCollectionViews(){for(const [kind,selector] of Object.entries(collectionSelectors)){const list=document.querySelector(selector);list.classList.toggle('collection-list',uiPrefs().views?.[kind]==='list');let toolbar=Q(kind+'-display-mode');if(!toolbar){toolbar=E('div','display-mode');toolbar.id=kind+'-display-mode';toolbar.setAttribute('role','group');list.before(toolbar);}toolbar.setAttribute('aria-label',t()[kind]);toolbar.replaceChildren();for(const mode of ['cards','list']){const b=button(mode==='cards'?'cardsView':'listView',()=>{const p=uiPrefs();(p.views||={})[kind]=mode;persistExtras();setupCollectionViews();});b.setAttribute('aria-pressed',String((uiPrefs().views?.[kind]||'cards')===mode));toolbar.append(b);}}}
for(const name of ['projects','snippets','resources']){if(name==='projects'){const base=renderProjects;renderProjects=function(){base();decorateProjects();setupCollectionViews();};}if(name==='snippets'){const base=renderSnippets;renderSnippets=function(){base();setupCollectionViews();};}if(name==='resources'){const base=renderResources;renderResources=function(){base();setupCollectionViews();};}}
function decorateProjects(){const shown=projects.filter(p=>!!p.archived===Q('project-archive-toggle').classList.contains('active')&&matchesSearch('projects',[p.name,p.descriptionKey==='projectDescription'?t().projectDescription:p.description,...p.technologies,t()[p.status]]));Q('all-projects').querySelectorAll('.project-card').forEach((card,i)=>{const project=shown[i];if(!project)return;const p=uiPrefs(),pins=Array.isArray(p.projectPins)?p.projectPins:[];const pin=button(pins.includes(project.id)?'unpin':'pin',()=>{p.projectPins=pins.includes(project.id)?pins.filter(id=>id!==project.id):[...pins,project.id];persistExtras();renderProjects();renderHome();});pin.classList.add('pin-control');pin.setAttribute('aria-pressed',String(pins.includes(project.id)));card.append(pin);});}
const originalHomeWithUI=renderHome;renderHome=function(){originalHomeWithUI();if(workTab!=='home')return;const section=E('section','home-personal');section.id='home-personal';section.append(E('h2','',t().myHome));const grid=E('div','personal-grid'),focus=E('article','dashboard-panel focus-card');focus.append(E('span','eyebrow',t().todayFocus));const selected=tasks.find(x=>x.id===uiPrefs().focusTask&&!x.completed);if(selected){const label=E('label','task-row'),check=E('input');check.type='checkbox';check.setAttribute('aria-label',taskName(selected));check.addEventListener('change',()=>{selected.completed=true;saveTasks();renderTasks();renderProjects();renderHome();});label.append(check,E('strong','',taskName(selected)));focus.append(label);}else focus.append(E('p','panel-note',t().noFocus));const select=E('select');select.setAttribute('aria-label',t().chooseFocus);selectOptions(select,[['',t().chooseFocus],...tasks.filter(x=>!x.completed).map(x=>[x.id,taskName(x)])],selected?.id||'');select.addEventListener('change',()=>{uiPrefs().focusTask=select.value;persistExtras();renderHome();});focus.append(select);grid.append(focus);
const pinned=E('article','dashboard-panel');pinned.append(E('h3','',t().pinnedItems));const rows=[...projects.filter(p=>(uiPrefs().projectPins||[]).includes(p.id)).map(p=>({name:p.name,kind:'projects',id:p.id})),...notes.filter(n=>n.pinned&&!n.deleted).map(n=>({name:n.title||t().untitledNote,kind:'notes',id:n.id}))];for(const row of rows.slice(0,5))pinned.append(button(row.name,()=>openEntity(row.kind,row.id),'personal-link'));if(!rows.length)pinned.append(E('p','panel-note',t().nothingPinned));grid.append(pinned);section.append(grid);const recent=E('div','recent-strip');recent.append(E('strong','',t().recentOpened));const history=Array.isArray(uiPrefs().recent)?uiPrefs().recent:[];for(const kind of history.filter(k=>['projects','tasks','learning','notes','snippets','resources','settings'].includes(k)).slice(0,4)){const a=E('a','secondary-button',t()[kind]);a.href='#'+kind;recent.append(a);}if(!history.length)recent.append(E('span','panel-note',t().nothingRecent));section.append(recent);homeSurface.append(section);};
function rememberRoute(){const kind=location.hash.slice(1).split('?')[0];if(!['projects','tasks','learning','notes','snippets','resources','settings'].includes(kind))return;const p=uiPrefs();p.recent=[kind,...(Array.isArray(p.recent)?p.recent:[]).filter(k=>k!==kind)].slice(0,7);persistExtras();}window.addEventListener('hashchange',()=>{rememberRoute();renderHome();});
// Undo only soft deletion: permanent deletion and full data reset retain their confirmation.
let undoTimer;function offerUndo(action){clearTimeout(undoTimer);const node=Q('app-notice');clearTimeout(noticeTimer);node.replaceChildren(E('span','',t().itemDeleted),button('undoAction',()=>{clearTimeout(undoTimer);action();node.replaceChildren();}));node.classList.add('action-notice');undoTimer=setTimeout(()=>{node.replaceChildren();node.classList.remove('action-notice');},10000);}
let undoTaskSnapshot=tasks.slice();const saveBeforeUndo=saveTasks;saveTasks=function(){const removed=undoTaskSnapshot.filter(old=>!tasks.some(x=>x.id===old.id));saveBeforeUndo();undoTaskSnapshot=tasks.slice();if(removed.length)offerUndo(()=>{for(const task of removed)if(!tasks.some(x=>x.id===task.id))tasks.push(task);workspace.trash=workspace.trash.filter(x=>!removed.some(r=>r.id===x.id));persistWorkspace();saveTasks();renderTasks();renderProjects();renderHome();});};
Q('note-delete').addEventListener('click',()=>{const n=notes.find(n=>n.deleted&&n.id===lastDeletingNote);if(n)offerUndo(()=>{n.deleted=false;selectedNote=n.id;showTrash=false;persistNotes();renderNotes();renderHome();});});let lastDeletingNote=null;Q('note-delete').addEventListener('click',()=>{lastDeletingNote=selectedNote;},true);
function dismissMobileMenu(){Q('workspace-navigation').classList.remove('open');Q('menu-toggle').setAttribute('aria-expanded','false');document.querySelector('.sidebar').classList.remove('menu-open');}document.addEventListener('keydown',e=>{if(e.key==='Escape')dismissMobileMenu();});document.addEventListener('click',e=>{if(e.target.closest('[data-view-link]'))dismissMobileMenu();});
window.addEventListener('languagechange',()=>{fillCreate();setupCollectionViews();renderProjects();renderHome();});setupCollectionViews();decorateProjects();renderHome();
// Preserve related data when undoing project or material deletion.
document.addEventListener('click',e=>{const target=e.target.closest('button');if(!target||![t().deleteProject,t().remove].includes(target.textContent.trim()))return;const before={projects:structuredClone(projects),snippets:structuredClone(snippets),resources:structuredClone(extras.customResources),materials:structuredClone(extras.materials),comments:structuredClone(extras.resourceNotes),favorites:favorites.slice(),links:tasks.map(x=>({id:x.id,projectId:x.projectId}))};setTimeout(()=>{const removed={projects:before.projects.filter(x=>!projects.some(y=>y.id===x.id)),snippets:before.snippets.filter(x=>!snippets.some(y=>y.id===x.id)),resources:before.resources.filter(x=>!extras.customResources.some(y=>y.id===x.id))};if(!Object.values(removed).some(x=>x.length))return;offerUndo(()=>{projects.push(...removed.projects.filter(x=>!projects.some(y=>y.id===x.id)));snippets.push(...removed.snippets.filter(x=>!snippets.some(y=>y.id===x.id)));extras.customResources.push(...removed.resources.filter(x=>!extras.customResources.some(y=>y.id===x.id)));for(const p of removed.projects)for(const link of before.links.filter(x=>x.projectId===p.id)){const task=tasks.find(x=>x.id===link.id);if(task&&!task.projectId)task.projectId=p.id;}for(const item of [...removed.snippets,...removed.resources]){if(before.materials[item.id])extras.materials[item.id]=before.materials[item.id];if(before.comments[item.id])extras.resourceNotes[item.id]=before.comments[item.id];if(before.favorites.includes(item.id)&&!favorites.includes(item.id))favorites.push(item.id);}saveProjects();saveTasks();writeData('devspace-snippets',snippets);persistExtras();writeData('devspace-favorites',favorites);renderProjects();renderTasks();renderSnippets();renderResources();renderHome();});},0);},true);

function rememberMaterial(kind,id,name){if(!id)return;const p=uiPrefs(),rows=Array.isArray(p.materialHistory)?p.materialHistory:[];p.materialHistory=[{kind,id,name:String(name).slice(0,160)},...rows.filter(x=>x.kind!==kind||x.id!==id)].slice(0,8);persistExtras();}
const entityBeforeHistory=openEntity;openEntity=function(kind,id){entityBeforeHistory(kind,id);const item=kind==='notes'?notes.find(x=>x.id===id):kind==='projects'?projects.find(x=>x.id===id):kind==='snippets'?snippets.find(x=>x.id===id):kind==='resources'?resourceRows().find(x=>x.id===id):null;rememberMaterial(kind,id,item?.name||item?.title||t()[kind]);};
const noteEditorBeforeHistory=renderNoteEditor;renderNoteEditor=function(){noteEditorBeforeHistory();if(location.hash==='#notes'){const n=notes.find(x=>x.id===selectedNote&&!x.deleted);if(n)rememberMaterial('notes',n.id,n.title||t().untitledNote);}};
window.addEventListener('hashchange',()=>{const id=new URLSearchParams(location.hash.split('?')[1]||'').get('project'),p=projects.find(x=>x.id===id);if(p)rememberMaterial('projects',p.id,p.name);});
const homeBeforeHistory=renderHome;renderHome=function(){homeBeforeHistory();if(workTab!=='home')return;const rows=(Array.isArray(uiPrefs().materialHistory)?uiPrefs().materialHistory:[]).filter(row=>row&&typeof row.name==='string'&&typeof row.id==='string'&&({projects:projects,notes:notes.filter(n=>!n.deleted),snippets:snippets,resources:resourceRows()})[row.kind]?.some(x=>x.id===row.id)).slice(0,4);if(!rows.length)return;const strip=homeSurface.querySelector('.recent-strip');strip.replaceChildren(E('strong','',t().recentOpened));for(const row of rows)strip.append(button(row.name,()=>openEntity(row.kind,row.id),'secondary-button'));};renderHome();
// The focus command reveals the corresponding workday tab before scrolling.
const searchBeforeFocus=searchItems;searchItems=function(){return searchBeforeFocus().map(item=>item.name===t().focus?{...item,action:()=>{location.hash='dashboard';showView();workTab='focus';arrangeWorkday();focusPanel.scrollIntoView({block:'start'});}}:item);};
// Close overlays consistently without losing their native focus handling.
searchDialog.addEventListener('click',e=>{if(e.target!==searchDialog)return;const r=searchDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)searchDialog.close();});new MutationObserver(()=>document.body.classList.toggle('editor-window-open',!!document.querySelector('dialog[open]'))).observe(searchDialog,{attributes:true,attributeFilter:['open']});document.addEventListener('click',e=>{if(document.querySelector('.sidebar').classList.contains('menu-open')&&!e.target.closest('.sidebar'))dismissMobileMenu();});
