// Additional chapters supplement the original practice courses without replacing progress.
const extraChapters=[];
function chapter(course,id,title,paragraphs,code,task,expected,question,answers,correct,docs){extraChapters.push({course,id,title:bi(...title),paragraphs:bi(...paragraphs),code,task:bi(...task),expected:bi(...expected),question:bi(...question),answers:answers.map(x=>bi(...x)),correct,docs});}
chapter('HTML','responsive-images',['Адаптивні зображення','Responsive images'],[
 ['Зображення має відповідати не лише ширині блока, а й екрану. Звичайний img із max-width: 100% змінює видимий розмір, але не обов’язково зменшує завантажений файл. Підготуй кілька розмірів одного зображення.', 'srcset з дескриптором w описує ширину файлів, sizes — очікувану ширину зображення в макеті. Браузер обирає кандидат із урахуванням екрана. picture потрібен, коли на вузькому екрані треба змінити саму композицію, наприклад використати інший кадр.', 'width і height задають співвідношення сторін та допомагають залишити місце до завантаження. loading="lazy" доречний для зображень нижче першого екрана; важливе початкове зображення не відкладай. alt пояснює зміст, а не повторює назву файла.'],
 ['Match an image to the screen as well as its container. max-width: 100% changes its displayed size but does not necessarily reduce the downloaded file. Prepare several sizes of the same image.', 'srcset with w descriptors lists file widths; sizes describes the expected layout width. The browser chooses a candidate for the screen. Use picture when mobile requires a different composition or crop.', 'width and height establish an aspect ratio and reserve space. Use loading="lazy" below the fold, not for an important initial image. alt describes meaning rather than repeating a filename.']
 ],'<img src="project-800.jpg"\n  srcset="project-400.jpg 400w, project-800.jpg 800w"\n  sizes="(max-width: 600px) 100vw, 50vw"\n  width="800" height="500"\n  alt="Dashboard with a project list">',
 ['Підготуй зображення 400 і 800 px. Додай його до картки, на мобільному покажи на всю ширину, на десктопі — на половину. Перевір вибраний файл у Network із вимкненим кешем.','Prepare 400 and 800 px files. Show the image full width on mobile and half width on desktop. Inspect the selected file in Network with cache disabled.'],
 ['Місце під зображення зарезервоване до завантаження. На різних екранах браузер може обрати різні кандидати; selection залежить також від щільності пікселів.','Space is reserved before loading. Different screens may select different candidates; pixel density also affects selection.'],
 ['Що робить sizes?','What does sizes describe?'],[['Ширину зображення у макеті','Image width in the layout'],['Розмір файла в байтах','File size in bytes'],['Висоту екрана','Screen height']],0,'https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Responsive_images');
chapter('HTML','form-validation',['Форми: валідація й повідомлення','Forms: validation and messages'],[
 ['Спочатку опиши поля й результат відправлення. label пов’язуй із полем через for та id. Використовуй відповідні type, required і межі: це дає браузеру можливість перевірити базові вимоги.', 'Помилка має пояснювати, що виправити, а не лише фарбувати рамку. Перевірку у браузері можна обійти, тому сервер повинен перевіряти дані повторно. Тут ми будуємо лише клієнтський інтерфейс.', 'Відправлення обробляй через submit форми, а не тільки click кнопки: тоді працює Enter. checkValidity повертає результат перевірки; reportValidity також показує повідомлення. Не стирай введення після помилки — користувачу треба його виправити.'],
 ['Define fields and the submission outcome first. Connect labels through for and id. Appropriate type, required and bounds give the browser basic validation rules.', 'Explain how to fix an error rather than only changing a border color. Browser validation can be bypassed, so the server must validate again. This exercise builds the client interface only.', 'Handle form submit rather than only a button click, so Enter works too. checkValidity returns validation status; reportValidity also displays feedback. Preserve entered values when validation fails.']
 ],'<form id="contact">\n  <label for="email">Email</label>\n  <input id="email" name="email" type="email" required>\n  <button type="submit">Send</button>\n  <p id="status" role="status"></p>\n</form>',
 ['Додай ім’я й email, обов’язкові поля та повідомлення про успіх. Перевір порожній email, неправильну адресу та відправлення Enter. Не роби мережевий запит: покажи лише результат перевірки.','Add name and email, required rules and success feedback. Test empty email, invalid email and Enter submission. Display validation results without sending a network request.'],
 ['Неправильний email не проходить; правильний показує повідомлення. Значення лишаються у формі, label фокусує потрібне поле.','Invalid email is rejected; valid input displays feedback. Values remain in the form and each label focuses its field.'],
 ['Чи замінює HTML-валідація перевірку на сервері?','Does HTML validation replace server validation?'],[['Так','Yes'],['Ні, її можна обійти','No, it can be bypassed']],1,'https://developer.mozilla.org/en-US/docs/Web/HTML/Guides/Constraint_validation');
chapter('CSS','container-queries',['Компонентна адаптивність','Container-based responsiveness'],[
 ['Media query описує умови вікна браузера. Але одна картка може стояти і в широкому контенті, і у вузькому sidebar на тому самому екрані. Для такого компонента корисно реагувати на його контейнер.', 'Встанови container-type: inline-size на обгортці, а правило @container застосуй до елементів усередині. Порогове значення обирай там, де контент реально перестає вміщатися, а не під конкретну модель телефона.', 'Залиш базові стилі придатними для вузького контейнера. Потім додай ширший варіант. Перевір довгий заголовок і переклад: адаптивність означає, що зміст зберігається, а не просто стає меншим.'],
 ['Media queries describe viewport conditions. The same card can appear in broad content and a narrow sidebar on one screen. A component can instead respond to its container.', 'Set container-type: inline-size on a wrapper and apply @container rules to descendants. Choose a breakpoint where content no longer fits rather than for a particular phone model.', 'Make base styles usable in a narrow container, then add a wider version. Try long titles and translations: responsiveness must preserve content rather than simply shrink it.']
 ],'.wrapper { container-type: inline-size; }\n.card { display: grid; gap: 16px; }\n@container (min-width: 500px) {\n  .card { grid-template-columns: 160px 1fr; }\n}',
 ['Постав однакову картку у дві обгортки: 300 і 700 px. У широкій зроби дві колонки, у вузькій — одну.','Place the same card in 300 and 700 px wrappers. Use two columns in the wide wrapper and one in the narrow one.'],
 ['На одному екрані картки мають різний макет відповідно до доступної ширини. Текст не обрізається.','On one screen, cards use different layouts according to their available widths. Text is not clipped.'],
 ['Що вимірює size container query?','What does a size container query measure?'],[['Ширину відповідного контейнера','The relevant container width'],['Лише ширину вікна','Only viewport width']],0,'https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Containment/Container_queries');
chapter('CSS','quality-check',['Перевірка CSS перед публікацією','CSS checks before shipping'],[
 ['Гарний макет на твоєму екрані — лише один стан. Перевір 320 px, середню ширину і широкий екран; збільш текст і підстав довші назви. Шукати треба не красивий скриншот, а збереження змісту.', 'Якщо правило не працює, вибери елемент у DevTools і подивися Computed. Перекреслене правило могло програти каскад; активне правило може працювати, але його результат обмежений батьківським контейнером.', 'Перевір клавіатурний фокус, контраст, overflow і поведінку відкритого меню. Для анімацій передбач prefers-reduced-motion. Виправляй причину: overflow-x: hidden може приховати помилку разом із потрібним контентом.'],
 ['A good layout on your screen is one state only. Test 320 px, medium and wide screens; enlarge text and use longer titles. Look for content preservation rather than a perfect screenshot.', 'Inspect the element and Computed styles in DevTools when a rule fails. A crossed-out rule may have lost the cascade; an active rule may be constrained by a parent container.', 'Check keyboard focus, contrast, overflow and open menus. Respect prefers-reduced-motion for animation. Fix the cause: overflow-x: hidden can hide useful content along with the bug.']
 ],'/* Let content wrap rather than overflow. */\n.row { display: flex; flex-wrap: wrap; gap: 12px; }\n.row > * { min-width: 0; }\n.title { overflow-wrap: anywhere; }\n@media (prefers-reduced-motion: reduce) {\n  .card { transition: none; }\n}',
 ['Зроби картку з довгим URL і двома кнопками. Перевір 320 px та збільшення тексту. Знайди причину переповнення через DevTools.','Build a card with a long URL and two buttons. Test 320 px and enlarged text. Find overflow causes in DevTools.'],
 ['Кнопки переносяться, URL не розтягує сторінку; всі елементи доступні Tab.','Buttons wrap, the URL does not widen the page, and all controls are reachable with Tab.'],
 ['Що краще зробити при переповненні?','What should you do about overflow?'],[['Знайти елемент і виправити компонування','Find the element and fix its layout'],['Завжди приховати всю горизонтальну прокрутку','Always hide horizontal scrolling']],0,'https://developer.chrome.com/docs/devtools/');
chapter('JavaScript','api-errors',['API: очікування, помилки й повтор','APIs: loading, errors and retry'],[
 ['Перш ніж писати запит, визнач стани інтерфейсу: очікування, дані, порожня відповідь і помилка. Користувач має розуміти, чому список поки порожній.', 'fetch може успішно повернути Response для HTTP-помилки, тому перевір response.ok перед читанням JSON. await json() теж може завершитися помилкою. Обробляй це у try/catch, а зняття стану loading — у finally.', 'Повторний клік не повинен непомітно створювати паралельні запити. Відключи кнопку на час очікування або скасуй попередній запит через AbortController. Не показуй внутрішню технічну помилку як є: повідомлення має пояснювати наступну дію.'],
 ['Define loading, data, empty and error states before writing a request. Users should understand why a list is currently empty.', 'fetch can return a Response for an HTTP error, so check response.ok before reading JSON. await json() can also fail. Use try/catch and clear loading in finally.', 'Repeated clicks should not silently create concurrent requests. Disable the button while waiting or cancel the previous request with AbortController. User feedback should explain the next action rather than expose an internal error.']
 ],'async function loadItems(url) {\n  const response = await fetch(url);\n  if (!response.ok) throw new Error("HTTP " + response.status);\n  const items = await response.json();\n  if (!Array.isArray(items)) throw new Error("Expected an array");\n  return items;\n}',
 ['У локальному проєкті зроби кнопку завантаження й список. Спробуй тестовий API, неправильний шлях та порожній масив. У пісочниці Kachan мережа ізольована — там використай mock-функцію з Promise.','In a local project, create a load button and list. Try a test API, wrong path and empty array. Kachan isolates the playground network; use a mock Promise function there.'],
 ['Loading зникає і при успіху, і при помилці; є окреме повідомлення для порожнього масиву та можливість повторити.','Loading ends on success and failure, empty arrays have distinct feedback, and users can retry.'],
 ['Чи гарантує успішний fetch статус 200?','Does a resolved fetch guarantee status 200?'],[['Так','Yes'],['Ні, треба перевіряти response.ok','No, check response.ok']],1,'https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch');
chapter('JavaScript','modules',['Модулі та межі відповідальності','Modules and responsibility boundaries'],[
 ['Коли один script.js містить усе, зміну важко локалізувати. Виділяй модуль за відповідальністю: робота з даними, обчислення або відображення. Не створюй окремий файл для кожного рядка.', 'export робить значення доступним, import явно описує залежність. Підключай точку входу через script type="module". Перевір шляхи відносно файла, який імпортує, а не відносно HTML.', 'У модулі краще передавати потрібні дані параметрами й повертати результат. Чиста функція не змінює чужий масив непомітно. DOM-оновлення залишай ближче до інтерфейсу — тоді обчислення можна перевірити окремо.'],
 ['When one script contains everything, changes become hard to isolate. Split responsibilities such as data access, calculations and rendering, not every line into a separate file.', 'export exposes values and import declares dependencies. Load the entry point using script type="module". Resolve paths relative to the importing file, not the HTML file.', 'Pass required data as parameters and return a result. A pure function does not silently mutate a caller’s array. Keep DOM updates near the UI so calculations can be tested separately.']
 ],'// progress.js\nexport function completedCount(tasks) {\n  return tasks.filter(task => task.completed).length;\n}\n// app.js\nimport { completedCount } from "./progress.js";\nconsole.log(completedCount([{ completed: true }]));',
 ['Створи progress.js та app.js у навчальній папці й запусти локальний сервер. Перевір порожній список, одну завершену й дві активні задачі. Пісочниця з одним JS-полем не відтворює імпорт локальних файлів.','Create progress.js and app.js in a learning folder and use a local server. Test empty input, one completed and two active tasks. The single-file playground does not emulate local file imports.'],
 ['Лічильник повертає 0, 1 та 0 відповідно; початкові масиви не змінені.','The counter returns 0, 1 and 0 respectively, leaving original arrays unchanged.'],
 ['Відносно чого обчислюється шлях import?','What is an import path relative to?'],[['Файла, який імпортує','The importing file'],['Завжди кореня диска','Always the disk root']],0,'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules');
chapter('TypeScript','narrowing-extra',['unknown і безпечне звуження','unknown and safe narrowing'],[
 ['Тип із сервера не стає правильним лише через as. Якщо дані невідомі, починай з unknown і перевіряй їх перед використанням. Це допомагає відділити зовнішні дані від внутрішньої моделі.', 'Звуження означає, що перевірка дозволяє компілятору уточнити тип у певній гілці. Перевір typeof, наявність властивостей і конкретні значення. Для рядків після typeof можна викликати trim; для unknown без перевірки — ні.', 'Передай у функцію рядок, число й null. Добрий контракт визначає, що робити з кожним із них. Не прибирай попередження за допомогою any, якщо можеш явно описати поведінку.'],
 ['Server data does not become valid merely through as. Start with unknown and validate before use to separate external data from internal models.', 'Narrowing lets the compiler refine a type within a branch. Inspect typeof, property presence and specific values. After a string check you can call trim; arbitrary unknown values do not allow it.', 'Try a string, number and null. Define behavior for each input rather than suppress warnings with any.']
 ],'function displayName(value: unknown): string {\n  if (typeof value === "string") {\n    return value.trim() || "Anonymous";\n  }\n  return "Anonymous";\n}',
 ['Перевір " Rubin ", "   ", 42 і null. Потім додай підтримку об’єкта з полем name, перевіривши і об’єкт, і тип поля.','Test " Rubin ", whitespace, 42 and null. Then support an object with name by checking the object and field type.'],
 ['Перший рядок дає Rubin, інші базові значення — Anonymous. Жоден випадок не викликає trim на числі чи null.','The first input returns Rubin; other base inputs return Anonymous. trim is never called on a number or null.'],
 ['Чи перевіряє as дані під час виконання?','Does as validate data at runtime?'],[['Так','Yes'],['Ні','No']],1,'https://www.typescriptlang.org/docs/handbook/2/narrowing.html');
chapter('TypeScript','generics-extra',['Generics: зберігаємо зв’язок типів','Generics: preserving type relationships'],[
 ['Generic потрібен, коли результат залежить від типу вводу. Функція, що бере перший елемент, повинна повернути елемент того самого типу, а не any.', 'Параметр T означає тип, який буде обрано для конкретного виклику. Для порожнього масиву результат може бути undefined, тому контракт має це показувати. Назва параметра не створює перевірки під час виконання.', 'Не роби generic там, де зв’язку між типами немає. Перед складними обмеженнями спробуй два різних виклики: числа й об’єкти. Переконайся, що редактор правильно підказує тип результату.'],
 ['Use a generic when an output type depends on an input type. A first-item function should preserve the element type instead of returning any.', 'T represents the type chosen for a call. An empty array can produce undefined, which belongs in the contract. A type parameter does not create runtime validation.', 'Avoid generics without meaningful type relationships. Test number and object calls and inspect the inferred results before adding complex constraints.']
 ],'function first<T>(items: T[]): T | undefined {\n  return items[0];\n}\nconst number = first([10, 20]);\nconst project = first([{ name: "Kachan" }]);\nconsole.log(first([]));',
 ['Створи функцію last<T>. Перевір числа, об’єкти та порожній масив. Оброби undefined перед використанням результата.','Create last<T>. Test numbers, objects and an empty array. Handle undefined before using the result.'],
 ['Для [1, 2] отримуєш 2; для порожнього масиву — undefined. Об’єкт зберігає свій тип.','[1, 2] produces 2; an empty array produces undefined. Objects retain their types.'],
 ['Для чого тут T?','What is T for here?'],[['Зберегти зв’язок типу вводу й результату','Preserve the input/output type relationship'],['Автоматично перевірити JSON','Automatically validate JSON']],0,'https://www.typescriptlang.org/docs/handbook/2/generics.html');
chapter('Git','merge-conflicts',['Конфлікти без паніки','Handling merge conflicts'],[
 ['Конфлікт означає, що Git не зміг сам об’єднати зміни. Це не зникнення репозиторію. Почни з git status і переліку файлів, а не з випадкових команд.', 'У конфліктному файлі порівняй обидві версії та напиши потрібний кінцевий результат. Прибери маркери конфлікту, перевір код, додай файл до індексу й заверши поточну операцію за підказкою status.', 'Відпрацьовуй це в окремому навчальному репозиторії. Не використовуй reset --hard як універсальне лікування. Для незавершеного merge є merge --abort; спершу перевір стан і збережи потрібні локальні зміни.'],
 ['A conflict means Git could not combine changes automatically; the repository is not lost. Start with git status and the affected files instead of random commands.', 'Compare both versions in the conflicted file and write the intended final result. Remove conflict markers, test the code, stage the file and finish the operation as status directs.', 'Practise in a separate learning repository. Do not use reset --hard as a universal fix. merge --abort can cancel an unfinished merge; inspect state and preserve needed changes first.']
 ],'git status\n# Edit the conflicted file and remove conflict markers.\ngit diff\ngit add index.html\ngit commit',
 ['У навчальному репозиторії зміни один заголовок у двох гілках. Об’єднай гілки, обери фінальний текст, перевір сторінку й заверши merge. Ця вправа потребує реального Git: симулятор не моделює довільні конфлікти файлів.','In a learning repository, change one heading in two branches. Merge, choose final text, inspect the page and finish. This needs real Git; the simulator does not model arbitrary file conflicts.'],
 ['status більше не показує unmerged paths, у файлі немає маркерів, історія містить завершене об’єднання.','status shows no unmerged paths, files have no conflict markers and history contains the completed merge.'],
 ['Що перше робити після конфлікту?','What should you do first after a conflict?'],[['Перевірити git status','Inspect git status'],['Одразу видалити репозиторій','Delete the repository']],0,'https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging');
chapter('Git','undo-safely',['Як скасовувати зміни','Undoing changes deliberately'],[
 ['Спочатку визнач, де зміна: лише у файлі, в індексі чи вже в коміті. Одна команда не підходить для всіх трьох станів. Дивись status, diff і diff --staged.', 'restore --staged прибирає файл з індексу, залишаючи робочу зміну. restore файла відновлює його вміст і може знищити незбережене редагування. Спробуй це лише на копії, де втрата навмисна.', 'Якщо коміт уже спільний, revert створює новий коміт зі зворотною зміною. Це зберігає історію для інших учасників. Перед будь-яким скасуванням поясни собі, який стан має залишитися.'],
 ['Locate the change first: working file, staging area or commit. No single command fits all three states. Inspect status, diff and diff --staged.', 'restore --staged unstages a file while preserving the working change. Restoring file contents can discard editing; try it only on a disposable copy.', 'For a shared commit, revert records a new inverse commit while preserving history. Define the desired remaining state before undoing anything.']
 ],'git status\ngit diff\ngit diff --staged\n# Unstage without discarding the working edit:\ngit restore --staged index.html',
 ['У навчальному репозиторії зміни файл, додай його в індекс і прибери з індексу. Перевір, що сам текст не зник. Не запускай руйнівні команди у робочому проєкті.','Change and stage a file in a learning repository, then unstage it. Verify the text remains. Do not run destructive commands in your working project.'],
 ['Зміна видима в diff, але відсутня в diff --staged. Робочий файл містить твоє редагування.','The change appears in diff but not diff --staged; the working file retains the edit.'],
 ['Що зберігає restore --staged?','What does restore --staged preserve?'],[['Робочу зміну файла','The working file change'],['Обов’язково видаляє всю історію','It deletes all history']],0,'https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things');
chapter('Figma','responsive-layout',['Auto layout із реальним контентом','Auto layout with real content'],[
 ['Макет має витримувати зміну тексту. Почни з вертикальної картки: заголовок, опис і кнопка. Вибери осмислені gap та padding, щоб не пересувати кожен елемент вручну.', 'Hug підлаштовує контейнер під його зміст, Fill дає дочірньому елементу зайняти доступний простір. Fixed зберігає заданий розмір. Перевір обидві осі: гарна ширина не гарантує правильної висоти.', 'Зроби дві версії тексту, коротку й довгу, і змінюй ширину батька. Передавання макета починається з пояснення цієї поведінки. Скріншот одного стану не описує правила компонування.'],
 ['A design should survive text changes. Start with a vertical title, description and button card. Use deliberate gap and padding instead of manually moving every layer.', 'Hug adapts to content, Fill occupies available parent space and Fixed retains a specified size. Inspect both axes; correct width does not guarantee correct height.', 'Try short and long text while changing parent width. Explain this behavior when handing off the design: one screenshot does not define layout rules.']
 ],'Card: vertical auto layout\nPadding: 24\nGap: 16\nWidth: Fill container\nHeight: Hug contents\nButton: Hug contents',
 ['У Figma створи картку і зроби три копії шириною 280, 400 та 600 px. Додай довгий заголовок і перевір поведінку кнопки.','In Figma, create a card and copies at 280, 400 and 600 px. Add a long heading and inspect the button.'],
 ['Текст переноситься, висота росте за змістом, кнопка не перекриває опис. Перевірка виконується вручну у Figma.','Text wraps, height grows with content and the button does not overlap the description. Check manually in Figma.'],
 ['Що доречно для висоти картки зі змінним текстом?','What fits a card height with changing text?'],[['Hug contents','Hug contents'],['Завжди Fixed 100 px','Always Fixed 100 px']],0,'https://help.figma.com/hc/en-us/articles/360040451373-Guide-to-auto-layout-in-Figma');
chapter('Figma','handoff',['Компоненти й передавання в розробку','Components and developer handoff'],[
 ['Опиши компонент через його роль і стани, а не лише колір. Для кнопки потрібні назва, тип дії та поведінка при недоступності. Зберігай спільну основу через компонент і використовуй instances для повторів.', 'До макета додай пояснення: що змінюється на вузькому екрані, як виглядає довгий текст, де фокус і що відбувається після натискання. Це допомагає розробнику реалізувати поведінку, а не копіювати пікселі.', 'Відділи дизайн-значення від обіцянок реалізації. Наявність disabled-стану в макеті не означає, що HTML-кнопка вже має disabled. Після верстки звір компонування й доступність у браузері.'],
 ['Describe component roles and states, not just colors. A button needs a name, action type and unavailable behavior. Use a shared component and instances for repetition.', 'Document narrow-screen behavior, long text, focus and click outcomes. This helps developers implement behavior rather than copy pixels.', 'Separate design values from implemented behavior: a disabled visual state does not give an HTML button a disabled attribute. Review layout and accessibility in the browser after implementation.']
 ],'Button / primary\nStates: default, hover, focus, disabled\nText: editable\nSpacing: shared token\nHandoff: action + responsive rules + keyboard behavior',
 ['Створи компонент кнопки та дві instances. Зміни базовий відступ, перевір обидві копії. Запиши правила фокусу й поведінки disabled поруч із компонентом.','Create a button component and two instances. Change base padding and inspect both copies. Document focus and disabled behavior beside the component.'],
 ['Спільні зміни відображаються в instances; текст може відрізнятись. Правила поведінки зрозумілі без усного пояснення.','Shared changes appear in instances while text can differ. Behavior rules are understandable without a verbal explanation.'],
 ['Чи достатньо макета для перевірки HTML-доступності?','Is a design file enough to verify HTML accessibility?'],[['Ні, треба перевірити реалізацію','No, inspect the implementation'],['Так, браузерна перевірка зайва','Yes, browser testing is unnecessary']],0,'https://help.figma.com/hc/en-us/articles/360038662654-Guide-to-components-in-Figma');

const extraResources=[
 ['responsive-images','MDN · Responsive images','Docs',extraChapters[0].docs,'Як обирати зображення для різних екранів.','How to choose images for different screens.','HTML'],
 ['form-validation','MDN · Form validation','Docs',extraChapters[1].docs,'Правила перевірки форм і повідомлення про помилки.','Form validation rules and error feedback.','HTML'],
 ['container-queries','MDN · Container queries','Docs',extraChapters[2].docs,'Адаптивні компоненти за розміром контейнера.','Responsive components based on container size.','CSS'],
 ['chrome-devtools','Chrome DevTools','Tools',extraChapters[3].docs,'Перевіряй CSS, JavaScript, мережу й швидкість.','Inspect CSS, JavaScript, network and performance.','quality'],
 ['fetch-guide','MDN · Using Fetch','Docs',extraChapters[4].docs,'HTTP-запити, відповіді та обробка помилок.','HTTP requests, responses and error handling.','API'],
 ['js-modules','MDN · JavaScript modules','Docs',extraChapters[5].docs,'Import, export та організація коду у файлах.','Import, export and organizing code across files.','JavaScript'],
 ['ts-narrowing','TypeScript · Narrowing','Docs',extraChapters[6].docs,'Звуження типів і перевірка невідомих значень.','Narrowing types and checking unknown values.','TypeScript'],
 ['ts-generics','TypeScript · Generics','Docs',extraChapters[7].docs,'Функції, що зберігають зв’язок між типами.','Functions preserving type relationships.','TypeScript'],
 ['git-merge','Git · Branching and merging','Docs',extraChapters[8].docs,'Робота з гілками й об’єднанням змін.','Branches and merging changes.','Git'],
 ['git-undo','Git · Undoing things','Docs',extraChapters[9].docs,'Обирай скасування відповідно до стану змін.','Choose undo operations based on change state.','Git'],
 ['figma-auto-layout-guide','Figma · Auto layout','Docs',extraChapters[10].docs,'Розміри, відступи й зміна контенту в макетах.','Sizing, spacing and content changes in designs.','design'],
 ['figma-components-guide','Figma · Components','Docs',extraChapters[11].docs,'Компоненти та їх повторне використання.','Components and reuse through instances.','design'],
 ['wai-tutorials','W3C · Accessibility tutorials','Docs','https://www.w3.org/WAI/tutorials/','Практичні пояснення доступних форм, зображень і навігації.','Practical accessible forms, images and navigation.','accessibility'],
 ['mdn-performance','MDN · Web performance','Docs','https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Performance','Основи швидкості сайту та вимірювання результатів.','Website performance fundamentals and measurement.','quality'],
 ['js-promises-guide','MDN · Using promises','Docs','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises','Послідовність асинхронних операцій та помилки.','Async sequencing and errors.','JavaScript']
];
for(const row of extraResources)if(!resources.some(r=>r[0]===row[0]||r[3]===row[3]))resources.push(row);
