Object.assign(translations.uk,{quickTask:'＋ Нова задача',todayTitle:'Сьогодні та найближчі дедлайни',continueLearning:'Продовжити навчання',continueButton:'До уроку →',dailyGoals:'Мій фокус',dayGoal:'Ціль на сьогодні',weekGoal:'Ціль на тиждень',activityTitle:'Остання активність',weeklyActivity:'Активність за 7 днів',chartLegend:'Завершені задачі / уроки',activityHint:'Завершені задачі й уроки від моменту ввімкнення історії. Старі дії не відновлюються.',noToday:'Задач із дедлайном на найближчі 7 днів немає.',noActivity:'Історія з’явиться після твоїх наступних дій.',allLessonsDone:'Усі уроки HTML завершено. Можна повторити останній.',taskCreated:'Створено задачу',taskCompleted:'Завершено задачу',taskReopened:'Повернуто задачу в роботу',taskEdited:'Оновлено задачу',taskDeleted:'Видалено задачу',projectCreated:'Створено проєкт',noteCreated:'Створено нотатку',noteEdited:'Оновлено нотатку',lessonCompleted:'Завершено урок',goalsSaved:'Цілі збережено',upcoming:'Найближчі',todayDue:'На сьогодні'});
Object.assign(translations.en,{quickTask:'＋ New task',todayTitle:'Today and upcoming deadlines',continueLearning:'Continue learning',continueButton:'Go to lesson →',dailyGoals:'My focus',dayGoal:'Today’s goal',weekGoal:'This week’s goal',activityTitle:'Recent activity',weeklyActivity:'7-day activity',chartLegend:'Completed tasks / lessons',activityHint:'Completed tasks and lessons since activity tracking began. Earlier actions are not reconstructed.',noToday:'No tasks due within the next 7 days.',noActivity:'Your next actions will appear here.',allLessonsDone:'All HTML lessons completed. Revisit the last lesson.',taskCreated:'Task created',taskCompleted:'Task completed',taskReopened:'Task reopened',taskEdited:'Task updated',taskDeleted:'Task deleted',projectCreated:'Project created',noteCreated:'Note created',noteEdited:'Note updated',lessonCompleted:'Lesson completed',goalsSaved:'Goals saved',upcoming:'Upcoming',todayDue:'Due today'});
const activityKinds=['taskCreated','taskCompleted','taskReopened','taskEdited','taskDeleted','projectCreated','noteCreated','noteEdited','lessonCompleted'];
function validDashboard(d){return d&&d.version===1&&Array.isArray(d.activity)&&d.activity.length<=1000&&d.activity.every(a=>a&&activityKinds.includes(a.kind)&&typeof a.subject==='string'&&a.subject.length<=200&&(a.entityId===undefined||(typeof a.entityId==='string'&&a.entityId.length<=100))&&typeof a.at==='string'&&Number.isFinite(Date.parse(a.at)))&&d.goals&&['day','week'].every(k=>d.goals[k]&&typeof d.goals[k].text==='string'&&d.goals[k].text.length<=200&&typeof d.goals[k].period==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d.goals[k].period));}
function weekStart(){const date=new Date(todayInKyiv()+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));return date.toISOString().slice(0,10);}
let dashboardData=readData('devspace-dashboard',{version:1,activity:[],goals:{day:{text:'',period:todayInKyiv()},week:{text:'',period:weekStart()}}},validDashboard);
function saveDashboard(){return writeData('devspace-dashboard',dashboardData);}
function recordActivity(kind,subject,entityId=''){const at=new Date().toISOString();const previous=dashboardData.activity[0];if(kind==='noteEdited'&&previous?.kind===kind&&previous.entityId===entityId&&Date.parse(at)-Date.parse(previous.at)<60000){previous.at=at;previous.subject=String(subject).slice(0,200);}else dashboardData.activity.unshift({kind,subject:String(subject).slice(0,200),entityId,at});dashboardData.activity=dashboardData.activity.slice(0,1000);saveDashboard();}
let taskSnapshot=JSON.parse(JSON.stringify(tasks)),projectIds=new Set(projects.map(p=>p.id)),noteSnapshot=JSON.parse(JSON.stringify(notes)),lessonSnapshot=new Set(htmlLessons.filter(l=>htmlCourse.lessons[l.id]?.completed).map(l=>l.id));
const originalSaveTasks=saveTasks;
saveTasks=function(){originalSaveTasks();for(const task of tasks){const old=taskSnapshot.find(t=>t.id===task.id);const title=task.translationKey?t()[task.translationKey]:task.title;if(!old)recordActivity('taskCreated',title,task.id);else if(old.completed!==task.completed)recordActivity(task.completed?'taskCompleted':'taskReopened',title,task.id);else if(JSON.stringify(old)!==JSON.stringify(task))recordActivity('taskEdited',title,task.id);}for(const old of taskSnapshot)if(!tasks.some(t=>t.id===old.id))recordActivity('taskDeleted',old.translationKey?t()[old.translationKey]:old.title,old.id);taskSnapshot=JSON.parse(JSON.stringify(tasks));renderDailyDashboard();};
const originalSaveProjects=saveProjects;
saveProjects=function(){originalSaveProjects();for(const p of projects)if(!projectIds.has(p.id))recordActivity('projectCreated',p.name,p.id);projectIds=new Set(projects.map(p=>p.id));renderDailyDashboard();};
const originalPersistNotes=persistNotes;
persistNotes=function(){originalPersistNotes();for(const n of notes){const old=noteSnapshot.find(o=>o.id===n.id);if(!old)recordActivity('noteCreated',n.title||t().untitledNote,n.id);else if((old.title!==n.title||old.body!==n.body)&&!n.deleted)recordActivity('noteEdited',n.title||t().untitledNote);}noteSnapshot=JSON.parse(JSON.stringify(notes));renderDailyDashboard();};
const originalSaveHtml=saveHtmlCourse;
saveHtmlCourse=function(){const saved=originalSaveHtml();for(const lesson of htmlLessons)if(htmlCourse.lessons[lesson.id]?.completed&&!lessonSnapshot.has(lesson.id)){recordActivity('lessonCompleted',lesson.title[document.documentElement.lang],lesson.id);lessonSnapshot.add(lesson.id);}renderDailyDashboard();return saved;};
function calendarDay(at){return new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/Kyiv'}).format(new Date(at));}
function renderDailyDashboard(){
 const text=t(),today=todayInKyiv(),limit=new Date(today+'T12:00:00Z');limit.setUTCDate(limit.getUTCDate()+7);const until=limit.toISOString().slice(0,10);
 const due=tasks.filter(task=>!task.completed&&task.deadline&&task.deadline<=until).sort((a,b)=>a.deadline.localeCompare(b.deadline));
 document.querySelector('#today-count').textContent=due.length;
 document.querySelector('#today-summary').textContent=text.overdue+': '+due.filter(t=>t.deadline<today).length+' · '+text.todayDue+': '+due.filter(t=>t.deadline===today).length+' · '+text.upcoming+': '+due.filter(t=>t.deadline>today).length;
 const list=document.querySelector('#today-tasks');list.replaceChildren();if(!due.length)list.append(projectElement('li','empty-state',text.noToday));for(const task of due.slice(0,8)){const li=document.createElement('li');const label=projectElement('label','task-row');const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.addEventListener('change',()=>{task.completed=checkbox.checked;saveTasks();markProjectWorked(task.projectId);renderTasks();renderProjects();});label.append(checkbox,projectElement('span','',task.translationKey?text[task.translationKey]:task.title));const meta=projectElement('div','task-metadata',task.deadline+(task.deadline<today?' · '+text.overdue:''));li.append(label,meta);list.append(li);}
 const current=htmlLessons.find(l=>l.id===htmlCourse.selected&&!htmlCourse.lessons[l.id]?.completed)||htmlLessons.find(l=>!htmlCourse.lessons[l.id]?.completed)||htmlLessons[htmlLessons.length-1];document.querySelector('#continue-lesson').textContent=current.title[document.documentElement.lang]+(htmlLessons.every(l=>htmlCourse.lessons[l.id]?.completed)?' · '+text.allLessonsDone:'');document.querySelector('#continue-html').dataset.lesson=current.id;
 const recent=document.querySelector('#daily-notes');recent.replaceChildren();const recentNotes=notes.filter(n=>!n.deleted).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||Date.parse(b.updatedAt)-Date.parse(a.updatedAt)).slice(0,4);if(!recentNotes.length)recent.append(projectElement('p','panel-note',text.emptyNotes));for(const n of recentNotes){const b=projectElement('button','note-list-item',(n.pinned?'★ ':'')+(n.title||text.untitledNote));b.type='button';b.addEventListener('click',()=>{selectedNote=n.id;showTrash=false;document.querySelector('#notes-search').value='';document.querySelector('#notes-folder').value='all';location.hash='notes';renderNotes();});recent.append(b);}
 const activity=document.querySelector('#activity-list');activity.replaceChildren();if(!dashboardData.activity.length)activity.append(projectElement('li','panel-note',text.noActivity));for(const a of dashboardData.activity.slice(0,6)){const li=projectElement('li','');li.append(projectElement('span','',text[a.kind]+': '+(a.kind==='lessonCompleted'?(htmlLessons.find(l=>l.id===a.entityId)?.title[document.documentElement.lang]||a.subject):['noteCreated','noteEdited'].includes(a.kind)?(notes.find(n=>n.id===a.entityId)?.title||a.subject):a.subject)),projectElement('time','',new Intl.DateTimeFormat(document.documentElement.lang==='uk'?'uk-UA':'en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Kyiv'}).format(new Date(a.at))));activity.append(li);}
 const chart=document.querySelector('#activity-chart');chart.replaceChildren();for(let offset=6;offset>=0;offset--){const date=new Date(today+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-offset);const day=date.toISOString().slice(0,10);const entries=dashboardData.activity.filter(a=>calendarDay(a.at)===day);const completed=new Set(entries.filter(a=>a.kind==='taskCompleted').map(a=>a.entityId||a.subject)).size;const lessons=new Set(entries.filter(a=>a.kind==='lessonCompleted').map(a=>a.subject)).size;const column=projectElement('div','chart-column');const counts=projectElement('span','',completed+' / '+lessons);const bar=projectElement('div','chart-bar');bar.style.height=Math.min(80,(completed+lessons)*10)+'px';column.append(counts,bar,projectElement('span','',new Intl.DateTimeFormat(document.documentElement.lang==='uk'?'uk-UA':'en-GB',{weekday:'short',timeZone:'Europe/Kyiv'}).format(date)));column.setAttribute('aria-label',day+': '+text.completedTasks+' '+completed+', HTML '+lessons);chart.append(column);}
}
function fillGoals(){document.querySelector('#day-goal').value=dashboardData.goals.day.period===todayInKyiv()?dashboardData.goals.day.text:'';document.querySelector('#week-goal').value=dashboardData.goals.week.period===weekStart()?dashboardData.goals.week.text:'';}
document.querySelector('#goal-form').addEventListener('submit',e=>{e.preventDefault();dashboardData.goals={day:{text:document.querySelector('#day-goal').value.trim(),period:todayInKyiv()},week:{text:document.querySelector('#week-goal').value.trim(),period:weekStart()}};document.querySelector('#goal-status').textContent=t()[saveDashboard()?'goalsSaved':'storageFailed'];});
document.querySelector('#quick-task').addEventListener('click',()=>{location.hash='tasks';showView();resetTaskForm();document.querySelector('#task-input').focus();});
document.querySelector('#quick-project').addEventListener('click',()=>{location.hash='projects';showView();resetProjectForm();document.querySelector('#project-editor').open=true;document.querySelector('#project-name').focus();});
document.querySelector('#quick-note').addEventListener('click',()=>{location.hash='notes';showView();document.querySelector('#note-template').value='blank';document.querySelector('#note-new').click();});
document.querySelector('#continue-html').addEventListener('click',()=>{htmlCourse.selected=document.querySelector('#continue-html').dataset.lesson;courseResults=null;saveHtmlCourse();location.hash='learning';renderHtmlCourse();requestAnimationFrame(()=>document.querySelector('#html-course').scrollIntoView({behavior:'smooth'}));});
window.addEventListener('languagechange',renderDailyDashboard);window.addEventListener('hashchange',()=>{if(location.hash==='#dashboard'){renderDailyDashboard();fillGoals();}});document.addEventListener('visibilitychange',()=>{if(!document.hidden){renderDailyDashboard();fillGoals();}});fillGoals();setLanguage(document.documentElement.lang);
