// Generators use controlled values; user JavaScript runs in the existing opaque worker sandbox.
const developerCopy={uk:{flex:'CSS · Flexbox',paint:'CSS · Градієнти й тіні',form:'HTML · Конструктор форми',audit:'HTML · Перевірка розмітки',practice:'JavaScript · Практика',free:'Вільний код',run:'Запустити',check:'Перевірити',reset:'Відновити чернетку?',starter:'Початковий код',hint:'Підказка',solution:'Показати рішення',console:'Консоль і результат',saved:'Чернетки зберігаються у цьому браузері.',empty:'Натисни «Запустити» або «Перевірити».',pass:'Пройдено',fail:'Не пройдено',gap:'Проміжок',direction:'Напрямок',justify:'Головна вісь',align:'Поперечна вісь',wrap:'Переносити рядки',color1:'Перший колір',color2:'Другий колір',angle:'Кут градієнта',blur:'Розмиття тіні',offset:'Зсув тіні',radius:'Округлення',label:'Підпис поля',type:'Тип поля',required:'Обов’язкове поле',submit:'Текст кнопки',html:'HTML-код',preview:'Перегляд',basic:'Базова перевірка: назви, підписи, дублікати ID та зображення. Це не повний HTML-валідатор.',none:'У цих перевірках проблем не знайдено.',sandbox:'Код працює окремо від сайту, без доступу до твоїх даних. DOM недоступний; для DOM використовуй пісочницю HTML/CSS/JS. fetch тут повертає навчальні дані, а не робить зовнішній запит.',draft:'Код',copy:'Копіювати'},en:{flex:'CSS · Flexbox',paint:'CSS · Gradients & shadows',form:'HTML · Form builder',audit:'HTML · Markup checks',practice:'JavaScript · Practice',free:'Free code',run:'Run',check:'Check',reset:'Restore the starter draft?',starter:'Starter code',hint:'Hint',solution:'Show solution',console:'Console & result',saved:'Drafts save in this browser.',empty:'Select Run or Check.',pass:'Passed',fail:'Not passed',gap:'Gap',direction:'Direction',justify:'Main axis',align:'Cross axis',wrap:'Wrap rows',color1:'First colour',color2:'Second colour',angle:'Gradient angle',blur:'Shadow blur',offset:'Shadow offset',radius:'Radius',label:'Field label',type:'Field type',required:'Required field',submit:'Button text',html:'HTML code',preview:'Preview',basic:'Basic checks for names, labels, duplicate IDs and images. This is not a full HTML validator.',none:'No issues found by these checks.',sandbox:'Code runs separately from the site without access to your data. DOM is unavailable; use the HTML/CSS/JS playground for DOM. fetch returns educational mock data rather than making external requests.',draft:'Code',copy:'Copy'}};
const dc=()=>developerCopy[document.documentElement.lang];
const developerCheckLabels={
 'New array; input unchanged':bi('Новий масив; вхід не змінено','New array; input unchanged'),
 'Spaces and case':bi('Пробіли й регістр','Spaces and case'),
 'No match':bi('Немає збігу','No match'),
 'Empty query':bi('Порожній запит','Empty query'),
 'Distinct values and order':bi('Унікальні значення й порядок','Distinct values and order'),
 'Empty input':bi('Порожній ввід','Empty input'),
 'Input unchanged':bi('Вхід не змінено','Input unchanged'),
 'Boundary values':bi('Межові значення','Boundary values'),
 'Out of range / decimal':bi('Поза межами / дробове число','Out of range / decimal'),
 'Invalid types':bi('Неправильні типи','Invalid types'),
 'Returns Promise':bi('Повертає Promise','Returns Promise')
};
const developerExercises=[
 {id:'sum',title:bi('Сума чисел','Sum numbers'),task:bi('Напиши sum(numbers), яка повертає суму масиву. Порожній масив має дати 0.','Write sum(numbers) returning an array sum. An empty array must return 0.'),starter:'function sum(numbers) {\n  return 0;\n}\nconsole.log(sum([2, 3]));',solution:'function sum(numbers) { return numbers.reduce((total, number) => total + number, 0); }',hint:bi('Використай reduce з початковим значенням 0.','Use reduce with an initial value of 0.'),checks:[['sum([2,3]) === 5','2 + 3 = 5'],['sum([]) === 0','[] → 0'],['sum([-2,5]) === 3','-2 + 5 = 3']]},
 {id:'active',title:bi('Відбір активних задач','Filter active tasks'),task:bi('active(tasks) повертає новий масив задач із completed: false та не змінює вхід.','active(tasks) returns a new array of tasks with completed: false without changing the input.'),starter:'function active(tasks) {\n  return tasks;\n}',solution:'function active(tasks) { return tasks.filter(task => !task.completed); }',hint:bi('filter створює новий масив.','filter creates a new array.'),checks:[['active([{completed:false},{completed:true}]).length === 1','false / true → 1'],['active([]).length === 0','[] → []'],['(()=>{const a=[{completed:false},{completed:true}];const r=active(a);return r!==a&&a.length===2&&r[0]===a[0];})()','New array; input unchanged']]},
 {id:'search',title:bi('Пошук без регістру','Case-insensitive search'),task:bi('matches(title, query) перевіряє підрядок без регістру, прибираючи пробіли навколо query.','matches(title, query) checks a substring ignoring case and surrounding query spaces.'),starter:'function matches(title, query) {\n  return title.includes(query);\n}',solution:'function matches(title, query) { return title.toLowerCase().includes(query.trim().toLowerCase()); }',hint:bi('Нормалізуй обидва рядки; trim застосуй до запиту.','Normalize both strings; trim the query.'),checks:[['matches("JavaScript"," script ") === true','Spaces and case'],['matches("CSS","Git") === false','No match'],['matches("HTML","") === true','Empty query']]},
 {id:'unique',title:bi('Прибрати дублікати','Remove duplicates'),task:bi('unique(values) повертає значення без повторів у порядку першої появи. Вхідний масив не змінюється.','unique(values) returns distinct values in first-appearance order without changing the input array.'),starter:'function unique(values) {\n  return values;\n}',solution:'function unique(values) { return [...new Set(values)]; }',hint:bi('Set зберігає унікальні значення й порядок додавання.','Set preserves distinct values and insertion order.'),checks:[['JSON.stringify(unique([2,1,2,3])) === "[2,1,3]"','Distinct values and order'],['unique([]).length === 0','Empty input'],['(()=>{const a=[1,1];unique(a);return a.length===2;})()','Input unchanged']]},
 {id:'quantity',title:bi('Перевірити кількість','Validate a quantity'),task:bi('isQuantity(value) приймає число — ціле від 1 до 100. Рядки, NaN та інші значення відхиляє.','isQuantity(value) accepts integers from 1 to 100. Reject strings, NaN and other values.'),starter:'function isQuantity(value) {\n  return true;\n}',solution:'function isQuantity(value) { return Number.isInteger(value) && value >= 1 && value <= 100; }',hint:bi('Number.isInteger перевіряє тип і цілісність. Додай межі.','Number.isInteger checks type and integerness. Add bounds.'),checks:[['isQuantity(1)&&isQuantity(100)','Boundary values'],['!isQuantity(0)&&!isQuantity(101)&&!isQuantity(1.5)','Out of range / decimal'],['!isQuantity("3")&&!isQuantity(NaN)&&!isQuantity(null)','Invalid types']]},
 {id:'async',title:bi('Асинхронний результат','Async result'),task:bi('async doubleLater(value) повертає подвоєне число. Виклик має повертати Promise.','async doubleLater(value) returns double the number. Calling it must return a Promise.'),starter:'async function doubleLater(value) {\n  return value;\n}',solution:'async function doubleLater(value) { return value * 2; }',hint:bi('async автоматично обгортає повернене значення у Promise.','async wraps the return value in a Promise.'),checks:[['doubleLater(2) instanceof Promise','Returns Promise'],['(await doubleLater(3)) === 6','3 → 6'],['(await doubleLater(-2)) === -4','-2 → -4']]}
];
function developerState(){if(!validDeveloperTools(extras.preferences.developerTools))extras.preferences.developerTools={flex:{direction:'row',justify:'flex-start',align:'center',gap:16,wrap:true},paint:{color1:'#176c9d',color2:'#79caff',angle:135,blur:24,offset:8,radius:4},form:{label:'Email',type:'email',required:true,submit:'Send'},html:'<form>\n  <input id="email" type="email">\n  <button>Send</button>\n</form>',exercise:'sum',drafts:{}};return extras.preferences.developerTools;}
function saveDeveloperTools(){persistExtras();}
for(const [id,key] of [['flex','flex'],['paint','paint'],['form','form'],['markup','audit'],['js-practice','practice']]){const translation='developer-'+key;translations.uk[translation]=developerCopy.uk[key];translations.en[translation]=developerCopy.en[key];toolTabs.push([id,translation]);purposeText[id]=[developerCopy.uk[key],developerCopy.en[key]];}
purposeText.tools=['Генератори HTML і CSS, практика JavaScript та інструменти для щоденної розробки. Обери потрібне через каталог або пошук.','HTML and CSS generators, JavaScript practice and everyday development tools. Choose from the catalog or search.'];
function devField(parent,key,type,value,change,options){const field=E('label','form-field',dc()[key]||key),input=E(type==='select'?'select':'input');input.id='dev-'+key;if(type==='select')selectOptions(input,options.map(v=>[v,v]),value);else{input.type=type;input.value=value;if(type==='checkbox')input.checked=value;if(type==='range'){input.min=0;input.max=key==='angle'?360:64;}}input.addEventListener(type==='select'||type==='checkbox'?'change':'input',()=>change(type==='checkbox'?input.checked:type==='range'?Number(input.value):input.value));field.append(input);if(type==='range'){const valueLabel=E('output','',String(value)+(key==='angle'?'°':' px'));valueLabel.htmlFor=input.id;input.addEventListener('input',()=>valueLabel.textContent=input.value+(key==='angle'?'°':' px'));field.append(valueLabel);}parent.append(field);return input;}
function developerCode(parent){const out=E('textarea','utility-output');out.readOnly=true;out.setAttribute('aria-label','HTML / CSS');parent.append(out,button(dc().copy,()=>copyToolText(out.value)));return out;}
function renderFlexTool(body){const v=developerState().flex,layout=E('div','developer-layout'),controls=E('section','dashboard-panel'),preview=E('section','dashboard-panel'),stage=E('div','flex-preview');stage.id='flex-preview';for(let i=1;i<=5;i++)stage.append(E('div','',String(i)));preview.append(stage);const code=developerCode(preview);const update=()=>{stage.style.cssText=`display:flex;flex-direction:${v.direction};justify-content:${v.justify};align-items:${v.align};gap:${v.gap}px;flex-wrap:${v.wrap?'wrap':'nowrap'}`;code.value=`.container {\n  display: flex;\n  flex-direction: ${v.direction};\n  justify-content: ${v.justify};\n  align-items: ${v.align};\n  gap: ${v.gap}px;\n  flex-wrap: ${v.wrap?'wrap':'nowrap'};\n}`;saveDeveloperTools();};for(const [key,options] of [['direction',['row','column','row-reverse','column-reverse']],['justify',['flex-start','center','flex-end','space-between','space-around','space-evenly']],['align',['flex-start','center','flex-end','stretch']]])devField(controls,key,'select',v[key],x=>{v[key]=x;update();},options);devField(controls,'gap','range',v.gap,x=>{v.gap=x;update();});devField(controls,'wrap','checkbox',v.wrap,x=>{v.wrap=x;update();});layout.append(controls,preview);body.append(layout);update();}
function renderPaintTool(body){const v=developerState().paint,layout=E('div','developer-layout'),controls=E('section','dashboard-panel'),preview=E('section','dashboard-panel'),stage=E('div','paint-preview',dc().preview);stage.id='paint-preview';preview.append(stage);const code=developerCode(preview);const update=()=>{const background=`linear-gradient(${v.angle}deg, ${v.color1}, ${v.color2})`,shadow=`0 ${v.offset}px ${v.blur}px rgb(0 0 0 / 25%)`;stage.style.background=background;stage.style.boxShadow=shadow;stage.style.borderRadius=v.radius+'px';code.value=`.card {\n  background: ${background};\n  box-shadow: ${shadow};\n  border-radius: ${v.radius}px;\n}`;saveDeveloperTools();};for(const key of ['color1','color2','angle','blur','offset','radius'])devField(controls,key,key.startsWith('color')?'color':'range',v[key],x=>{v[key]=x;update();});layout.append(controls,preview);body.append(layout);update();}
const devEscape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function formToolHTML(v){return `<form>\n  <label for="field">${devEscape(v.label)}</label>\n  <input id="field" name="field" type="${v.type}"${v.required?' required':''}>\n  <button type="submit">${devEscape(v.submit)}</button>\n</form>`;}
function developerFrame(){const frame=E('iframe','tool-preview');frame.title=dc().preview;frame.setAttribute('sandbox','');return frame;}
function renderFormTool(body){const v=developerState().form,layout=E('div','developer-layout'),controls=E('section','dashboard-panel'),preview=E('section','dashboard-panel'),frame=developerFrame();preview.append(frame);const code=developerCode(preview);const update=()=>{code.value=formToolHTML(v);frame.srcdoc=safeToolDocument({html:code.value,css:'body{font:16px system-ui;padding:20px;color:#202a35}form{display:grid;gap:16px}input,button{font:inherit;padding:12px}',js:''});saveDeveloperTools();};for(const key of ['label','submit']){const input=devField(controls,key,'text',v[key],x=>{v[key]=x;update();});input.maxLength=120;}devField(controls,'type','select',v.type,x=>{v.type=x;update();},['text','email','password','number','url','date']);devField(controls,'required','checkbox',v.required,x=>{v.required=x;update();});layout.append(controls,preview);body.append(layout);update();}
function inspectMarkup(html){const doc=new DOMParser().parseFromString(html,'text/html'),issues=[],lang=document.documentElement.lang;const say=(uk,en)=>lang==='uk'?uk:en;const ids=new Set();for(const el of doc.querySelectorAll('[id]')){if(!el.id||ids.has(el.id))issues.push(say('Порожній або повторений ID: ','Empty or duplicate ID: ')+el.id);ids.add(el.id);}for(const img of doc.querySelectorAll('img:not([alt])'))issues.push(say('Зображення без alt: ','Image without alt: ')+(img.getAttribute('src')||'img'));for(const input of doc.querySelectorAll('input:not([type=hidden]),textarea,select')){const name=input.getAttribute('aria-label')?.trim()||[...(input.labels||[])].some(l=>l.textContent.trim())||input.getAttribute('aria-labelledby')?.split(/\s+/).some(id=>doc.getElementById(id)?.textContent.trim());if(!name&&!['submit','button','reset'].includes(input.type))issues.push(say('Поле без підпису: ','Unlabelled field: ')+(input.id||input.tagName.toLowerCase()));}for(const button of doc.querySelectorAll('button')){if(!button.textContent.trim()&&!button.getAttribute('aria-label')?.trim())issues.push(say('Кнопка без доступної назви.','Button without an accessible name.'));if(button.closest('form')&&!button.hasAttribute('type'))issues.push(say('Уточни type кнопки у формі: submit або button.','Specify a form button type: submit or button.'));}for(const label of doc.querySelectorAll('label[for]'))if(!doc.getElementById(label.htmlFor))issues.push(say('label посилається на відсутній ID: ','label refers to a missing ID: ')+label.htmlFor);if(doc.querySelectorAll('h1').length>1)issues.push(say('Кілька h1: перевір структуру заголовків.','Multiple h1 headings: review the heading structure.'));return issues;}
function renderMarkupTool(body){body.append(E('p','panel-note',dc().basic));const input=E('textarea','tool-code-editor');input.id='markup-code';input.maxLength=50000;input.spellcheck=false;input.setAttribute('aria-label',dc().html);input.value=developerState().html;const output=E('ul','developer-checks');output.id='markup-results';output.setAttribute('role','status');const frame=developerFrame();const run=()=>{output.replaceChildren();const issues=inspectMarkup(input.value);if(!issues.length)output.append(E('li','',dc().none));else for(const issue of issues)output.append(E('li','',issue));frame.srcdoc=safeToolDocument({html:input.value,css:'body{font:16px system-ui;padding:16px}img{max-width:100%}',js:''});};input.addEventListener('input',()=>{developerState().html=input.value;saveDeveloperTools();output.replaceChildren();});body.append(input,button(dc().check,run,'primary-button'),output,frame);}
let developerRun=0;
function renderDeveloperPractice(body){const state=developerState(),select=E('select'),label=E('label','form-field',dc().practice);select.id='developer-exercise';selectOptions(select,[['free',dc().free],...developerExercises.map(x=>[x.id,x.title[document.documentElement.lang]])],state.exercise);label.append(select);select.addEventListener('change',()=>{developerRun++;state.exercise=select.value;saveDeveloperTools();renderTools();});body.append(label);const exercise=developerExercises.find(x=>x.id===state.exercise);body.append(E('p','',exercise?.task[document.documentElement.lang]||dc().sandbox));const input=E('textarea','tool-code-editor');input.id='developer-js';input.maxLength=50000;input.spellcheck=false;input.setAttribute('aria-label',dc().draft);input.value=state.drafts[state.exercise]??exercise?.starter??'console.log("Hello, Kachan!");';input.addEventListener('input',()=>{developerRun++;state.drafts[state.exercise]=input.value;saveDeveloperTools();output.textContent=dc().empty;});const actions=E('div','editor-actions'),output=E('pre','tool-output');output.id='developer-results';output.setAttribute('role','status');output.textContent=dc().empty;
 let practiceBusy=false;const setPracticeBusy=value=>{practiceBusy=value;output.setAttribute('aria-busy',String(value));for(const control of actions.querySelectorAll('[data-practice-run]'))control.disabled=value;};
 const execute=async(check)=>{if(practiceBusy)return;setPracticeBusy(true);const generation=++developerRun;try{const source=input.value;state.drafts[state.exercise]=source;saveDeveloperTools();output.textContent=document.documentElement.lang==='uk'?'Виконую код…':'Running code…';const compiled=await compilePractice(source);if(generation!==developerRun||!output.isConnected)return;if(compiled.error){output.textContent=compiled.error;return;}const checks=exercise?.checks.map(([expression,title])=>({kind:'js',expression,label:developerCheckLabels[title]||bi(title,title)}))||[];const result=await runAcademyPractice({id:'developer-'+state.exercise,kind:'js',checks},{html:'',css:'',js:compiled.code},check);if(generation!==developerRun||!output.isConnected)return;output.textContent=[...(result.output||[]),...(result.error?[result.error]:[]),...(result.results||[]).map(r=>(r.passed?'✓ '+dc().pass:'✕ '+dc().fail)+' · '+r.label)].join('\n')|| (document.documentElement.lang==='uk'?'Виконано без повідомлень.':'Completed without output.');}catch(error){if(generation===developerRun&&output.isConnected)output.textContent=document.documentElement.lang==='uk'?'Не вдалося виконати код. Спробуй ще раз.':'Could not run the code. Try again.';}finally{setPracticeBusy(false);}};actions.append(button(dc().run,()=>execute(false),'primary-button'));if(exercise)actions.append(button(dc().check,()=>execute(true)));for(const control of actions.children)control.dataset.practiceRun='true';actions.append(button(dc().starter,()=>{if(!confirm(dc().reset))return;developerRun++;delete state.drafts[state.exercise];saveDeveloperTools();renderTools();}),button(dc().copy,()=>copyToolText(input.value)));body.append(input,actions,E('p','panel-note',dc().saved),E('h2','',dc().console),output);if(exercise){for(const [key,value] of [['hint',exercise.hint[document.documentElement.lang]],['solution',exercise.solution]]){const fold=E('details','cheat-entry');fold.append(E('summary','',dc()[key]),E(key==='solution'?'pre':'p',key==='solution'?'tool-output':'',value));body.append(fold);}}body.append(E('p','panel-note',dc().sandbox));}
const toolsBeforeDeveloper=renderTools;renderTools=function(){toolsBeforeDeveloper();const body=toolsView.querySelector('.tool-body');if(toolCatalogOpen){for(const card of toolsView.querySelectorAll('.tool-catalog-card')){const id=toolTabs.find(([,key])=>card.textContent.includes(t()[key]))?.[0];if(['flex','paint','form','markup','js-practice'].includes(id))card.querySelector('.tool-card-mark').textContent=id==='js-practice'?'JS':id==='flex'?'↔':id==='paint'?'◩':'</>';}}else if(['flex','paint','form','markup','js-practice'].includes(selectedTool)){body.replaceChildren();({flex:renderFlexTool,paint:renderPaintTool,form:renderFormTool,markup:renderMarkupTool,'js-practice':renderDeveloperPractice})[selectedTool](body);}scheduleSectionNavigation();};
window.addEventListener('hashchange',()=>developerRun++);window.addEventListener('languagechange',()=>{developerRun++;renderTools();});renderTools();
