Object.assign(translations.uk,{menuVisibility:'Розділи в меню',menuVisibilityHint:'Залиш потрібні розділи. Приховані можна відкрити через пошук або повернути тут.',restoreMenu:'Показати всі розділи',projectTaskNew:'Нова задача проєкту',clearSectionFilters:'Скинути фільтри'});Object.assign(translations.en,{menuVisibility:'Menu sections',menuVisibilityHint:'Keep the sections you use. Hidden sections remain available through search and can be restored here.',restoreMenu:'Show all sections',projectTaskNew:'New project task',clearSectionFilters:'Reset filters'});
const optionalMenuRoutes=['projects','tasks','learning','snippets','notes','resources'];
function hiddenMenuRoutes(){const value=uiPrefs().hiddenMenu;return Array.isArray(value)?value.filter(k=>optionalMenuRoutes.includes(k)):[];}
function applyMenuVisibility(){const hidden=hiddenMenuRoutes();for(const link of document.querySelectorAll('[data-view-link]'))link.hidden=hidden.includes(link.dataset.viewLink);for(const a of homeSurface.querySelectorAll('.home-launcher'))a.hidden=hidden.includes(a.hash.slice(1));}
function renderMenuPreferences(){Q('menu-preferences')?.remove();const panel=E('section','menu-preferences');panel.id='menu-preferences';panel.append(E('h3','',t().menuVisibility),E('p','panel-note',t().menuVisibilityHint));const list=E('div','menu-choice-list');for(const route of optionalMenuRoutes){const label=E('label','menu-choice'),check=E('input');check.type='checkbox';check.dataset.menuRoute=route;check.checked=!hiddenMenuRoutes().includes(route);check.addEventListener('change',()=>{const hidden=hiddenMenuRoutes();uiPrefs().hiddenMenu=check.checked?hidden.filter(k=>k!==route):[...hidden,route];persistExtras();applyMenuVisibility();});label.append(check,E('span','',t()[route]));list.append(label);}panel.append(list,button('restoreMenu',()=>{uiPrefs().hiddenMenu=[];persistExtras();applyMenuVisibility();renderMenuPreferences();}));comfortPanel.append(panel);}
const comfortBeforeMenu=renderComfort;renderComfort=function(){comfortBeforeMenu();renderMenuPreferences();};const homeBeforeMenu=renderHome;renderHome=function(){homeBeforeMenu();applyMenuVisibility();};window.addEventListener('languagechange',()=>{applyMenuVisibility();renderMenuPreferences();});renderMenuPreferences();applyMenuVisibility();
if(!uiPrefs().views?.projects){(uiPrefs().views||={}).projects='list';persistExtras();}
function compactProjectRows(){for(const card of Q('all-projects').querySelectorAll('.project-card')){const actions=card.querySelector(':scope > .editor-actions');if(actions&&!actions.querySelector('.project-row-more')){const more=E('details','project-row-more'),summary=E('summary','',t().minimalMore),body=E('div','project-row-actions');more.append(summary,body);for(const child of [...actions.children].slice(1))body.append(child);const pin=card.querySelector('.pin-control');if(pin)body.append(pin);actions.append(more);}const heading=card.querySelector('.project-info h2');if(heading&&!heading.querySelector('a')){const target=actions?.querySelector('a[href*="project="]');if(target){const a=E('a','project-name-link',heading.textContent);a.href=target.href;heading.replaceChildren(a);}}}}
const projectsBeforeRows=renderProjects;renderProjects=function(){projectsBeforeRows();compactProjectRows();};
const tasksBeforeRows=renderTasks;renderTasks=function(){tasksBeforeRows();for(const row of Q('all-tasks').children){const id=row.dataset.taskId,title=row.querySelector('.task-row>span');if(!id||!title)continue;const open=E('button','task-name-open',title.textContent);open.type='button';open.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openTaskDetails(id);});title.replaceWith(open);row.querySelector('.task-detail-open')?.remove();}}
const projectBeforeQuickTask=renderProjectDetail;renderProjectDetail=function(){projectBeforeQuickTask();const id=new URLSearchParams(location.hash.split('?')[1]||'').get('project');if(!projects.some(x=>x.id===id))return;Q('project-detail').querySelector('.project-hub-actions')?.prepend(button('projectTaskNew',()=>{projectDetailsWindow.shut();launchCreate('tasks');Q('task-project').value=id;}));};
// A recovery action helps when filters hide all records.
function filteredEmptyActions(){for(const kind of ['projects','tasks','snippets']){const list=Q({projects:'all-projects',tasks:'all-tasks',snippets:'snippet-list'}[kind]);const count=list.querySelectorAll(kind==='tasks'?'li':'article').length,query=Q(kind+'-search').value;let reset=Q(kind+'-reset-filters');const filtered=!!query||(kind==='tasks'&&(taskFilter!=='all'||Q('filter-project').value!=='all'||Q('filter-priority').value!=='all'))||(kind==='snippets'&&(snippetFilter!=='all'||snippetOnlyFavorites))||(kind==='projects'&&Q('project-archive-toggle').classList.contains('active'));if(count||!filtered){reset?.remove();continue;}if(reset)reset.textContent=t().clearSectionFilters;if(!reset){reset=button('clearSectionFilters',()=>{Q(kind+'-search').value='';if(kind==='tasks'){taskFilter='all';Q('filter-project').value='all';Q('filter-priority').value='all';renderTasks();}else if(kind==='snippets'){snippetFilter='all';snippetOnlyFavorites=false;favoriteToggle.setAttribute('aria-pressed','false');renderSnippets();}else{Q('project-archive-toggle').classList.remove('active');renderProjects();}});reset.id=kind+'-reset-filters';list.after(reset);}}}
for(const [kind,input] of [['projects','projects-search'],['tasks','tasks-search'],['snippets','snippets-search']])Q(input).addEventListener('input',filteredEmptyActions);window.addEventListener('languagechange',filteredEmptyActions);renderProjects();renderTasks();renderHome();setupCollectionViews();
// Linking a code snippet to a project should also make it visible in that project.
const metaBeforeProjectLinks=saveMeta;saveMeta=function(id,value){const oldProject=meta(id).project;metaBeforeProjectLinks(id,value);if(!snippets.some(s=>s.id===id))return;let changed=false;for(const p of projects){if(p.id===oldProject&&p.id!==value.project&&(p.snippets||[]).includes(id)){p.snippets=p.snippets.filter(x=>x!==id);changed=true;}if(p.id===value.project&&!(p.snippets||[]).includes(id)){(p.snippets||=[]).push(id);changed=true;}}if(changed)saveProjects();};
// Bring existing snippet links into the project hub as well.
let existingCodeLinksChanged=false;for(const s of snippets){const project=projects.find(p=>p.id===meta(s.id).project);if(project&&!(project.snippets||[]).includes(s.id)){(project.snippets||=[]).push(s.id);existingCodeLinksChanged=true;}}if(existingCodeLinksChanged){saveProjects();renderProjects();}

const tasksBeforeEmptyRecovery=renderTasks;renderTasks=function(){tasksBeforeEmptyRecovery();filteredEmptyActions();};const projectsBeforeEmptyRecovery=renderProjects;renderProjects=function(){projectsBeforeEmptyRecovery();filteredEmptyActions();};const snippetsBeforeEmptyRecovery=renderSnippets;renderSnippets=function(){snippetsBeforeEmptyRecovery();filteredEmptyActions();};
