// Additional sections share the existing translations and browser storage.
Object.assign(translations.uk, {openLearning:'Відкрити навчання ↗',newSnippet:'Новий фрагмент коду',category:'Категорія',code:'Код',save:'Зберегти',copy:'Копіювати',copied:'Код скопійовано',copyError:'Копіювання недоступне. Виділи код і скопіюй вручну.',edit:'Редагувати',remove:'Видалити',emptySnippets:'Тут поки немає фрагментів.',favorites:'Обране',favorite:'Додати в обране',unfavorite:'Прибрати з обраного',openResource:'Відкрити ресурс ↗',emptyFavorites:'Обраних ресурсів поки немає.',userName:'Ім’я користувача',accentColor:'Акцентний колір',red:'Червоний',violet:'Фіолетовий',blue:'Синій',green:'Зелений',theme:'Тема',dark:'Темна',light:'Світла',resetTitle:'Скидання даних',resetDescription:'Видалить задачі, проєкти, фрагменти, прогрес та налаштування тільки цього сайту в цьому браузері.',reset:'Скинути дані',resetConfirm:'Скинути всі дані Kachan? Цю дію неможливо скасувати.',saved:'Збережено',next:'Усі основні розділи готові. Створюй свої проєкти та розвивай навички.',foundation:'Твій простір готовий',step:'KEEP BUILDING'});
Object.assign(translations.en, {openLearning:'Open learning ↗',newSnippet:'New code snippet',category:'Category',code:'Code',save:'Save',copy:'Copy',copied:'Code copied',copyError:'Copy unavailable. Select the code and copy manually.',edit:'Edit',remove:'Delete',emptySnippets:'No snippets in this category yet.',favorites:'Favorites',favorite:'Add to favorites',unfavorite:'Remove from favorites',openResource:'Open resource ↗',emptyFavorites:'No favorite resources yet.',userName:'User name',accentColor:'Accent color',red:'Red',violet:'Violet',blue:'Blue',green:'Green',theme:'Theme',dark:'Dark',light:'Light',resetTitle:'Reset data',resetDescription:'Removes tasks, projects, snippets, progress, and settings for this site in this browser only.',reset:'Reset data',resetConfirm:'Reset all Kachan data? This cannot be undone.',saved:'Saved',next:'All core sections are ready. Build your projects and grow your skills.',foundation:'Your workspace is ready',step:'KEEP BUILDING'});
const categories=['HTML','CSS','JavaScript','TypeScript','Git'];
function readData(key,fallback,validate){try{const value=JSON.parse(kachanStorage.getItem(key));return validate(value)?value:fallback;}catch{return fallback;}}
function writeData(key,value){try{kachanStorage.setItem(key,JSON.stringify(value));return true;}catch{notice(t().storageFailed);return false;}}
function t(){return translations[document.documentElement.lang];}
let noticeTimer;
function notice(message){clearTimeout(noticeTimer);document.querySelector('#app-notice').textContent=message;noticeTimer=setTimeout(()=>{document.querySelector('#app-notice').textContent='';},5000);}
let snippets=readData('devspace-snippets',[
{id:'css-center',name:'Flexbox center',category:'CSS',description:'',code:'.container {\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}'},
{id:'js-array',name:'Array filter',category:'JavaScript',description:'',code:'const activeTasks = tasks.filter(task => !task.completed);'}
],v=>Array.isArray(v)&&v.every(s=>s&&typeof s.id==='string'&&typeof s.name==='string'&&typeof s.description==='string'&&typeof s.code==='string'&&categories.includes(s.category))&&new Set(v.map(s=>s.id)).size===v.length);
let snippetFilter='all',editingSnippet=null;
function filterButtons(container,values,current,change){container.replaceChildren();for(const value of values){const b=projectElement('button','',value==='all'?t().filterAll:value==='favorites'?t().favorites:value);b.type='button';b.setAttribute('aria-pressed',String(value===current));b.addEventListener('click',()=>change(value));container.append(b);}}
function renderSnippets(){
filterButtons(document.querySelector('#snippet-filters'),['all',...categories],snippetFilter,v=>{snippetFilter=v;renderSnippets();});
const list=document.querySelector('#snippet-list');list.replaceChildren();
const items=snippets.filter(s=>(snippetFilter==='all'||s.category===snippetFilter)&&matchesSearch('snippets',[s.name,s.description,s.category,s.code]));
searchStatus('snippets',items.length,t());
if(!items.length)list.append(projectElement('p','empty-state',document.querySelector('#snippets-search').value.trim()?t().noSearchResults:t().emptySnippets));
for(const snippet of items){const card=projectElement('article','dashboard-panel');card.append(projectElement('span','badge',snippet.category),projectElement('h2','',snippet.name),projectElement('p','panel-note',snippet.description));const pre=projectElement('pre','snippet-code');const code=projectElement('code','',snippet.code);pre.append(code);card.append(pre);const actions=projectElement('div','editor-actions');
const copy=projectElement('button','secondary-button',t().copy);copy.type='button';copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(snippet.code);notice(t().copied);}catch{const range=document.createRange();range.selectNodeContents(code);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);notice(t().copyError);}});
const edit=projectElement('button','secondary-button',t().edit);edit.type='button';edit.addEventListener('click',()=>{editingSnippet=snippet.id;const form=document.querySelector('#snippet-form');for(const key of ['name','category','description','code'])form.elements[key].value=snippet[key];document.querySelector('#snippet-editor').open=true;document.querySelector('#snippet-name').focus();});
const remove=projectElement('button','secondary-button danger-button',t().remove);remove.type='button';remove.addEventListener('click',()=>{snippets=snippets.filter(s=>s.id!==snippet.id);writeData('devspace-snippets',snippets);if(editingSnippet===snippet.id)resetSnippet();renderSnippets();});actions.append(copy,edit,remove);card.append(actions);list.append(card);}}
function resetSnippet(){editingSnippet=null;document.querySelector('#snippet-form').reset();document.querySelector('#snippet-editor').open=false;}
document.querySelector('#snippet-cancel').addEventListener('click',resetSnippet);
document.querySelector('#snippet-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const name=form.elements.name.value.trim(),code=form.elements.code.value;if(!name||!code.trim())return;const value={id:editingSnippet||crypto.randomUUID(),name,code,category:form.elements.category.value,description:form.elements.description.value.trim()};snippets=editingSnippet?snippets.map(s=>s.id===editingSnippet?value:s):[...snippets,value];snippetFilter='all';const saved=writeData('devspace-snippets',snippets);resetSnippet();renderSnippets();if(saved)notice(t().saved);});
const resources=[
['mdn','MDN','Docs','https://developer.mozilla.org/','Документація HTML, CSS і JavaScript.','HTML, CSS, and JavaScript documentation.'],
['github','GitHub','Tools','https://github.com/','Репозиторії, спільна робота та відкритий код.','Repositories, collaboration, and open source.'],
['caniuse','Can I Use','Tools','https://caniuse.com/','Підтримка вебможливостей у браузерах.','Browser compatibility for web features.'],
['fonts','Google Fonts','Design','https://fonts.google.com/','Шрифти для твоїх проєктів.','Fonts for your projects.'],
['figma','Figma','Design','https://www.figma.com/','Дизайн інтерфейсів і прототипи.','Interface design and prototypes.'],
['mentor','Frontend Mentor','Practice','https://www.frontendmentor.io/','Практика верстки на реальних макетах.','Frontend challenges with real designs.'],
['csstricks','CSS-Tricks','Docs','https://css-tricks.com/','Статті та приклади для веброзробки.','Articles and examples for web development.']
];
Object.assign(translations.uk,{Docs:'Документація',Tools:'Інструменти',Design:'Дизайн',Practice:'Практика'});Object.assign(translations.en,{Docs:'Docs',Tools:'Tools',Design:'Design',Practice:'Practice'});
let favorites=readData('devspace-favorites',[],v=>Array.isArray(v)&&v.every(id=>typeof id==='string'&&id.length<=100));let resourceFilter='all';
function renderResources(){const filters=document.querySelector('#resource-filters');filterButtons(filters,['all','favorites','Docs','Tools','Design','Practice'],resourceFilter,v=>{resourceFilter=v;renderResources();});for(const b of filters.children)if(t()[b.textContent])b.textContent=t()[b.textContent];const list=document.querySelector('#resource-list');list.replaceChildren();const items=resources.filter(r=>resourceFilter==='all'||(resourceFilter==='favorites'?favorites.includes(r[0]):r[2]===resourceFilter));if(!items.length)list.append(projectElement('p','empty-state',t().emptyFavorites));for(const [id,name,category,url,uk,en] of items){const card=projectElement('article','dashboard-panel');const favorite=projectElement('button','favorite-button',favorites.includes(id)?'★':'☆');favorite.type='button';favorite.setAttribute('aria-label',t()[favorites.includes(id)?'unfavorite':'favorite']+': '+name);favorite.setAttribute('aria-pressed',String(favorites.includes(id)));favorite.addEventListener('click',()=>{favorites=favorites.includes(id)?favorites.filter(f=>f!==id):[...favorites,id];writeData('devspace-favorites',favorites);renderResources();});card.append(favorite,projectElement('span','badge',t()[category]),projectElement('h2','',name),projectElement('p','panel-note',document.documentElement.lang==='uk'?uk:en));const link=projectElement('a','text-link',t().openResource);link.href=url;link.target='_blank';link.rel='noopener noreferrer';card.append(link);list.append(card);}}
const palette={red:'#ff3838',violet:'#a38bfa',blue:'#459bff',green:'#28bd80'};
let settings=readData('devspace-settings',{userName:'Rubin',accent:'blue',theme:'dark'},v=>v&&typeof v.userName==='string'&&v.userName.trim()&&Object.hasOwn(palette,v.accent)&&['dark','light'].includes(v.theme));
function applySettings(){document.documentElement.dataset.theme=settings.theme;document.documentElement.style.setProperty('--accent',palette[settings.accent]);document.querySelector('.profile strong').textContent=settings.userName;document.querySelector('.avatar').textContent=Array.from(settings.userName)[0].toUpperCase();const form=document.querySelector('#settings-form');for(const key of ['userName','accent','theme'])form.elements[key].value=settings[key];}
document.querySelector('#settings-form').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;const userName=form.elements.userName.value.trim();if(!userName)return;settings={userName,accent:form.elements.accent.value,theme:form.elements.theme.value};const saved=writeData('devspace-settings',settings);applySettings();if(saved)notice(t().saved);});
document.querySelector('#reset-data').addEventListener('click',async()=>{if(!window.confirm(t().resetConfirm))return;try{for(const key of ['devspace-settings','devspace-snippets','devspace-favorites','devspace-progress','devspace-tasks','devspace-projects','devspace-language','devspace-htmlCourse','devspace-notes','devspace-dashboard','devspace-workspace','devspace-extras','kachan-cloud-config','devspace-academy','devspace-personalization'])kachanStorage.removeItem(key);await kachanStorage.flush();await kachanStorage.resetLegacy();timer.end=null;sessionStorage.removeItem('kachan-cloud-session');sessionStorage.removeItem('kachan-cloud-state');location.reload();}catch{notice(t().storageFailed);}});
function renderLearningOverview(){const container=document.querySelector('#learning-overview');container.replaceChildren();document.querySelectorAll('[data-progress]').forEach(bar=>{const label=projectElement('div','progress-label');label.append(projectElement('span','',bar.dataset.progress),projectElement('span','',bar.textContent));const progress=projectElement('progress');progress.max=bar.max;progress.value=bar.value;progress.setAttribute('aria-label',bar.dataset.progress);container.append(label,progress);});}
function refreshFeatures(){renderSnippets();renderResources();renderLearningOverview();}
window.addEventListener('languagechange',refreshFeatures);
document.addEventListener('change',e=>{if(e.target.matches('[data-topic]'))renderLearningOverview();});
applySettings();setLanguage(document.documentElement.lang);
// Appearance changes apply immediately; the Save button remains for the user name.
for (const [selector, key] of [['#theme-select', 'theme'], ['#accent-color', 'accent']]) {
  document.querySelector(selector).addEventListener('change', event => {
    settings[key] = event.target.value;
    document.documentElement.dataset.theme = settings.theme;
    document.documentElement.style.setProperty('--accent', palette[settings.accent]);
    if (writeData('devspace-settings', settings)) notice(t().saved);
  });
}

document.querySelector('#snippets-search').addEventListener('input',renderSnippets);document.querySelector('[data-clear-search="snippets"]').addEventListener('click',()=>{const input=document.querySelector('#snippets-search');input.value='';renderSnippets();input.focus();});
