Object.assign(translations.uk,{whyBlock:'Навіщо це?',snippetPurpose:'Зберігай невеликі шматки коду, щоб повторно використовувати їх у своїх проєктах.',snippetHow:'Дай прикладу назву, поясни коли він потрібен і встав код. Потім знайди його та натисни «Копіювати».',trySnippet:'Спробувати приклад',snippetUse:'Коли використовувати',exampleCenter:'Центрування блока',exampleFilter:'Відбір елементів',exampleButton:'HTML-кнопка',exampleGit:'Перевірка змін Git',helpExample:'Приклад',snippetDescriptionPlaceholder:'Наприклад: центрує картку всередині контейнера.',snippetNamePlaceholder:'Наприклад: Центрування через Flexbox'});
Object.assign(translations.en,{whyBlock:'What is this for?',snippetPurpose:'Save small pieces of code to reuse in your projects.',snippetHow:'Name the example, explain when to use it and paste the code. Find it later and press Copy.',trySnippet:'Try an example',snippetUse:'When to use it',exampleCenter:'Center a block',exampleFilter:'Filter items',exampleButton:'HTML button',exampleGit:'Inspect Git changes',helpExample:'Example',snippetDescriptionPlaceholder:'For example: centers a card inside its container.',snippetNamePlaceholder:'For example: Centering with Flexbox'});
const purposeText={
dashboard:['Швидкий старт: переходи до своїх проєктів, навчання та записів. Детальна статистика доступна в огляді.','A quick start for your projects, learning and notes. Detailed statistics live in the overview.'],
projects:['Проєкт — це сайт або застосунок, над яким ти працюєш. Тут зібрані його прогрес, задачі, нотатки, код і посилання. Наприклад: портфоліо або інтернет-магазин.','A project is a website or app you are building. Keep its progress, tasks, notes, code and links together. For example: a portfolio or an online store.'],
tasks:['Задача — конкретний крок роботи. Наприклад: зробити мобільне меню. Відкрий «Деталі», щоб додати опис, підзадачі, дедлайн і нотатки; відміть виконане галочкою.','A task is one concrete step, such as building a mobile menu. Open Details for a description, subtasks, deadline and notes; check it off when done.'],
learning:['Уроки пояснюють тему, практика дозволяє спробувати код, а тест перевіряє розуміння. Наприклад: прочитай про Flexbox, виконай вправу й збережи конспект.','Lessons explain a topic, practice lets you try code, and tests check understanding. For example: learn Flexbox, complete an exercise and save study notes.'],
snippets:['Це твоя бібліотека готових шматків коду, а не цілих проєктів. Зберігай рішення, які хочеш використати знову: центрування CSS, обробку масиву JavaScript або команду Git. «Копіювати» переносить код у буфер обміну.','Your library of reusable code pieces rather than whole projects. Save solutions you want to use again: CSS centering, a JavaScript array operation or a Git command. Copy puts the code on your clipboard.'],
notes:['Блокнот для думок, конспектів і планів. Папки впорядковують записи, закріплення тримає важливе поруч, а прив’язки з’єднують запис із задачею або проєктом. Текст зберігається автоматично.','A notebook for ideas, study notes and plans. Folders organize records, pins keep important ones close, and links connect notes to tasks or projects. Text saves automatically.'],
resources:['Посилання на зовнішні сайти: документацію, інструменти й вправи. Відкрий тип і тему або скористайся пошуком. Обране зберігає потрібні посилання, коментар — твою підказку до ресурсу.','Links to external documentation, tools and exercises. Open a type and topic or use search. Favorites keep useful links handy; comments store your own reminders.'],
settings:['Налаштуй вигляд і розмір тексту, обери блоки огляду та керуй резервними копіями. Дані зараз зберігаються в цьому браузері — копія допоможе перенести їх або відновити.','Adjust appearance and text size, choose overview blocks and manage backups. Data currently lives in this browser; backups help transfer or restore it.'],
stats:['Короткі числа з твоїх записів: проєкти, активні й завершені задачі та прогрес навчання. Вони оновлюються після твоїх дій.','A summary of your records: projects, active and completed tasks, and learning progress. Counts update as you work.'],
today:['Додатковий список задач із дедлайном сьогодні або раніше. Ним можна користуватись за потреби; він не визначає весь твій робочий процес.','An optional list of tasks due today or overdue. Use it when useful; it does not dictate your workflow.'],
goals:['Необов’язкові орієнтири на день і тиждень. Наприклад: завершити меню. Це короткі текстові плани, а не окремі задачі.','Optional goals for the day and week, such as finishing the menu. These are short written intentions rather than separate tasks.'],
continue:['Повертає до останнього навчального матеріалу, щоб не шукати його знову.','Return to your current learning material without finding it again.'],
activity:['Історія змін: що ти створив, змінив або завершив. Допомагає згадати останню роботу.','A history of what you created, changed or completed. Helps you recall recent work.'],
chart:['Показує кількість записаних дій за останні дні. Це огляд активності, а не оцінка якості твоєї роботи.','Shows recorded actions over recent days. It summarizes activity rather than judging your work.'],
focus:['Необов’язковий таймер для роботи й перерв та картки повторення. Запиши запитання й відповідь, щоб повернутися до теми пізніше.','An optional work/break timer and review cards. Save a question and answer to revisit a topic later.'],
calendar:['Показує, коли заплановане повторення навчальних карток. Обери день, щоб побачити відповідні запитання.','Shows when learning cards are due for review. Select a day to see its questions.'],
pinned:['Закріплені проєкти й нотатки завжди під рукою. Закріпи проєкт у списку або нотатку в її параметрах.','Pinned projects and notes stay within reach. Pin a project in its list or a note in its options.'],
folders:['Власні папки групують нотатки за твоїми темами. Наприклад: «Ідеї» або «Портфоліо». Видалення папки залишає її нотатки.','Custom folders group notes by your topics, such as Ideas or Portfolio. Removing a folder keeps its notes.'],
backup:['JSON-копія містить твої записи й налаштування. Завантаж її для резерву або перенесення в інший браузер; імпорт відновлює чи об’єднує дані.','A JSON backup contains your records and settings. Download one for safekeeping or another browser; import restores or merges data.']};
const helpContent=E('div','utility-content help-copy'),helpWindow=utilityWindow('purpose-window','whyBlock',helpContent);
function showPurpose(key,title){helpContent.replaceChildren(E('h3','',title),E('p','',purposeText[key]?.[document.documentElement.lang==='uk'?0:1]||purposeText.dashboard[document.documentElement.lang==='uk'?0:1]));helpWindow.open();}
function addPurpose(host,key,title){if(!host||host._purposeButton&&host.contains(host._purposeButton))return;const b=E('button','purpose-button','?');host._purposeButton=b;b._helpHost=host;b.type='button';b.dataset.purposeKey=key;b.title=t().whyBlock;b.setAttribute('aria-label',t().whyBlock+' · '+title);b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();showPurpose(key,host.querySelector('h1,h2,h3,h4')?.textContent||title);});host.append(b);}
function annotateBlocks(){for(const key of ['dashboard','projects','tasks','learning','snippets','notes','resources','settings']){const view=Q(key+'-view');addPurpose(view.querySelector('.page-heading'),key,t()[key]);}addPurpose(homeSurface.querySelector('.home-hero-copy'),'dashboard',t().homeTab);for(const [id,block] of dashboardBlocks)addPurpose(block,id==='learning'?'learning':id==='notes'?'notes':id,block.querySelector('h2,h3')?.textContent||t()[id]||id);const targets=[['.home-resume','continue'],['.focus-card','today'],['.personal-grid>.dashboard-panel','pinned'],['.notes-browser','folders'],['.note-editor','notes'],['#resource-list .resource-type-group','resources'],['#snippet-list article','snippets'],['#learning-progress-window .dashboard-panel','learning'],['#settings-form','settings'],['#dashboard-settings','dashboard'],['#notification-settings','settings'],['#task-detail-window .utility-content','tasks'],['#folders-window .utility-content','folders']];for(const [selector,key] of targets)for(const block of document.querySelectorAll(selector))addPurpose(block,key,block.querySelector('h1,h2,h3,h4')?.textContent||t()[key]||key);for(const block of Q('settings-view').querySelectorAll('.dashboard-panel'))addPurpose(block,block.textContent.includes(t().backupTitle)?'backup':'settings',block.querySelector('h2,h3')?.textContent||t().settings);}
const snippetIntro=E('section','snippet-introduction');snippetIntro.id='snippet-introduction';Q('snippets-view').querySelector('.page-heading').after(snippetIntro);
const snippetExamples=[['exampleCenter','CSS','.container {\n  display: flex;\n  align-items: center;\n  justify-content: center;\n}', ['Центрує вміст контейнера по горизонталі й вертикалі.','Centers container content horizontally and vertically.']],['exampleFilter','JavaScript','const activeTasks = tasks.filter(task => !task.completed);',['Залишає в масиві лише невиконані задачі.','Keeps only incomplete tasks in the array.']],['exampleButton','HTML','<button type="button">Click me</button>',['Кнопка для дії на сторінці без надсилання форми.','A button for a page action without submitting a form.']],['exampleGit','Git','git status\ngit diff',['Показує змінені файли та зміни перед комітом.','Shows modified files and changes before committing.']]];
function renderSnippetIntro(){snippetIntro.replaceChildren(E('strong','',t().snippetPurpose),E('p','panel-note',t().snippetHow));const examples=E('details','snippet-starters');examples.append(E('summary','',t().trySnippet));const actions=E('div','starter-actions');for(const [key,category,code,description] of snippetExamples)actions.append(button(key,()=>{resetSnippet();const form=Q('snippet-form');form.elements.name.value=t()[key];form.elements.category.value=category;form.elements.description.value=description[document.documentElement.lang==='uk'?0:1];form.elements.code.value=code;Q('snippet-editor').open=true;snippetWindow.open();Q('snippet-name').focus();}));examples.append(actions);snippetIntro.append(examples);Q('snippet-name').placeholder=t().snippetNamePlaceholder;Q('snippet-description').placeholder=t().snippetDescriptionPlaceholder;const descriptionLabel=document.querySelector('label[for="snippet-description"]');if(descriptionLabel){descriptionLabel.dataset.i18n='snippetUse';descriptionLabel.textContent=t().snippetUse;}}
const snippetsBeforeGuide=renderSnippets;renderSnippets=function(){snippetsBeforeGuide();const list=Q('snippet-list'),cards=[...list.querySelectorAll('article')],groups=new Map();for(const card of cards){const category=card.querySelector('.badge')?.textContent;if(!category)continue;if(!groups.has(category)){const section=E('section','snippet-language-group'),body=E('div','snippet-language-grid');section.append(E('h2','',category),body);list.append(section);groups.set(category,body);}const title=card.querySelector('h2');if(title)title.replaceWith(E('h3','',title.textContent));const description=card.querySelector('.panel-note');if(description&&!description.textContent.trim()){const example=snippetExamples.find(([,cat,code])=>cat===category&&code===card.querySelector('code')?.textContent);if(example)description.textContent=example[3][document.documentElement.lang==='uk'?0:1];}const actionRows=[...card.querySelectorAll(':scope > .editor-actions')];if(actionRows.length>1){actionRows[0].append(...actionRows[1].children);actionRows[1].remove();}const copy=actionRows[0]?.querySelector('button');if(copy){copy.classList.remove('secondary-button');copy.classList.add('primary-button');}groups.get(category).append(card);}for(const category of categories)if(groups.has(category))list.append(groups.get(category).parentElement);annotateBlocks();};
let helpScheduled=false;const helpObserver=new MutationObserver(()=>{if(helpScheduled)return;helpScheduled=true;requestAnimationFrame(()=>{helpScheduled=false;annotateBlocks();});});helpObserver.observe(document.querySelector('.content'),{childList:true,subtree:true});for(const d of document.querySelectorAll('dialog'))if(d!==helpWindow.dialog)helpObserver.observe(d,{childList:true,subtree:true});window.addEventListener('languagechange',()=>{renderSnippetIntro();renderSnippets();for(const b of document.querySelectorAll('.purpose-button')){b.title=t().whyBlock;b.setAttribute('aria-label',t().whyBlock+' · '+(b.parentElement.querySelector('h1,h2,h3,h4')?.textContent||t()[b.dataset.purposeKey]||t().homeTab));}helpWindow.shut();annotateBlocks();});renderSnippetIntro();renderSnippets();annotateBlocks();
// Cover individual summary cards and smaller functional panels as they appear.
const annotateBeforePanels=annotateBlocks;annotateBlocks=function(){annotateBeforePanels();for(const card of document.querySelectorAll('.stat-card'))addPurpose(card,'stats',card.textContent.trim().slice(0,80));for(const view of document.querySelectorAll('.content>section[id$="-view"]')){const key=view.id.replace('-view','');for(const panel of view.querySelectorAll('.dashboard-panel')){if(panel.closest('[data-dashboard-block]'))continue;addPurpose(panel,key,panel.querySelector('h2,h3,h4')?.textContent||t()[key]);}}for(const link of homeSurface.querySelectorAll('.home-launcher')){const key=link.hash.slice(1);link.title=purposeText[key]?.[document.documentElement.lang==='uk'?0:1]||'';}};window.addEventListener('hashchange',()=>helpWindow.shut());annotateBlocks();
