// Original HTML curriculum. Each exercise checks observable document structure.
const htmlLessons = [];
function addHtmlLesson(id, titleUk, titleEn, theoryUk, theoryEn, taskUk, taskEn, hintsUk, hintsEn, solution, checks, starter='<!doctype html>\n<html lang="uk">\n<head>\n  <meta charset="UTF-8">\n  <title>My page</title>\n</head>\n<body>\n\n</body>\n</html>') {
 htmlLessons.push({id,title:{uk:titleUk,en:titleEn},theory:{uk:theoryUk,en:theoryEn},task:{uk:taskUk,en:taskEn},hints:{uk:hintsUk,en:hintsEn},solution,checks,starter});
}
const rule=(uk,en,test)=>({uk,en,test});
const hasText=(doc,selector)=>[...doc.querySelectorAll(selector)].some(el=>el.textContent.trim());
addHtmlLesson('document','Структура документа','Document structure',
['HTML описує зміст і структуру сторінки. Тег відкриває елемент, а закривальний тег завершує його: <h1>Привіт</h1>. Елементи вкладені один в одного, тому закривай їх у зворотному порядку.', '<!doctype html> вмикає стандартний режим браузера. <html lang="uk"> задає мову. <head> містить метадані, а <body> — видимий вміст. UTF-8 потрібен для коректного відображення українських літер. <title> задає назву вкладки, а не заголовок сторінки.'],
['HTML describes content and document structure. An opening tag starts an element and a closing tag ends it: <h1>Hello</h1>. Close nested elements in reverse order.', '<!doctype html> enables standards mode. <html lang="en"> declares the language. <head> holds metadata; <body> holds visible content. UTF-8 supports international text. <title> names the browser tab, not the visible heading.'],
'Створи документ із doctype, мовою uk або en, UTF-8, непорожнім title і заголовком h1 у body.','Create a document with a doctype, uk or en language, UTF-8, a nonempty title, and an h1 in the body.',
['Почни з <!doctype html> і елемента html.','У head додай meta charset="UTF-8" та title.','Додай <h1>Мій перший сайт</h1> у body.'],['Start with <!doctype html> and html.','Add meta charset="UTF-8" and title inside head.','Place <h1>My first site</h1> in body.'],
'<!doctype html>\n<html lang="uk">\n<head>\n  <meta charset="UTF-8">\n  <title>Мій перший сайт</title>\n</head>\n<body>\n  <h1>Привіт, HTML!</h1>\n</body>\n</html>',
[rule('Є HTML doctype','HTML doctype exists',(d,s)=>/^\s*<!doctype\s+html\s*>/i.test(s)),rule('Мова uk або en','Language is uk or en',d=>['uk','en'].includes(d.documentElement.lang)),rule('Кодування UTF-8','UTF-8 charset',d=>d.querySelector('meta[charset]')?.getAttribute('charset').toLowerCase()==='utf-8'),rule('Назва вкладки й h1 заповнені','Tab title and h1 have content',d=>hasText(d,'head title')&&hasText(d,'body h1'))], '<!-- Напиши повний документ / Write the complete document -->');
addHtmlLesson('text','Заголовки та текст','Headings and text',
['Заголовки h1–h6 позначають рівні структури, а не просто розмір шрифту. Для цієї сторінки використай один головний h1 і h2 для підрозділу. Абзаци оформлюй через p; br — лише для потрібного переносу рядка, не для відступів.', 'strong позначає важливість, em — смисловий наголос. Для символів, що мають значення в HTML, використовуй сутності: &lt; для <, &gt; для > та &amp; для &. Візуальне оформлення краще задавати CSS.'],
['Headings h1–h6 express hierarchy, not just font size. Use one main h1 and an h2 for a subsection in this exercise. Paragraphs use p; br is for meaningful line breaks, not spacing.', 'strong indicates importance; em indicates emphasis. Escape HTML-sensitive characters with &lt;, &gt;, and &amp;. Use CSS for visual styling.'],
'Напиши h1, h2 та два абзаци. В одному абзаці використай strong, в іншому em.','Write an h1, an h2, and two paragraphs. Use strong in one paragraph and em in another.',
['Абзац: <p>Текст</p>.','Важливість: <strong>важливо</strong>.','Наголос: <em>щодня</em>.'],['Paragraph: <p>Text</p>.','Importance: <strong>important</strong>.','Emphasis: <em>daily</em>.'],
'<h1>Мій шлях у frontend</h1>\n<h2>Перші кроки</h2>\n<p>Вивчати основи <strong>важливо</strong>.</p>\n<p>Я практикуюся <em>щодня</em>.</p>',
[rule('Один непорожній h1','One nonempty h1',d=>d.querySelectorAll('h1').length===1&&hasText(d,'h1')),rule('Є h2 і два абзаци','An h2 and two paragraphs',d=>hasText(d,'h2')&&d.querySelectorAll('p').length>=2),rule('strong і em усередині абзаців','strong and em inside paragraphs',d=>hasText(d,'p strong')&&hasText(d,'p em'))]);
addHtmlLesson('links','Посилання та навігація','Links and navigation',
['Елемент a з href створює посилання. Абсолютна адреса веде на інший сайт, відносна — на файл твого сайту, а #about — на елемент із id="about". Текст посилання має пояснювати, куди воно веде.', 'nav об’єднує основні навігаційні посилання. target="_blank" відкриває нову вкладку; явно доданий rel="noopener" відокремлює її від поточної. Кнопка button виконує дію, а посилання переходить до адреси.'],
['An a element with href creates a link. Absolute URLs lead to another site; relative URLs lead to local files; #about targets an element with id="about". Link text should describe the destination.', 'nav groups major navigation links. target="_blank" opens a new tab; explicit rel="noopener" separates it from the current tab. Buttons perform actions; links navigate.'],
'Створи nav із посиланням #about, секцію id="about" з h2 і посилання на https://developer.mozilla.org/ у новій вкладці з rel="noopener".','Create nav with a #about link, a section id="about" with h2, and a link to https://developer.mozilla.org/ in a new tab with rel="noopener".',
['href="#about" має відповідати id="about".','Зовнішнє посилання починається з https://.','Додай target="_blank" rel="noopener".'],['href="#about" must match id="about".','The external URL starts with https://.','Add target="_blank" rel="noopener".'],
'<nav><a href="#about">Про мене</a></nav>\n<section id="about"><h2>Про мене</h2></section>\n<a href="https://developer.mozilla.org/" target="_blank" rel="noopener">Документація MDN</a>',
[rule('Якір у nav веде до секції','Nav anchor targets the section',d=>!!d.querySelector('nav a[href="#about"]')&&hasText(d,'section#about h2')),rule('MDN відкривається безпечно в новій вкладці','MDN opens safely in a new tab',d=>[...d.querySelectorAll('a')].some(a=>a.href.startsWith('https://developer.mozilla.org/')&&a.target==='_blank'&&a.rel.split(/\s+/).includes('noopener')&&a.textContent.trim()))]);
addHtmlLesson('lists','Списки та вкладені елементи','Lists and nesting',
['ul — список без заданого порядку, ol — послідовність кроків. Кожен пункт міститься в li. Не підмінюй список абзацами з тире: семантика допомагає браузерам і допоміжним технологіям.', 'Вкладений список розташовуй усередині li батьківського списку. dl, dt та dd підходять для термінів та їх пояснень. У цій практиці тренуємо ul та ol.'],
['ul is an unordered list; ol is an ordered sequence. Each item lives inside li. Avoid replacing real lists with paragraphs and dashes: semantics help browsers and assistive technology.', 'A nested list belongs inside a parent li. dl, dt, and dd represent terms and descriptions. This exercise focuses on ul and ol.'],
'Створи ul із трьома технологіями та ol із трьома кроками навчання. Усередині одного пункту ul додай вкладений ul із двома темами.','Create a ul with three technologies and an ol with three learning steps. Put a nested ul with two topics inside one item of the first ul.',
['ul і ol містять li.','Вкладений ul постав перед закривальним </li>.','Порахуй лише безпосередні пункти зовнішнього списку.'],['ul and ol contain li.','Place the nested ul before the closing </li>.','Count only direct items of the outer list.'],
'<ul>\n  <li>HTML<ul><li>Текст</li><li>Форми</li></ul></li>\n  <li>CSS</li>\n  <li>JavaScript</li>\n</ul>\n<ol><li>Прочитати</li><li>Спробувати</li><li>Перевірити</li></ol>',
[rule('Зовнішній ul має три пункти','Outer ul has three items',d=>[...d.querySelectorAll('ul')].some(el=>el.querySelectorAll(':scope > li').length>=3)),rule('ol має три кроки','ol has three steps',d=>d.querySelectorAll('ol > li').length>=3),rule('Вкладений список у li має дві теми','Nested list inside li has two topics',d=>[...d.querySelectorAll('li > ul')].some(el=>el.children.length>=2))]);
addHtmlLesson('images','Зображення та підписи','Images and captions',
['img — порожній елемент, закривальний </img> не потрібен. src вказує файл, alt передає зміст зображення для тих, хто його не бачить. Для суто декоративного зображення використовуй alt="".', 'figure об’єднує самостійний матеріал, а figcaption — його підпис. width і height дозволяють браузеру зарезервувати місце ще до завантаження. У цій вправі data URL забезпечує картинку без зовнішньої мережі.'],
['img is a void element with no closing </img>. src points to the image; alt conveys its meaning when it cannot be seen. Purely decorative images use alt="".', 'figure groups self-contained content and figcaption gives it a caption. width and height reserve space before loading. A data URL keeps this exercise independent of external networking.'],
'Додай figure з img, непорожнім alt, width="160", height="100" та figcaption. Для src використай data URL із прикладу.','Add figure with an img, nonempty alt, width="160", height="100", and figcaption. Use the sample data URL for src.',
['figure містить img та figcaption.','alt має описувати зміст, а не слово «картинка».','Джерело можна скопіювати з прикладу в теорії.'],['figure contains img and figcaption.','alt should describe the content, not just say “image”.','Copy the image source from the theory example.'],
'<figure>\n  <img src="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%27160%27 height=%27100%27%3E%3Crect width=%27160%27 height=%27100%27 fill=%27%23ffcc4d%27/%3E%3C/svg%3E" alt="Жовта картка" width="160" height="100">\n  <figcaption>Мій перший приклад зображення</figcaption>\n</figure>',
[rule('figure має зображення й підпис','figure has an image and caption',d=>!!d.querySelector('figure img')&&hasText(d,'figure figcaption')),rule('img має src, змістовний alt і розміри','img has src, descriptive alt, and dimensions',d=>[...d.querySelectorAll('figure img')].some(img=>img.getAttribute('src')?.trim()&&img.alt.trim()&&img.getAttribute('width')==='160'&&img.getAttribute('height')==='100'))]);
addHtmlLesson('semantics','Семантична сторінка','Semantic page',
['header — вступний блок, nav — навігація, main — основний унікальний вміст, footer — завершальна інформація. article — самостійний матеріал, section — тематичний розділ, зазвичай із заголовком.', 'div використовуй, коли немає відповідного семантичного елемента. Семантика не замінює CSS і сама не робить макет красивим; вона дає зміст структури. На сторінці має бути один видимий main.'],
['header introduces content, nav is navigation, main is the unique primary content, and footer holds closing information. article is self-contained content; section is a thematic grouping, usually with a heading.', 'Use div when no semantic element fits. Semantics do not replace CSS or make layouts attractive by themselves; they give structure meaning. A page should have one visible main.'],
'Створи header з h1 і nav, один main з article та h2, і footer з текстом.','Create header with h1 and nav, one main with article and h2, and a footer with text.',
['Основний вміст розмісти в main.','article має мати заголовок h2.','footer і header можуть бути сусідами main.'],['Put primary content inside main.','Give article an h2 heading.','footer and header can be siblings of main.'],
'<header><h1>Мій блог</h1><nav><a href="#post">Стаття</a></nav></header>\n<main><article id="post"><h2>Вивчаю HTML</h2><p>Семантика пояснює структуру.</p></article></main>\n<footer>Автор: Rubin</footer>',
[rule('header має h1 і nav','header has h1 and nav',d=>hasText(d,'header h1')&&!!d.querySelector('header nav')),rule('Один main містить article з h2','One main contains article with h2',d=>d.querySelectorAll('main').length===1&&hasText(d,'main article h2')),rule('footer заповнений','footer has content',d=>hasText(d,'footer'))]);
addHtmlLesson('forms','Форми та поля вводу','Forms and inputs',
['form об’єднує поля для надсилання. label пов’язується з полем через for та id. name — ключ, під яким значення поля передається при надсиланні. placeholder є підказкою, а не заміною label.', 'type="email" вмикає базову перевірку адреси, required робить поле обов’язковим. button type="submit" надсилає форму. HTML забезпечує клієнтську перевірку, але справжній сервер теж має перевіряти дані. У прев’ю надсилання вимкнене.'],
['form groups controls for submission. label connects to a control with matching for and id. name is the submitted value key. A placeholder is a hint, not a replacement for a label.', 'type="email" enables basic email validation; required makes a control mandatory. button type="submit" submits a form. Real servers must validate data too. Submission is disabled in the preview.'],
'Створи form із label та input для імені й email. Обидва поля повинні мати name та required; email — type="email". Додай кнопку submit.','Create a form with labeled name and email inputs. Both need name and required; email uses type="email". Add a submit button.',
['Наприклад, label for="email" та input id="email".','Не забудь name і required.','Задай кнопці type="submit".'],['For example, label for="email" and input id="email".','Remember name and required.','Set type="submit" on the button.'],
'<form>\n<label for="name">Ім’я</label><input id="name" name="name" required>\n<label for="email">Email</label><input id="email" name="email" type="email" required>\n<button type="submit">Надіслати</button>\n</form>',
[rule('Два обов’язкові іменовані поля','Two required named inputs',d=>d.querySelectorAll('form input[name][required]').length>=2),rule('Є поле email','Email input exists',d=>!!d.querySelector('form input[type="email"][required]')),rule('Кожне поле має пов’язаний label','Each input has an associated label',d=>{const inputs=[...d.querySelectorAll('form input')];return inputs.length>=2&&inputs.every(input=>input.id&&[...d.querySelectorAll('label')].some(label=>label.htmlFor===input.id&&label.textContent.trim()));}),rule('Є явна кнопка submit','Explicit submit button exists',d=>hasText(d,'form button[type="submit"]'))]);
addHtmlLesson('tables','Таблиці даних','Data tables',
['table використовують для даних із рядками й колонками, а не для розташування блоків сторінки. tr — рядок, th — комірка заголовка, td — комірка даних. caption називає таблицю.', 'thead і tbody відокремлюють заголовки від даних. scope="col" на th пояснює, що заголовок належить колонці. Для складніших таблиць потрібні складніші зв’язки; тут тренуємо просту таблицю.'],
['table represents row-and-column data, not page layout. tr is a row, th a header cell, td a data cell. caption names the table.', 'thead and tbody separate headings from data. scope="col" associates a header with a column. Complex tables need more complex relationships; this exercise uses a simple table.'],
'Створи таблицю навчального плану: caption, thead із двома th scope="col" і tbody з двома рядками по дві td.','Create a study plan table: caption, thead with two th scope="col", and tbody with two rows of two td cells.',
['Рядок має структуру <tr><td>...</td></tr>.','Заголовки розмісти в thead.','caption і tbody знаходяться всередині table.'],['A row looks like <tr><td>...</td></tr>.','Put headings in thead.','caption and tbody belong inside table.'],
'<table>\n<caption>Навчальний план</caption>\n<thead><tr><th scope="col">Тема</th><th scope="col">Статус</th></tr></thead>\n<tbody><tr><td>HTML</td><td>У роботі</td></tr><tr><td>CSS</td><td>Далі</td></tr></tbody>\n</table>',
[rule('Є caption та заголовки колонок','Caption and column headers exist',d=>hasText(d,'table caption')&&d.querySelectorAll('thead th[scope="col"]').length>=2),rule('Два рядки даних по дві комірки','Two data rows with two cells',d=>[...d.querySelectorAll('tbody tr')].filter(row=>row.querySelectorAll('td').length>=2).length>=2)]);
addHtmlLesson('accessibility','Доступність і метадані','Accessibility and metadata',
['Доступний HTML починається з правильних елементів: button для дії, a для переходу, label для поля. Пропуск навігації дозволяє користувачу клавіатури швидко перейти до основного вмісту.', 'meta name="viewport" допомагає правильно показувати сторінку на мобільному. meta description коротко описує її. ARIA потрібна лише там, де HTML не передає потрібного змісту; вона не виправляє неправильний елемент автоматично.'],
['Accessible HTML starts with correct elements: button for an action, a for navigation, label for a field. A skip link lets keyboard users jump directly to primary content.', 'meta name="viewport" supports mobile display. A meta description summarizes the page. Use ARIA where native HTML cannot express the meaning; it does not automatically repair the wrong element.'],
'Додай viewport з width=device-width, непорожній meta description, посилання #content перед main id="content" і button type="button" з текстом.','Add a viewport with width=device-width, a nonempty meta description, a #content link before main id="content", and a button type="button" with text.',
['Метадані розмісти у head.','href="#content" відповідає main id="content".','Для дії без надсилання форми використовуй type="button".'],['Put metadata inside head.','href="#content" matches main id="content".','Use type="button" for an action without form submission.'],
'<!doctype html>\n<html lang="uk"><head><meta charset="UTF-8"><title>Доступна сторінка</title>\n<meta name="viewport" content="width=device-width, initial-scale=1">\n<meta name="description" content="Мій навчальний сайт"></head><body>\n<a href="#content">Перейти до вмісту</a>\n<main id="content"><h1>Вітаю</h1><button type="button">Показати деталі</button></main>\n</body></html>',
[rule('Viewport і description заповнені','Viewport and description exist',d=>d.querySelector('meta[name="viewport"]')?.content.includes('width=device-width')&&!!d.querySelector('meta[name="description"]')?.content.trim()),rule('Skip link стоїть перед main','Skip link precedes main',d=>{const a=d.querySelector('a[href="#content"]'),main=d.querySelector('main#content');return !!a&&!!main&&!!(a.compareDocumentPosition(main)&4);}),rule('Є кнопка з текстом і явним типом','Button has text and explicit type',d=>hasText(d,'button[type="button"]'))]);
addHtmlLesson('portfolio','Мініпроєкт: сторінка портфоліо','Mini project: portfolio page',
['Об’єднай вивчене в одну сторінку: метадані, зрозумілі заголовки, навігація, основний вміст, список навичок і форма контакту. Почни зі структури, потім додай текст.', 'Перед завершенням пройди самоперевірку: чи логічні заголовки, чи зрозумілі посилання, чи кожне поле має label? Автоматичні перевірки оцінюють структуру, а не красу дизайну. Стилі додамо в модулі CSS.'],
['Combine what you learned into one page: metadata, meaningful headings, navigation, primary content, skills, and a contact form. Start with structure, then add content.', 'Before finishing, review heading hierarchy, link clarity, and input labels. Automated checks evaluate structure, not visual design. Styling comes in the CSS module.'],
'Зроби портфоліо: документ із мовою, title, charset і viewport; header із h1 та nav до #skills; main із section id="skills", h2 і списком 3 навичок; form із підписаним email та submit; footer.','Build a portfolio: document language, title, charset, viewport; header with h1 and nav to #skills; main with section id="skills", h2 and 3 skills; form with a labeled required email and submit; footer.',
['Збери каркас header → main → footer.','У main додай section id="skills" зі списком.','Форма має label, email з name та required і кнопку submit.'],['Build header → main → footer.','Add section id="skills" with a list inside main.','The form needs a label, email with name and required, and a submit button.'],
'<!doctype html>\n<html lang="uk"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Моє портфоліо</title></head><body>\n<header><h1>Rubin — frontend developer</h1><nav><a href="#skills">Навички</a></nav></header>\n<main><section id="skills"><h2>Мої навички</h2><ul><li>HTML</li><li>CSS</li><li>Git</li></ul></section>\n<form><label for="email">Ваш email</label><input id="email" name="email" type="email" required><button type="submit">Зв’язатися</button></form></main>\n<footer>Моє портфоліо</footer>\n</body></html>',
[rule('Документ має doctype, мову та метадані','Document has doctype, language, and metadata',(d,s)=>/^\s*<!doctype\s+html\s*>/i.test(s)&&!!d.documentElement.lang&&hasText(d,'title')&&d.querySelector('meta[charset]')?.getAttribute('charset').toLowerCase()==='utf-8'&&d.querySelector('meta[name="viewport"]')?.content.includes('width=device-width')),rule('header має h1 та навігацію до skills','header has h1 and navigation to skills',d=>hasText(d,'header h1')&&!!d.querySelector('header nav a[href="#skills"]')),rule('main має заголовок і три навички','main has a heading and three skills',d=>d.querySelectorAll('main').length===1&&hasText(d,'main section#skills h2')&&d.querySelectorAll('main section#skills ul > li').length>=3),rule('Контактна форма має підписаний email і submit','Contact form has labeled email and submit',d=>{const input=d.querySelector('main form input[type="email"][required][name]');return !!input&&input.id&&[...d.querySelectorAll('main form label')].some(label=>label.htmlFor===input.id&&label.textContent.trim())&&hasText(d,'main form button[type="submit"]');}),rule('footer заповнений','footer has content',d=>hasText(d,'footer'))]);
Object.assign(translations.uk,{htmlCourseTitle:'HTML: від першого тега до портфоліо',courseRun:'Оновити прев’ю',courseCheck:'Перевірити завдання',courseHint:'Наступна підказка',courseSolution:'Показати розв’язок',courseReset:'Повернути початковий код',courseResetConfirm:'Замінити свою чернетку початковим кодом?',courseTheory:'Пояснення',courseExample:'Приклад синтаксису',courseTask:'Твоє завдання',courseCode:'Твій HTML-код',coursePreview:'Результат у браузері',coursePassed:'Усі перевірки пройдено. Урок завершено!',courseRetry:'Є що виправити. Перевір пункти нижче.',courseSaved:'Чернетку збережено',courseUnsaved:'Не вдалося зберегти чернетку. Експортуй HTML перед виходом.',courseDownload:'Завантажити HTML',courseNext:'Наступний урок →',coursePrevious:'← Попередній',courseCompleted:'Завершено',coursePending:'Ще не завершено',courseLimit:'Умови перевіряють структуру HTML, а не дизайн чи всі помилки синтаксису. Скрипти, мережеві запити та надсилання форм у прев’ю вимкнено.',courseSolutionNote:'Приклад розв’язку — для порівняння. Він не замінює твій код.',courseStart:'Почни з практики. Розв’язок відкриється після першої перевірки.',courseResults:'Результати перевірки',courseLessons:'Уроки HTML',courseRestore:'Курс зберігає уроки й чернетки автоматично.'});
Object.assign(translations.en,{htmlCourseTitle:'HTML: from your first tag to a portfolio',courseRun:'Update preview',courseCheck:'Check exercise',courseHint:'Next hint',courseSolution:'Show solution',courseReset:'Restore starter code',courseResetConfirm:'Replace your draft with the starter code?',courseTheory:'Explanation',courseExample:'Syntax example',courseTask:'Your exercise',courseCode:'Your HTML code',coursePreview:'Browser result',coursePassed:'All checks passed. Lesson completed!',courseRetry:'Some checks need attention. Review the items below.',courseSaved:'Draft saved',courseUnsaved:'Could not save your draft. Download the HTML before leaving.',courseDownload:'Download HTML',courseNext:'Next lesson →',coursePrevious:'← Previous',courseCompleted:'Completed',coursePending:'Not completed yet',courseLimit:'Checks evaluate HTML structure, not design or every syntax error. Scripts, network requests, and form submission are disabled in the preview.',courseSolutionNote:'Reference solution for comparison. It does not replace your code.',courseStart:'Try the exercise first. The solution unlocks after your first check.',courseResults:'Check results',courseLessons:'HTML lessons',courseRestore:'Lessons and drafts are saved automatically.'});
function validHtmlCourse(value){return value&&value.version===1&&htmlLessons.some(l=>l.id===value.selected)&&value.lessons&&typeof value.lessons==='object'&&!Array.isArray(value.lessons)&&Object.entries(value.lessons).every(([id,s])=>htmlLessons.some(l=>l.id===id)&&s&&typeof s.code==='string'&&s.code.length<=20000&&typeof s.completed==='boolean'&&Number.isInteger(s.attempts)&&s.attempts>=0&&Number.isInteger(s.hints)&&s.hints>=0&&s.hints<=3);}
let htmlCourse=readData('devspace-htmlCourse',{version:1,selected:'document',lessons:{}},validHtmlCourse);
let courseResults=null,courseSaveTimer,courseStorageOk=true;
const courseStartButton=projectElement('button','secondary-button');courseStartButton.type='button';courseStartButton.addEventListener('click',()=>document.querySelector('#html-course').scrollIntoView({behavior:'smooth'}));document.querySelector('#learning-view .page-heading').append(courseStartButton);
function lessonState(lesson){return htmlCourse.lessons[lesson.id] ||= {code:lesson.starter,completed:false,attempts:0,hints:0};}
function saveHtmlCourse(){const success=writeData('devspace-htmlCourse',htmlCourse);courseStorageOk=success;const status=document.querySelector('#course-save');if(status)status.textContent=t()[success?'courseSaved':'courseUnsaved'];return success;}
function syncHtmlProgress(){
 const group=document.querySelector('[data-tech="HTML"]').closest('.topic-list');group.replaceChildren();
 for(const lesson of htmlLessons){const input=document.createElement('input');input.type='checkbox';input.hidden=true;input.dataset.topic='htmlLesson-'+lesson.id;input.dataset.tech='HTML';input.checked=htmlCourse.lessons[lesson.id]?.completed===true;group.append(input);savedProgress[input.dataset.topic]=input.checked;}
 const note=projectElement('a','text-link',t().htmlCourseTitle+' ↗');note.href='#html-course';note.addEventListener('click',e=>{e.preventDefault();document.querySelector('#html-course').scrollIntoView({behavior:'smooth'});});group.append(note);
 try{kachanStorage.setItem('devspace-progress',JSON.stringify(savedProgress));}catch{}
 updateProgress();renderLearningOverview();
}
function coursePreview(){const frame=document.querySelector('#course-preview');const code=document.querySelector('#course-code').value;
 const doc=new DOMParser().parseFromString(code,'text/html');
 doc.querySelectorAll('script,iframe,object,embed,base,meta[http-equiv]').forEach(el=>el.remove());
 doc.querySelectorAll('a[href]').forEach(a=>{if(!a.getAttribute('href').startsWith('#'))a.removeAttribute('href');a.removeAttribute('target');});
 frame.srcdoc='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data:; style-src \'unsafe-inline\'; form-action \'none\'; base-uri \'none\'; navigate-to \'none\'">'+doc.documentElement.outerHTML;
}
function runHtmlChecks(lesson,code){const doc=new DOMParser().parseFromString(code,'text/html');return lesson.checks.map(check=>({label:check[document.documentElement.lang],passed:!!check.test(doc,code)}));}
function drawCourseResults(){const list=document.querySelector('#course-results');list.replaceChildren();if(!courseResults)return;list.append(projectElement('p','',courseResults.every(r=>r.passed)?t().coursePassed:t().courseRetry));for(const result of courseResults)list.append(projectElement('p',result.passed?'check-pass':'check-fail',(result.passed?'✓ ':'○ ')+result.label));}
const htmlSyntaxExamples={
 document:'<!doctype html>\n<html lang="uk">\n<head><meta charset="UTF-8"><title>Назва вкладки</title></head>\n<body><!-- Вміст сторінки --></body>\n</html>',
 text:'<h2>Тема</h2>\n<p>Це <strong>важлива</strong> думка.</p>',
 links:'<a href="#contacts">Контакти</a>\n<section id="contacts"><h2>Контакти</h2></section>',
 lists:'<ul>\n  <li>Перша тема</li>\n  <li>Друга тема</li>\n</ul>',
 semantics:'<main>\n  <section><h2>Розділ</h2><p>Зміст</p></section>\n</main>',
 forms:'<label for="city">Місто</label>\n<input id="city" name="city" required>',
 tables:'<table><caption>Приклад</caption>\n<tr><th scope="col">Тема</th></tr>\n<tr><td>HTML</td></tr></table>',
 accessibility:'<meta name="viewport" content="width=device-width, initial-scale=1">\n<a href="#main">До вмісту</a>\n<main id="main">...</main>',
 portfolio:'<header>...</header>\n<main>...</main>\n<footer>...</footer>'
};

function renderHtmlCourse(){
 courseStartButton.textContent=document.documentElement.lang==='uk'?'Почати курс HTML ↓':'Start HTML course ↓';
 const language=document.documentElement.lang;const lesson=htmlLessons.find(l=>l.id===htmlCourse.selected);const state=lessonState(lesson);
 document.querySelector('#html-course-title').textContent=t().htmlCourseTitle;
 document.querySelector('#html-course-summary').textContent=htmlLessons.filter(l=>htmlCourse.lessons[l.id]?.completed).length+' / '+htmlLessons.length+' · '+t().courseRestore;
 const nav=document.querySelector('#html-lessons');nav.setAttribute('aria-label',t().courseLessons);nav.replaceChildren();
 htmlLessons.forEach((item,index)=>{const b=projectElement('button','lesson-button',(index+1)+'. '+item.title[language]);b.type='button';if(item.id===lesson.id)b.setAttribute('aria-current','step');if(htmlCourse.lessons[item.id]?.completed){b.append(projectElement('span','lesson-done',' ✓'));b.setAttribute('aria-label',item.title[language]+': '+t().courseCompleted);}b.addEventListener('click',()=>{clearTimeout(courseSaveTimer);saveHtmlCourse();htmlCourse.selected=item.id;courseResults=null;saveHtmlCourse();renderHtmlCourse();});nav.append(b);});
 const container=document.querySelector('#html-lesson');container.replaceChildren();container.append(projectElement('span','badge','HTML · '+(htmlLessons.indexOf(lesson)+1)+' / '+htmlLessons.length),projectElement('h2','',lesson.title[language]),projectElement('h3','',t().courseTheory));
 lesson.theory[language].forEach(paragraph=>container.append(projectElement('p','lesson-theory',paragraph)));
 const example=projectElement('details','course-example');example.append(projectElement('summary','',t().courseExample));const pre=projectElement('pre','snippet-code');pre.append(projectElement('code','',lesson.id==='images'?lesson.solution:htmlSyntaxExamples[lesson.id]));example.append(pre);container.append(example);
 container.append(projectElement('h3','',t().courseTask),projectElement('p','lesson-theory',lesson.task[language]));
 const label=projectElement('label','course-code-label',t().courseCode);label.htmlFor='course-code';const textarea=projectElement('textarea','course-code',state.code);textarea.id='course-code';textarea.maxLength=20000;textarea.spellcheck=false;textarea.rows=14;
 textarea.addEventListener('input',()=>{state.code=textarea.value;courseResults=null;drawCourseResults();clearTimeout(courseSaveTimer);saveHtmlCourse();});
 container.append(label,textarea,projectElement('p','panel-note',t().courseLimit),projectElement('p','panel-note',t()[courseStorageOk?'courseSaved':'courseUnsaved']));container.lastChild.id='course-save';container.lastChild.setAttribute('role','status');
 const actions=projectElement('div','editor-actions');
 function button(key,handler,primary=false){const b=projectElement('button',primary?'primary-button':'secondary-button',t()[key]);b.type='button';b.addEventListener('click',handler);actions.append(b);return b;}
 button('courseRun',coursePreview);
 button('courseCheck',()=>{clearTimeout(courseSaveTimer);state.code=textarea.value;state.attempts++;courseResults=runHtmlChecks(lesson,state.code);if(courseResults.every(r=>r.passed))state.completed=true;saveHtmlCourse();syncHtmlProgress();renderHtmlCourse();},true);
 const hint=button('courseHint',()=>{state.hints=Math.min(state.hints+1,lesson.hints[language].length);saveHtmlCourse();renderHtmlCourse();});hint.disabled=state.hints>=lesson.hints[language].length;
 button('courseReset',()=>{if(!window.confirm(t().courseResetConfirm))return;state.code=lesson.starter;courseResults=null;saveHtmlCourse();renderHtmlCourse();});
 button('courseDownload',()=>{const url=URL.createObjectURL(new Blob([textarea.value],{type:'text/html'}));const a=document.createElement('a');a.href=url;a.download='kachan-html-'+lesson.id+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});container.append(actions);
 const hints=projectElement('ol','course-hints');lesson.hints[language].slice(0,state.hints).forEach(text=>hints.append(projectElement('li','',text)));container.append(hints);
 const solution=projectElement('details','course-example');solution.append(projectElement('summary','',t().courseSolution));if(state.attempts){solution.append(projectElement('p','panel-note',t().courseSolutionNote));const code=projectElement('pre','snippet-code',lesson.solution);solution.append(code);}else{solution.append(projectElement('p','panel-note',t().courseStart));}container.append(solution);
 const results=projectElement('div','course-results');results.id='course-results';results.setAttribute('role','status');results.setAttribute('aria-live','polite');container.append(results);drawCourseResults();
 container.append(projectElement('h3','',t().coursePreview));const iframe=document.createElement('iframe');iframe.id='course-preview';iframe.title=t().coursePreview;iframe.setAttribute('sandbox','');iframe.referrerPolicy='no-referrer';container.append(iframe);
 const navigation=projectElement('div','course-pagination');for(const [offset,key] of [[-1,'coursePrevious'],[1,'courseNext']]){const next=htmlLessons[htmlLessons.indexOf(lesson)+offset];if(next){const b=projectElement('button','secondary-button',t()[key]);b.type='button';b.addEventListener('click',()=>{clearTimeout(courseSaveTimer);saveHtmlCourse();htmlCourse.selected=next.id;courseResults=null;saveHtmlCourse();renderHtmlCourse();document.querySelector('#html-lesson').scrollIntoView({behavior:'smooth'});});navigation.append(b);}}container.append(navigation);coursePreview();
}
window.addEventListener('languagechange',()=>{courseResults=null;syncHtmlProgress();renderHtmlCourse();});

syncHtmlProgress();setLanguage(document.documentElement.lang);
