// Presentation only: curriculum, checks and saved learner records stay in their modules.
let learningScreen='library';
const learningLookCopy={uk:{catalog:'Обери, що вивчатимеш',intro:'Одна тема за раз. Прочитай пояснення, спробуй сам і перевір результат.',courses:'Усі курси',lessons:'уроків',done:'завершено',start:'Почати курс',resume:'Продовжити',syllabus:'Зміст курсу',lesson:'Урок',key:'Ключова ідея',example:'Приклад із поясненням',extra:'Підказки й додаткові вправи',notes:'Конспекти уроку',html:'Структура сторінок, форми та доступність.',css:'Стилі, компонування й адаптивні інтерфейси.',javascript:'Логіка, дані та взаємодія зі сторінкою.',git:'Історія змін, гілки й робота з репозиторієм.',typescript:'Типи та зрозумілі контракти для коду.',figma:'Макети, компоненти й інтерактивні прототипи.'},en:{catalog:'Choose what to learn',intro:'One topic at a time. Read, try it yourself, then check the result.',courses:'All courses',lessons:'lessons',done:'completed',start:'Start course',resume:'Continue',syllabus:'Course outline',lesson:'Lesson',key:'Key idea',example:'Annotated example',extra:'Tips and extra exercises',notes:'Lesson notes',html:'Page structure, forms and accessibility.',css:'Styling, layouts and responsive interfaces.',javascript:'Logic, data and interaction with the page.',git:'Change history, branches and repositories.',typescript:'Types and clear contracts for your code.',figma:'Layouts, components and interactive prototypes.'}};
const learningLibrary=E('section','learning-library');learningLibrary.id='learning-library';Q('learning-view').querySelector('.page-heading').after(learningLibrary);
let learningLibrarySignature='';
function learningModules(){return[{id:'HTML',lessons:htmlLessons.map(l=>({...l,id:'html-'+l.id}))},...academyCourses];}
function learningDone(l){return l.id.startsWith('html-')?!!htmlCourse.lessons[l.id.slice(5)]?.completed:!!academy.states[l.id]?.completed;}
function renderLearningLibrary(){
 const lang=document.documentElement.lang,c=learningLookCopy[lang],modules=learningModules();const signature=lang+'|'+modules.map(m=>m.lessons.filter(learningDone).length).join(',');if(signature===learningLibrarySignature)return;learningLibrarySignature=signature;learningLibrary.replaceChildren();
 const intro=E('div','learning-library-intro');intro.append(E('h2','',c.catalog),E('p','',c.intro));learningLibrary.append(intro);const grid=E('div','learning-course-grid');
 for(const [index,module] of modules.entries()){const done=module.lessons.filter(learningDone).length,card=E('article','learning-course-card'),top=E('div','learning-card-top'),mark=E('span','learning-course-mark',({HTML:'</>',CSS:'{ }',JavaScript:'JS',Git:'↗',TypeScript:'TS',Figma:'◈'})[module.id]);mark.setAttribute('aria-hidden','true');top.append(mark,E('span','learning-course-count',String(index+1).padStart(2,'0')));card.append(top,E('h3','',module.id),E('p','learning-course-description',c[module.id.toLowerCase()]));const progress=E('progress');progress.max=module.lessons.length;progress.value=done;progress.setAttribute('aria-label',module.id+' · '+done+'/'+module.lessons.length);const meta=E('div','learning-card-meta');meta.append(E('span','',module.lessons.length+' '+c.lessons),E('span','',done+'/'+module.lessons.length+' '+c.done));const next=module.lessons.find(l=>!learningDone(l))||module.lessons[0];const start=button(done?c.resume:c.start,()=>openLesson(next.id),'learning-course-start');start.setAttribute('aria-label',(done?c.resume:c.start)+' · '+module.id);start.append(E('span','','→'));card.append(progress,meta,start);grid.append(card);}learningLibrary.append(grid);
}
function polishLessonBody(body,html){
 if(!body)return;const lang=document.documentElement.lang,c=learningLookCopy[lang];body.classList.add('learning-reader');
 const children=[...body.children];for(const el of children){if(el.tagName==='H3'&&el.textContent===t().lessonGoal){el.classList.add('learning-redundant');el.nextElementSibling?.classList.add('learning-redundant');}if(el.tagName==='H3'&&el.textContent===t().courseTheory)el.classList.add('learning-redundant');}
 if(html){const example=children.find(el=>el.matches('details.course-example'));example?.classList.add('learning-redundant');}
 const guide=body.querySelector('.lesson-deep-guide');if(guide&&!guide.dataset.polished){guide.dataset.polished='true';guide.querySelector(':scope>h3')?.remove();const items=[...guide.querySelectorAll(':scope>details')];if(items.length===6){const [why,walk,reference,mistake,extra,check]=items;why.classList.add('learning-key-idea');why.open=true;why.querySelector('summary').textContent=c.key;reference.classList.add('learning-example');reference.querySelector('summary').textContent=c.example;reference.open=false;const more=E('details','learning-more');more.append(E('summary','',c.extra));for(const item of [walk,mistake,extra,check]){item.open=false;more.append(item);}guide.replaceChildren(why,reference,more);}}
 const read=children.find(el=>el.classList.contains('form-field')&&el.querySelector('input[type=checkbox]'));if(guide&&read&&guide.nextElementSibling!==read)guide.after(read);
 const notesHeading=children.find(el=>el.tagName==='H3'&&el.textContent===t().lessonNotes);if(notesHeading&&!body.querySelector('.learning-notes-fold')){notesHeading.classList.add('learning-redundant');const linked=notesHeading.nextElementSibling;if(linked&&!linked.classList.contains('course-pagination')){const fold=E('details','learning-notes-fold');fold.append(E('summary','',c.notes));linked.before(fold);fold.append(linked);}}
 const layout=body.closest('.course-layout'),nav=layout?.querySelector('.lesson-navigation');if(nav&&!nav.closest('.learning-syllabus')){const fold=E('details','learning-syllabus');fold.open=innerWidth>850;const summary=E('summary');summary.append(E('span','',c.syllabus),E('span','learning-syllabus-counter',String(nav.querySelectorAll('button').length)));nav.before(fold);fold.append(summary,nav);}
 if(nav){const summary=nav.closest('details').querySelector('summary');summary.firstElementChild.textContent=c.syllabus;const active=nav.querySelector('[aria-current=step]');for(const [i,b] of [...nav.querySelectorAll('button')].entries()){if(b.dataset.learnStyled)continue;b.dataset.learnStyled='true';const title=b.textContent.replace(/^\d+\.\s*/,'').replace(/\s*✓$/,'');const completed=b.textContent.includes('✓');b.replaceChildren(E('span','learning-lesson-number',completed?'✓':String(i+1).padStart(2,'0')),E('span','learning-lesson-title',title));}if(active)summary.setAttribute('aria-label',c.syllabus+' · '+active.textContent);if(!nav.dataset.mobileClose){nav.dataset.mobileClose='true';nav.addEventListener('click',event=>{if(innerWidth<=850&&event.target.closest('button'))nav.closest('details').open=false;});}}
}
function applyLearningLook(){
 renderLearningLibrary();const showing=learningScreen==='library';learningLibrary.hidden=!showing;Q('learning-view').classList.toggle('learning-catalog-open',showing);
 academyPanel.hidden=showing;Q('html-course').hidden=showing||academy.course!=='HTML';courseStartButton.hidden=true;
 let toolbar=Q('learning-course-toolbar');if(!toolbar){toolbar=E('div','learning-course-toolbar');toolbar.id='learning-course-toolbar';academyPanel.before(toolbar);}toolbar.hidden=showing;toolbar.replaceChildren();const c=learningLookCopy[document.documentElement.lang];const back=button(c.courses,()=>{learningScreen='library';applyLearningLook();Q('learning-library').scrollIntoView({block:'start',behavior:'smooth'});},'learning-back');back.prepend(E('span','','← '));toolbar.append(back,E('span','learning-current-course',academy.course));
 const body=academy.course==='HTML'?Q('html-lesson'):academyPanel.querySelector('.course-layout>section');polishLessonBody(body,academy.course==='HTML');
}
const arrangementBeforeLearningLook=arrangeLesson;arrangeLesson=function(){arrangementBeforeLearningLook();applyLearningLook();};
const academyBeforeLearningLook=renderAcademy;renderAcademy=function(){academyBeforeLearningLook();applyLearningLook();};
const htmlBeforeLearningLook=renderHtmlCourse;renderHtmlCourse=function(){htmlBeforeLearningLook();applyLearningLook();};
const openBeforeLearningLook=openLesson;openLesson=function(id){if(!lessonCatalog().some(l=>l.id===id))return;learningScreen='lesson';openBeforeLearningLook(id);applyLearningLook();};
window.addEventListener('languagechange',()=>{learningLibrarySignature='';applyLearningLook();});
const syllabusMedia=matchMedia('(max-width:850px)');syllabusMedia.addEventListener('change',()=>{for(const fold of Q('learning-view').querySelectorAll('.learning-syllabus'))fold.open=!syllabusMedia.matches;});
applyLearningLook();
