// Convenient navigation and deeper material are added to the existing reader.
const plusCopy={uk:{resumeTitle:'Твій наступний урок',resume:'Відкрити урок',outline:'Усі теми',close:'Закрити',question:'Спробуй пояснити',answer:'Показати пояснення',terms:'Словничок модуля',experiment:'Ще один спосіб потренуватись',copy:'Скопіювати приклад',copied:'Приклад скопійовано',copyFail:'Не вдалося скопіювати. Виділи текст прикладу й скопіюй вручну.',reading:'хв читання',step:'Крок',of:'із',practice:'До практики',readPractice:'Прочитано → до практики',test:'До тесту',next:'Наступний урок',courses:'До курсів',finished:'Урок завершено',optional:'Ці запитання для самоперевірки. Вони не змінюють результат тесту.',try:'Перевір припущення у вкладці «Практика», потім порівняй із поясненням.'},en:{resumeTitle:'Your next lesson',resume:'Open lesson',outline:'All topics',close:'Close',question:'Try to explain',answer:'Show explanation',terms:'Module glossary',experiment:'Another way to practise',copy:'Copy example',copied:'Example copied',copyFail:'Could not copy. Select the example text and copy it manually.',reading:'min read',step:'Step',of:'of',practice:'To practice',readPractice:'Read → to practice',test:'To test',next:'Next lesson',courses:'Back to courses',finished:'Lesson completed',optional:'These questions are for self-review and do not change quiz results.',try:'Test your prediction in Practice, then compare it with the explanation.'}};
let learningFocus=false;
const learningMapDialog=E('dialog','learning-map-dialog');learningMapDialog.setAttribute('aria-labelledby','learning-map-title');document.body.append(learningMapDialog);let learningMapOrigin=null;
learningMapDialog.addEventListener('close',()=>{if(learningMapOrigin?.isConnected&&learningMapOrigin.getClientRects().length)learningMapOrigin.focus();});learningMapDialog.addEventListener('click',event=>{if(event.target!==learningMapDialog)return;const r=learningMapDialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)learningMapDialog.close();});
function openLearningMap(module){const lang=document.documentElement.lang,c=plusCopy[lang];learningMapOrigin=document.activeElement;learningMapDialog.replaceChildren();const header=E('div','learning-map-header'),title=E('h2','',module.id);title.id='learning-map-title';header.append(title,button(c.close,()=>learningMapDialog.close(),'secondary-button'));learningMapDialog.append(header,E('p','panel-note',module.lessons.length+' '+learningLookCopy[lang].lessons));const list=E('div','learning-map-list');for(const [i,l] of module.lessons.entries()){const b=button(l.title[lang],()=>{learningMapDialog.close();openLesson(l.id);},'learning-map-item');b.replaceChildren(E('span','learning-map-number',learningDone(l)?'✓':String(i+1).padStart(2,'0')),E('span','',l.title[lang]),E('span','learning-map-arrow','→'));list.append(b);}learningMapDialog.append(list);learningMapDialog.showModal();}
function currentLearningEntry(){const id=academy.course==='HTML'?'html-'+htmlCourse.selected:academy.selected;return lessonCatalog().find(l=>l.id===id)||lessonCatalog()[0];}
function nextResumeEntry(){const current=currentLearningEntry(),module=learningModules().find(m=>m.id===current.course);return !learningDone(current)?current:module.lessons.find(l=>!learningDone(l))||learningModules().flatMap(m=>m.lessons).find(l=>!learningDone(l))||current;}
function addDeeperMaterial(body,l){
 const guide=body.querySelector('.lesson-deep-guide');if(!guide||guide.dataset.plus)return;guide.dataset.plus='true';const lang=document.documentElement.lang,c=plusCopy[lang],row=lessonCases[l.id],course=l.course;if(!row)return;
 const reference=guide.querySelector('.learning-example .lesson-detail-content');if(reference){const recall=E('section','learning-recall');recall.append(E('h3','',c.question),E('p','',row[lang==='uk'?0:1]));const answer=E('details','learning-answer');answer.append(E('summary','',c.answer),E('p','',row[lang==='uk'?2:3]));recall.append(answer,E('p','panel-note',c.optional));reference.append(recall);const sample=depthExamples[l.id];if(sample){const copy=button(c.copy,async()=>{try{await navigator.clipboard.writeText(sample[0]);notice(c.copied);}catch{notice(c.copyFail);}},'learning-copy');reference.querySelector('pre')?.before(copy);}}
 const more=guide.querySelector('.learning-more');if(more){const glossary=E('details','lesson-detail learning-glossary');glossary.append(E('summary','',c.terms));const dl=E('dl','lesson-detail-content');for(const [term,uk,en] of courseGlossaries[course]){const names=term.split(' / ');dl.append(E('dt','',names[lang==='uk'?0:1]||names[0]),E('dd','',lang==='uk'?uk:en));}glossary.append(dl);more.append(glossary);}
 if(more){const exercise=lessonExperiments[l.id],fold=E('details','lesson-detail learning-experiment'),content=E('div','lesson-detail-content'),expected=E('details','learning-answer');fold.append(E('summary','',c.experiment));content.append(E('p','',exercise[lang==='uk'?0:1]),E('p','panel-note',lang==='uk'?'Експериментуй в окремій чернетці, щоб не замінити розв’язок основної вправи. Git — у навчальному репозиторії або симуляторі, Figma — у своєму файлі.':'Experiment in a separate draft to preserve the main exercise solution. Use a learning repository or simulator for Git and your own file for Figma.'));expected.append(E('summary','',lang==='uk'?'Очікуваний результат':'Expected result'),E('p','',exercise[lang==='uk'?2:3]));content.append(expected);fold.append(content);more.append(fold);}
}
function enhanceLearning(){
 const lang=document.documentElement.lang,c=plusCopy[lang];
 Q('learning-view').classList.toggle('learning-focus-mode',learningFocus&&learningScreen!=='library');
 const toolbar=Q('learning-course-toolbar');if(toolbar&&!toolbar.querySelector('.learning-focus-toggle')){const focus=button(learningFocus?(lang==='uk'?'Показати зміст':'Show outline'):(lang==='uk'?'Фокус':'Focus'),()=>{learningFocus=!learningFocus;applyLearningLook();},'learning-focus-toggle');focus.setAttribute('aria-pressed',String(learningFocus));toolbar.append(focus);}
 const modules=learningModules();for(const [i,card] of [...learningLibrary.querySelectorAll('.learning-course-card')].entries()){if(!card.querySelector('.learning-outline'))card.append(button(c.outline,()=>openLearningMap(modules[i]),'learning-outline'));}
 const next=nextResumeEntry(),heroSignature=lang+'|'+next.id;let hero=learningLibrary.querySelector('.learning-resume-banner');if(!hero||hero.dataset.signature!==heroSignature){hero?.remove();hero=E('section','learning-resume-banner');hero.dataset.signature=heroSignature;const copy=E('div');copy.append(E('span','learning-resume-kicker',c.resumeTitle+' · '+next.course),E('h3','',next.title[lang]));hero.append(copy,button(c.resume,()=>openLesson(next.id),'primary-button'));learningLibrary.querySelector('.learning-library-intro').after(hero);}
 if(learningScreen==='library')return;const l=currentLearningEntry(),html=l.course==='HTML',body=html?Q('html-lesson'):academyPanel.querySelector('.course-layout>section');if(!body)return;addDeeperMaterial(body,l);
 const module=modules.find(m=>m.id===l.course),index=module.lessons.findIndex(item=>item.id===l.id),sourceLesson=html?htmlLessons.find(item=>'html-'+item.id===l.id):l;
 const text=[...sourceLesson.theory[lang],deepTopics[l.id][lang==='uk'?0:1],lessonCases[l.id][lang==='uk'?2:3],depthExamples[l.id]?.[lang==='uk'?1:2]||'',lessonExperiments[l.id][lang==='uk'?0:1],lessonExperiments[l.id][lang==='uk'?2:3],...courseGlossaries[l.course].map(term=>term[lang==='uk'?1:2])].join(' '),minutes=Math.max(1,Math.ceil(text.split(/\s+/).length/160));const badge=body.querySelector(':scope>.badge');if(badge)badge.textContent=l.course+' · '+(index+1)+' / '+module.lessons.length+' · ~'+minutes+' '+c.reading;
 const state=html?htmlCourse.lessons[l.id.slice(5)]:academy.states[l.id],passed=html?[false,!!state?.completed,!!state?.completed]:[!!state?.theoryRead,!!state?.practicePassed,!!state?.quizPassed];for(const [i,b] of [...body.querySelectorAll('.lesson-step-tabs button')].entries()){b.querySelector('.learning-step-dot')?.remove();const dot=E('span','learning-step-dot',passed[i]?'✓':String(i+1));dot.setAttribute('aria-hidden','true');b.prepend(dot);b.classList.toggle('learning-step-passed',passed[i]);}
 body.querySelector('.learning-step-footer')?.remove();const footer=E('div','learning-step-footer'),stepIndex=['theory','practice','test'].indexOf(learningStep),status=E('span','learning-step-caption',learningDone(l)?'✓ '+c.finished:c.step+' '+(stepIndex+1)+' '+c.of+' 3');
 if(learningStep==='test'&&!html&&!learningDone(l)){const remaining=[!state?.theoryRead?t().learnTheory:null,!state?.practicePassed?t().learnPractice:null,!state?.quizPassed?t().learnTest:null,(l.project||l.manualReview)&&!state?.selfReview?(lang==='uk'?'самоперевірка':'self-review'):null].filter(Boolean);status.textContent=(lang==='uk'?'Ще потрібно: ':'Remaining: ')+remaining.join(', ');}
 const nextLesson=module.lessons[index+1];let label=learningStep==='theory'?(!html&&!state?.theoryRead?c.readPractice:c.practice):learningStep==='practice'?c.test:nextLesson?c.next:c.courses;
 footer.append(status,button(label+' →',()=>{if(learningStep==='theory'){if(!html){const s=academyState(l);s.theoryRead=true;completeAcademy(l,s);renderAcademy();}learningStep='practice';arrangeLesson();}else if(learningStep==='practice'){learningStep='test';arrangeLesson();}else if(nextLesson)openLesson(nextLesson.id);else{learningScreen='library';applyLearningLook();}if(learningScreen==='lesson'){const active=academy.course==='HTML'?Q('html-lesson'):academyPanel.querySelector('.course-layout>section');active?.querySelector('h2')?.scrollIntoView({block:'start',behavior:motionPreference.matches?'instant':'smooth'});}},'primary-button'));body.append(footer);footer.hidden=false;
}
const lookBeforePlus=applyLearningLook;applyLearningLook=function(){lookBeforePlus();enhanceLearning();};
// Opening a different HTML lesson must rebuild its content even when the route hash stays the same.
const openBeforePlus=openLesson;openLesson=function(id){if(!lessonCatalog().some(l=>l.id===id))return;openBeforePlus(id);if(id.startsWith('html-'))renderHtmlCourse();const body=academy.course==='HTML'?Q('html-lesson'):academyPanel.querySelector('.course-layout>section'),heading=body?.querySelector('h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true});}};
window.addEventListener('hashchange',()=>{if(location.hash.split('?')[0]==='#learning')applyLearningLook();});
applyLearningLook();
