Object.assign(translations.uk,{folders:'Папки',newFolder:'Нова папка',folderName:'Назва папки',noFolder:'Без папки',allFolders:'Усі папки',pinnedOnly:'Закріплені',quickThought:'Записати думку',thoughtPlaceholder:'Ідея, посилання або короткий запис…',noteTools:'Організація блокнота',projectHub:'Матеріали проєкту',projectTasksOpen:'Відкрити задачі проєкту',projectNoteNew:'Нова нотатка проєкту',linkedProject:'Пов’язаний проєкт',folderRemoved:'Папку видалено. Нотатки залишено.',folderExists:'Така папка вже є.'});
Object.assign(translations.en,{folders:'Folders',newFolder:'New folder',folderName:'Folder name',noFolder:'Unfiled',allFolders:'All folders',pinnedOnly:'Pinned',quickThought:'Capture a thought',thoughtPlaceholder:'An idea, link or quick note…',noteTools:'Organize notebook',projectHub:'Project materials',projectTasksOpen:'Open project tasks',projectNoteNew:'New project note',linkedProject:'Linked project',folderRemoved:'Folder removed. Notes kept.',folderExists:'This folder already exists.'});
function userFolders(){const p=uiPrefs();if(!Array.isArray(p.folders))p.folders=[];p.folders=p.folders.filter(x=>x&&typeof x.id==='string'&&typeof x.name==='string').slice(0,100);return p.folders;}
let chosenFolder='all',pinnedNotesOnly=false;
const folderBar=E('div','folder-bar');folderBar.id='folder-bar';Q('notes-list').before(folderBar);
const folderContent=E('div','utility-content'),folderWindow=utilityWindow('folders-window','folders',folderContent);
function renderFolders(){folderBar.replaceChildren();const filter=E('select');filter.id='custom-folder-filter';filter.setAttribute('aria-label',t().folders);selectOptions(filter,[['all',t().allFolders],['none',t().noFolder],...userFolders().map(f=>[f.id,f.name])],chosenFolder);filter.addEventListener('change',()=>{chosenFolder=filter.value;renderNotesList();});const pin=button('pinnedOnly',()=>{pinnedNotesOnly=!pinnedNotesOnly;renderFolders();renderNotesList();});pin.id='notes-pinned-only';pin.setAttribute('aria-pressed',String(pinnedNotesOnly));folderBar.append(filter,pin,button('folders',()=>{renderFolderManager();folderWindow.open();}));}
function renderFolderManager(){folderContent.replaceChildren();const form=E('form','folder-create-form'),input=labelField(form,'folderName',E('input'));input.id='folder-name';input.maxLength=60;input.required=true;const error=E('p','panel-note');error.setAttribute('role','status');const submit=E('button','primary-button',t().newFolder);submit.type='submit';form.append(submit,error);form.addEventListener('submit',e=>{e.preventDefault();const name=input.value.trim();if(!name)return;if(userFolders().some(f=>f.name.toLocaleLowerCase()===name.toLocaleLowerCase())){error.textContent=t().folderExists;return;}if(userFolders().length>=100)return;userFolders().push({id:crypto.randomUUID(),name});persistExtras();renderFolderManager();renderFolders();renderNoteFolder();});folderContent.append(form);for(const f of userFolders()){const row=E('div','folder-row');row.append(E('strong','',f.name),button('remove',()=>{uiPrefs().folders=userFolders().filter(x=>x.id!==f.id);for(const n of notes)if(n.folderId===f.id)n.folderId='';if(chosenFolder===f.id)chosenFolder='all';persistExtras();persistNotes();renderFolderManager();renderFolders();renderNotes();notice(t().folderRemoved);}));folderContent.append(row);}}
const noteFolderField=E('div','form-field');Q('note-options-window').querySelector('.utility-content').prepend(noteFolderField);
function renderNoteFolder(){noteFolderField.replaceChildren();const n=notes.find(n=>n.id===selectedNote);if(!n)return;const label=E('label','',t().folders),select=E('select');select.id='note-folder-id';label.htmlFor=select.id;selectOptions(select,[['',t().noFolder],...userFolders().map(f=>[f.id,f.name])],n.folderId||'');select.disabled=n.deleted;select.addEventListener('change',()=>{n.folderId=select.value;n.updatedAt=new Date().toISOString();persistNotes();renderNotesList();});noteFolderField.append(label,select);}
const listBeforeFolders=renderNotesList;renderNotesList=function(){const all=notes;try{notes=all.filter(n=>(chosenFolder==='all'||(chosenFolder==='none'?!n.folderId:n.folderId===chosenFolder))&&(!pinnedNotesOnly||n.pinned));listBeforeFolders();}finally{notes=all;}renderFolders();};
const editorBeforeFolders=renderNoteEditor;renderNoteEditor=function(){editorBeforeFolders();renderNoteFolder();renderNoteConnections();};
const thoughtContent=E('form','utility-content'),thoughtWindow=utilityWindow('thought-window','quickThought',thoughtContent),thoughtInput=E('textarea');thoughtInput.id='thought-input';thoughtInput.maxLength=100000;thoughtInput.rows=7;thoughtInput.required=true;thoughtInput.setAttribute('aria-label',t().quickThought);const thoughtSave=E('button','primary-button',t().save);thoughtSave.type='submit';thoughtContent.append(thoughtInput,thoughtSave);thoughtContent.addEventListener('submit',e=>{e.preventDefault();const body=thoughtInput.value.trim();if(!body)return;thoughtWindow.shut();chosenFolder='all';pinnedNotesOnly=false;location.hash='notes';showView();Q('note-template').value='blank';Q('note-new').click();const n=notes.find(n=>n.id===selectedNote);n.title=body.split('\n')[0].slice(0,120);n.body=body;persistNotes();renderNotes();thoughtInput.value='';Q('note-body').focus();});const thoughtButton=button('quickThought',()=>{thoughtInput.placeholder=t().thoughtPlaceholder;thoughtWindow.open();thoughtInput.focus();});thoughtButton.id='quick-thought';thoughtButton.dataset.i18n='quickThought';Q('notes-view').querySelector('.notes-toolbar').append(thoughtButton);
const createBeforeThought=fillCreate;fillCreate=function(){createBeforeThought();createContent.append(button('quickThought',()=>{createWindow.shut();thoughtButton.click();},'create-option'));};fillCreate();
// Secondary notebook controls are available on demand, leaving search and records visible.
const noteTools=E('details','notebook-tools'),noteToolsTitle=E('summary','',t().noteTools);noteToolsTitle.dataset.i18n='noteTools';noteTools.append(noteToolsTitle,Q('notes-folder').closest('.form-field'),Q('notes-sort').closest('.form-field'),Q('notes-trash').closest('.task-filters'));Q('notes-search').closest('.form-field').after(noteTools);const templateTools=E('details','template-tools');templateTools.append(E('summary','',t().noteTemplate),Q('note-template').closest('.form-field'));Q('notes-view').querySelector('.notes-toolbar').append(templateTools);
const connections=E('div','note-connections');Q('note-title').closest('.form-field').after(connections);
function openProjectTasks(id){location.hash='tasks';showView();taskFilter='all';trashMode=false;kanbanMode=false;Q('tasks-search').value='';Q('filter-project').value=id;Q('filter-priority').value='all';renderTasks();Q('all-tasks').scrollIntoView({block:'start'});}
function renderNoteConnections(){connections.replaceChildren();const n=notes.find(n=>n.id===selectedNote);if(!n)return;const project=projects.find(p=>p.id===n.projectId),task=tasks.find(x=>x.id===n.taskId),lesson=getLinkedLesson(n.lessonId||'');if(project)connections.append(button(project.name,()=>{noteWindow.shut();openEntity('projects',project.id);},'secondary-button'));if(task)connections.append(button(taskName(task),()=>{noteWindow.shut();openEntity('tasks',task.id);},'secondary-button'));if(lesson)connections.append(button(lesson.title[document.documentElement.lang],()=>{noteWindow.shut();openLesson(lesson.id);},'secondary-button'));}
const detailBeforeHub=renderProjectDetail;renderProjectDetail=function(){detailBeforeHub();const id=new URLSearchParams(location.hash.split('?')[1]||'').get('project'),project=projects.find(p=>p.id===id);if(!project)return;const host=Q('project-detail'),actions=E('div','project-hub-actions');actions.append(button('projectTasksOpen',()=>{projectDetailsWindow.shut();openProjectTasks(id);}),button('projectNoteNew',()=>{projectDetailsWindow.shut();location.hash='notes';showView();chosenFolder='all';pinnedNotesOnly=false;Q('note-template').value='blank';Q('note-new').click();const n=notes.find(n=>n.id===selectedNote);n.projectId=id;n.title=project.name;persistNotes();renderNotes();}));host.querySelector('h2').after(actions);for(const a of host.querySelectorAll('a[href="#snippets"]')){const old=a.cloneNode(true);a.replaceWith(old);old.addEventListener('click',e=>{e.preventDefault();const s=snippets.find(s=>s.name===old.textContent);if(s){projectDetailsWindow.shut();openEntity('snippets',s.id);}});}for(const b of host.querySelectorAll('.note-list-item'))b.addEventListener('click',()=>{chosenFolder='all';pinnedNotesOnly=false;Q('notes-search').value='';Q('notes-folder').value='all';projectDetailsWindow.shut();renderNotes();});};
const entityBeforeFolderReset=openEntity;openEntity=function(kind,id){if(kind==='notes'){chosenFolder='all';pinnedNotesOnly=false;Q('notes-search').value='';Q('notes-folder').value='all';}for(const d of document.querySelectorAll('dialog[open]'))d.close();entityBeforeFolderReset(kind,id);};
window.addEventListener('languagechange',()=>{renderFolders();renderFolderManager();renderNoteFolder();renderNoteConnections();thoughtSave.textContent=t().save;thoughtInput.setAttribute('aria-label',t().quickThought);templateTools.querySelector('summary').textContent=t().noteTemplate;});renderFolders();renderNotes();
Q('note-new').addEventListener('click',()=>{chosenFolder='all';pinnedNotesOnly=false;},true);
// A short project summary stays visible; linked lists expand only when needed.
const projectBeforeCompact=renderProjectDetail;renderProjectDetail=function(){projectBeforeCompact();const host=Q('project-detail');if(host.hidden)return;for(const heading of [...host.querySelectorAll(':scope > h3')]){const group=E('details','project-section'),summary=E('summary','',heading.textContent);heading.before(group);group.append(summary);let next=heading.nextSibling;heading.remove();while(next&&!(next.nodeType===1&&next.tagName==='H3')){const current=next;next=next.nextSibling;group.append(current);} }};
