Object.assign(translations.uk,{notePreview:'Перегляд Markdown',markdownHelp:'Підтримує заголовки #, списки -, checklist - [ ], цитати >, **жирний текст**, `код` і блоки коду з ```.',exportMarkdown:'Завантажити .md',notesIntro:'Конспекти, ідеї та думки — під рукою.',newNote:'Нова нотатка',noteTemplate:'Шаблон',blankNote:'Порожня',lessonNote:'Конспект',ideaNote:'Ідея',dailyNote:'Звіт за день',bugNote:'Розбір помилки',searchNotes:'Пошук нотаток',recentNotes:'Останні зміни',titleOrder:'За назвою',trash:'Корзина',chooseNote:'Створи нотатку або обери запис зі списку.',noteTitle:'Заголовок',noteTags:'Теги (через кому)',noteBody:'Текст нотатки',exportNote:'Завантажити .txt',restoreNote:'Відновити',pinNote:'Закріпити',unpinNote:'Відкріпити',trashNote:'До корзини',deleteForever:'Видалити назавжди',deleteNoteConfirm:'Назавжди видалити цю нотатку?',untitledNote:'Без назви',emptyNotes:'Нотаток не знайдено.',noteSaved:'Збережено',noteSaveError:'Не вдалося зберегти. Завантаж нотатку як файл перед виходом.',general:'Загальні',study:'Навчання',ideas:'Ідеї',project:'Проєкти',bugs:'Помилки'});
Object.assign(translations.en,{notePreview:'Markdown preview',markdownHelp:'Supports # headings, - lists, - [ ] checklists, > quotes, **bold**, `code`, and fenced code blocks.',exportMarkdown:'Download .md',notesIntro:'Your study notes, ideas, and thoughts in one place.',newNote:'New note',noteTemplate:'Template',blankNote:'Blank',lessonNote:'Study notes',ideaNote:'Idea',dailyNote:'Daily report',bugNote:'Bug analysis',searchNotes:'Search notes',recentNotes:'Recently updated',titleOrder:'Title',trash:'Trash',chooseNote:'Create a note or select one from the list.',noteTitle:'Title',noteTags:'Tags (comma separated)',noteBody:'Note content',exportNote:'Download .txt',restoreNote:'Restore',pinNote:'Pin',unpinNote:'Unpin',trashNote:'Move to trash',deleteForever:'Delete permanently',deleteNoteConfirm:'Permanently delete this note?',untitledNote:'Untitled',emptyNotes:'No notes found.',noteSaved:'Saved',noteSaveError:'Could not save. Download your note before leaving.',general:'General',study:'Learning',ideas:'Ideas',project:'Projects',bugs:'Bugs'});
const noteCategories=['general','study','ideas','project','bugs'];
function validNotes(value){return Array.isArray(value)&&value.length<=10000&&value.every(n=>n&&typeof n.id==='string'&&n.id.length<=100&&typeof n.title==='string'&&n.title.length<=120&&typeof n.body==='string'&&n.body.length<=100000&&noteCategories.includes(n.category)&&typeof n.projectId==='string'&&['taskId','lessonId'].every(k=>n[k]===undefined||typeof n[k]==='string'&&n[k].length<=100)&&Array.isArray(n.tags)&&n.tags.length<=30&&n.tags.every(tag=>typeof tag==='string'&&tag.length<=100)&&typeof n.pinned==='boolean'&&typeof n.deleted==='boolean'&&typeof n.updatedAt==='string'&&Number.isFinite(Date.parse(n.updatedAt)))&&new Set(value.map(n=>n.id)).size===value.length;}
let notes=readData('devspace-notes',[],validNotes),selectedNote=null,showTrash=false,notesSaved=true;
const templates={uk:{blank:'',lesson:'Тема:\n\nЩо я зрозумів:\n\nПриклади:\n\nПитання:\n\nНаступний крок:\n',idea:'Ідея:\n\nЯку проблему вирішує:\n\nДля кого:\n\nПерші кроки:\n',daily:'Що зробив:\n\nЩо вивчив:\n\nЩо завадило:\n\nПлан на завтра:\n',bug:'Проблема:\n\nЯк відтворити:\n\nОчікуваний результат:\n\nПричина:\n\nРішення:\n'}};
templates.en={blank:'',lesson:'Topic:\n\nWhat I learned:\n\nExamples:\n\nQuestions:\n\nNext step:\n',idea:'Idea:\n\nProblem it solves:\n\nAudience:\n\nFirst steps:\n',daily:'Completed:\n\nLearned:\n\nObstacles:\n\nTomorrow:\n',bug:'Problem:\n\nSteps to reproduce:\n\nExpected result:\n\nCause:\n\nSolution:\n'};
function persistNotes(){notesSaved=writeData('devspace-notes',notes);document.querySelector('#note-saved').textContent=t()[notesSaved?'noteSaved':'noteSaveError'];}
function noteOptions(){for(const id of ['notes-folder','note-category']){const select=document.querySelector('#'+id),current=select.value;select.replaceChildren();if(id==='notes-folder'){const option=projectElement('option','',t().filterAll);option.value='all';select.append(option);}for(const key of noteCategories){const option=projectElement('option','',t()[key]);option.value=key;select.append(option);}select.value=current|| (id==='notes-folder'?'all':'general');}const select=document.querySelector('#note-project'),current=select.value;select.replaceChildren();const empty=projectElement('option','',t().noProject);empty.value='';select.append(empty);for(const p of projects){const o=projectElement('option','',p.name);o.value=p.id;select.append(o);}select.value=projects.some(p=>p.id===current)?current:'';}
function renderNotesList(){const query=document.querySelector('#notes-search').value.trim().toLocaleLowerCase(),folder=document.querySelector('#notes-folder').value;const items=notes.filter(n=>n.deleted===showTrash&&(folder==='all'||n.category===folder)&&[n.title,n.body,...n.tags].join(' ').toLocaleLowerCase().includes(query)).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||(document.querySelector('#notes-sort').value==='title'?a.title.localeCompare(b.title):Date.parse(b.updatedAt)-Date.parse(a.updatedAt)));const list=document.querySelector('#notes-list');list.replaceChildren();document.querySelector('#notes-count').textContent=t().searchResults+': '+items.length;document.querySelector('#notes-trash').setAttribute('aria-pressed',String(showTrash));if(!items.length)list.append(projectElement('p','panel-note',t().emptyNotes));for(const n of items){const b=projectElement('button','note-list-item');b.type='button';b.setAttribute('aria-pressed',String(n.id===selectedNote));b.append(projectElement('strong','',(n.pinned?'★ ':'')+(n.title||t().untitledNote)),projectElement('span','',t()[n.category]+' · '+new Intl.DateTimeFormat(document.documentElement.lang==='uk'?'uk-UA':'en-GB',{day:'numeric',month:'short',timeZone:'Europe/Kyiv'}).format(new Date(n.updatedAt))));b.addEventListener('click',()=>{selectedNote=n.id;renderNotes();});list.append(b);}}
function renderNoteEditor(){const n=notes.find(n=>n.id===selectedNote);document.querySelector('#note-empty').hidden=!!n;document.querySelector('#note-fields').hidden=!n;if(!n)return;for(const [field,key] of [['title','title'],['body','body'],['category','category'],['project','projectId'],['tags','tags']]){const input=document.querySelector('#note-'+field);input.value=key==='tags'?n.tags.join(', '):n[key];if(field==='project'&&!projects.some(p=>p.id===n.projectId))input.value='';input.disabled=n.deleted;}renderMarkdown(n.body);document.querySelector('#note-saved').textContent=t()[notesSaved?'noteSaved':'noteSaveError'];document.querySelector('#note-pin').textContent=t()[n.pinned?'unpinNote':'pinNote'];document.querySelector('#note-pin').disabled=n.deleted;document.querySelector('#note-pin').setAttribute('aria-pressed',String(n.pinned));document.querySelector('#note-delete').textContent=t()[n.deleted?'deleteForever':'trashNote'];document.querySelector('#note-restore').hidden=!n.deleted;}
function renderNotes(){noteOptions();renderNotesList();renderNoteEditor();}
document.querySelector('#note-new').addEventListener('click',()=>{const template=document.querySelector('#note-template').value;const n={id:crypto.randomUUID(),title:'',body:templates[document.documentElement.lang][template],category:template==='lesson'?'study':template==='idea'?'ideas':template==='bug'?'bugs':'general',projectId:'',tags:[],pinned:false,deleted:false,updatedAt:new Date().toISOString()};notes.unshift(n);selectedNote=n.id;showTrash=false;document.querySelector('#notes-search').value='';document.querySelector('#notes-folder').value='all';persistNotes();renderNotes();document.querySelector('#note-title').focus();});
for(const field of ['title','body','category','project','tags']){const input=document.querySelector('#note-'+field);input.addEventListener(field==='category'||field==='project'?'change':'input',()=>{const n=notes.find(n=>n.id===selectedNote);if(!n||n.deleted)return;const key=field==='project'?'projectId':field;n[key]=field==='tags'?input.value.split(',').map(s=>s.trim().slice(0,100)).filter(Boolean).slice(0,30):input.value;n.updatedAt=new Date().toISOString();persistNotes();renderNotesList();if(field==='body')renderMarkdown(n.body);});}
for(const id of ['notes-search','notes-folder','notes-sort'])document.querySelector('#'+id).addEventListener(id==='notes-search'?'input':'change',renderNotesList);
document.querySelector('#notes-trash').addEventListener('click',()=>{showTrash=!showTrash;selectedNote=null;renderNotes();});
document.querySelector('#note-pin').addEventListener('click',()=>{const n=notes.find(n=>n.id===selectedNote);if(!n)return;n.pinned=!n.pinned;persistNotes();renderNotes();});
document.querySelector('#note-delete').addEventListener('click',()=>{const n=notes.find(n=>n.id===selectedNote);if(!n)return;if(n.deleted){if(!confirm(t().deleteNoteConfirm))return;notes=notes.filter(item=>item.id!==n.id);}else n.deleted=true;selectedNote=null;persistNotes();renderNotes();});
document.querySelector('#note-restore').addEventListener('click',()=>{const n=notes.find(n=>n.id===selectedNote);if(!n)return;n.deleted=false;n.updatedAt=new Date().toISOString();showTrash=false;persistNotes();renderNotes();});
document.querySelector('#note-export').addEventListener('click',()=>{const n=notes.find(n=>n.id===selectedNote);if(!n)return;const url=URL.createObjectURL(new Blob([(n.title||t().untitledNote)+'\n\n'+n.body],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=(n.title||'kachan-note').replace(/[^\p{L}\p{N}\-_ ]/gu,'').slice(0,80)+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
window.addEventListener('languagechange',renderNotes);window.addEventListener('hashchange',()=>{if(location.hash==='#notes')renderNotes();});setLanguage(document.documentElement.lang);

function renderMarkdown(text){
 const container=document.querySelector('#note-preview');container.replaceChildren();let code=null,list=null;
 function inline(element,text){const pattern=/(\*\*([^*]+)\*\*|`([^`]+)`)/g;let last=0;for(const match of text.matchAll(pattern)){element.append(document.createTextNode(text.slice(last,match.index)));element.append(projectElement(match[2]?'strong':'code','',match[2]||match[3]));last=match.index+match[0].length;}element.append(document.createTextNode(text.slice(last)));}
 for(const line of text.split('\n')){
  if(line.trim().startsWith('```')){if(code)code=null;else{const pre=projectElement('pre','snippet-code');code=projectElement('code','');pre.append(code);container.append(pre);}list=null;continue;}
  if(code){code.append(document.createTextNode(line+'\n'));continue;}
  const heading=line.match(/^(#{1,6})\s+(.+)$/),item=line.match(/^[-*]\s+(.+)$/);
  if(item){if(!list){list=document.createElement('ul');container.append(list);}const li=document.createElement('li');const check=item[1].match(/^\[([ xX])\]\s*(.*)$/);if(check){const box=document.createElement('input');box.type='checkbox';box.disabled=true;box.checked=check[1].toLowerCase()==='x';li.append(box,document.createTextNode(' '));inline(li,check[2]);}else inline(li,item[1]);list.append(li);continue;}
  list=null;if(!line.trim())continue;const element=document.createElement(heading?'h'+heading[1].length:line.startsWith('> ')?'blockquote':'p');inline(element,heading?heading[2]:line.startsWith('> ')?line.slice(2):line);container.append(element);
 }
}
document.querySelector('#note-export-md').addEventListener('click',()=>{const n=notes.find(n=>n.id===selectedNote);if(!n)return;const url=URL.createObjectURL(new Blob(['# '+(n.title||t().untitledNote)+'\n\n'+n.body],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=(n.title||'kachan-note').replace(/[^\p{L}\p{N}\-_ ]/gu,'').slice(0,80)+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
