Object.assign(translations.uk,{dashboardLayout:'Мій Dashboard',dashboardLayoutInfo:'Обери потрібні блоки й зміни їх порядок. Щонайменше один блок залишається видимим.',moveUp:'Вище',moveDown:'Нижче',restoreLayout:'Відновити порядок',noteTask:'Пов’язана задача',noteLesson:'Пов’язаний урок',openLinked:'Відкрити',missingLink:'Пов’язаний запис видалено',taskNotes:'Нотатки задачі',makeTaskNote:'Створити нотатку задачі',reviewCalendar:'Календар повторень',monthBack:'Попередній місяць',monthNext:'Наступний місяць',calendarToday:'Поточний місяць',calendarEmpty:'На цей день повторень немає.',reviewLesson:'Урок картки',reviewExisting:'Цей урок уже є у повторенні',storageTitle:'Збереження даних',storageIndexed:'Дані зберігаються в розширеному сховищі браузера.',storageFallback:'Розширене сховище недоступне. Використовується LocalStorage з меншим лімітом.',storageSaving:'Зберігаємо…',storageSaved:'Усі зміни збережено',storageError:'Не вдалося записати зміни. Завантаж JSON-копію перед закриттям сторінки.',storageConflict:'Дані змінились в іншій вкладці. Збережи свої чернетки файлом і онови сторінку.',storageRetry:'Повторити запис',storageUsage:'Використано сховище',persistentStorage:'Захистити локальні дані від автоматичного очищення',persistentGranted:'Браузер надав постійне сховище',persistentDenied:'Браузер не надав постійне сховище; зберігай JSON-копії',pausedCloud:'Локальні зміни зберігаються у браузері. Хмарні копії — у вкладці «Дані».',lessonReviewAdded:'Урок додано до повторення',layoutToday:'Сьогодні',layoutContinue:'Продовжити навчання',layoutGoals:'Цілі',layoutStats:'Статистика',layoutProjects:'Проєкти',layoutTasks:'Задачі',layoutLearning:'Прогрес навчання',layoutNotes:'Останні нотатки',layoutActivity:'Активність',layoutChart:'Графік за тиждень',layoutFocus:'Фокус і картки',layoutCalendar:'Календар повторень'});
Object.assign(translations.en,{dashboardLayout:'My Dashboard',dashboardLayoutInfo:'Choose visible blocks and their order. At least one block stays visible.',moveUp:'Move up',moveDown:'Move down',restoreLayout:'Restore order',noteTask:'Linked task',noteLesson:'Linked lesson',openLinked:'Open',missingLink:'Linked record was deleted',taskNotes:'Task notes',makeTaskNote:'Create task note',reviewCalendar:'Review calendar',monthBack:'Previous month',monthNext:'Next month',calendarToday:'Current month',calendarEmpty:'No reviews on this date.',reviewLesson:'Card lesson',reviewExisting:'This lesson is already scheduled for review',storageTitle:'Data storage',storageIndexed:'Data is saved in the browser’s larger local storage.',storageFallback:'Larger storage is unavailable. LocalStorage is used with a smaller limit.',storageSaving:'Saving…',storageSaved:'All changes saved',storageError:'Changes could not be saved. Download a JSON backup before closing.',storageConflict:'Another tab updated the data. Download your drafts and reload.',storageRetry:'Retry saving',storageUsage:'Storage used',persistentStorage:'Protect local data from automatic eviction',persistentGranted:'Browser granted persistent storage',persistentDenied:'Browser did not grant persistent storage; keep JSON backups',pausedCloud:'Changes save locally. Cloud backups are available in the Data tab.',lessonReviewAdded:'Lesson added to review',layoutToday:'Today',layoutContinue:'Continue learning',layoutGoals:'Goals',layoutStats:'Statistics',layoutProjects:'Projects',layoutTasks:'Tasks',layoutLearning:'Learning progress',layoutNotes:'Recent notes',layoutActivity:'Activity',layoutChart:'Weekly chart',layoutFocus:'Focus and cards',layoutCalendar:'Review calendar'});
const blockDefinitions=[['today','layoutToday'],['continue','layoutContinue'],['goals','layoutGoals'],['stats','layoutStats'],['projects','layoutProjects'],['tasks','layoutTasks'],['learning','layoutLearning'],['notes','layoutNotes'],['activity','layoutActivity'],['chart','layoutChart'],['focus','layoutFocus'],['calendar','layoutCalendar']];
function personalizationDefault(){return {version:1,blocks:blockDefinitions.map(([id])=>({id,visible:true})),reviewLinks:{}};}
function validPersonalization(p){return p&&p.version===1&&Array.isArray(p.blocks)&&p.blocks.length===blockDefinitions.length&&new Set(p.blocks.map(b=>b?.id)).size===blockDefinitions.length&&p.blocks.every(b=>b&&blockDefinitions.some(([id])=>id===b.id)&&typeof b.visible==='boolean')&&p.blocks.some(b=>b.visible)&&p.reviewLinks&&typeof p.reviewLinks==='object'&&!Array.isArray(p.reviewLinks)&&Object.entries(p.reviewLinks).length<=10000&&Object.entries(p.reviewLinks).every(([id,lesson])=>typeof id==='string'&&id.length<=100&&typeof lesson==='string'&&lesson.length<=100);}
let personalization=readData('devspace-personalization',personalizationDefault(),validPersonalization);
function savePersonalization(){writeData('devspace-personalization',personalization);}
function getLinkedLesson(id){return lessonCatalog().find(l=>l.id===id)||lessonCatalog().find(l=>l.id==='html-'+id);}
function makeLinkedNote({taskId='',lessonId=''}={}){Q('note-template').value=lessonId?'lesson':'blank';Q('note-new').click();const n=notes.find(n=>n.id===selectedNote);n.taskId=taskId;n.lessonId=lessonId;const task=tasks.find(t=>t.id===taskId),l=getLinkedLesson(lessonId);if(task){n.title=taskName(task);n.projectId=task.projectId||'';}if(l)n.title=l.title[document.documentElement.lang];n.updatedAt=new Date().toISOString();persistNotes();location.hash='notes';showView();renderNotes();Q('note-title').focus();}
function addLessonReview(id){const l=getLinkedLesson(id);if(!l)return;const existing=extras.cards.find(c=>personalization.reviewLinks[c.id]===l.id);if(existing){notice(t().reviewExisting);return;}let question,answer;if(l.course==='HTML'){question=l.title[document.documentElement.lang];answer=htmlLessons.find(x=>'html-'+x.id===l.id)?.theory[document.documentElement.lang].join('\n')||'';}else{question=l.quiz.question[document.documentElement.lang];answer=l.quiz.options[l.quiz.answer][document.documentElement.lang]+' — '+l.quiz.explanation[document.documentElement.lang];}const card={id:crypto.randomUUID(),question:question.slice(0,500),answer:answer.slice(0,2000),due:todayInKyiv(),interval:0};extras.cards.push(card);personalization.reviewLinks[card.id]=l.id;persistExtras();savePersonalization();renderFocus();renderReviewCalendar();notice(t().lessonReviewAdded);}
const noteLinks=E('div','note-metadata');Q('note-body').closest('.form-field').before(noteLinks);
function renderNoteLinks(){noteLinks.replaceChildren();const n=notes.find(n=>n.id===selectedNote);if(!n)return;for(const [key,label,items] of [['taskId','noteTask',tasks.map(x=>[x.id,taskName(x)])],['lessonId','noteLesson',lessonCatalog().map(l=>[l.id,l.course+' · '+l.title[document.documentElement.lang]])]]){const select=labelField(noteLinks,label,E('select'));select.id='note-'+key;select.previousElementSibling.htmlFor=select.id;selectOptions(select,[['',t().noLink],...items],n[key]||'');select.disabled=n.deleted;if(n[key]&&!items.some(([id])=>id===n[key])){const missing=E('option','',t().missingLink);missing.value=n[key];select.append(missing);select.value=n[key];}select.addEventListener('change',()=>{n[key]=select.value;n.updatedAt=new Date().toISOString();persistNotes();renderNoteLinks();});if(n[key]&&items.some(([id])=>id===n[key]))noteLinks.append(button('openLinked',()=>key==='taskId'?openEntity('tasks',n[key]):openLesson(n[key])));}}
const linkedRenderNote=renderNoteEditor;renderNoteEditor=function(){linkedRenderNote();renderNoteLinks();};window.addEventListener('languagechange',renderNoteLinks);
function appendTaskNotes(shown){[...Q('all-tasks').children].forEach((li,i)=>{const task=shown[i];if(!task)return;li.dataset.taskId=task.id;const detail=E('details','task-linked-notes');detail.append(E('summary','',t().taskNotes));for(const n of notes.filter(n=>!n.deleted&&n.taskId===task.id))detail.append(button(n.title||t().untitledNote,()=>openEntity('notes',n.id)));detail.append(button('makeTaskNote',()=>makeLinkedNote({taskId:task.id})));li.append(detail);});}
const baseWorkspaceTasks=renderWorkspaceTasks;renderWorkspaceTasks=function(shown){baseWorkspaceTasks(shown);appendTaskNotes(shown);};
// Reuse existing HTML lessons with the new notes and review connections.
const linkedHTMLRender=renderHtmlCourse;renderHtmlCourse=function(){linkedHTMLRender();const controls=E('div','editor-actions');controls.append(button('makeLessonNote',()=>makeLinkedNote({lessonId:'html-'+htmlCourse.selected})),button('addReview',()=>addLessonReview('html-'+htmlCourse.selected)));Q('html-lesson').append(controls);};
let calendarMonth=todayInKyiv().slice(0,7),calendarDaySelected=todayInKyiv();
const calendarPanel=E('section','dashboard-panel review-calendar-panel');calendarPanel.id='review-calendar';Q('dashboard-view').append(calendarPanel);
function renderReviewCalendar(){calendarPanel.replaceChildren();calendarPanel.append(E('h2','',t().reviewCalendar));const [year,month]=calendarMonth.split('-').map(Number),first=new Date(Date.UTC(year,month-1,1,12)),offset=(first.getUTCDay()+6)%7,start=new Date(first);start.setUTCDate(1-offset);const controls=E('div','calendar-controls');for(const [key,delta] of [['monthBack',-1],['monthNext',1]])controls.append(button(key,()=>{const d=new Date(Date.UTC(year,month-1+delta,1,12));calendarMonth=d.toISOString().slice(0,7);renderReviewCalendar();}));controls.append(E('strong','',new Intl.DateTimeFormat(document.documentElement.lang==='uk'?'uk-UA':'en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(first)),button('calendarToday',()=>{calendarMonth=todayInKyiv().slice(0,7);calendarDaySelected=todayInKyiv();renderReviewCalendar();}));calendarPanel.append(controls);const grid=E('div','review-calendar-grid');for(let i=0;i<7;i++){const d=new Date(Date.UTC(2024,0,1+i,12));grid.append(E('span','calendar-weekday',new Intl.DateTimeFormat(document.documentElement.lang,{weekday:'short',timeZone:'UTC'}).format(d)));}for(let i=0;i<42;i++){const d=new Date(start);d.setUTCDate(start.getUTCDate()+i);const day=d.toISOString().slice(0,10),count=extras.cards.filter(c=>c.due===day).length;const b=button(String(d.getUTCDate()),()=>{calendarDaySelected=day;renderReviewCalendar();});b.className='calendar-day'+(day.slice(0,7)!==calendarMonth?' outside-month':'');b.setAttribute('aria-label',day+' · '+count+' '+t().cards);b.setAttribute('aria-pressed',String(day===calendarDaySelected));if(day===todayInKyiv())b.setAttribute('aria-current','date');if(count)b.append(E('span','calendar-count',String(count)));grid.append(b);}calendarPanel.append(grid,E('h3','',calendarDaySelected));const due=extras.cards.filter(c=>c.due===calendarDaySelected);if(!due.length)calendarPanel.append(E('p','panel-note',t().calendarEmpty));for(const c of due){const details=E('details','review-card');details.append(E('summary','',c.question),E('p','',c.answer));const l=getLinkedLesson(personalization.reviewLinks[c.id]||'');if(l)details.append(button(l.title[document.documentElement.lang],()=>openLesson(l.id)));calendarPanel.append(details);}}
const linkedFocusRender=renderFocus;renderFocus=function(){linkedFocusRender();const shown=extras.cards.filter(c=>reviewAll||c.due<=todayInKyiv());[...focusPanel.querySelectorAll('.review-card')].forEach((row,i)=>{const c=shown[i];if(!c)return;const select=labelField(row,'reviewLesson',E('select'));selectOptions(select,[['',t().noLink],...lessonCatalog().map(l=>[l.id,l.course+' · '+l.title[document.documentElement.lang]])],personalization.reviewLinks[c.id]||'');select.addEventListener('change',()=>{personalization.reviewLinks[c.id]=select.value;savePersonalization();});const l=getLinkedLesson(personalization.reviewLinks[c.id]||'');if(l)row.append(button(l.title[document.documentElement.lang],()=>openLesson(l.id)));});renderReviewCalendar();};
const dashboard=Q('dashboard-view'),dashboardBlocks=new Map();
function claimBlock(id,element,wide=false){if(!element)return;element.dataset.dashboardBlock=id;element.classList.add('dashboard-block');if(wide)element.classList.add('dashboard-wide');dashboardBlocks.set(id,element);}
claimBlock('today',dashboard.querySelector('.today-panel'),true);claimBlock('stats',dashboard.querySelector('.stats-grid'),true);claimBlock('projects',dashboard.querySelector('.projects-section'),true);claimBlock('chart',dashboard.querySelector('.activity-chart-panel'),true);claimBlock('focus',focusPanel,true);claimBlock('calendar',calendarPanel,true);
for(const [selector,ids] of [['.daily-grid',['continue','goals']],['.dashboard-columns',['tasks','learning']]]){const group=dashboard.querySelector(selector);for(const [i,el] of [...group.children].entries()){claimBlock(ids[i],el);dashboard.insertBefore(el,group);}group.remove();}const recent=dashboard.querySelector('.daily-grid');for(const [i,el] of [...recent.children].entries()){claimBlock(['notes','activity'][i],el);dashboard.insertBefore(el,recent);}recent.remove();dashboard.querySelector('.page-heading').classList.add('dashboard-wide');dashboard.querySelector('.daily-actions').classList.add('dashboard-wide');
const layoutPanel=E('section','dashboard-panel productivity-panel');layoutPanel.id='dashboard-settings';Q('settings-form').after(layoutPanel);
function applyDashboardLayout(){for(const block of personalization.blocks){const element=dashboardBlocks.get(block.id);element.hidden=!block.visible;dashboard.append(element);}}
function renderLayoutSettings(){layoutPanel.replaceChildren();layoutPanel.append(E('h2','',t().dashboardLayout),E('p','panel-note',t().dashboardLayoutInfo));for(const [i,block] of personalization.blocks.entries()){const row=E('div','layout-setting-row');const checkbox=labelField(row,blockDefinitions.find(([id])=>id===block.id)[1],E('input'));checkbox.type='checkbox';checkbox.checked=block.visible;checkbox.setAttribute('data-layout-block',block.id);checkbox.addEventListener('change',()=>{if(!checkbox.checked&&personalization.blocks.filter(b=>b.visible).length===1){checkbox.checked=true;return;}block.visible=checkbox.checked;savePersonalization();applyDashboardLayout();});for(const [key,delta] of [['moveUp',-1],['moveDown',1]]){const b=button(key,()=>{[personalization.blocks[i],personalization.blocks[i+delta]]=[personalization.blocks[i+delta],personalization.blocks[i]];savePersonalization();applyDashboardLayout();renderLayoutSettings();});b.disabled=i+delta<0||i+delta>=personalization.blocks.length;b.setAttribute('aria-label',t()[key]+': '+t()[blockDefinitions.find(([id])=>id===block.id)[1]]);row.append(b);}layoutPanel.append(row);}layoutPanel.append(button('restoreLayout',()=>{personalization.blocks=personalizationDefault().blocks;savePersonalization();applyDashboardLayout();renderLayoutSettings();}));}
const storagePanel=E('section','dashboard-panel productivity-panel');Q('settings-view').append(storagePanel);const storageStatus=E('span','storage-status');storageStatus.id='storage-status';storageStatus.setAttribute('role','status');document.querySelector('.topbar-actions').append(storageStatus);
function updateStorageStatus(){const key=kachanStorage.external?'storageConflict':kachanStorage.error?'storageError':kachanStorage.dirty.size||kachanStorage.pending?'storageSaving':'storageSaved';storageStatus.textContent=t()[key];storageStatus.classList.toggle('storage-problem',!!kachanStorage.error||kachanStorage.external);}
function renderStorageSettings(){storagePanel.replaceChildren();storagePanel.append(E('h2','',t().storageTitle),E('p','panel-note',t()[kachanStorage.mode==='indexeddb'?'storageIndexed':'storageFallback']),E('p','panel-note',t().pausedCloud),button('storageRetry',async()=>{try{await kachanStorage.flush();notice(t().storageSaved);}catch{notice(t().storageError);}}),button('persistentStorage',async()=>{const granted=await navigator.storage?.persist?.();notice(t()[granted?'persistentGranted':'persistentDenied']);}));kachanStorage.estimate().then(info=>{if(info)storagePanel.append(E('p','panel-note',t().storageUsage+': '+(info.usage/1024/1024).toFixed(1)+' MB / '+(info.quota/1024/1024).toFixed(0)+' MB'));});}
window.addEventListener('kachan-storage-status',updateStorageStatus);window.addEventListener('languagechange',()=>{renderLayoutSettings();renderReviewCalendar();renderStorageSettings();updateStorageStatus();});window.addEventListener('hashchange',()=>{if(location.hash==='#dashboard')renderReviewCalendar();});
// Extend global search with actual card content.
const learningSearchItems=searchItems;searchItems=function(){return [...learningSearchItems(),...extras.cards.map(c=>({name:c.question,body:c.answer,action:()=>{location.hash='dashboard';showView();reviewAll=true;renderFocus();focusPanel.scrollIntoView();}}))];};
const legacyLessonName=lessonName;lessonName=function(id){return getLinkedLesson(id)?.title[document.documentElement.lang]||legacyLessonName(id);};
renderNoteLinks();renderTasks();renderHtmlCourse();renderFocus();renderReviewCalendar();renderLayoutSettings();applyDashboardLayout();renderStorageSettings();updateStorageStatus();
// Daily resume follows the current module as well as the original HTML course.
const resumeButton=Q('continue-html').cloneNode(true);Q('continue-html').replaceWith(resumeButton);
resumeButton.addEventListener('click',()=>{if(resumeButton.dataset.academyLesson)openLesson(resumeButton.dataset.academyLesson);else openLesson('html-'+resumeButton.dataset.lesson);});
const academyDailyRender=renderDailyDashboard;
renderDailyDashboard=function(){academyDailyRender();const eyebrow=resumeButton.parentElement.querySelector('.eyebrow');delete resumeButton.dataset.academyLesson;if(academy.course!=='HTML'){const module=academyCourses.find(c=>c.id===academy.course),current=module.lessons.find(l=>l.id===academy.selected&&!academy.states[l.id]?.completed)||module.lessons.find(l=>!academy.states[l.id]?.completed)||module.lessons[module.lessons.length-1];Q('continue-lesson').textContent=current.title[document.documentElement.lang];resumeButton.dataset.academyLesson=current.id;eyebrow.textContent=current.course;}else eyebrow.textContent='HTML';};
renderDailyDashboard();
function refreshAccessibleNames(){Q('workspace-navigation').setAttribute('aria-label',document.documentElement.lang==='uk'?'Основна навігація':'Main navigation');document.querySelector('.language-switch').setAttribute('aria-label',document.documentElement.lang==='uk'?'Мова сайту':'Site language');Q('bulk-project').setAttribute('aria-label',t().taskProject);Q('bulk-priority').setAttribute('aria-label',t().priority);document.querySelector('.skip-link').textContent=document.documentElement.lang==='uk'?'Перейти до вмісту':'Skip to content';}
window.addEventListener('languagechange',refreshAccessibleNames);refreshAccessibleNames();
