// Keep the existing forms and their validation; only change how they are presented.
const editorWindows=new Map();
function createEditorWindow(kind,form,field){
 const dialog=E('dialog','editor-window'),header=E('header','editor-window-header'),heading=E('h2');heading.id=kind+'-window-title';
 const close=button('close',()=>dialog.close());close.className='window-close';close.textContent='×';
 header.append(heading,close);dialog.append(header,form);dialog.setAttribute('aria-labelledby',heading.id);document.body.append(dialog);
 const state={dialog,heading,field,previous:null};editorWindows.set(kind,state);
 dialog.addEventListener('close',()=>{document.body.classList.toggle('editor-window-open',[...editorWindows.values()].some(s=>s.dialog.open));if(state.previous?.isConnected)state.previous.focus();});
 dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
 return state;
}
function openEditorWindow(kind){const state=editorWindows.get(kind);if(!state||state.dialog.open)return;state.previous=document.activeElement;updateWindowLabels();state.dialog.showModal();document.body.classList.add('editor-window-open');Q(state.field).focus();}
function updateWindowLabels(){for(const [kind,state] of editorWindows){state.heading.textContent=t()[kind==='task'?(editingTaskId?'editTask':'newTask'):(editingProjectId?'editProject':'newProject')];state.dialog.querySelector('.window-close').setAttribute('aria-label',t().close);}taskCreate.textContent='+ '+t().newTask;projectCreate.textContent='+ '+t().newProject;}
const taskCreate=button('newTask',()=>{resetTaskForm();openEditorWindow('task');},'primary-button');taskCreate.id='open-task-window';
const taskToolbar=E('div','view-toolbar');taskToolbar.append(taskCreate);Q('task-form').before(taskToolbar);createEditorWindow('task',Q('task-form'),'task-input');
const projectCreate=button('newProject',()=>{resetProjectForm();Q('project-editor').open=true;openEditorWindow('project');},'primary-button');projectCreate.id='open-project-window';
const projectToolbar=E('div','view-toolbar');projectToolbar.append(projectCreate);Q('project-editor').before(projectToolbar);createEditorWindow('project',Q('project-form'),'project-name');Q('project-editor').hidden=true;
new MutationObserver(()=>{if(Q('project-editor').open)openEditorWindow('project');else editorWindows.get('project').dialog.close();}).observe(Q('project-editor'),{attributes:true,attributeFilter:['open']});
const taskResetBeforeWindow=resetTaskForm;resetTaskForm=function(){taskResetBeforeWindow();editorWindows.get('task').dialog.close();};
Q('quick-task').addEventListener('click',()=>openEditorWindow('task'));
Q('quick-project').addEventListener('click',()=>openEditorWindow('project'));
Q('cancel-task-edit').addEventListener('click',()=>editorWindows.get('task').dialog.close());
document.addEventListener('click',e=>{if(e.target.closest('.task-edit')){openEditorWindow('task');queueMicrotask(updateWindowLabels);}},true);
window.addEventListener('languagechange',updateWindowLabels);
window.addEventListener('hashchange',()=>{const route=location.hash.slice(1).split('?')[0];for(const [kind,state] of editorWindows)if(state.dialog.open&&route!==(kind==='task'?'tasks':'projects'))state.dialog.close();});
// Animate newly visible routes, rather than every render of a timer or a task.
let animatedRoute='';const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
function animateRoute(){const route=(location.hash.slice(1)||'dashboard').split('?')[0];if(route===animatedRoute)return;animatedRoute=route;const view=Q(route+'-view');if(!view||motionPreference.matches)return;playMotion(view,[{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:300});[...view.children].slice(0,12).forEach((el,index)=>{if(!el.hidden)playMotion(el,[{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,delay:Math.min(index*40,240)});});}
window.addEventListener('hashchange',animateRoute);window.addEventListener('kachan-ready',animateRoute);updateWindowLabels();
const activeMotions=new Set(),revealedCards=new WeakSet();
function playMotion(element,frames,options={}){if(motionPreference.matches||!element.isConnected)return;const animation=element.animate(frames,{easing:'cubic-bezier(.2,.8,.2,1)',...options});activeMotions.add(animation);animation.finished.catch(()=>{}).finally(()=>activeMotions.delete(animation));return animation;}
const cardRevealObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting||entry.target.closest('[hidden]'))continue;cardRevealObserver.unobserve(entry.target);if(revealedCards.has(entry.target))continue;revealedCards.add(entry.target);playMotion(entry.target,[{opacity:.25,transform:'translateY(20px)'},{opacity:1,transform:'translateY(0)'}],{duration:500});}},{threshold:.08});
function observeCards(root=document){for(const el of root.querySelectorAll('.project-card,.resource-card,.stat-card,.note-list-item'))if(!revealedCards.has(el))cardRevealObserver.observe(el);}
observeCards();const motionTreeObserver=new MutationObserver(records=>{for(const record of records){for(const removed of record.removedNodes)if(removed.nodeType===1){cardRevealObserver.unobserve(removed);removed.querySelectorAll('.project-card,.resource-card,.stat-card,.note-list-item').forEach(el=>cardRevealObserver.unobserve(el));}for(const added of record.addedNodes)if(added.nodeType===1){if(added.matches('.project-card,.resource-card,.stat-card,.note-list-item'))cardRevealObserver.observe(added);observeCards(added);}}});motionTreeObserver.observe(Q('main-content'),{childList:true,subtree:true});
document.addEventListener('toggle',event=>{const detail=event.target;if(!(detail instanceof HTMLDetailsElement)||!detail.open||detail.hidden)return;for(const child of detail.children)if(child.tagName!=='SUMMARY')playMotion(child,[{opacity:0,transform:'translateY(-6px)'},{opacity:1,transform:'translateY(0)'}],{duration:240});},true);
document.addEventListener('pointerdown',event=>{const b=event.target.closest('button.primary-button,button.secondary-button,.nav-item');if(!b||b.disabled||motionPreference.matches||event.button!==0)return;const rect=b.getBoundingClientRect(),ripple=E('span','click-ripple'),size=Math.max(rect.width,rect.height)*2;ripple.style.width=ripple.style.height=size+'px';ripple.style.left=(event.clientX-rect.left-size/2)+'px';ripple.style.top=(event.clientY-rect.top-size/2)+'px';ripple.setAttribute('aria-hidden','true');b.append(ripple);const animation=playMotion(ripple,[{transform:'scale(0)',opacity:.2},{transform:'scale(1)',opacity:0}],{duration:450});if(animation)animation.finished.catch(()=>{}).finally(()=>ripple.remove());else ripple.remove();});
document.addEventListener('change',event=>{const checkbox=event.target;if(!checkbox.matches('.task-row input[type=checkbox]')||!checkbox.checked)return;const row=checkbox.closest('li'),id=row?.dataset.taskId;queueMicrotask(()=>{const replacement=id?document.querySelector('[data-task-id="'+CSS.escape(id)+'"]'):null;if(replacement){playMotion(replacement,[{background:'var(--accent-soft)'},{background:'transparent'}],{duration:650});const check=replacement.querySelector('.task-row input');if(check)playMotion(check,[{transform:'scale(1)'},{transform:'scale(1.3)'},{transform:'scale(1)'}],{duration:300});}});},true);
motionPreference.addEventListener('change',()=>{if(motionPreference.matches){for(const animation of activeMotions)animation.cancel();document.querySelectorAll('.click-ripple').forEach(el=>el.remove());}});
