/* Core navigation. Existing editors and stored records are reused in their new homes. */
const focusCopy={uk:{primary:'Основне',extra:'Додатково',title:'Знайди. Навчись. Створи.',intro:'Корисні матеріали, зрозумілі уроки та інструменти для розробки.',resources:'Добірки документації, сервісів і натхнення.',learning:'Уроки, практика та власна бібліотека коду.',tools:'Експерименти й утиліти для щоденної роботи.',courses:'Курси та практика',library:'Бібліотека коду',overview:'Усі проєкти',scope:'Проєкт',all:'Усі проєкти',unassigned:'Без проєкту',json:'JSON-форматер',text:'Текст та URL',grid:'CSS-сітка',input:'Вхідні дані',output:'Результат',format:'Форматувати',minify:'Стиснути',encode:'Кодувати URL',decode:'Декодувати URL',upper:'Великі літери',lower:'Малі літери',trim:'Прибрати зайві пробіли',columns:'Колонки',gap:'Проміжок',copy:'Копіювати',valid:'Коректний JSON',invalid:'Помилка: ',back:'← Усі інструменти',choose:'Обери інструмент',projectHint:'Задачі та нотатки зібрані тут. Обери проєкт або відкрий записи без проєкту.'},en:{primary:'Core',extra:'Additional',title:'Discover. Learn. Build.',intro:'Useful resources, clear lessons and tools for development.',resources:'Documentation, services and inspiration in one place.',learning:'Lessons, practice and your personal code library.',tools:'Experiments and utilities for everyday development.',courses:'Courses & practice',library:'Code library',overview:'All projects',scope:'Project',all:'All projects',unassigned:'Without a project',json:'JSON formatter',text:'Text & URL',grid:'CSS grid',input:'Input',output:'Result',format:'Format',minify:'Minify',encode:'Encode URL',decode:'Decode URL',upper:'Uppercase',lower:'Lowercase',trim:'Trim whitespace',columns:'Columns',gap:'Gap',copy:'Copy',valid:'Valid JSON',invalid:'Error: ',back:'← All tools',choose:'Choose a tool',projectHint:'Tasks and notes live here. Select a project or open unassigned records.'}};
const fc=()=>focusCopy[document.documentElement.lang];
Object.assign(translations.uk,{jsonTool:focusCopy.uk.json,textTool:focusCopy.uk.text,gridTool:focusCopy.uk.grid});
Object.assign(translations.en,{jsonTool:focusCopy.en.json,textTool:focusCopy.en.text,gridTool:focusCopy.en.grid});
Object.assign(purposeText,{json:['Перевіряй JSON, додавай відступи або стискай його для передачі. Обробка відбувається у браузері; помилки показуються під кнопками.','Validate JSON, format it with indentation or minify it. Processing stays in your browser; errors appear below the buttons.'],text:['Кодуй і декодуй частини URL, змінюй регістр та прибирай зайві пробіли. Результат можна скопіювати.','Encode or decode URL components, change case and clean up whitespace. Copy the result when ready.'],grid:['Обери кількість колонок і проміжок. Прев’ю змінюється одразу; скопіюй CSS із мобільним правилом для свого проєкту.','Choose columns and gap, inspect the live preview and copy CSS with a mobile rule for your project.']});
optionalMenuRoutes.splice(0,optionalMenuRoutes.length,'projects');
const focusedNav=Q('workspace-navigation');
for(const route of ['tasks','notes','snippets'])focusedNav.querySelector(`[data-view-link="${route}"]`)?.remove();
for(const route of ['dashboard','resources','learning','tools','projects'])focusedNav.append(focusedNav.querySelector(`[data-view-link="${route}"]`));
const coreLabel=E('p','focus-nav-label'),extraLabel=E('p','focus-nav-label');focusedNav.querySelector('[data-view-link=resources]').before(coreLabel);focusedNav.querySelector('[data-view-link=projects]').before(extraLabel);
const projectWorkspace=E('div','nested-workspace');projectWorkspace.id='project-workspace';Q('projects-view').append(projectWorkspace);projectWorkspace.append(Q('tasks-view'),Q('notes-view'));
Q('learning-view').append(Q('snippets-view'));
for(const id of ['tasks-view','notes-view','snippets-view']){const view=Q(id),heading=view.querySelector('.page-heading'),actions=heading?.querySelector('.view-header-actions');if(actions){actions.classList.add('nested-actions');heading.after(actions);}}
let projectScope='all';
function focusNoteMatches(note){return projectScope==='all'||(projectScope==='__none'?!note.projectId:note.projectId===projectScope);}
function focusedRoute(){const [route,query='']=location.hash.slice(1).split('?');return {route:route||'dashboard',params:new URLSearchParams(query)};}
function workspaceRoute(tab,scope=projectScope){return 'projects?tab='+tab+'&scope='+encodeURIComponent(scope);}
function focusDestination(route){return route==='snippets'?'learning?tab=code':['tasks','notes'].includes(route)?workspaceRoute(route):route;}
function focusedTabs(id,items,selected,action){return compositionTabs(id,items,selected,action);}
function refreshFocusControls(){
 coreLabel.textContent=fc().primary;extraLabel.textContent=fc().extra;
 const {route,params}=focusedRoute(),tab=params.get('tab')||'overview';
 Q('project-focus-tabs')?.remove();const tabs=focusedTabs('project-focus-tabs',[['overview',fc().overview],['tasks',t().tasks],['notes',t().notes]],tab,id=>{location.hash=id==='overview'?'projects':workspaceRoute(id);});Q('projects-view').querySelector('.page-heading').after(tabs);
 Q('project-scope-bar')?.remove();const scope=E('div','project-scope-bar');scope.id='project-scope-bar';scope.hidden=route!=='projects'||tab==='overview';const label=E('label','',fc().scope),select=E('select');select.id='project-context';label.htmlFor=select.id;
 for(const [id,name] of [['all',fc().all],['__none',fc().unassigned],...projects.map(p=>[p.id,p.name])]){const o=E('option','',name);o.value=id;select.append(o);}select.value=projectScope;select.addEventListener('change',()=>{location.hash=workspaceRoute(tab,select.value);});scope.append(label,select,E('p','panel-note',fc().projectHint));tabs.after(scope);
 Q('learning-focus-tabs')?.remove();const lt=focusedTabs('learning-focus-tabs',[['courses',fc().courses],['code',fc().library]],params.get('tab')==='code'?'code':'courses',id=>{location.hash=id==='code'?'learning?tab=code':'learning';});Q('learning-view').querySelector('.page-heading').after(lt);
}
const focusViewBefore=showView;const projectOriginalHidden=new Map([...Q('projects-view').children].map(child=>[child,child.hidden]));
showView=function(){
 let {route,params}=focusedRoute();
 if(['tasks','notes','snippets'].includes(route)){const destination=route==='snippets'?'learning?tab=code':workspaceRoute(route);history.replaceState(null,'','#'+destination);({route,params}=focusedRoute());}
 projectScope=params.get('scope')||projectScope;if(projectScope!=='all'&&projectScope!=='__none'&&!projects.some(p=>p.id===projectScope))projectScope='__none';
 focusViewBefore();refreshFocusControls();
 const tab=params.get('tab');
 if(route==='projects'){
  Q('projects-view').dataset.projectTab=tab||'overview';
  for(const child of [...Q('projects-view').children])if(!['project-focus-tabs','project-scope-bar','project-workspace','project-detail','all-projects'].includes(child.id)&&!child.classList.contains('page-heading'))child.hidden=tab==='tasks'||tab==='notes'||!!projectOriginalHidden.get(child);
  if(tab==='tasks'||tab==='notes')Q('all-projects').hidden=true;
  projectWorkspace.hidden=!['tasks','notes'].includes(tab);Q('tasks-view').hidden=tab!=='tasks';Q('notes-view').hidden=tab!=='notes';
  if(tab==='tasks'){Q('filter-project').value=projectScope;renderTasks();}if(tab==='notes'){const n=notes.find(n=>n.id===selectedNote);if(n&&!focusNoteMatches(n))selectedNote=null;renderNotes();}
 }
 if(route==='learning'){const code=tab==='code';Q('snippets-view').hidden=!code;for(const child of [...Q('learning-view').children])if(child.id!=='snippets-view'&&child.id!=='learning-focus-tabs'&&!child.classList.contains('page-heading')){if(code)child.hidden=true;}if(!code)applyLearningLook();}
 document.body.dataset.focusRoute=route;document.querySelectorAll('a[href="#tasks"],a[href="#notes"],a[href="#snippets"]').forEach(a=>{const kind=a.hash.slice(1);a.href='#'+(kind==='snippets'?'learning?tab=code':workspaceRoute(kind));});
};
const noteCreateFocus=()=>{const n=notes.find(n=>n.id===selectedNote);if(n&&projectScope!=='all'){n.projectId=projectScope==='__none'?'':projectScope;persistNotes();renderNotes();}};Q('note-new').addEventListener('click',noteCreateFocus);
Q('quick-task').addEventListener('click',()=>{if(projectScope!=='all')Q('task-project').value=projectScope==='__none'?'':projectScope;});
Q('open-task-window').addEventListener('click',()=>{if(projectScope!=='all')Q('task-project').value=projectScope==='__none'?'':projectScope;});
openProjectTasks=function(id){projectScope=id;location.hash=workspaceRoute('tasks',id);showView();taskFilter='all';trashMode=false;Q('tasks-search').value='';Q('filter-priority').value='all';renderTasks();};
const focusLaunchBefore=launchCreate;launchCreate=function(kind){focusLaunchBefore(kind);showView();if(kind==='tasks'&&projectScope!=='all')Q('task-project').value=projectScope==='__none'?'':projectScope;};
const focusEntityBefore=openEntity;openEntity=function(kind,id){if(kind==='notes'||kind==='tasks'){const record=(kind==='notes'?notes:tasks).find(x=>x.id===id);if(record)projectScope=record.projectId||'__none';}focusEntityBefore(kind,id);showView();};
const focusLinkedNoteBefore=makeLinkedNote;makeLinkedNote=function(options={}){const task=tasks.find(x=>x.id===options.taskId);projectScope=task?.projectId||'__none';focusLinkedNoteBefore(options);};
const focusOpenLessonBefore=openLesson;openLesson=function(id){if(focusedRoute().params.get('tab')==='code')history.replaceState(null,'','#learning');focusOpenLessonBefore(id);showView();};
const focusDetailBefore=renderProjectDetail;renderProjectDetail=function(){focusDetailBefore();const id=new URLSearchParams(location.hash.split('?')[1]||'').get('project');if(!projects.some(p=>p.id===id))return;const actions=Q('project-detail').querySelector('.project-hub-actions');if(actions){actions.replaceChildren();for(const kind of ['tasks','notes'])actions.append(button(t()[kind],()=>{projectDetailsWindow.shut();projectScope=id;location.hash=workspaceRoute(kind,id);}));}};
renderHome=function(){homeSurface.replaceChildren();const hero=E('div','focus-hero');hero.append(E('p','eyebrow','KACHAN'),E('h1','',fc().title),E('p','',fc().intro));homeSurface.append(hero);const grid=E('div','focus-portals');for(const [route,icon] of [['resources','↗'],['learning','◫'],['tools','⌘']]){const card=E('a','focus-portal');card.href='#'+route;card.append(E('span','focus-portal-icon',icon),E('h2','',t()[route]),E('p','',fc()[route]),E('span','focus-portal-arrow','↗'));grid.append(card);}homeSurface.append(grid);};
toolTabs.push(['json','jsonTool'],['text','textTool'],['grid','gridTool']);
let utilityDrafts={json:'{"name":"Kachan","ready":true}',text:'Hello, Kachan!'};
function renderFocusUtility(body){
 const panel=E('section','dashboard-panel focus-utility');panel.append(E('h2','',fc()[selectedTool]));body.append(panel);
 if(selectedTool==='grid'){const preview=E('div','grid-tool-preview'),out=E('textarea','utility-output');out.readOnly=true;out.setAttribute('aria-label',fc().output);let columns=3,gap=16;const update=()=>{preview.style.gridTemplateColumns=`repeat(${columns}, minmax(0, 1fr))`;preview.style.gap=gap+'px';out.value=`.grid {\n  display: grid;\n  grid-template-columns: repeat(${columns}, minmax(0, 1fr));\n  gap: ${gap}px;\n}\n\n@media (max-width: 600px) {\n  .grid { grid-template-columns: 1fr; }\n}`;};for(const [key,max,value] of [['columns',6,3],['gap',48,16]]){const label=E('label','form-field',fc()[key]),input=E('input');input.type='range';input.min=key==='columns'?1:0;input.max=max;input.value=value;input.setAttribute('aria-label',fc()[key]);input.addEventListener('input',()=>{if(key==='columns')columns=Number(input.value);else gap=Number(input.value);update();});label.append(input);panel.append(label);}for(let i=1;i<=6;i++)preview.append(E('div','',String(i)));panel.append(preview,out,button(fc().copy,()=>copyToolText(out.value)));update();return;}
 const input=E('textarea','utility-input');input.maxLength=100000;input.value=utilityDrafts[selectedTool];input.setAttribute('aria-label',fc().input);const result=E('textarea','utility-output');result.readOnly=true;result.setAttribute('aria-label',fc().output);const status=E('p','panel-note');status.setAttribute('role','status');const actions=E('div','utility-actions');input.addEventListener('input',()=>{utilityDrafts[selectedTool]=input.value;});
 const run=fn=>{try{result.value=fn(input.value);status.textContent=selectedTool==='json'?fc().valid:'';}catch(error){result.value='';status.textContent=fc().invalid+error.message;}};
 const operations=selectedTool==='json'?[['format',s=>JSON.stringify(JSON.parse(s),null,2)],['minify',s=>JSON.stringify(JSON.parse(s))]]:[['encode',encodeURIComponent],['decode',decodeURIComponent],['upper',s=>s.toLocaleUpperCase()],['lower',s=>s.toLocaleLowerCase()],['trim',s=>s.trim().replace(/[ \t]+/g,' ')]];
 for(const [key,fn] of operations)actions.append(button(fc()[key],()=>run(fn)));panel.append(E('label','',fc().input),input,actions,status,E('label','',fc().output),result,button(fc().copy,()=>copyToolText(result.value)));
}
let toolCatalogOpen=true;
const focusToolsBefore=renderTools;renderTools=function(){focusToolsBefore();Q('tool-tabs').hidden=true;const body=toolsView.querySelector('.tool-body');if(toolCatalogOpen){const header=toolsView.querySelector('.page-heading');header._purposeButton?.remove();header._purposeButton=null;addPurpose(header,'tools',t().tools);body.replaceChildren();const cards=E('div','tool-catalog');for(const [id,key] of toolTabs){const card=button(t()[key],()=>{toolCatalogOpen=false;selectedTool=id;renderTools();},'tool-catalog-card');card.prepend(E('span','tool-card-mark',({json:'{}',text:'Aa',grid:'▦',playground:'</>',reviews:'↗',ideas:'✦',cheats:'≡',lab:'◐'})[id]));cards.append(card);}body.append(E('p','panel-note',fc().choose),cards);}else{body.before(button(fc().back,()=>{previewRun++;previewToken='';toolCatalogOpen=true;renderTools();},'text-link tool-catalog-back'));if(['json','text','grid'].includes(selectedTool))renderFocusUtility(body);}};
const focusOpenToolBefore=openTool;openTool=function(id){toolCatalogOpen=false;focusOpenToolBefore(id);};
fillCreate=function(){createContent.replaceChildren();for(const kind of ['resources','snippets','projects','tasks','notes']){const label=kind==='snippets'?t().learning+' · '+fc().library:['tasks','notes'].includes(kind)?t().projects+' · '+t()[kind]:t()[kind];const action=button(label,()=>{createWindow.shut();launchCreate(kind);},'create-option');action.prepend(homeIcon(kind));createContent.append(action);}};fillCreate();
window.addEventListener('hashchange',()=>{showView();if(focusedRoute().route==='tools')renderTools();});
window.addEventListener('languagechange',()=>{renderHome();renderTools();showView();});
focusedNav.addEventListener('click',event=>{if(event.target.closest('a')){document.querySelector('.sidebar').classList.remove('menu-open');Q('menu-toggle').setAttribute('aria-expanded','false');}});
renderMenuPreferences();renderHome();renderTools();showView();
