Object.assign(translations.uk,{accessibilityLabel:'Доступність',tools:'Інструменти',playground:'Пісочниця',siteReviews:'Розбір сайтів',ideaGenerator:'Генератор ідей',cheatsheets:'Шпаргалки',designLab:'Лабораторія дизайну',toolIntro:'Окремий простір для експериментів і власних відкриттів.',runPreview:'Запустити',clearPreview:'Очистити результат',preview:'Результат',consoleOutput:'Консоль',playgroundHint:'HTML, CSS і JavaScript зберігаються автоматично. Запускай код кнопкою; прев’ю ізольоване від даних сайту й мережі.',saveAsSnippet:'Зберегти код',newReview:'Новий розбір',reviewName:'Назва сайту',reviewColors:'Кольори',reviewFonts:'Шрифти',reviewSpacing:'Відступи й сітка',reviewComponents:'Компоненти',reviewTakeaway:'Що хочу повторити',noReviews:'Збережи сайт, дизайн якого хочеш розібрати.',reviewHint:'Відкрий сайт в іншій вкладці та запиши свої спостереження. Це твоя колекція розборів.',openWebsite:'Відкрити сайт',level:'Рівень',beginner:'Початковий',intermediate:'Середній',advanced:'Складний',technology:'Технологія',generateIdea:'Нова ідея',requirements:'Що зробити',ideaToProject:'Створити проєкт за ідеєю',cheatSearch:'Пошук у шпаргалках',backgroundColor:'Фон',textColor:'Текст',accentColor:'Акцент',radiusControl:'Округлення',spaceControl:'Відступ',shadowControl:'Тінь',fontControl:'Шрифт',copyCSS:'Копіювати CSS',labTitle:'Зроби свою наступну ідею видимою.',labDescription:'Змінюй кольори, відступи й форму картки. Забери готові стилі у свій проєкт.',contrast:'Контраст тексту',reviewDelete:'Видалити розбір?',localExperiment:'Мій експеримент',toolEmpty:'Нічого не знайдено.'});
Object.assign(translations.en,{accessibilityLabel:'Accessibility',tools:'Tools',playground:'Playground',siteReviews:'Site reviews',ideaGenerator:'Idea generator',cheatsheets:'Cheatsheets',designLab:'Design lab',toolIntro:'A separate space for experiments and discoveries.',runPreview:'Run',clearPreview:'Clear preview',preview:'Preview',consoleOutput:'Console',playgroundHint:'HTML, CSS and JavaScript save automatically. Run code with the button; the preview is isolated from app data and the network.',saveAsSnippet:'Save code',newReview:'New review',reviewName:'Website name',reviewColors:'Colors',reviewFonts:'Fonts',reviewSpacing:'Spacing and grid',reviewComponents:'Components',reviewTakeaway:'What I want to recreate',noReviews:'Save a website whose design you want to explore.',reviewHint:'Open a website in another tab and record your observations. This is your own review collection.',openWebsite:'Open website',level:'Level',beginner:'Beginner',intermediate:'Intermediate',advanced:'Advanced',technology:'Technology',generateIdea:'New idea',requirements:'What to build',ideaToProject:'Create project from idea',cheatSearch:'Search cheatsheets',backgroundColor:'Background',textColor:'Text',accentColor:'Accent',radiusControl:'Radius',spaceControl:'Spacing',shadowControl:'Shadow',fontControl:'Font',copyCSS:'Copy CSS',labTitle:'Make your next idea visible.',labDescription:'Adjust colors, spacing and shape. Take the styles into your own project.',contrast:'Text contrast',reviewDelete:'Delete this review?',localExperiment:'My experiment',toolEmpty:'Nothing found.'});
function toolboxDefault(){return{version:1,playground:{html:'<main class="card">\n  <h1>Hello, builder!</h1>\n  <button id="hello">Click me</button>\n</main>',css:'.card { padding: 24px; border-radius: 16px; background: #f2f2f5; }\nbutton { padding: 12px 20px; border: 0; border-radius: 10px; background: #ff3838; color: white; }',js:'document.querySelector("#hello").addEventListener("click", () => {\n  document.querySelector("h1").textContent = "Keep building!";\n  console.log("Button clicked");\n});'},analyses:[],lab:{background:'#17191f',text:'#f5f5f7',accent:'#ff3838',radius:20,space:24,shadow:20,font:'system'},idea:''};}
if(!extras.toolbox)extras.toolbox=toolboxDefault();function toolboxState(){return extras.toolbox;}function saveToolbox(){persistExtras();}
let selectedTool='playground',playgroundFile='html',previewToken='',previewRun=0;
const toolsView=E('section');toolsView.id='tools-view';toolsView.hidden=true;const toolContent=document.querySelector('.content');toolContent.insertBefore(toolsView,toolContent.querySelector('footer'));
const toolsLink=E('a','nav-item');toolsLink.href='#tools';toolsLink.dataset.viewLink='tools';const toolIcon=E('span');toolIcon.setAttribute('aria-hidden','true');toolIcon.textContent='⌘';const toolName=E('span','nav-text',t().tools);toolName.dataset.i18n='tools';toolsLink.append(toolIcon,toolName);Q('workspace-navigation').append(toolsLink);optionalMenuRoutes.push('tools');
const toolTabs=[['playground','playground'],['reviews','siteReviews'],['ideas','ideaGenerator'],['cheats','cheatsheets'],['lab','designLab']];
const viewBeforeTools=showView;showView=function(){viewBeforeTools();const active=location.hash.split('?')[0]==='#tools';toolsView.hidden=!active;if(active){dashboard.hidden=true;Q('page-breadcrumb').textContent=t().tools;for(const a of document.querySelectorAll('[data-view-link]')){const current=a===toolsLink;a.classList.toggle('active',current);if(current)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}}};window.addEventListener('hashchange',()=>{showView();if(location.hash.split('?')[0]!=='#tools'){previewRun++;previewToken='';const frame=Q('tool-preview');if(frame)frame.srcdoc='';}});
async function navigateToolResult(route){if(location.hash.split('?')[0]!=='#'+route)await new Promise(resolve=>{window.addEventListener('hashchange',resolve,{once:true});location.hash=route;});showView();}
function openTool(id){selectedTool=id;location.hash='tools';showView();renderTools();}
const searchBeforeTools=searchItems;searchItems=function(){return [...searchBeforeTools(),...toolTabs.map(([id,key])=>({name:t()[key],body:t().tools,action:()=>openTool(id)}))];};
purposeText.tools=['П’ять незалежних інструментів: експериментуй із кодом, розбирай дизайн сайтів, знаходь ідеї, відкривай шпаргалки та підбирай власні стилі.','Five independent tools: experiment with code, review website design, find ideas, browse cheatsheets and create your own styles.'];
Object.assign(purposeText,{playground:['Вільні експерименти з HTML, CSS і JavaScript. Обери файл, зміни код і натисни Запустити. Чернетка зберігається; потрібний файл можна перенести у фрагменти коду.','Experiment freely with HTML, CSS and JavaScript. Select a file, edit it and Run. Your draft saves; send a useful file to your snippets.'],reviews:['Записуй, як побудовані сайти, які тобі подобаються: кольори, шрифти, сітка, компоненти й власні висновки. Розбір заповнюється вручну та зберігається у твоїй колекції.','Record how websites you like are built: colors, fonts, grid, components and observations. Reviews are filled in manually and saved in your collection.'],ideas:['Обери рівень і технології, щоб отримати ідею з вимогами з готової добірки. Можеш одразу створити проєкт та уточнити його опис перед збереженням.','Choose a level and technologies to get an idea and requirements from a curated collection. Create a project and refine its description before saving.'],cheats:['Короткі приклади й правила, які зручно тримати під рукою. Відфільтруй тему, знайди потрібне та скопіюй код або команду.','Short examples and rules to keep close. Filter a topic, find what you need and copy code or a command.'],lab:['Підбирай кольори, шрифт, відступи, округлення й тінь на живій картці. Стилі зберігаються; готовий CSS можна скопіювати. Контраст показує співвідношення кольорів тексту й фону.','Try colors, font, spacing, radius and shadow on a live card. Styles save and you can copy the CSS. Contrast shows the ratio between text and background colors.']});
function renderTools(){toolsView.replaceChildren();const header=E('div','page-heading view-header');header.append(E('h1','',t().tools));toolsView.append(header);addPurpose(header,selectedTool,t()[toolTabs.find(([id])=>id===selectedTool)[1]]);alignHelpTitles();const tabs=compositionTabs('tool-tabs',toolTabs,selectedTool,id=>{previewRun++;previewToken='';selectedTool=id;renderTools();});toolsView.append(tabs);const body=E('div','tool-body');toolsView.append(body);if(selectedTool==='playground')renderPlayground(body);if(selectedTool==='reviews')renderReviews(body);if(selectedTool==='ideas')renderIdeas(body);if(selectedTool==='cheats')renderCheats(body);if(selectedTool==='lab')renderLab(body);scheduleSectionNavigation();}
async function copyToolText(value){try{await navigator.clipboard.writeText(value);notice(t().copied);}catch{notice(t().copyError);}}
function safeToolDocument(files,runtime=''){return safePracticeDocument({...files,css:files.css.replaceAll('<','\\3c ')},runtime.replace(/<\/script/gi,'<\\/script'));}
function renderPlayground(body){body.append(E('p','panel-note',t().playgroundHint));const layout=E('div','playground-layout'),editor=E('section','dashboard-panel'),result=E('section','dashboard-panel');const tabs=compositionTabs('playground-files',[['html','HTML'],['css','CSS'],['js','JavaScript']],playgroundFile,file=>{playgroundFile=file;renderTools();});for(const b of tabs.children)b.textContent=b.dataset.tab==='js'?'JavaScript':b.dataset.tab.toUpperCase();const input=E('textarea','tool-code-editor');input.id='playground-code';input.spellcheck=false;input.maxLength=100000;input.setAttribute('aria-label',playgroundFile.toUpperCase());input.value=toolboxState().playground[playgroundFile];input.addEventListener('input',()=>{toolboxState().playground[playgroundFile]=input.value;saveToolbox();});const actions=E('div','editor-actions');actions.append(button('runPreview',runPlayground,'primary-button'),button('saveAsSnippet',async()=>{const files=toolboxState().playground;await navigateToolResult('snippets');openEntity('snippets','');resetSnippet();const form=Q('snippet-form');form.elements.name.value=t().localExperiment;form.elements.category.value={html:'HTML',css:'CSS',js:'JavaScript'}[playgroundFile];form.elements.code.value=files[playgroundFile];Q('snippet-editor').open=true;snippetWindow.open();}));editor.append(tabs,input,actions);result.append(E('h2','',t().preview));const frame=E('iframe','tool-preview');frame.id='tool-preview';frame.title=t().preview;frame.setAttribute('sandbox','allow-scripts');frame.srcdoc=safeToolDocument(toolboxState().playground);const output=E('pre','tool-output');output.id='tool-output';output.setAttribute('aria-label',t().consoleOutput);output.setAttribute('role','status');result.append(frame,E('h3','',t().consoleOutput),output,button('clearPreview',()=>{previewRun++;previewToken='';frame.srcdoc='';output.textContent='';}));layout.append(editor,result);body.append(layout);}
async function runPlayground(){const run=++previewRun,frame=Q('tool-preview'),output=Q('tool-output');if(!frame)return;frame.dataset.runReady='false';frame.srcdoc='<!doctype html><p>…</p>';output.textContent='…';const files=structuredClone(toolboxState().playground);const compiled=await compilePractice(files.js,false,true);if(run!==previewRun||!frame.isConnected)return;if(compiled.error){output.textContent=compiled.error;return;}previewToken=crypto.randomUUID();const token=JSON.stringify(previewToken);const runtime=`(()=>{let steps=0;const __kachanTick=()=>{if(++steps>10000)throw Error('Execution limit exceeded');};const send=(value)=>parent.postMessage({toolToken:${token},value:String(value).slice(0,4000)},'*');const console={log:(...args)=>send(args.map(String).join(' ')),error:(...args)=>send(args.map(String).join(' '))};window.addEventListener('error',e=>send(e.message));try{${compiled.code}\n}catch(e){send(e.message);}parent.postMessage({toolToken:${token},ready:true},'*');})();`;output.textContent='';frame.srcdoc=safeToolDocument(files,runtime).replace(" 'unsafe-eval' blob:","").replace("worker-src blob:","worker-src 'none'");}
window.addEventListener('message',e=>{const frame=Q('tool-preview');if(frame&&e.source===frame.contentWindow&&previewToken&&e.data?.toolToken===previewToken){if(e.data.ready){frame.dataset.runReady='true';return;}if(typeof e.data.value!=='string')return;const output=Q('tool-output');if(output.textContent.length<16000)output.textContent+=e.data.value.slice(0,4000)+'\n';}});
let editingReview=null;const reviewForm=E('form','utility-content project-form-grid'),reviewWindow=utilityWindow('site-review-window','siteReviews',reviewForm);
function editReview(id=null){editingReview=id;const value=toolboxState().analyses.find(a=>a.id===id);reviewForm.replaceChildren();for(const [key,label,max,multiline] of [['name','reviewName',120,false],['url','url',1000,false],['colors','reviewColors',5000,true],['fonts','reviewFonts',5000,true],['spacing','reviewSpacing',5000,true],['components','reviewComponents',5000,true],['takeaway','reviewTakeaway',5000,true]]){const field=labelField(reviewForm,label,E(multiline?'textarea':'input'));field.name=key;field.maxLength=max;field.value=value?.[key]||'';if(multiline)field.rows=2;if(['name','url'].includes(key))field.required=true;if(key==='url')field.type='url';}const save=E('button','primary-button',t().save);save.type='submit';reviewForm.append(save);reviewWindow.open();reviewForm.elements.name.focus();}
reviewForm.addEventListener('submit',e=>{e.preventDefault();const value=Object.fromEntries(new FormData(reviewForm));value.name=value.name.trim();value.url=value.url.trim();if(!value.name||!/^https?:\/\//i.test(value.url)||!validProjectUrl(value.url)){reviewForm.elements.url.setCustomValidity(t().url);reviewForm.elements.url.reportValidity();return;}const state=toolboxState();if(!editingReview&&state.analyses.length>=500)return;value.id=editingReview||crypto.randomUUID();state.analyses=editingReview?state.analyses.map(a=>a.id===editingReview?value:a):[value,...state.analyses];saveToolbox();reviewWindow.shut();renderTools();});reviewForm.addEventListener('input',()=>reviewForm.elements.url.setCustomValidity(''));
function renderReviews(body){const toolbar=E('div','view-toolbar');toolbar.append(E('p','panel-note',t().reviewHint),button('newReview',()=>editReview(),'primary-button'));body.append(toolbar);if(!toolboxState().analyses.length)body.append(E('p','empty-state',t().noReviews));for(const a of toolboxState().analyses){const card=E('details','review-record'),summary=E('summary','',a.name);card.append(summary);const link=E('a','text-link',t().openWebsite);link.href=a.url;link.target='_blank';link.rel='noopener noreferrer';card.append(link);for(const [key,label] of [['colors','reviewColors'],['fonts','reviewFonts'],['spacing','reviewSpacing'],['components','reviewComponents'],['takeaway','reviewTakeaway']])if(a[key])card.append(E('h3','',t()[label]),E('p','review-text',a[key]));const actions=E('div','editor-actions');actions.append(button('edit',()=>editReview(a.id)),button('remove',()=>{if(!confirm(t().reviewDelete))return;toolboxState().analyses=toolboxState().analyses.filter(x=>x.id!==a.id);saveToolbox();renderTools();}));card.append(actions);body.append(card);}}
const ideaDeck=[
['profile','beginner',['Особиста сторінка','Personal page'],['Створи заголовок, опис, список навичок і контакти. Зроби мобільний вигляд.','Build a heading, bio, skills and contacts. Add a mobile layout.']],
['menu','beginner',['Меню кав’ярні','Cafe menu'],['Згрупуй страви, ціни й описи. Зроби читабельну сітку та стани кнопок.','Group dishes, prices and descriptions. Build a readable grid and button states.']],
['gallery','beginner',['Галерея робіт','Work gallery'],['Покажи шість карток, додай підписи й адаптивну сітку.','Show six cards with captions and a responsive grid.']],
['landing','beginner',['Сторінка продукту','Product page'],['Зроби головний блок, переваги, ціни та заклик до дії.','Build a hero, benefits, pricing and a call to action.']],
['expenses','intermediate',['Трекер витрат','Expense tracker'],['Додавання витрат, категорії, сума та фільтр за місяцем. Перевіряй введення.','Add expenses, categories, totals and a monthly filter. Validate input.']],
['quiz','intermediate',['Вікторина','Quiz app'],['П’ять питань, підрахунок результату й повторний запуск.','Five questions, score calculation and restart.']],
['recipes','intermediate',['Каталог рецептів','Recipe catalog'],['Пошук, фільтри, обране й окремий перегляд рецепта.','Search, filters, favorites and a recipe detail view.']],
['reading','intermediate',['Список читання','Reading list'],['Додавання книг, статуси, пошук і збереження списку.','Add books, statuses, search and persist the list.']],
['board','advanced',['Дошка проєкту','Project board'],['Колонки статусів, перенесення задач, фільтри й доступне керування клавіатурою.','Status columns, moving tasks, filters and accessible keyboard controls.']],
['calendar','advanced',['Календар подій','Event calendar'],['Місяці, створення подій, перевірка дат і пошук.','Month navigation, event creation, date validation and search.']],
['shop','advanced',['Каталог із кошиком','Catalog and cart'],['Сортування товарів, фільтри, кошик, кількість і підсумок.','Product sorting, filters, cart, quantities and totals.']],
['editor','advanced',['Редактор Markdown','Markdown editor'],['Текст, живий перегляд, збереження, експорт і безпечне відображення.','Text, live preview, persistence, export and safe rendering.']]];
let ideaLevel=ideaDeck.find(i=>i[0]===toolboxState().idea)?.[1]||'beginner',ideaStack=toolboxState().ideaStack||'HTML + CSS + JavaScript';
function renderIdeas(body){const controls=E('div','tool-controls'),level=labelField(controls,'level',E('select')),stack=labelField(controls,'technology',E('select'));selectOptions(level,['beginner','intermediate','advanced'].map(k=>[k,t()[k]]),ideaLevel);selectOptions(stack,['HTML + CSS','HTML + CSS + JavaScript','HTML + CSS + TypeScript'].map(k=>[k,k]),ideaStack);level.addEventListener('change',()=>{ideaLevel=level.value;});stack.addEventListener('change',()=>{ideaStack=stack.value;toolboxState().ideaStack=ideaStack;saveToolbox();});controls.append(button('generateIdea',()=>{const choices=ideaDeck.filter(i=>i[1]===ideaLevel&&i[0]!==toolboxState().idea);toolboxState().idea=choices[crypto.getRandomValues(new Uint32Array(1))[0]%choices.length][0];saveToolbox();renderTools();},'primary-button'));body.append(controls);const idea=ideaDeck.find(i=>i[0]===toolboxState().idea);if(!idea)return;const lang=document.documentElement.lang==='uk'?0:1,card=E('article','dashboard-panel');card.append(E('span','badge',t()[idea[1]]+' · '+ideaStack),E('h2','',idea[2][lang]),E('h3','',t().requirements),E('p','',idea[3][lang]),E('p','panel-note',ideaStack==='HTML + CSS'?(lang===0?'Реалізуй макет і стани інтерфейсу; поведінку можна додати пізніше.':'Build the layout and interface states; behavior can come later.'):(lang===0?'Реалізуй поведінку та перевір введення. Додай порожні стани й мобільну версію.':'Implement behavior and validate input. Add empty states and a mobile layout.')),button('ideaToProject',()=>{launchCreate('projects');const f=Q('project-form');f.elements.name.value=idea[2][lang];f.elements.description.value=idea[3][lang];f.elements.technologies.value=ideaStack.replaceAll(' + ', ', ');f.elements.status.value='planning';},'primary-button'));body.append(card);}
const cheatDeck=[
['HTML',['Семантична сторінка','Semantic page'],['Зміст сторінки в main, навігація в nav.','Put page content in main and navigation in nav.'],'<header>...</header>\n<nav>...</nav>\n<main>...</main>\n<footer>...</footer>'],
['HTML',['Поле з підписом','Labeled input'],['Пов’язуй label та input через for/id.','Connect label and input with for/id.'],'<label for="email">Email</label>\n<input id="email" type="email" required>'],
['HTML',['Кнопка','Button'],['type="button" не надсилає форму.','type="button" does not submit a form.'],'<button type="button">Open</button>'],
['CSS',['Flexbox: центр','Flexbox center'],['Центрування по обох осях.','Center on both axes.'],'display: flex;\nalign-items: center;\njustify-content: center;'],
['CSS',['Адаптивна сітка','Responsive grid'],['Колонки автоматично підлаштовуються.','Columns adjust automatically.'],'display: grid;\ngrid-template-columns: repeat(auto-fit, minmax(min(240px, 100%), 1fr));\ngap: 16px;'],
['CSS',['Мобільні стилі','Mobile styles'],['Правила для вузьких екранів.','Rules for narrow screens.'],'@media (max-width: 700px) {\n  .layout { grid-template-columns: 1fr; }\n}'],
['CSS',['Розміри елементів','Element sizing'],['Враховуй padding і border у ширині.','Include padding and border in width.'],'*, *::before, *::after { box-sizing: border-box; }'],
['JavaScript',['Відбір масиву','Filter an array'],['Повертає лише елементи, що відповідають умові.','Return only items matching a condition.'],'const active = tasks.filter(task => !task.completed);'],
['JavaScript',['Перетворення масиву','Map an array'],['Створює новий масив значень.','Create a new array of values.'],'const names = users.map(user => user.name);'],
['JavaScript',['Обробка натискання','Click handler'],['Зареєструй обробник події.','Register an event handler.'],'button.addEventListener("click", () => {\n  console.log("Clicked");\n});'],
['JavaScript',['Пошук у масиві','Find an item'],['Перший відповідний елемент або undefined.','First matching item or undefined.'],'const item = items.find(item => item.id === selectedId);'],
['TypeScript',['Тип об’єкта','Object type'],['Описує поля й типи значень.','Describe fields and value types.'],'type Task = { id: string; title: string; completed: boolean };'],
['TypeScript',['Тип параметра','Parameter type'],['Визначає вхід і результат функції.','Define a function input and result.'],'function double(value: number): number {\n  return value * 2;\n}'],
['Git',['Стан і зміни','Status and changes'],['Подивись зміни перед комітом.','Inspect changes before committing.'],'git status\ngit diff'],
['Git',['Зберегти коміт','Save a commit'],['Додай потрібний файл і створи коміт.','Stage the intended file and create a commit.'],'git add index.html\ngit commit -m "Add layout"'],
['Git',['Нова гілка','New branch'],['Створи гілку та перемкнись на неї.','Create a branch and switch to it.'],'git switch -c feature/menu'],
['Accessibility',['Видимий фокус','Visible focus'],['Не ховай фокус клавіатури.','Keep keyboard focus visible.'],':focus-visible { outline: 2px solid #ff3838; outline-offset: 3px; }'],
['Accessibility',['Опис зображення','Image description'],['Змістовним зображенням — опис, декоративним — порожній alt.','Describe meaningful images; use empty alt for decoration.'],'<img src="diagram.png" alt="Layout diagram">\n<img src="decoration.svg" alt="">']];
let cheatQuery='',cheatCategory='all';function renderCheats(body){const controls=E('div','tool-controls'),query=labelField(controls,'cheatSearch',E('input')),category=labelField(controls,'category',E('select'));query.type='search';query.value=cheatQuery;selectOptions(category,[['all',t().filterAll],...new Set(cheatDeck.map(c=>c[0]))].map(x=>Array.isArray(x)?x:[x,x==='Accessibility'?t().accessibilityLabel:x]),cheatCategory);const list=E('div','cheat-list');const fill=()=>{list.replaceChildren();const lang=document.documentElement.lang==='uk'?0:1,rows=cheatDeck.filter(c=>(cheatCategory==='all'||c[0]===cheatCategory)&&[c[0],c[0]==='Accessibility'?t().accessibilityLabel:'',c[1][lang],c[2][lang],c[3]].join(' ').toLocaleLowerCase().includes(cheatQuery.toLocaleLowerCase()));if(!rows.length)list.append(E('p','empty-state',t().toolEmpty));for(const c of rows){const entry=E('details','cheat-entry');entry.append(E('summary','',(c[0]==='Accessibility'?t().accessibilityLabel:c[0])+' · '+c[1][lang]),E('p','panel-note',c[2][lang]),E('pre','tool-output',c[3]),button('copy',()=>copyToolText(c[3])));list.append(entry);}};query.addEventListener('input',()=>{cheatQuery=query.value;fill();});category.addEventListener('change',()=>{cheatCategory=category.value;fill();});body.append(controls,list);fill();}
function labCSS(){const v=toolboxState().lab;return '.card {\n  background: '+v.background+';\n  color: '+v.text+';\n  padding: '+v.space+'px;\n  border-radius: '+v.radius+'px;\n  box-shadow: 0 8px '+v.shadow+'px rgb(0 0 0 / 20%);\n  font-family: '+({system:'system-ui, sans-serif',serif:'Georgia, serif',mono:'Consolas, monospace'}[v.font])+';\n}\n.card button {\n  background: '+v.accent+';\n  color: '+contrastText(v.accent)+';\n  padding: 12px 20px;\n  border: 0;\n  border-radius: '+Math.min(v.radius,16)+'px;\n}';}
function luminance(hex){const values=[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return values[0]*.2126+values[1]*.7152+values[2]*.0722;}
function contrastText(hex){return luminance(hex)>.179?'#000000':'#ffffff';}
function renderLab(body){const layout=E('div','lab-layout'),controls=E('section','dashboard-panel'),preview=E('section','lab-stage'),card=E('div','lab-preview-card');card.append(E('h2','',t().labTitle),E('p','',t().labDescription),E('button','',t().preview));preview.append(card);const ratio=E('p','panel-note'),css=E('pre','tool-output');const update=()=>{const v=toolboxState().lab;card.style.background=v.background;card.style.color=v.text;card.style.padding=v.space+'px';card.style.borderRadius=v.radius+'px';card.style.boxShadow='0 8px '+v.shadow+'px #0003';card.style.fontFamily={system:'system-ui,sans-serif',serif:'Georgia,serif',mono:'Consolas,monospace'}[v.font];const b=card.querySelector('button');b.style.cssText='padding:12px 20px;border:0;border-radius:'+Math.min(v.radius,16)+'px;background:'+v.accent+';color:'+contrastText(v.accent);const a=luminance(v.background),z=luminance(v.text);ratio.textContent=t().contrast+': '+((Math.max(a,z)+.05)/(Math.min(a,z)+.05)).toFixed(2)+' : 1';css.textContent=labCSS();};for(const [key,label] of [['background','backgroundColor'],['text','textColor'],['accent','accentColor'],['radius','radiusControl'],['space','spaceControl'],['shadow','shadowControl']]){const field=labelField(controls,label,E('input'));field.id='lab-'+key;field.type=['radius','space','shadow'].includes(key)?'range':'color';if(field.type==='range'){field.min=0;field.max=64;}field.value=toolboxState().lab[key];field.addEventListener('input',()=>{toolboxState().lab[key]=field.type==='range'?Number(field.value):field.value;saveToolbox();update();});}const font=labelField(controls,'fontControl',E('select'));selectOptions(font,[['system','System'],['serif','Georgia'],['mono','Consolas']],toolboxState().lab.font);font.addEventListener('change',()=>{toolboxState().lab.font=font.value;saveToolbox();update();});controls.append(button('copyCSS',()=>copyToolText(labCSS()),'primary-button'));layout.append(controls,preview);body.append(layout,ratio,css);update();}
window.addEventListener('languagechange',()=>{toolName.textContent=t().tools;showView();renderTools();renderMenuPreferences();});renderTools();showView();renderMenuPreferences();applyMenuVisibility();
