Object.assign(translations.uk,{homeTab:'Головна',homeTitle:'Твій простір. Твій наступний крок.',homeIntro:'Створюй, навчайся й зберігай ідеї — усе поруч.',homeStart:'З чого почнемо?',homeProjects:'Від ідеї до готового сайту',homeLearning:'Один урок — нова навичка',homeNotes:'Збережи думку, поки вона свіжа',homeResources:'Корисні інструменти під рукою',homeResume:'Продовжити навчання',homeWelcome:'Привіт',homeWork:'До робочого дня',noteOptions:'Параметри нотатки',taskMoreFilters:'Фільтри й сортування',resourceManage:'Додати посилання',snippetManage:'Додати код'});
Object.assign(translations.en,{homeTab:'Home',homeTitle:'Your space. Your next step.',homeIntro:'Build, learn and capture ideas — all in one place.',homeStart:'Where do we start?',homeProjects:'From an idea to a live website',homeLearning:'One lesson, one new skill',homeNotes:'Capture an idea while it is fresh',homeResources:'Useful tools within reach',homeResume:'Continue learning',homeWelcome:'Hello',homeWork:'Open workday',noteOptions:'Note options',taskMoreFilters:'Filters and sorting',resourceManage:'Add a link',snippetManage:'Add code'});
const homeSurface=E('section','home-surface');homeSurface.id='home-surface';dashboard.prepend(homeSurface);
function homeIcon(route){const source=document.querySelector('[data-view-link="'+route+'"] svg');return source?.cloneNode(true)||E('span','','↗');}
function renderHome(){const home=workTab==='home';homeSurface.hidden=!home;dashboard.querySelector('.page-heading').hidden=home;dashboard.querySelector('.daily-actions').hidden=home;if(!home)return;homeSurface.replaceChildren();const hero=E('section','home-hero'),copy=E('div','home-hero-copy');copy.append(E('p','eyebrow','KACHAN · '+t().homeWelcome+', '+settings.userName),E('h1','',t().homeTitle),E('p','home-intro',t().homeIntro));const actions=E('div','editor-actions');actions.append(button('newTask',()=>Q('quick-task').click(),'primary-button'),button('homeWork',()=>{workTab='overview';arrangeWorkday();}));copy.append(actions);const art=E('div','home-art');art.setAttribute('aria-hidden','true');art.append(E('span','','</>'));hero.append(copy,art);homeSurface.append(hero);
 const row=E('div','home-summary');for(const [value,key] of [[projects.filter(p=>!p.archived).length,'projects'],[tasks.filter(task=>!task.completed).length,'activeTasks'],[notes.filter(n=>!n.deleted).length,'notes']]){const item=E('div');item.append(E('strong','',String(value)),E('span','',t()[key]||key));row.append(item);}homeSurface.append(row,E('h2','',t().homeStart));const launchers=E('div','home-launchers');for(const [route,key] of [['projects','homeProjects'],['learning','homeLearning'],['notes','homeNotes'],['resources','homeResources']]){const link=E('a','home-launcher');link.href='#'+route;const icon=E('span','home-launcher-icon');icon.append(homeIcon(route));const body=E('div');body.append(E('h3','',t()[route]),E('p','',t()[key]));link.append(icon,body,E('span','launcher-arrow','↗'));launchers.append(link);}homeSurface.append(launchers);const resume=E('div','home-resume');resume.append(homeIcon('learning'),E('div'));resume.lastChild.append(E('strong','',t().homeResume),E('p','',Q('continue-lesson').textContent||'HTML'));resume.append(button('continueButton',()=>Q('continue-html').click()));homeSurface.append(resume);dashboard.insertBefore(homeSurface,Q('workday-tabs'));}
const dailyBeforeHome=renderDailyDashboard;renderDailyDashboard=function(){dailyBeforeHome();renderHome();};
function utilityWindow(id,key,content){const dialog=E('dialog','utility-window editor-window');dialog.id=id;const header=E('header','editor-window-header'),heading=E('h2','',t()[key]);heading.id=id+'-title';heading.dataset.i18n=key;const close=E('button','window-close','×');close.type='button';close.setAttribute('aria-label',t().close);header.append(heading,close);dialog.append(header,content);dialog.setAttribute('aria-labelledby',heading.id);document.body.append(dialog);let previous;
 const open=()=>{if(dialog.open)return;previous=document.activeElement;dialog.showModal();document.body.classList.add('editor-window-open');};const shut=()=>dialog.close();close.addEventListener('click',shut);dialog.addEventListener('close',()=>{document.body.classList.toggle('editor-window-open',!!document.querySelector('dialog[open]'));if(previous?.isConnected)previous.focus();});dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)shut();});window.addEventListener('languagechange',()=>close.setAttribute('aria-label',t().close));return{dialog,open,shut};}
const snippetWindow=utilityWindow('snippet-window','newSnippet',Q('snippet-form'));Q('snippet-editor').hidden=true;const snippetCreate=button('snippetManage',()=>{resetSnippet();Q('snippet-editor').open=true;snippetWindow.open();Q('snippet-name').focus();},'primary-button');snippetCreate.id='open-snippet-window';snippetCreate.dataset.i18n='snippetManage';const snippetToolbar=E('div','view-toolbar');snippetToolbar.append(snippetCreate);Q('snippet-editor').before(snippetToolbar);new MutationObserver(()=>{if(Q('snippet-editor').open){snippetWindow.open();Q('snippet-name').focus();}else snippetWindow.shut();}).observe(Q('snippet-editor'),{attributes:true,attributeFilter:['open']});
let resourceWindow;
function arrangeResourceWindow(){const details=Q('resource-editor'),form=Q('resource-form');if(!details||!form||form.closest('dialog'))return;const toolbar=E('div','resource-add-toolbar'),open=button('resourceManage',()=>{details.open=true;resourceWindow.open();form.elements.name.focus();},'primary-button');open.id='open-resource-window';open.dataset.i18n='resourceManage';toolbar.append(open);details.before(toolbar);resourceWindow?.shut();resourceWindow?.dialog.remove();resourceWindow=utilityWindow('resource-window','newResource',form);details.hidden=true;new MutationObserver(()=>{if(details.open)resourceWindow.open();}).observe(details,{attributes:true,attributeFilter:['open']});if(editingResource)resourceWindow.open();}
const resourceToolsBeforeWindows=renderResourceTools;renderResourceTools=function(){resourceToolsBeforeWindows();arrangeResourceWindow();};arrangeResourceWindow();
const metadata=Q('notes-view').querySelector('.note-metadata');const noteOptionsContent=E('div','utility-content');noteOptionsContent.append(metadata,noteLinks);const noteWindow=utilityWindow('note-options-window','noteOptions',noteOptionsContent);const noteOptionsButton=button('noteOptions',()=>{const selected=notes.find(n=>n.id===selectedNote);if(selected)noteWindow.open();});noteOptionsButton.id='open-note-options';noteOptionsButton.dataset.i18n='noteOptions';Q('note-title').closest('.form-field').after(noteOptionsButton);
// Keep filter controls together, while the list remains the main task surface.
const taskPanel=Q('tasks-view').querySelector('.tasks-page-panel'),filterContent=E('div','utility-content');const sort=Q('task-sort').closest('.form-field'),filters=Q('filter-project').closest('.workspace-controls');filterContent.append(sort,filters);const filterWindow=utilityWindow('task-filters-window','taskMoreFilters',filterContent),filterButton=button('taskMoreFilters',filterWindow.open);filterButton.id='open-task-filters';filterButton.dataset.i18n='taskMoreFilters';taskPanel.querySelector('.task-filters').after(filterButton);
const taskViewsToolbar=E('div','task-view-tools');filterButton.before(taskViewsToolbar);taskViewsToolbar.append(filterButton,Q('toggle-kanban'),Q('task-trash-open'));
const noteActions=Q('note-fields').querySelector('.editor-actions');noteOptionsContent.append(noteActions);for(const id of ['note-delete','note-restore'])Q(id).addEventListener('click',()=>noteWindow.shut());
const learningOverview=Q('learning-title').closest('.dashboard-panel'),learningWindow=utilityWindow('learning-progress-window','learningProgress',learningOverview);learningOverview.hidden=false;const learningProgressButton=button('learningProgress',learningWindow.open);learningProgressButton.id='open-learning-progress';learningProgressButton.dataset.i18n='learningProgress';Q('learning-view').querySelector('.page-heading').after(learningProgressButton);
const projectDetailsWindow=utilityWindow('project-details-window','projects',Q('project-detail'));projectDetailsWindow.dialog.classList.add('project-details-window');
const detailBeforeWindow=renderProjectDetail;renderProjectDetail=function(){detailBeforeWindow();if(!Q('project-detail').hidden){Q('all-projects').hidden=false;Q('projects-view').classList.remove('project-open');projectDetailsWindow.open();}else projectDetailsWindow.shut();};
projectDetailsWindow.dialog.addEventListener('close',()=>{if(location.hash.startsWith('#projects?project='))location.hash='projects';});
window.addEventListener('hashchange',()=>{for(const w of [snippetWindow,resourceWindow,noteWindow,filterWindow,learningWindow])w?.shut();});window.addEventListener('languagechange',renderHome);arrangeWorkday();renderProjectDetail();
