Object.assign(translations.uk,{kanban:'Kanban / список',bulkComplete:'Завершити обрані',bulkMove:'Перенести',bulkPriority:'Змінити пріоритет',repeatTask:'Повторення після виконання',noRepeat:'Не повторювати',dailyRepeat:'Щодня',weeklyRepeat:'Щотижня',showArchive:'Архів / активні',projectDetails:'Деталі проєкту',archiveProject:'Архівувати',restoreProject:'Повернути з архіву',progressMode:'Режим прогресу',autoProgress:'За задачами',manualMode:'Вручну',subtasks:'Підзадачі',addSubtask:'Додати підзадачу',stages:'Етапи проєкту',addStage:'Додати етап',selectTask:'Обрати для масових дій',selected:'Обрано',emptyTrash:'Корзина задач порожня.',permanentConfirm:'Назавжди видалити цю задачу?',projectMaterials:'Матеріали проєкту',attach:'Додати',openAllProjects:'← Усі проєкти',repeatHint:'Наступна задача створюється один раз після виконання; без дедлайну відлік починається сьогодні.',stagePlanning:'Заплановано',stageProgress:'У роботі',stageFinished:'Завершено'});
Object.assign(translations.en,{kanban:'Kanban / list',bulkComplete:'Complete selected',bulkMove:'Move',bulkPriority:'Set priority',repeatTask:'Repeat after completion',noRepeat:'Do not repeat',dailyRepeat:'Daily',weeklyRepeat:'Weekly',showArchive:'Archive / active',projectDetails:'Project details',archiveProject:'Archive',restoreProject:'Unarchive',progressMode:'Progress mode',autoProgress:'From tasks',manualMode:'Manual',subtasks:'Subtasks',addSubtask:'Add subtask',stages:'Project stages',addStage:'Add stage',selectTask:'Select for bulk actions',selected:'Selected',emptyTrash:'Task trash is empty.',permanentConfirm:'Permanently delete this task?',projectMaterials:'Project materials',attach:'Attach',openAllProjects:'← All projects',repeatHint:'The next task is created once after completion; without a deadline the schedule starts today.',stagePlanning:'Planning',stageProgress:'In progress',stageFinished:'Finished'});
function validWorkspace(w){return w&&w.version===1&&Array.isArray(w.trash)&&w.trash.length<=10000&&w.trash.every(task=>task&&typeof task.id==='string'&&task.id.length<=100&&typeof task.completed==='boolean'&&validTaskExtras(task)&&((typeof task.title==='string'&&task.title.length<=160)||['taskFlex','taskArrays','taskPush','taskLayout'].includes(task.translationKey)));}
let workspace=readData('devspace-workspace',{version:1,trash:[]},validWorkspace),taskSelection=new Set(),kanbanMode=false,trashMode=false;
let previousTasks=JSON.parse(JSON.stringify(tasks));
function persistWorkspace(){writeData('devspace-workspace',workspace);}
const workspaceSaveTasks=saveTasks;
saveTasks=function(){
 for(const old of previousTasks)if(!tasks.some(task=>task.id===old.id)&&!workspace.trash.some(task=>task.id===old.id))workspace.trash.unshift(old);
 const generated=[];for(const task of tasks){const old=previousTasks.find(o=>o.id===task.id);if(task.completed&&!old?.completed&&['daily','weekly'].includes(task.repeat)&&!task.repeatGenerated){const date=new Date((task.deadline||todayInKyiv())+'T12:00:00Z');date.setUTCDate(date.getUTCDate()+(task.repeat==='daily'?1:7));if(date.getUTCFullYear()>9999)continue;task.repeatGenerated=true;generated.push({...task,id:crypto.randomUUID(),completed:false,stage:'planning',repeatGenerated:false,deadline:date.toISOString().slice(0,10),subtasks:(task.subtasks||[]).map(s=>({...s,completed:false}))});}}tasks.push(...generated);
 previousTasks=JSON.parse(JSON.stringify(tasks));persistWorkspace();workspaceSaveTasks();
};
function workspaceTaskMatches(task){const project=document.querySelector('#filter-project').value,priority=document.querySelector('#filter-priority').value;return (!project||project==='all'||(project==='__none'?!task.projectId:task.projectId===project))&&(priority==='all'||(task.priority||'medium')===priority);}
function workspaceButton(key,action){const b=projectElement('button','secondary-button',t()[key]);b.type='button';b.addEventListener('click',action);return b;}
function fillWorkspaceProjects(){for(const id of ['filter-project','bulk-project']){const select=document.querySelector('#'+id),value=select.value;select.replaceChildren();for(const [key,label] of (id==='filter-project'?[['all',t().filterAll],['__none',t().noProject]]:[['',t().noProject]])){const o=projectElement('option','',label);o.value=key;select.append(o);}for(const p of projects){const o=projectElement('option','',p.name);o.value=p.id;select.append(o);}select.value=[...select.options].some(o=>o.value===value)?value:select.options[0].value;}document.querySelector('#bulk-project').setAttribute('aria-label',t().taskProject);document.querySelector('#bulk-priority').setAttribute('aria-label',t().priority);}
function stageSelect(task){const select=projectElement('select','');select.setAttribute('aria-label',task.translationKey?t()[task.translationKey]:task.title);for(const [key,label] of [['planning','stagePlanning'],['inProgress','stageProgress'],['finished','stageFinished']]){const o=projectElement('option','',t()[label]);o.value=key;select.append(o);}select.value=task.completed?'finished':task.stage||'planning';select.addEventListener('change',()=>{task.stage=select.value;task.completed=select.value==='finished';saveTasks();renderTasks();renderProjects();});return select;}
function renderWorkspaceTasks(shown){
 document.querySelector('#all-tasks').hidden=kanbanMode||trashMode;document.querySelector('#kanban-board').hidden=!kanbanMode||trashMode;document.querySelector('#task-trash-list').hidden=!trashMode;document.querySelector('#task-trash-open').setAttribute('aria-pressed',String(trashMode));document.querySelector('#toggle-kanban').setAttribute('aria-pressed',String(kanbanMode));for(const id of [...taskSelection])if(!tasks.some(task=>task.id===id))taskSelection.delete(id);document.querySelector('#bulk-count').textContent=t().selected+': '+taskSelection.size;
 shown.forEach((task,index)=>{const li=document.querySelector('#all-tasks').children[index];if(!li)return;const pick=document.createElement('input');pick.type='checkbox';pick.checked=taskSelection.has(task.id);pick.setAttribute('aria-label',t().selectTask+': '+(task.translationKey?t()[task.translationKey]:task.title));pick.addEventListener('change',()=>{if(pick.checked)taskSelection.add(task.id);else taskSelection.delete(task.id);document.querySelector('#bulk-count').textContent=t().selected+': '+taskSelection.size;});li.prepend(pick);
 const detail=projectElement('details','subtask-editor');detail.append(projectElement('summary','',t().subtasks+' · '+(task.subtasks||[]).filter(s=>s.completed).length+'/'+(task.subtasks||[]).length));for(const sub of task.subtasks||[]){const label=projectElement('label','topic-row');const check=document.createElement('input');check.type='checkbox';check.checked=sub.completed;check.addEventListener('change',()=>{sub.completed=check.checked;saveTasks();detail.querySelector('summary').textContent=t().subtasks+' · '+task.subtasks.filter(s=>s.completed).length+'/'+task.subtasks.length;});label.append(check,projectElement('span','',sub.title));detail.append(label,workspaceButton('remove',()=>{task.subtasks=task.subtasks.filter(item=>item!==sub);saveTasks();renderTasks();}));}const form=document.createElement('form');const input=document.createElement('input');input.required=true;input.maxLength=160;input.setAttribute('aria-label',t().addSubtask);const button=projectElement('button','secondary-button',t().addSubtask);button.type='submit';form.append(input,button);form.addEventListener('submit',e=>{e.preventDefault();if(!input.value.trim()||(task.subtasks||[]).length>=100)return;(task.subtasks||=[]).push({title:input.value.trim(),completed:false});saveTasks();renderTasks();});detail.append(form);li.querySelector('.task-content').append(detail);
 });
 const board=document.querySelector('#kanban-board');board.replaceChildren();for(const [stage,key] of [['planning','stagePlanning'],['inProgress','stageProgress'],['finished','stageFinished']]){const column=projectElement('section','dashboard-panel');column.append(projectElement('h3','',t()[key]));for(const task of shown.filter(task=>(task.completed?'finished':task.stage||'planning')===stage)){const card=projectElement('article','kanban-card');card.append(projectElement('p','',task.translationKey?t()[task.translationKey]:task.title),stageSelect(task));column.append(card);}board.append(column);}
 const trash=document.querySelector('#task-trash-list');trash.replaceChildren();if(!workspace.trash.length)trash.append(projectElement('p','empty-state',t().emptyTrash));for(const task of workspace.trash){const row=projectElement('div','trash-task');row.append(projectElement('span','',task.translationKey?t()[task.translationKey]:task.title),workspaceButton('restoreNote',()=>{if(!tasks.some(t=>t.id===task.id))tasks.push(task);workspace.trash=workspace.trash.filter(t=>t.id!==task.id);saveTasks();persistWorkspace();renderTasks();renderProjects();}),workspaceButton('deleteForever',()=>{if(!confirm(t().permanentConfirm))return;workspace.trash=workspace.trash.filter(t=>t.id!==task.id);persistWorkspace();renderTasks();}));trash.append(row);}
}
const baseRenderProjects=renderProjects;
renderProjects=function(){baseRenderProjects();fillWorkspaceProjects();renderProjectDetail();};
function renderProjectDetail(){
 const id=new URLSearchParams(location.hash.split('?')[1]||'').get('project'),project=projects.find(p=>p.id===id);const container=document.querySelector('#project-detail');container.hidden=!project;document.querySelector('#projects-view').classList.toggle('project-open',!!project);document.querySelector('#all-projects').hidden=!!project;if(!project)return;container.replaceChildren();const back=projectElement('a','text-link',t().openAllProjects);back.href='#projects';container.append(back,projectElement('h2','',project.name),projectElement('p','lesson-theory',project.descriptionKey?t().projectDescription:project.description));
 const mode=document.createElement('select');mode.setAttribute('aria-label',t().progressMode);for(const [key,label] of [['auto','autoProgress'],['manual','manualMode']]){const o=projectElement('option','',t()[label]);o.value=key;mode.append(o);}mode.value=project.progressMode||'auto';mode.addEventListener('change',()=>{project.progressMode=mode.value;saveProjects();renderProjects();});container.append(projectElement('p','panel-note',t().progressMode),mode,workspaceButton(project.archived?'restoreProject':'archiveProject',()=>{project.archived=!project.archived;saveProjects();renderProjects();}));
 const stageTitle=projectElement('h3','',t().stages);container.append(stageTitle);for(const stage of project.stages||[]){const label=projectElement('label','topic-row');const check=document.createElement('input');check.type='checkbox';check.checked=stage.completed;check.addEventListener('change',()=>{stage.completed=check.checked;saveProjects();});label.append(check,projectElement('span','',stage.title));container.append(label,workspaceButton('remove',()=>{project.stages=project.stages.filter(item=>item!==stage);saveProjects();renderProjects();}));}const form=document.createElement('form');form.className='subtask-editor';const input=document.createElement('input');input.maxLength=160;input.required=true;input.setAttribute('aria-label',t().addStage);const add=projectElement('button','secondary-button',t().addStage);add.type='submit';form.append(input,add);form.addEventListener('submit',e=>{e.preventDefault();if(!input.value.trim()||(project.stages||[]).length>=100)return;(project.stages||=[]).push({title:input.value.trim(),completed:false});saveProjects();renderProjects();});container.append(form);
 container.append(projectElement('h3','',t().linkedTasks));for(const task of tasks.filter(t=>t.projectId===project.id)){const row=projectElement('div','trash-task');row.append(projectElement('span','',task.translationKey?t()[task.translationKey]:task.title),stageSelect(task));container.append(row);}container.append(projectElement('h3','',t().notes));for(const note of notes.filter(n=>!n.deleted&&n.projectId===project.id)){const b=projectElement('button','note-list-item',note.title||t().untitledNote);b.type='button';b.addEventListener('click',()=>{selectedNote=note.id;showTrash=false;location.hash='notes';renderNotes();});container.append(b);}
 container.append(projectElement('h3','',t().projectMaterials));for(const [kind,catalog] of [['snippets',snippets.map(s=>({id:s.id,title:s.name}))],['resources',resources.map(r=>({id:r[0],title:r[1]}))]]){const label=projectElement('label','form-field',t()[kind]);const select=document.createElement('select');for(const item of catalog){const o=projectElement('option','',item.title);o.value=item.id;select.append(o);}label.append(select);container.append(label,workspaceButton('attach',()=>{if(!select.value)return;const ids=project[kind]||=[];if(!ids.includes(select.value))ids.push(select.value);saveProjects();renderProjects();}));for(const key of project[kind]||[]){const item=catalog.find(c=>c.id===key);if(item){const a=projectElement('a','text-link',item.title);if(kind==='resources'){a.href=resources.find(r=>r[0]===key)[3];a.target='_blank';a.rel='noopener noreferrer';}else{a.href='#snippets';a.addEventListener('click',()=>{snippetFilter='all';document.querySelector('#snippets-search').value=item.title;renderSnippets();});}container.append(a,workspaceButton('remove',()=>{project[kind]=project[kind].filter(id=>id!==key);saveProjects();renderProjects();}));}}}
}
for(const id of ['filter-project','filter-priority'])document.querySelector('#'+id).addEventListener('change',renderTasks);
document.querySelector('#toggle-kanban').addEventListener('click',()=>{kanbanMode=!kanbanMode;trashMode=false;renderTasks();});document.querySelector('#task-trash-open').addEventListener('click',()=>{trashMode=!trashMode;renderTasks();});document.querySelector('#project-archive-toggle').addEventListener('click',e=>{e.currentTarget.classList.toggle('active');renderProjects();});
for(const [id,action] of [['bulk-complete',task=>task.completed=true],['bulk-move',task=>task.projectId=document.querySelector('#bulk-project').value],['bulk-prioritize',task=>task.priority=document.querySelector('#bulk-priority').value]])document.querySelector('#'+id).addEventListener('click',()=>{for(const task of tasks.filter(t=>taskSelection.has(t.id)))action(task);saveTasks();taskSelection.clear();renderTasks();renderProjects();});
window.addEventListener('hashchange',()=>{renderProjectDetail();});window.addEventListener('languagechange',()=>{fillWorkspaceProjects();renderTasks();renderProjectDetail();});fillWorkspaceProjects();setLanguage(document.documentElement.lang);
