const assert=require('node:assert/strict');
const {chromium}=require(process.env.KACHAN_PLAYWRIGHT||'playwright');
const url=process.env.KACHAN_URL||'http://127.0.0.1:5173';
const snapshot=page=>page.evaluate(()=>({app:'Kachan',version:7,data:{settings,snippets,favorites,progress:savedProgress,tasks,projects,language:document.documentElement.lang,htmlCourse,notes,dashboard:dashboardData,workspace,extras,academy,personalization}}));
(async()=>{const browser=await chromium.launch({channel:process.env.KACHAN_BROWSER||'msedge',headless:true});try{
 const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{if(window!==window.top)return;if(!localStorage.getItem('qa-seeded')){localStorage.setItem('qa-seeded','1');localStorage.setItem('devspace-notes',JSON.stringify([{id:'legacy-note',title:'Legacy note',body:'Preserved',category:'general',projectId:'',tags:[],pinned:false,deleted:false,updatedAt:'2026-10-04T12:00:00Z'}]));}});
 await page.goto(url);await page.waitForFunction(()=>window.kachanReady);assert.equal(await page.evaluate(()=>kachanStorage.mode),'indexeddb');assert.equal(await page.evaluate(()=>notes[0].body),'Preserved');assert.equal(await page.evaluate(()=>localStorage.getItem('devspace-notes')),null);
 const checked=await page.evaluate(async()=>{const report=[];for(const l of academyLessonList()){const files={html:'',css:'',js:'',...l.starter,...l.solution},r=await runAcademyPractice(l,files);report.push({id:l.id,passed:!r.error&&r.results.length>0&&r.results.every(c=>c.passed)});}return report;});assert.equal(checked.length,24);assert(checked.every(r=>r.passed),JSON.stringify(checked.filter(r=>!r.passed)));
 const bad=await page.evaluate(async()=>runAcademyPractice(academyLessonList().find(l=>l.id==='javascript-arrays'),{html:'',css:'',js:'function activeTitles(items) { return []; }'}));assert(bad.results.some(r=>!r.passed));
 const stuck=await page.evaluate(async()=>runAcademyPractice(academyLessonList().find(l=>l.id==='javascript-values'),{html:'',css:'',js:'while(true){}'}));assert(stuck.error.includes('вичерпано')||stuck.error.includes('timed out'));assert(await page.evaluate(()=>window.kachanReady));
 const isolated=await page.evaluate(async()=>runAcademyPractice(academyLessonList().find(l=>l.id==='javascript-values'),{html:'',css:'',js:'console.log(typeof document); try { indexedDB.open("kachan-local"); } catch(e) { console.log("blocked"); }'}));assert(isolated.output.includes('undefined'));assert(isolated.output.includes('blocked'));
 await page.evaluate(()=>openLesson('javascript-values'));await page.locator('#academy-code-js').fill('const userName = "Rubin";\nfunction isPassed(score) { return score >= 60; }');await page.getByLabel('Теорію прочитано',{exact:true}).check();await page.getByRole('button',{name:'Перевірити практику',exact:true}).click();await page.waitForFunction(()=>!academyRunning&&academy.states['javascript-values'].practicePassed);await page.locator('#academy-quiz input[value="0"]').check();await page.locator('#academy-quiz button').click();assert.equal(await page.evaluate(()=>academy.states['javascript-values'].completed),false);await page.locator('#academy-quiz input[value="1"]').check();await page.locator('#academy-quiz button').click();assert.equal(await page.evaluate(()=>academy.states['javascript-values'].completed),true);
 await page.getByRole('button',{name:'Додати урок до повторення',exact:true}).click();assert.equal(await page.evaluate(()=>extras.cards.length),1);assert.equal(await page.evaluate(()=>personalization.reviewLinks[extras.cards[0].id]),'javascript-values');await page.getByRole('button',{name:'Створити конспект',exact:true}).click();assert.equal(await page.evaluate(()=>notes.find(n=>n.id===selectedNote).lessonId),'javascript-values');await page.locator('#note-taskId').selectOption('taskFlex');assert.equal(await page.evaluate(()=>notes.find(n=>n.id===selectedNote).taskId),'taskFlex');
 await page.evaluate(()=>{location.hash='tasks';showView();renderTasks();});assert(await page.locator('.task-linked-notes').count()>0);await page.locator('#tasks-search').fill('Flex');assert.equal(await page.locator('.task-linked-notes').count(),1);assert((await page.locator('.task-linked-notes').textContent()).includes('Змінні'));
 await page.evaluate(()=>{location.hash='settings';showView();});await page.locator('[data-layout-block="stats"]').uncheck();await page.getByRole('button',{name:'Вище: Календар повторень',exact:true}).click();assert.equal(await page.evaluate(()=>personalization.blocks[10].id),'calendar');await page.evaluate(()=>kachanStorage.flush());await page.reload();await page.waitForFunction(()=>window.kachanReady);assert.equal(await page.evaluate(()=>personalization.blocks.find(b=>b.id==='stats').visible),false);assert.equal(await page.evaluate(()=>academy.states['javascript-values'].completed),true);assert.equal(await page.evaluate(()=>notes.find(n=>n.lessonId==='javascript-values').taskId),'taskFlex');
 // Store more than the previous localStorage quota using actual note records.
 await page.evaluate(async()=>{for(let i=0;i<65;i++)notes.push({id:'large-'+i,title:'Large '+i,body:'x'.repeat(100000),category:'general',projectId:'',tags:[],pinned:false,deleted:false,updatedAt:new Date().toISOString()});persistNotes();await kachanStorage.flush();});await page.reload();await page.waitForFunction(()=>window.kachanReady);assert.equal(await page.evaluate(()=>notes.filter(n=>n.id.startsWith('large-')).length),65);
 const exported=await snapshot(page);assert(await page.evaluate(d=>validateBackup(d),exported));assert(Buffer.byteLength(JSON.stringify(exported))>5*1024*1024);
 await page.evaluate(()=>{location.hash='settings';showView();});const imported=structuredClone(exported);imported.data.notes.push({id:'imported-new',title:'Imported',body:'New note',category:'general',projectId:'',taskId:'taskFlex',lessonId:'javascript-values',tags:[],pinned:false,deleted:false,updatedAt:new Date().toISOString()});await page.locator('#import-file').setInputFiles({name:'large-backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>pendingBackup!==null);page.once('dialog',d=>d.accept());await Promise.all([page.waitForEvent('load'),page.locator('#merge-import').click()]);await page.waitForFunction(()=>window.kachanReady);await page.waitForFunction(()=>notes.some(n=>n.id==='imported-new'));assert.equal(await page.evaluate(()=>notes.filter(n=>n.id.startsWith('large-')).length),65);
 // An older version stays valid and starts new modules from defaults.
 const old=structuredClone(exported);old.version=6;delete old.data.academy;delete old.data.personalization;assert(await page.evaluate(d=>validateBackup(d),old));const malformed=structuredClone(exported);malformed.data.academy.states['not-a-lesson']={};assert.equal(await page.evaluate(d=>validateBackup(d),malformed),false);
 const second=await context.newPage();await second.goto(url);await second.waitForFunction(()=>window.kachanReady);await page.evaluate(async()=>{notes[0].body='Changed in first tab';persistNotes();await kachanStorage.flush();});await second.waitForFunction(()=>kachanStorage.external);assert(await second.locator('#storage-status').textContent().then(t=>t.includes('іншій вкладці')));await second.close();
 // Offline boot must include the new module files.
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>window.kachanReady&&navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.kachanReady);assert.equal(await page.evaluate(()=>academyLessonList().length),24);await context.setOffline(false);
 for(const lang of ['uk','en'])for(const theme of ['dark','light'])for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.evaluate(({lang,theme})=>{setLanguage(lang);settings.theme=theme;applyComfort();},{lang,theme});for(const route of ['dashboard','projects','tasks','learning','snippets','notes','resources','settings']){await page.evaluate(route=>{location.hash=route;showView();},route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${route} ${lang} ${theme} ${width} overflows`);}}
 await page.evaluate(()=>{openLesson('css-project');setLanguage('uk');settings.theme='dark';applyComfort();scrollTo(0,0);});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'.qa/academy-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.qa/academy-mobile.png',fullPage:true});await page.evaluate(()=>{location.hash='dashboard';showView();scrollTo(0,0);});await page.screenshot({path:'.qa/personal-dashboard.png',fullPage:true});
 // Keyboard navigation: native dialog traps focus and Escape returns it.
 await page.locator('#global-search-open').focus();await page.keyboard.press('Control+k');assert(await page.locator('#command-dialog').isVisible());await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'global-search-open');
 assert.deepEqual(errors,[]);console.log('PASS: 24 reference exercises, failures, worker timeout/isolation, quiz completion, notes links, layout, migration, >5MB persistence/import, backward validation, concurrent tabs, offline, 128 route/language/theme/width layouts, keyboard dialog.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
