const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.emulateMedia({reducedMotion:'reduce'});await page.goto(process.env.KACHAN_URL||'http://127.0.0.1:5173');await page.waitForFunction(()=>window.kachanReady);
 const ids=await page.evaluate(()=>lessonCatalog().map(l=>l.id));assert.equal(ids.length,46);assert.equal(await page.evaluate(()=>Object.keys(beginnerLessons).length),46);
 for(const lang of ['uk','en']){await page.evaluate(lang=>setLanguage(lang),lang);for(const id of ids){await page.evaluate(id=>openLesson(id),id);assert.equal(await page.locator('.beginner-lesson:visible').count(),1,id);assert((await page.locator('.beginner-lesson:visible').innerText()).length>300,id);await page.locator('.beginner-lesson:visible details>summary').click();assert.equal(await page.locator('.beginner-lesson:visible pre code').textContent(),await page.evaluate(id=>beginnerLessons[id].code,id));await page.locator('.lesson-step-tabs:visible [data-tab=practice]').click();assert.equal(await page.locator('.beginner-lesson:visible').count(),0,id);}}
 const newIds=['javascript-comparisons','javascript-conditions','javascript-loops','javascript-strings','css-units','css-typography'];
 for(const id of newIds){const result=await page.evaluate(async id=>{const l=academyLessonList().find(l=>l.id===id);return await runAcademyPractice(l,{...l.starter,...l.solution});},id);assert(!result.error,id+': '+result.error);assert(result.results.length&&result.results.every(r=>r.passed),id+JSON.stringify(result));const wrong=await page.evaluate(async id=>{const l=academyLessonList().find(l=>l.id===id);return await runAcademyPractice(l,l.starter);},id);assert(wrong.error||wrong.results.some(r=>!r.passed),id+' must reject starter');}
 await page.evaluate(()=>{location.hash='learning';learningScreen='library';showView();applyLearningLook();openFoundation();});for(let i=0;i<6;i++){assert.equal(await page.evaluate(()=>foundationIndex),i);assert(await page.locator('.foundation-reader h2').isVisible());if(i<5)await page.locator('.foundation-reader button').last().click();}await page.locator('.foundation-reader button').last().click();assert.equal(await page.evaluate(()=>htmlCourse.selected),'document');assert.equal(await page.locator('#foundation-window').isVisible(),false);
 for(const width of [390,1440])for(const lang of ['uk','en']){await page.setViewportSize({width,height:900});await page.evaluate(lang=>setLanguage(lang),lang);for(const id of ['html-document','javascript-loops','css-units','figma-frames']){await page.evaluate(id=>openLesson(id),id);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await page.evaluate(()=>{location.hash='tools';toolCatalogOpen=true;showView();renderTools();});assert.equal(await page.locator('.tool-guide-description').count(),13);for(const id of await page.evaluate(()=>toolTabs.map(r=>r[0]))){await page.evaluate(id=>{selectedTool=id;toolCatalogOpen=false;renderTools();},id);assert.equal(await page.locator('.tool-learning-guide').count(),1,id);await page.locator('.tool-learning-guide summary').click();assert.equal(await page.locator('.tool-learning-guide li').count(),3);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),id+width);}await page.evaluate(()=>{location.hash='resources';showView();renderResources();});assert.equal(await page.locator('.resource-use').count(),await page.locator('[data-resource-id]').count());assert(await page.evaluate(()=>new Set(resources.map(r=>r[0])).size===resources.length));}
 await page.evaluate(()=>{setLanguage('uk');openLesson('javascript-loops');academy.states['javascript-loops'].theoryRead=true;saveAcademy();});await page.evaluate(()=>kachanStorage.flush());await page.reload();await page.waitForFunction(()=>window.kachanReady);assert(await page.evaluate(()=>academy.selected==='javascript-loops'&&academy.states['javascript-loops'].theoryRead&&validAcademy(academy)));await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>window.kachanReady&&navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.kachanReady);assert.equal(await page.evaluate(()=>Object.keys(beginnerLessons).length),46);assert.deepEqual(errors,[]);console.log('PASS: 46 bilingual beginner guides; 6 new lessons positive/negative checks and persistence; 6 foundation steps; 13 tool guides; resource tips; mobile/desktop; offline.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
