const assert=require('node:assert/strict');const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const context=await browser.newContext();const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5173');await p.waitForFunction(()=>window.kachanReady);
 assert.equal(await p.evaluate(()=>htmlLessons.length+academyLessonList().length),40);
 assert.equal(await p.evaluate(()=>Object.keys(deepTopics).length),40);assert.equal(await p.evaluate(()=>Object.keys(depthExamples).length),34);
 const ids=await p.evaluate(()=>[...htmlLessons.map(l=>'html-'+l.id),...academyLessonList().map(l=>l.id)]);
 for(const lang of ['uk','en']){await p.evaluate(lang=>setLanguage(lang),lang);for(const id of ids){await p.evaluate(id=>openLesson(id),id);const guide=p.locator('.lesson-deep-guide:visible');assert.equal(await guide.count(),1,id);assert.equal(await guide.locator('details').count(),7,id);assert((await guide.locator('details').first().innerText()).length>100,id);await guide.locator('.learning-example').locator('summary').click();if(!id.startsWith('figma-'))assert.equal(await guide.locator('.learning-example').locator('code').count(),1,id);else assert(await guide.locator('.learning-example').locator('li').count()>0);await p.locator('.lesson-step-tabs:visible [data-tab=practice]').click();assert.equal(await guide.count(),0,id);assert(await p.locator(id.startsWith('html-')?'#course-code':'#academy-code-js').count()>0);}}
 const reports=await p.evaluate(async()=>{const ls=academyLessonList().filter(l=>l.kind==='design');const out=[];for(const l of ls){out.push((await runAcademyPractice(l,{js:l.solution.js})).results.every(r=>r.passed));out.push((await runAcademyPractice(l,{js:l.starter.js})).results.some(r=>!r.passed));}return out;});assert(reports.every(Boolean));
 assert(await p.evaluate(async()=>!!(await runAcademyPractice(academyLessonList().find(l=>l.kind==='design'),{js:'not JSON'})).error));
 await p.evaluate(()=>{setLanguage('uk');openLesson('figma-auto-layout');});await p.getByLabel('Теорію прочитано',{exact:true}).check();await p.locator('.lesson-step-tabs:visible [data-tab=practice]').click();await p.locator('#academy-code-js').fill('{"direction":"vertical","gap":16,"padding":24,"resizing":"hug"}');await p.getByRole('button',{name:'Перевірити практику',exact:true}).click();await p.waitForFunction(()=>!academyRunning&&academy.states['figma-auto-layout'].practicePassed);await p.locator('.lesson-step-tabs:visible [data-tab=test]').click();await p.locator('#academy-quiz input[value="0"]').check();await p.locator('#academy-quiz button').click();assert.equal(await p.evaluate(()=>academy.states['figma-auto-layout'].completed),false);
 await p.getByLabel('Я відкрив макет у Figma й перевірив вимоги, стани та поведінку вручну.',{exact:true}).check();await p.evaluate(()=>kachanStorage.flush());await p.reload();await p.waitForFunction(()=>window.kachanReady);assert(await p.evaluate(()=>validAcademy(academy)&&academy.states['figma-auto-layout'].completed));
 for(const lang of ['uk','en'])for(const theme of ['dark','light'])for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});await p.evaluate(({lang,theme})=>{setLanguage(lang);settings.theme=theme;applyComfort();},{lang,theme});for(const id of ['html-document','css-cascade','javascript-arrays','git-commit','typescript-types','figma-auto-layout']){await p.evaluate(id=>openLesson(id),id);await p.locator('.lesson-deep-guide:visible details').evaluateAll(ds=>ds.forEach(d=>d.open=true));for(const step of ['theory','practice','test']){await p.locator('.lesson-step-tabs:visible [data-tab='+step+']').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${id} ${step} ${lang} ${width}`);}}}
 await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>{setLanguage('uk');openLesson('figma-auto-layout');});await p.locator('.lesson-step-tabs:visible [data-tab=theory]').click();await p.screenshot({path:'.qa/learning-depth.png',fullPage:true});await p.evaluate(()=>navigator.serviceWorker.ready);await p.reload();await p.waitForFunction(()=>window.kachanReady&&navigator.serviceWorker.controller);await context.setOffline(true);await p.reload();await p.waitForFunction(()=>window.kachanReady);assert.equal(await p.evaluate(()=>Object.keys(deepTopics).length),40);assert.equal(await p.evaluate(()=>academy.states['figma-auto-layout'].completed),true);await context.setOffline(false);assert.deepEqual(errors,[]);console.log('PASS: 40 bilingual lesson guides, theory/practice separation, 6 Figma report checks, invalid JSON, manual-review completion, reload preservation, 288 responsive layouts.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
