const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.kachanReady);
await page.locator('#quick-task').click();await page.waitForFunction(()=>editorWindows.get('task').dialog.open);await page.locator('#task-input').fill('Modal task');await page.locator('#task-submit').click();assert.equal(await page.evaluate(()=>editorWindows.get('task').dialog.open),false);assert(await page.evaluate(()=>tasks.some(t=>t.title==='Modal task')));
await page.locator('.task-action-menu>summary').first().click();await page.locator('.task-edit').first().click();assert(await page.evaluate(()=>editorWindows.get('task').dialog.open));await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>editorWindows.get('task').dialog.open),false);assert(await page.evaluate(()=>document.activeElement.tagName==='SUMMARY'));
await page.evaluate(()=>{location.hash='dashboard';showView()});await page.locator('#quick-project').click();await page.waitForFunction(()=>editorWindows.get('project').dialog.open);await page.locator('#project-name').fill('Modal project');await page.locator('#project-form button[type=submit]').click();await page.waitForFunction(()=>!editorWindows.get('project').dialog.open);assert(await page.evaluate(()=>projects.some(p=>p.name==='Modal project')));
await page.locator('#open-project-window').click();await page.locator('.editor-window[open] .window-close').click();assert.equal(await page.evaluate(()=>editorWindows.get('project').dialog.open),false);
await page.evaluate(()=>{setLanguage('en');location.hash='tasks';showView()});await page.locator('#open-task-window').click();assert.equal(await page.locator('#task-window-title').textContent(),'New task');await page.locator('#task-input').fill('Draft stays');await page.keyboard.press('Escape');assert.equal(await page.locator('#task-input').inputValue(),'Draft stays');
for(const width of [320,390,768,1440])for(const theme of ['dark','light']){await page.setViewportSize({width,height:900});await page.evaluate(theme=>{settings.theme=theme;applyComfort();location.hash='tasks';showView()},theme);await page.locator('#open-task-window').click();assert(await page.evaluate(()=>{const d=editorWindows.get('task').dialog,r=d.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&d.scrollWidth<=d.clientWidth}));await page.keyboard.press('Escape');for(const route of ['dashboard','projects','tasks','learning','snippets','notes','resources','settings']){await page.evaluate(route=>{location.hash=route;showView()},route);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' '+width);}}
await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{setLanguage('uk');settings.theme='dark';applyComfort();location.hash='dashboard';showView();scrollTo(0,0)});await page.screenshot({path:'.qa/polish-dashboard.png',animations:'disabled'});await page.locator('#quick-task').click();await page.screenshot({path:'.qa/polish-modal.png',animations:'disabled'});await page.keyboard.press('Escape');await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>{location.hash='notes';showView()});assert.equal(await page.evaluate(()=>motionPreference.matches),true);assert.deepEqual(errors,[]);console.log('PASS: create/edit modal forms, validation-preserving save, Escape/focus, close button, bilingual titles, drafts, 64 responsive theme/routes, reduced motion.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
