// Run with KACHAN_PLAYWRIGHT pointing to Playwright if it is not installed locally.
const assert=require('node:assert/strict');
const {chromium}=require(process.env.KACHAN_PLAYWRIGHT||'playwright');
(async()=>{const browser=await chromium.launch({channel:process.env.KACHAN_BROWSER||'msedge',headless:true});try{
 const context=await browser.newContext(),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.KACHAN_URL||'http://127.0.0.1:5173');await page.waitForFunction(()=>window.kachanReady);
 const backup=()=>page.evaluate(()=>({app:'Kachan',version:6,data:{settings,snippets,favorites,progress:savedProgress,tasks,projects,language:document.documentElement.lang,htmlCourse,notes,dashboard:dashboardData,workspace,extras}}));
 assert(await page.evaluate(()=>validExtras(extras)));
 await page.evaluate(()=>{location.hash='snippets';showView();const m=meta('css-center');m.tags=['regression'];m.favorite=true;m.pinned=true;saveMeta('css-center',m);renderSnippets();});await page.locator('#snippets-search').fill('regression');assert.equal(await page.locator('#snippet-list article').count(),1);assert((await page.locator('#snippet-list code').textContent()).includes('display: flex'));assert(await page.locator('.syntax-keyword').count()>0);
 await page.evaluate(()=>{location.hash='resources';showView();});await page.locator('#resource-editor summary').click();const form=page.locator('#resource-form');await form.locator('[name=name]').fill('My docs');await form.locator('[name=url]').fill('https://example.com');await form.locator('[name=collection]').fill('HTML');await form.locator('button[type=submit]').click();await page.locator('#resource-query').fill('My docs');assert.equal(await page.locator('#resource-list article').count(),1);await page.locator('#resource-list .resource-comment summary').click();await page.locator('#resource-list textarea').fill('Personal test comment');await page.locator('#resource-list button').first().click();
 await page.keyboard.press('Control+k');await page.locator('#global-query').fill('My docs');await page.locator('.command-result').click();assert.equal(await page.locator('#resource-query').inputValue(),'My docs');
 await page.evaluate(()=>{timer={mode:'focus',target:'task:taskFlex',remaining:0.1,elapsed:4,end:Date.now()+100};timerMark=Date.now();});await page.waitForTimeout(1400);assert.equal(await page.evaluate(()=>extras.sessions.length),1);assert(await page.evaluate(()=>extras.sessions[0].seconds>=4));
 await page.evaluate(()=>{location.hash='dashboard';showView();workTab='focus';arrangeWorkday();renderFocus();});await page.locator('#review-form input').fill('What is HTML?');await page.locator('#review-form textarea').fill('Markup language');await page.locator('#review-form button').click();await page.locator('.productivity-panel .review-card summary').click();await page.locator('.productivity-panel .review-card button').nth(1).click();assert.equal(await page.locator('.productivity-panel .review-card').count(),0);assert.equal(await page.evaluate(()=>extras.cards[0].interval),3);
 const data=await backup();assert(await page.evaluate(d=>validateBackup(d),data));const bad=JSON.parse(JSON.stringify(data));bad.data.extras.customResources[0].url='javascript:alert(1)';assert.equal(await page.evaluate(d=>validateBackup(d),bad),false);
 await page.reload();await page.waitForFunction(()=>window.kachanReady);await page.waitForFunction(()=>window.kachanReady);assert.equal(await page.evaluate(()=>extras.customResources.length),1);assert.equal(await page.evaluate(()=>extras.sessions.length),1);assert.equal(await page.evaluate(()=>extras.cards.length),1);assert.equal(await page.evaluate(()=>favorites.includes(extras.customResources[0].id)),true);
 // Merge adds a new task but preserves current text on matching IDs.
 const imported=await backup();imported.data.tasks[0].title='SHOULD NOT REPLACE';imported.data.tasks.push({id:'import-test',title:'Imported task',completed:false});await page.evaluate(()=>{location.hash='settings';showView();});await page.locator('#settings-tabs [data-tab=data]').click();await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(imported))});await page.waitForFunction(()=>pendingBackup!==null);page.once('dialog',d=>d.accept());await Promise.all([page.waitForEvent('load'),page.locator('#merge-import').click()]);await page.waitForFunction(()=>window.kachanReady);assert(await page.evaluate(()=>tasks.some(t=>t.id==='import-test')));assert(await page.evaluate(()=>taskName(tasks[0])!=='SHOULD NOT REPLACE'));
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await page.waitForFunction(()=>window.kachanReady);await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.waitForFunction(()=>window.kachanReady);assert.equal(await page.title(),'Kachan');assert.equal(await page.evaluate(()=>extras.customResources.length),1);await context.setOffline(false);
 await page.evaluate(()=>setLanguage('en'));assert.equal(await page.locator('#global-search-open').textContent(),'Search and commands');await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{location.hash='dashboard';showView();});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>{document.activeElement?.blur();scrollTo(0,0);});await page.screenshot({path:'.qa/productivity-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{settings.theme='light';applyComfort();});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'.qa/productivity-light.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: materials, resources, search, timer, review, persistence, backup validation, merge, offline, languages, mobile; no page errors.');
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exitCode=1;});
