const assert=require('node:assert/strict');const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:5173');await p.waitForFunction(()=>window.kachanReady);assert(await p.locator('#home-surface').isVisible());assert.equal(await p.locator('[data-dashboard-block=stats]').isVisible(),false);assert.equal(await p.locator('.home-launcher').count(),4);assert.equal(await p.locator('#workday-tabs [data-tab=home]').textContent(),'Головна');await p.screenshot({path:'.qa/new-home-desktop.png',fullPage:true});await p.getByRole('button',{name:'До робочого дня',exact:true}).click();assert(await p.locator('[data-dashboard-block=stats]').isVisible());await p.locator('#workday-tabs [data-tab=home]').click();assert(await p.locator('#home-surface').isVisible());
await p.evaluate(()=>{location.hash='snippets';showView()});await p.locator('#open-snippet-window').click();await p.locator('#snippet-name').fill('Window snippet');await p.locator('#snippet-code').fill('console.log("hello");');await p.locator('#snippet-form button[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('#snippet-window').open);assert(await p.evaluate(()=>snippets.some(s=>s.name==='Window snippet')));await p.locator('#snippets-search').fill('Window snippet');await p.locator('#snippet-list .minimal-actions>summary').first().click();await p.locator('#snippet-list button').filter({hasText:'Редагувати'}).first().click();assert(await p.locator('#snippet-window').isVisible());await p.keyboard.press('Escape');
await p.evaluate(()=>{location.hash='resources';showView()});await p.locator('#open-resource-window').click();const form=p.locator('#resource-form');await form.locator('[name=name]').fill('UI resource');await form.locator('[name=url]').fill('https://example.com/');await form.locator('button[type=submit]').click();await p.waitForFunction(()=>!document.querySelector('#resource-window').open&&!document.body.classList.contains('editor-window-open'));assert(await p.evaluate(()=>extras.customResources.some(r=>r.name==='UI resource')));
await p.evaluate(()=>{location.hash='notes';showView();Q('note-new').click()});await p.locator('#note-title').fill('Clean note');await p.locator('#open-note-options').click();await p.locator('#note-tags').fill('test,compact');await p.locator('#note-taskId').selectOption('taskFlex');await p.keyboard.press('Escape');assert.equal(await p.locator('#note-tags').isVisible(),false);await p.locator('#note-body').fill('Saved note body');assert(await p.evaluate(()=>notes.find(n=>n.id===selectedNote).taskId==='taskFlex'));
await p.evaluate(()=>{location.hash='tasks';showView()});await p.locator('#open-task-filters').click();await p.locator('#filter-priority').selectOption('high');await p.keyboard.press('Escape');assert.equal(await p.locator('#filter-priority').isVisible(),false);
await p.evaluate(()=>{location.hash='learning';showView()});await p.locator('#open-learning-progress').click();assert(await p.locator('#learning-progress-window').isVisible());await p.keyboard.press('Escape');
await p.evaluate(()=>{location.hash='projects?project='+projects[0].id;showView()});await p.waitForFunction(()=>document.querySelector('#project-details-window').open);assert(await p.locator('#all-projects').isVisible());await p.keyboard.press('Escape');await p.waitForFunction(()=>location.hash==='#projects');
for(const lang of ['uk','en'])for(const theme of ['dark','light'])for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});await p.evaluate(({lang,theme})=>{setLanguage(lang);settings.theme=theme;applyComfort()}, {lang,theme});for(const route of ['dashboard','projects','tasks','learning','snippets','notes','resources','settings']){await p.evaluate(route=>{location.hash=route;showView()},route);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' '+width);}}
await p.evaluate(()=>{location.hash='dashboard';showView();setLanguage('uk');settings.theme='dark';applyComfort();scrollTo(0,0)});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'.qa/new-home-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: home, workday, snippet/resource dialogs and saves, note metadata/links, filters, learning progress, project details, 128 responsive bilingual/theme routes.');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
